## 작사/작곡가 -> 아이돌그룹 네트워크 시각화

In [1]:
import pandas as pd
import json
import re
import warnings
warnings.filterwarnings('ignore')

In [2]:
# 파일 불러오기
gen1 = pd.read_csv('idol_generation_1_kavin_ver01.csv', encoding = 'euc-kr')
gen2 = pd.read_csv('idol_generation_2_kavin_ver01.csv', encoding = 'utf-8')
gen3 = pd.read_csv('idol_generation_3_kavin_ver01.csv', encoding = 'utf-8')

In [3]:
# 맨 앞 Unnamed: 0 칼럼 제거
gen1 = gen1.drop(['Unnamed: 0'], axis = 1)
gen2 = gen2.drop(['Unnamed: 0'], axis = 1)
gen3 = gen3.drop(['Unnamed: 0'], axis = 1)

In [4]:
# NaN값 제거, lyricist에 있는 NA만을 제거
lyricist_gen1 =  gen1.dropna(subset=['lyricist'])
lyricist_gen1 = lyricist_gen1.reset_index()
lyricist_gen2 =  gen2.dropna(subset=['lyricist'])
lyricist_gen2 = lyricist_gen2.reset_index()
lyricist_gen3 =  gen3.dropna(subset=['lyricist'])
lyricist_gen3 = lyricist_gen3.reset_index()

In [5]:
# NaN값 제거, composer에 있는 NA만을 제거
composer_gen1 =  gen1.dropna(subset=['composer'])
composer_gen1 = lyricist_gen1.reset_index()
composer_gen2 =  gen2.dropna(subset=['composer'])
composer_gen2 = lyricist_gen2.reset_index()
composer_gen3 =  gen3.dropna(subset=['composer'])
composer_gen3 = lyricist_gen3.reset_index()

In [6]:
# 맨 앞 Unnamed: 0 칼럼 제거
lyricist_gen1 = lyricist_gen1.drop(['index'], axis = 1)
lyricist_gen2 = lyricist_gen2.drop(['index'], axis = 1)
lyricist_gen3 = lyricist_gen3.drop(['index'], axis = 1)
composer_gen1 = composer_gen1.drop(['index'], axis = 1)
composer_gen2 = composer_gen2.drop(['index'], axis = 1)
composer_gen3 = composer_gen3.drop(['index'], axis = 1)

## (1) Lyricist 작업

### 1) Gen1작업

In [7]:
def preprocess(text1, text2):
    splitArr = list(re.split(', ', text1))
    artist_name = list(text2)

    lyricist = []
    artist = []
    
    lyricist.clear()
    artist.clear()

    i = 0
    for i in range(0, len(splitArr)):
        lyricist.append(splitArr[i].strip())
        artist.append(text2)
        i = i + 1
    result = [lyricist, artist]
    return result

In [8]:
# lyricist_gen1의 가수 목록 데이터프레임 생성
i = 0
a = 0
b = 0
lyricist = []
artist = []

lyricist.clear()
artist.clear()
    
for i in range(0, len(lyricist_gen1)):
    try:
        for a in range(0, len(preprocess(lyricist_gen1.lyricist[i], lyricist_gen1.artist[i])[0])):
            lyricist.append(str(preprocess(lyricist_gen1.lyricist[i], lyricist_gen1.artist[i])[0][a]))
        for b in range(0, len(preprocess(lyricist_gen1.lyricist[i], lyricist_gen1.artist[i])[1])):
            artist.append(str(preprocess(lyricist_gen1.lyricist[i], lyricist_gen1.artist[i])[1][b]))
    except:
        lyricist.append('')
        artist.append('')
    
preprocessing_gen1 = pd.DataFrame({"lyricist" : lyricist, "artist" : artist, "generation" : 1})
preprocessing_gen1

          lyricist artist  generation
0              박진영    god           1
1              박진영    god           1
2              박진영    god           1
3              박진영    god           1
4              박진영    god           1
5              안용진    god           1
6              박진영    god           1
7              박진영    god           1
8              박진영    god           1
9              박진영    god           1
10             god    god           1
11             god    god           1
12             god    god           1
13             god    god           1
14             박진영    god           1
15             박진영    god           1
16             박진영    god           1
17             박진영    god           1
18             박진영    god           1
19             박진영    god           1
20             박진영    god           1
21             박진영    god           1
22             박진영    god           1
23             박진영    god           1
24             박진영    god           1
25             박진영    god           1
26             박진영    god           1
27             god    god           1
28             god    god           1
29             박진영    god           1
...            ...    ...         ...
1989           이순자     핑클           1
1990           최연지     핑클           1
1991           최연제     핑클           1
1992           전상진     핑클           1
1993           오승은     핑클           1
1994           강수지     핑클           1
1995           박건호     핑클           1
1996           최명섭     핑클           1
1997           강인원     핑클           1
1998           옥주현     핑클           1
1999           이효리     핑클           1
2000           성유리     핑클           1
2001           옥주현     핑클           1
2002           윤사라     핑클           1
2003           김영아     핑클           1
2004           천정아     핑클           1
2005           옥주현     핑클           1
2006           조은희     핑클           1
2007           김영아     핑클           1
2008           최희진     핑클           1
2009           조규만     핑클           1
2010           이효리     핑클           1
2011           정성윤     핑클           1
2012     정연준 (업타운)     핑클           1
2013            이진     핑클           1
2014           김태윤     핑클           1
2015           이희승     핑클           1
2016  메이비 (Maybee)     핑클           1
2017           이효리     핑클           1
2018           성유리     핑클           1

[2019 rows x 3 columns]

In [9]:
preprocessing_gen1.rename(columns={"lyricist":"source","artist":"target"}, inplace=True)

In [10]:
grouped_idol_gen1 = preprocessing_gen1.groupby(["source","target"]).size().reset_index()
grouped_idol_gen1.head(20) # 갑자기 빈 행이 존재함 ->삭제

            source       target   0
0            1월 8일           신화   2
1             3534          엔알지   2
2             3534          태사자   1
3          A.minor         제이워크   1
4               A4          에이포   1
5              BYP          쥬얼리   1
6         Boy Club        보이 클럽   2
7        Brian Joo  플라이 투 더 스카이   3
8        Brian Kim           신화  11
9   Brian McKnight  플라이 투 더 스카이   1
10      Browncloud           신화   1
11  CARLSON SANNIE          쥬얼리   1
12    COLEGATE ROY         제이티엘   1
13            Crom         문차일드   4
14          Curbin          에이포   1
15           Cyren          태사자   1
16       D.PICKELL           신화   1
17    DAVINK (다빈크)         문차일드   2
18    DAVINK (다빈크)         제이워크   1
19         DJ Tama          쥬얼리   1

In [11]:
# 칼럼 0 -> count로 이름 칼럼명 수정
grouped_idol_gen1.rename(columns={0:'count'}, inplace=True)
len(grouped_idol_gen1)

874

In [12]:
grouped_idol_gen1_ranking = grouped_idol_gen1.sort_values(by='count', ascending=False)
grouped_idol_gen1_ranking = grouped_idol_gen1_ranking.reset_index(drop=True)
grouped_idol_gen1_ranking.head()

    source target  count
0      박진영    god     68
1      유건형   언타이틀     40
2  M (이민우)     신화     26
3      김영아   젝스키스     24
4      이상민    샤크라     23

## json 파일 생성하기

In [13]:
unique_idol = pd.Index(grouped_idol_gen1_ranking['source']
                      .append(grouped_idol_gen1_ranking['target'])
                      .reset_index(drop=True).unique())

In [14]:
unique_idol

Index(['박진영', '유건형', 'M (이민우)', '김영아', '이상민', '이승호', '천명훈', '유영진', '송백경',
       '강타 (KANGTA)',
       ...
       '투야', '스맥스', '러브', '알', '보이 클럽', '티앤비', '에스지', '신비', '블랙 비트', '밀크'],
      dtype='object', length=622)

In [15]:
grouped_idol_gen1_ranking.rename(columns={0:'count'}, inplace=True)
len(grouped_idol_gen1_ranking)

874

In [16]:
grouped_idol_gen1_ranking['count'].unique()

array([68, 40, 26, 24, 23, 22, 19, 18, 17, 16, 14, 13, 12, 11, 10,  9,  8,
        7,  6,  5,  4,  3,  2,  1], dtype=int64)

In [17]:
grouped_idol_gen1_ranking.loc[grouped_idol_gen1_ranking['source'] == "TEDDY"]

   source target  count
22  TEDDY    원타임     11

In [18]:
grouped_idol_gen1_ranking['source'] = grouped_idol_gen1_ranking['source'].replace('TEDDY', '테디')

In [19]:
grouped_idol_gen1_ranking.loc[grouped_idol_gen1_ranking['source'] == "TEDDY"]

Empty DataFrame
Columns: [source, target, count]
Index: []

In [20]:
grouped_idol_gen1_ranking2 = grouped_idol_gen1_ranking[grouped_idol_gen1_ranking['count'] > 5]
grouped_idol_gen1_ranking2

         source       target  count
0           박진영          god     68
1           유건형         언타이틀     40
2       M (이민우)           신화     26
3           김영아         젝스키스     24
4           이상민          샤크라     23
5           이승호           구피     22
6           천명훈          엔알지     19
7           유영진        에이치오티     19
8           김영아           핑클     18
9           송백경          원타임     17
10  강타 (KANGTA)        에이치오티     16
11          서정환         언타이틀     16
12     박성호 (구피)           구피     14
13           테디          원타임     14
14           에릭           신화     14
15          문희준        에이치오티     14
16          신동욱           구피     13
17          유영진           신화     13
18           바다        에스이에스     13
19           제드         디베이스     12
20          장대성         젝스키스     12
21         Rain         제이워크     11
22           테디          원타임     11
23          신승희          테이크     11
24          장우혁         제이티엘     11
25    Brian Kim           신화     11
26          이재원         제이티엘     11
27          유영진        에스이에스     11
28          이승호         젝스키스     10
29          유영진  플라이 투 더 스카이     10
30           버즈           버즈     10
31          이도연           버즈      9
32          서융근  플라이 투 더 스카이      9
33          조은희  플라이 투 더 스카이      9
34          김영아           오션      9
35           Do         디베이스      9
36          이현도         디베이스      9
37         토니 안        에이치오티      9
38          god          god      9
39          안성일         제이워크      9
40          장대성        와이투케이      9
41          김수정           오션      8
42          신혜성           신화      8
43          임선아           버즈      8
44          김영아          엔알지      8
45            렌           오션      8
46          정진환           오션      7
47          조은희           구피      7
48          김진아           버즈      7
49        이단옆차기          god      7
50          안영민           신화      7
51          장용진        에이치오티      6
52          장성재          테이크      6
53          지국현           신화      6
54          조규만  플라이 투 더 스카이      6
55  강타 (KANGTA)           에스      6
56          이현우          엔알지      6
57          김이나           신화      6
58          양재선    베이비 복스 리브      6

In [21]:
grouped_idol_gen1_ranking2 = grouped_idol_gen1_ranking2.reset_index()

In [22]:
grouped_idol_gen1_ranking2 = grouped_idol_gen1_ranking2.drop(['index'], axis = 1)

In [23]:
grouped_idol_gen1_ranking2

         source       target  count
0           박진영          god     68
1           유건형         언타이틀     40
2       M (이민우)           신화     26
3           김영아         젝스키스     24
4           이상민          샤크라     23
5           이승호           구피     22
6           천명훈          엔알지     19
7           유영진        에이치오티     19
8           김영아           핑클     18
9           송백경          원타임     17
10  강타 (KANGTA)        에이치오티     16
11          서정환         언타이틀     16
12     박성호 (구피)           구피     14
13           테디          원타임     14
14           에릭           신화     14
15          문희준        에이치오티     14
16          신동욱           구피     13
17          유영진           신화     13
18           바다        에스이에스     13
19           제드         디베이스     12
20          장대성         젝스키스     12
21         Rain         제이워크     11
22           테디          원타임     11
23          신승희          테이크     11
24          장우혁         제이티엘     11
25    Brian Kim           신화     11
26          이재원         제이티엘     11
27          유영진        에스이에스     11
28          이승호         젝스키스     10
29          유영진  플라이 투 더 스카이     10
30           버즈           버즈     10
31          이도연           버즈      9
32          서융근  플라이 투 더 스카이      9
33          조은희  플라이 투 더 스카이      9
34          김영아           오션      9
35           Do         디베이스      9
36          이현도         디베이스      9
37         토니 안        에이치오티      9
38          god          god      9
39          안성일         제이워크      9
40          장대성        와이투케이      9
41          김수정           오션      8
42          신혜성           신화      8
43          임선아           버즈      8
44          김영아          엔알지      8
45            렌           오션      8
46          정진환           오션      7
47          조은희           구피      7
48          김진아           버즈      7
49        이단옆차기          god      7
50          안영민           신화      7
51          장용진        에이치오티      6
52          장성재          테이크      6
53          지국현           신화      6
54          조규만  플라이 투 더 스카이      6
55  강타 (KANGTA)           에스      6
56          이현우          엔알지      6
57          김이나           신화      6
58          양재선    베이비 복스 리브      6

In [24]:
total_2 = grouped_idol_gen1_ranking2.groupby(['source'], as_index=False).sum()
total2_2 = total_2.sort_values(by='count', ascending=False).reset_index()
total2_2 = total2_2.drop(['index'], axis = 1)
total2_2_sourcename = total2_2['source'].tolist()
total2_2_count = total2_2['count'].tolist()
len(total2_2_sourcename)

48

In [25]:
total2_2

         source  count
0           박진영     68
1           김영아     59
2           유영진     53
3           유건형     40
4           이승호     32
5       M (이민우)     26
6            테디     25
7           이상민     23
8   강타 (KANGTA)     22
9           장대성     21
10          천명훈     19
11          송백경     17
12          조은희     16
13          서정환     16
14          문희준     14
15     박성호 (구피)     14
16           에릭     14
17          신동욱     13
18           바다     13
19           제드     12
20          이재원     11
21         Rain     11
22    Brian Kim     11
23          신승희     11
24          장우혁     11
25           버즈     10
26          이현도      9
27          이도연      9
28         토니 안      9
29          안성일      9
30          god      9
31          서융근      9
32           Do      9
33          신혜성      8
34          임선아      8
35          김수정      8
36            렌      8
37        이단옆차기      7
38          안영민      7
39          정진환      7
40          김진아      7
41          김이나      6
42          지국현      6
43          장용진      6
44          조규만      6
45          장성재      6
46          이현우      6
47          양재선      6

In [26]:
a = pd.Index(total2_2_sourcename)
a

Index(['박진영', '김영아', '유영진', '유건형', '이승호', 'M (이민우)', '테디', '이상민',
       '강타 (KANGTA)', '장대성', '천명훈', '송백경', '조은희', '서정환', '문희준', '박성호 (구피)',
       '에릭', '신동욱', '바다', '제드', '이재원', 'Rain', 'Brian Kim', '신승희', '장우혁', '버즈',
       '이현도', '이도연', '토니 안', '안성일', 'god', '서융근', 'Do', '신혜성', '임선아', '김수정',
       '렌', '이단옆차기', '안영민', '정진환', '김진아', '김이나', '지국현', '장용진', '조규만', '장성재',
       '이현우', '양재선'],
      dtype='object')

In [27]:
unique_idol2 = pd.Index(grouped_idol_gen1_ranking2['source']
                      .append(grouped_idol_gen1_ranking2['target'])
                      .reset_index(drop=True).unique())
unique_idol2_lyricist = pd.Index(grouped_idol_gen1_ranking2['source'] .reset_index(drop=True).unique())
unique_idol2_artist = pd.Index(grouped_idol_gen1_ranking2['target'] .reset_index(drop=True).unique())

In [28]:
len(unique_idol2_lyricist)

48

In [29]:
len(unique_idol2_lyricist)+len(unique_idol2_artist)

69

In [30]:
source_name = grouped_idol_gen1_ranking2['source']

In [31]:
len(source_name)

59

In [32]:
# lyricist_group_dict2
group_dict2_lyricist = {}
group_dict2_lyricist.clear()
counter = 0
for idol in unique_idol2_lyricist:
    if idol not in group_dict2_lyricist:
        counter += 1
        group_dict2_lyricist[idol] = counter
    else:
        pass
group_dict2_lyricist

{'박진영': 1,
 '유건형': 2,
 'M (이민우)': 3,
 '김영아': 4,
 '이상민': 5,
 '이승호': 6,
 '천명훈': 7,
 '유영진': 8,
 '송백경': 9,
 '강타 (KANGTA)': 10,
 '서정환': 11,
 '박성호 (구피)': 12,
 '테디': 13,
 '에릭': 14,
 '문희준': 15,
 '신동욱': 16,
 '바다': 17,
 '제드': 18,
 '장대성': 19,
 'Rain': 20,
 '신승희': 21,
 '장우혁': 22,
 'Brian Kim': 23,
 '이재원': 24,
 '버즈': 25,
 '이도연': 26,
 '서융근': 27,
 '조은희': 28,
 'Do': 29,
 '이현도': 30,
 '토니 안': 31,
 'god': 32,
 '안성일': 33,
 '김수정': 34,
 '신혜성': 35,
 '임선아': 36,
 '렌': 37,
 '정진환': 38,
 '김진아': 39,
 '이단옆차기': 40,
 '안영민': 41,
 '장용진': 42,
 '장성재': 43,
 '지국현': 44,
 '조규만': 45,
 '이현우': 46,
 '김이나': 47,
 '양재선': 48}

In [33]:
# artist_group_dict2
group_dict2_artist = {}
group_dict2_artist.clear()
counter = 48
for idol in unique_idol2_artist:
    if idol not in group_dict2_artist:
        counter += 1
        group_dict2_artist[idol] = counter
    else:
        pass
group_dict2_artist

{'god': 49,
 '언타이틀': 50,
 '신화': 51,
 '젝스키스': 52,
 '샤크라': 53,
 '구피': 54,
 '엔알지': 55,
 '에이치오티': 56,
 '핑클': 57,
 '원타임': 58,
 '에스이에스': 59,
 '디베이스': 60,
 '제이워크': 61,
 '테이크': 62,
 '제이티엘': 63,
 '플라이 투 더 스카이': 64,
 '버즈': 65,
 '오션': 66,
 '와이투케이': 67,
 '에스': 68,
 '베이비 복스 리브': 69}

In [34]:
temp_link_list = []
temp_links_list = list(grouped_idol_gen1_ranking2.apply(lambda row: {"source": row['source'], "target": row['target'], "value": row['count']}, axis=1))

In [35]:
temp_links_list

[{'source': '박진영', 'target': 'god', 'value': 68},
 {'source': '유건형', 'target': '언타이틀', 'value': 40},
 {'source': 'M (이민우)', 'target': '신화', 'value': 26},
 {'source': '김영아', 'target': '젝스키스', 'value': 24},
 {'source': '이상민', 'target': '샤크라', 'value': 23},
 {'source': '이승호', 'target': '구피', 'value': 22},
 {'source': '천명훈', 'target': '엔알지', 'value': 19},
 {'source': '유영진', 'target': '에이치오티', 'value': 19},
 {'source': '김영아', 'target': '핑클', 'value': 18},
 {'source': '송백경', 'target': '원타임', 'value': 17},
 {'source': '강타 (KANGTA)', 'target': '에이치오티', 'value': 16},
 {'source': '서정환', 'target': '언타이틀', 'value': 16},
 {'source': '박성호 (구피)', 'target': '구피', 'value': 14},
 {'source': '테디', 'target': '원타임', 'value': 14},
 {'source': '에릭', 'target': '신화', 'value': 14},
 {'source': '문희준', 'target': '에이치오티', 'value': 14},
 {'source': '신동욱', 'target': '구피', 'value': 13},
 {'source': '유영진', 'target': '신화', 'value': 13},
 {'source': '바다', 'target': '에스이에스', 'value': 13},
 {'source': '제드', 'target': '디베이스', 'value': 12},
 {'source': '장대성', 'target': '젝스키스', 'value': 12},
 {'source': 'Rain', 'target': '제이워크', 'value': 11},
 {'source': '테디', 'target': '원타임', 'value': 11},
 {'source': '신승희', 'target': '테이크', 'value': 11},
 {'source': '장우혁', 'target': '제이티엘', 'value': 11},
 {'source': 'Brian Kim', 'target': '신화', 'value': 11},
 {'source': '이재원', 'target': '제이티엘', 'value': 11},
 {'source': '유영진', 'target': '에스이에스', 'value': 11},
 {'source': '이승호', 'target': '젝스키스', 'value': 10},
 {'source': '유영진', 'target': '플라이 투 더 스카이', 'value': 10},
 {'source': '버즈', 'target': '버즈', 'value': 10},
 {'source': '이도연', 'target': '버즈', 'value': 9},
 {'source': '서융근', 'target': '플라이 투 더 스카이', 'value': 9},
 {'source': '조은희', 'target': '플라이 투 더 스카이', 'value': 9},
 {'source': '김영아', 'target': '오션', 'value': 9},
 {'source': 'Do', 'target': '디베이스', 'value': 9},
 {'source': '이현도', 'target': '디베이스', 'value': 9},
 {'source': '토니 안', 'target': '에이치오티', 'value': 9},
 {'source': 'god', 'target': 'god', 'value': 9},
 {'source': '안성일', 'target': '제이워크', 'value': 9},
 {'source': '장대성', 'target': '와이투케이', 'value': 9},
 {'source': '김수정', 'target': '오션', 'value': 8},
 {'source': '신혜성', 'target': '신화', 'value': 8},
 {'source': '임선아', 'target': '버즈', 'value': 8},
 {'source': '김영아', 'target': '엔알지', 'value': 8},
 {'source': '렌', 'target': '오션', 'value': 8},
 {'source': '정진환', 'target': '오션', 'value': 7},
 {'source': '조은희', 'target': '구피', 'value': 7},
 {'source': '김진아', 'target': '버즈', 'value': 7},
 {'source': '이단옆차기', 'target': 'god', 'value': 7},
 {'source': '안영민', 'target': '신화', 'value': 7},
 {'source': '장용진', 'target': '에이치오티', 'value': 6},
 {'source': '장성재', 'target': '테이크', 'value': 6},
 {'source': '지국현', 'target': '신화', 'value': 6},
 {'source': '조규만', 'target': '플라이 투 더 스카이', 'value': 6},
 {'source': '강타 (KANGTA)', 'target': '에스', 'value': 6},
 {'source': '이현우', 'target': '엔알지', 'value': 6},
 {'source': '김이나', 'target': '신화', 'value': 6},
 {'source': '양재선', 'target': '베이비 복스 리브', 'value': 6}]

In [36]:
links_list = []
for link in temp_links_list:
    record = {"value":link['value'], "source":unique_idol2.get_loc(link['source']),
     "target": unique_idol2.get_loc(link['target'])}
    links_list.append(record)
links_list

[{'value': 68, 'source': 0, 'target': 31},
 {'value': 40, 'source': 1, 'target': 48},
 {'value': 26, 'source': 2, 'target': 49},
 {'value': 24, 'source': 3, 'target': 50},
 {'value': 23, 'source': 4, 'target': 51},
 {'value': 22, 'source': 5, 'target': 52},
 {'value': 19, 'source': 6, 'target': 53},
 {'value': 19, 'source': 7, 'target': 54},
 {'value': 18, 'source': 3, 'target': 55},
 {'value': 17, 'source': 8, 'target': 56},
 {'value': 16, 'source': 9, 'target': 54},
 {'value': 16, 'source': 10, 'target': 48},
 {'value': 14, 'source': 11, 'target': 52},
 {'value': 14, 'source': 12, 'target': 56},
 {'value': 14, 'source': 13, 'target': 49},
 {'value': 14, 'source': 14, 'target': 54},
 {'value': 13, 'source': 15, 'target': 52},
 {'value': 13, 'source': 7, 'target': 49},
 {'value': 13, 'source': 16, 'target': 57},
 {'value': 12, 'source': 17, 'target': 58},
 {'value': 12, 'source': 18, 'target': 50},
 {'value': 11, 'source': 19, 'target': 59},
 {'value': 11, 'source': 12, 'target': 56},
 {'value': 11, 'source': 20, 'target': 60},
 {'value': 11, 'source': 21, 'target': 61},
 {'value': 11, 'source': 22, 'target': 49},
 {'value': 11, 'source': 23, 'target': 61},
 {'value': 11, 'source': 7, 'target': 57},
 {'value': 10, 'source': 5, 'target': 50},
 {'value': 10, 'source': 7, 'target': 62},
 {'value': 10, 'source': 24, 'target': 24},
 {'value': 9, 'source': 25, 'target': 24},
 {'value': 9, 'source': 26, 'target': 62},
 {'value': 9, 'source': 27, 'target': 62},
 {'value': 9, 'source': 3, 'target': 63},
 {'value': 9, 'source': 28, 'target': 58},
 {'value': 9, 'source': 29, 'target': 58},
 {'value': 9, 'source': 30, 'target': 54},
 {'value': 9, 'source': 31, 'target': 31},
 {'value': 9, 'source': 32, 'target': 59},
 {'value': 9, 'source': 18, 'target': 64},
 {'value': 8, 'source': 33, 'target': 63},
 {'value': 8, 'source': 34, 'target': 49},
 {'value': 8, 'source': 35, 'target': 24},
 {'value': 8, 'source': 3, 'target': 53},
 {'value': 8, 'source': 36, 'target': 63},
 {'value': 7, 'source': 37, 'target': 63},
 {'value': 7, 'source': 27, 'target': 52},
 {'value': 7, 'source': 38, 'target': 24},
 {'value': 7, 'source': 39, 'target': 31},
 {'value': 7, 'source': 40, 'target': 49},
 {'value': 6, 'source': 41, 'target': 54},
 {'value': 6, 'source': 42, 'target': 60},
 {'value': 6, 'source': 43, 'target': 49},
 {'value': 6, 'source': 44, 'target': 62},
 {'value': 6, 'source': 9, 'target': 65},
 {'value': 6, 'source': 45, 'target': 53},
 {'value': 6, 'source': 46, 'target': 49},
 {'value': 6, 'source': 47, 'target': 66}]

In [37]:
nodes_list = []
nodes_list.clear()

for idol in group_dict2_lyricist:
    nodes_list.append({"name":idol, "type": "lyricist", "impor":total2_2_count[a.get_loc(idol)]})
for idol2 in group_dict2_artist:  
    nodes_list.append({"name":idol2, "type": "artist", "impor":0})
nodes_list

[{'name': '박진영', 'type': 'lyricist', 'impor': 68},
 {'name': '유건형', 'type': 'lyricist', 'impor': 40},
 {'name': 'M (이민우)', 'type': 'lyricist', 'impor': 26},
 {'name': '김영아', 'type': 'lyricist', 'impor': 59},
 {'name': '이상민', 'type': 'lyricist', 'impor': 23},
 {'name': '이승호', 'type': 'lyricist', 'impor': 32},
 {'name': '천명훈', 'type': 'lyricist', 'impor': 19},
 {'name': '유영진', 'type': 'lyricist', 'impor': 53},
 {'name': '송백경', 'type': 'lyricist', 'impor': 17},
 {'name': '강타 (KANGTA)', 'type': 'lyricist', 'impor': 22},
 {'name': '서정환', 'type': 'lyricist', 'impor': 16},
 {'name': '박성호 (구피)', 'type': 'lyricist', 'impor': 14},
 {'name': '테디', 'type': 'lyricist', 'impor': 25},
 {'name': '에릭', 'type': 'lyricist', 'impor': 14},
 {'name': '문희준', 'type': 'lyricist', 'impor': 14},
 {'name': '신동욱', 'type': 'lyricist', 'impor': 13},
 {'name': '바다', 'type': 'lyricist', 'impor': 13},
 {'name': '제드', 'type': 'lyricist', 'impor': 12},
 {'name': '장대성', 'type': 'lyricist', 'impor': 21},
 {'name': 'Rain', 'type': 'lyricist', 'impor': 11},
 {'name': '신승희', 'type': 'lyricist', 'impor': 11},
 {'name': '장우혁', 'type': 'lyricist', 'impor': 11},
 {'name': 'Brian Kim', 'type': 'lyricist', 'impor': 11},
 {'name': '이재원', 'type': 'lyricist', 'impor': 11},
 {'name': '버즈', 'type': 'lyricist', 'impor': 10},
 {'name': '이도연', 'type': 'lyricist', 'impor': 9},
 {'name': '서융근', 'type': 'lyricist', 'impor': 9},
 {'name': '조은희', 'type': 'lyricist', 'impor': 16},
 {'name': 'Do', 'type': 'lyricist', 'impor': 9},
 {'name': '이현도', 'type': 'lyricist', 'impor': 9},
 {'name': '토니 안', 'type': 'lyricist', 'impor': 9},
 {'name': 'god', 'type': 'lyricist', 'impor': 9},
 {'name': '안성일', 'type': 'lyricist', 'impor': 9},
 {'name': '김수정', 'type': 'lyricist', 'impor': 8},
 {'name': '신혜성', 'type': 'lyricist', 'impor': 8},
 {'name': '임선아', 'type': 'lyricist', 'impor': 8},
 {'name': '렌', 'type': 'lyricist', 'impor': 8},
 {'name': '정진환', 'type': 'lyricist', 'impor': 7},
 {'name': '김진아', 'type': 'lyricist', 'impor': 7},
 {'name': '이단옆차기', 'type': 'lyricist', 'impor': 7},
 {'name': '안영민', 'type': 'lyricist', 'impor': 7},
 {'name': '장용진', 'type': 'lyricist', 'impor': 6},
 {'name': '장성재', 'type': 'lyricist', 'impor': 6},
 {'name': '지국현', 'type': 'lyricist', 'impor': 6},
 {'name': '조규만', 'type': 'lyricist', 'impor': 6},
 {'name': '이현우', 'type': 'lyricist', 'impor': 6},
 {'name': '김이나', 'type': 'lyricist', 'impor': 6},
 {'name': '양재선', 'type': 'lyricist', 'impor': 6},
 {'name': 'god', 'type': 'artist', 'impor': 0},
 {'name': '언타이틀', 'type': 'artist', 'impor': 0},
 {'name': '신화', 'type': 'artist', 'impor': 0},
 {'name': '젝스키스', 'type': 'artist', 'impor': 0},
 {'name': '샤크라', 'type': 'artist', 'impor': 0},
 {'name': '구피', 'type': 'artist', 'impor': 0},
 {'name': '엔알지', 'type': 'artist', 'impor': 0},
 {'name': '에이치오티', 'type': 'artist', 'impor': 0},
 {'name': '핑클', 'type': 'artist', 'impor': 0},
 {'name': '원타임', 'type': 'artist', 'impor': 0},
 {'name': '에스이에스', 'type': 'artist', 'impor': 0},
 {'name': '디베이스', 'type': 'artist', 'impor': 0},
 {'name': '제이워크', 'type': 'artist', 'impor': 0},
 {'name': '테이크', 'type': 'artist', 'impor': 0},
 {'name': '제이티엘', 'type': 'artist', 'impor': 0},
 {'name': '플라이 투 더 스카이', 'type': 'artist', 'impor': 0},
 {'name': '버즈', 'type': 'artist', 'impor': 0},
 {'name': '오션', 'type': 'artist', 'impor': 0},
 {'name': '와이투케이', 'type': 'artist', 'impor': 0},
 {'name': '에스', 'type': 'artist', 'impor': 0},
 {'name': '베이비 복스 리브', 'type': 'artist', 'impor': 0}]

In [38]:
len(nodes_list)

69

In [39]:
len(links_list)

59

In [40]:
json_prep = {"links":links_list, "nodes":nodes_list}

json_prep.keys()

dict_keys(['links', 'nodes'])

In [41]:
json_dump = json.dumps(json_prep, indent=1, sort_keys=True, ensure_ascii=False)

In [42]:
print(json_dump)

{
 "links": [
  {
   "source": 0,
   "target": 31,
   "value": 68
  },
  {
   "source": 1,
   "target": 48,
   "value": 40
  },
  {
   "source": 2,
   "target": 49,
   "value": 26
  },
  {
   "source": 3,
   "target": 50,
   "value": 24
  },
  {
   "source": 4,
   "target": 51,
   "value": 23
  },
  {
   "source": 5,
   "target": 52,
   "value": 22
  },
  {
   "source": 6,
   "target": 53,
   "value": 19
  },
  {
   "source": 7,
   "target": 54,
   "value": 19
  },
  {
   "source": 3,
   "target": 55,
   "value": 18
  },
  {
   "source": 8,
   "target": 56,
   "value": 17
  },
  {
   "source": 9,
   "target": 54,
   "value": 16
  },
  {
   "source": 10,
   "target": 48,
   "value": 16
  },
  {
   "source": 11,
   "target": 52,
   "value": 14
  },
  {
   "source": 12,
   "target": 56,
   "value": 14
  },
  {
   "source": 13,
   "target": 49,
   "value": 14
  },
  {
   "source": 14,
   "target": 54,
   "value": 14
  },
  {
   "source": 15,
   "target": 52,
   "value": 13
  },
  {
   "source": 7,
   "target": 49,
   "value": 13
  },
  {
   "source": 16,
   "target": 57,
   "value": 13
  },
  {
   "source": 17,
   "target": 58,
   "value": 12
  },
  {
   "source": 18,
   "target": 50,
   "value": 12
  },
  {
   "source": 19,
   "target": 59,
   "value": 11
  },
  {
   "source": 12,
   "target": 56,
   "value": 11
  },
  {
   "source": 20,
   "target": 60,
   "value": 11
  },
  {
   "source": 21,
   "target": 61,
   "value": 11
  },
  {
   "source": 22,
   "target": 49,
   "value": 11
  },
  {
   "source": 23,
   "target": 61,
   "value": 11
  },
  {
   "source": 7,
   "target": 57,
   "value": 11
  },
  {
   "source": 5,
   "target": 50,
   "value": 10
  },
  {
   "source": 7,
   "target": 62,
   "value": 10
  },
  {
   "source": 24,
   "target": 24,
   "value": 10
  },
  {
   "source": 25,
   "target": 24,
   "value": 9
  },
  {
   "source": 26,
   "target": 62,
   "value": 9
  },
  {
   "source": 27,
   "target": 62,
   "value": 9
  },
  {
   "source": 3,
   "target": 63,
   "value": 9
  },
  {
   "source": 28,
   "target": 58,
   "value": 9
  },
  {
   "source": 29,
   "target": 58,
   "value": 9
  },
  {
   "source": 30,
   "target": 54,
   "value": 9
  },
  {
   "source": 31,
   "target": 31,
   "value": 9
  },
  {
   "source": 32,
   "target": 59,
   "value": 9
  },
  {
   "source": 18,
   "target": 64,
   "value": 9
  },
  {
   "source": 33,
   "target": 63,
   "value": 8
  },
  {
   "source": 34,
   "target": 49,
   "value": 8
  },
  {
   "source": 35,
   "target": 24,
   "value": 8
  },
  {
   "source": 3,
   "target": 53,
   "value": 8
  },
  {
   "source": 36,
   "target": 63,
   "value": 8
  },
  {
   "source": 37,
   "target": 63,
   "value": 7
  },
  {
   "source": 27,
   "target": 52,
   "value": 7
  },
  {
   "source": 38,
   "target": 24,
   "value": 7
  },
  {
   "source": 39,
   "target": 31,
   "value": 7
  },
  {
   "source": 40,
   "target": 49,
   "value": 7
  },
  {
   "source": 41,
   "target": 54,
   "value": 6
  },
  {
   "source": 42,
   "target": 60,
   "value": 6
  },
  {
   "source": 43,
   "target": 49,
   "value": 6
  },
  {
   "source": 44,
   "target": 62,
   "value": 6
  },
  {
   "source": 9,
   "target": 65,
   "value": 6
  },
  {
   "source": 45,
   "target": 53,
   "value": 6
  },
  {
   "source": 46,
   "target": 49,
   "value": 6
  },
  {
   "source": 47,
   "target": 66,
   "value": 6
  }
 ],
 "nodes": [
  {
   "impor": 68,
   "name": "박진영",
   "type": "lyricist"
  },
  {
   "impor": 40,
   "name": "유건형",
   "type": "lyricist"
  },
  {
   "impor": 26,
   "name": "M (이민우)",
   "type": "lyricist"
  },
  {
   "impor": 59,
   "name": "김영아",
   "type": "lyricist"
  },
  {
   "impor": 23,
   "name": "이상민",
   "type": "lyricist"
  },
  {
   "impor": 32,
   "name": "이승호",
   "type": "lyricist"
  },
  {
   "impor": 19,
   "name": "천명훈",
   "type": "lyricist"
  },
  {
   "impor": 53,
   "name": "유영진",
   "type": "lyricist"
  },
  {
   "impor": 17,
   "name": "송백경",
   "type": "lyricist"
  },
  {
   "impor": 22,
   "name": "강타 (KANGTA)",
   "type": "lyricist"
  },
  {
   "impor": 16,
   "name": "서정환",
   "type": "lyricist"
  },
  {
   "impor": 14,
   "name": "박성호 (구피)",
   "type": "lyricist"
  },
  {
   "impor": 25,
   "name": "테디",
   "type": "lyricist"
  },
  {
   "impor": 14,
   "name": "에릭",
   "type": "lyricist"
  },
  {
   "impor": 14,
   "name": "문희준",
   "type": "lyricist"
  },
  {
   "impor": 13,
   "name": "신동욱",
   "type": "lyricist"
  },
  {
   "impor": 13,
   "name": "바다",
   "type": "lyricist"
  },
  {
   "impor": 12,
   "name": "제드",
   "type": "lyricist"
  },
  {
   "impor": 21,
   "name": "장대성",
   "type": "lyricist"
  },
  {
   "impor": 11,
   "name": "Rain",
   "type": "lyricist"
  },
  {
   "impor": 11,
   "name": "신승희",
   "type": "lyricist"
  },
  {
   "impor": 11,
   "name": "장우혁",
   "type": "lyricist"
  },
  {
   "impor": 11,
   "name": "Brian Kim",
   "type": "lyricist"
  },
  {
   "impor": 11,
   "name": "이재원",
   "type": "lyricist"
  },
  {
   "impor": 10,
   "name": "버즈",
   "type": "lyricist"
  },
  {
   "impor": 9,
   "name": "이도연",
   "type": "lyricist"
  },
  {
   "impor": 9,
   "name": "서융근",
   "type": "lyricist"
  },
  {
   "impor": 16,
   "name": "조은희",
   "type": "lyricist"
  },
  {
   "impor": 9,
   "name": "Do",
   "type": "lyricist"
  },
  {
   "impor": 9,
   "name": "이현도",
   "type": "lyricist"
  },
  {
   "impor": 9,
   "name": "토니 안",
   "type": "lyricist"
  },
  {
   "impor": 9,
   "name": "god",
   "type": "lyricist"
  },
  {
   "impor": 9,
   "name": "안성일",
   "type": "lyricist"
  },
  {
   "impor": 8,
   "name": "김수정",
   "type": "lyricist"
  },
  {
   "impor": 8,
   "name": "신혜성",
   "type": "lyricist"
  },
  {
   "impor": 8,
   "name": "임선아",
   "type": "lyricist"
  },
  {
   "impor": 8,
   "name": "렌",
   "type": "lyricist"
  },
  {
   "impor": 7,
   "name": "정진환",
   "type": "lyricist"
  },
  {
   "impor": 7,
   "name": "김진아",
   "type": "lyricist"
  },
  {
   "impor": 7,
   "name": "이단옆차기",
   "type": "lyricist"
  },
  {
   "impor": 7,
   "name": "안영민",
   "type": "lyricist"
  },
  {
   "impor": 6,
   "name": "장용진",
   "type": "lyricist"
  },
  {
   "impor": 6,
   "name": "장성재",
   "type": "lyricist"
  },
  {
   "impor": 6,
   "name": "지국현",
   "type": "lyricist"
  },
  {
   "impor": 6,
   "name": "조규만",
   "type": "lyricist"
  },
  {
   "impor": 6,
   "name": "이현우",
   "type": "lyricist"
  },
  {
   "impor": 6,
   "name": "김이나",
   "type": "lyricist"
  },
  {
   "impor": 6,
   "name": "양재선",
   "type": "lyricist"
  },
  {
   "impor": 0,
   "name": "god",
   "type": "artist"
  },
  {
   "impor": 0,
   "name": "언타이틀",
   "type": "artist"
  },
  {
   "impor": 0,
   "name": "신화",
   "type": "artist"
  },
  {
   "impor": 0,
   "name": "젝스키스",
   "type": "artist"
  },
  {
   "impor": 0,
   "name": "샤크라",
   "type": "artist"
  },
  {
   "impor": 0,
   "name": "구피",
   "type": "artist"
  },
  {
   "impor": 0,
   "name": "엔알지",
   "type": "artist"
  },
  {
   "impor": 0,
   "name": "에이치오티",
   "type": "artist"
  },
  {
   "impor": 0,
   "name": "핑클",
   "type": "artist"
  },
  {
   "impor": 0,
   "name": "원타임",
   "type": "artist"
  },
  {
   "impor": 0,
   "name": "에스이에스",
   "type": "artist"
  },
  {
   "impor": 0,
   "name": "디베이스",
   "type": "artist"
  },
  {
   "impor": 0,
   "name": "제이워크",
   "type": "artist"
  },
  {
   "impor": 0,
   "name": "테이크",
   "type": "artist"
  },
  {
   "impor": 0,
   "name": "제이티엘",
   "type": "artist"
  },
  {
   "impor": 0,
   "name": "플라이 투 더 스카이",
   "type": "artist"
  },
  {
   "impor": 0,
   "name": "버즈",
   "type": "artist"
  },
  {
   "impor": 0,
   "name": "오션",
   "type": "artist"
  },
  {
   "impor": 0,
   "name": "와이투케이",
   "type": "artist"
  },
  {
   "impor": 0,
   "name": "에스",
   "type": "artist"
  },
  {
   "impor": 0,
   "name": "베이비 복스 리브",
   "type": "artist"
  }
 ]
}

In [43]:
pd.DataFrame(json_prep['nodes'])

    impor         name      type
0      68          박진영  lyricist
1      40          유건형  lyricist
2      26      M (이민우)  lyricist
3      59          김영아  lyricist
4      23          이상민  lyricist
5      32          이승호  lyricist
6      19          천명훈  lyricist
7      53          유영진  lyricist
8      17          송백경  lyricist
9      22  강타 (KANGTA)  lyricist
10     16          서정환  lyricist
11     14     박성호 (구피)  lyricist
12     25           테디  lyricist
13     14           에릭  lyricist
14     14          문희준  lyricist
15     13          신동욱  lyricist
16     13           바다  lyricist
17     12           제드  lyricist
18     21          장대성  lyricist
19     11         Rain  lyricist
20     11          신승희  lyricist
21     11          장우혁  lyricist
22     11    Brian Kim  lyricist
23     11          이재원  lyricist
24     10           버즈  lyricist
25      9          이도연  lyricist
26      9          서융근  lyricist
27     16          조은희  lyricist
28      9           Do  lyricist
29      9          이현도  lyricist
..    ...          ...       ...
39      7        이단옆차기  lyricist
40      7          안영민  lyricist
41      6          장용진  lyricist
42      6          장성재  lyricist
43      6          지국현  lyricist
44      6          조규만  lyricist
45      6          이현우  lyricist
46      6          김이나  lyricist
47      6          양재선  lyricist
48      0          god    artist
49      0         언타이틀    artist
50      0           신화    artist
51      0         젝스키스    artist
52      0          샤크라    artist
53      0           구피    artist
54      0          엔알지    artist
55      0        에이치오티    artist
56      0           핑클    artist
57      0          원타임    artist
58      0        에스이에스    artist
59      0         디베이스    artist
60      0         제이워크    artist
61      0          테이크    artist
62      0         제이티엘    artist
63      0  플라이 투 더 스카이    artist
64      0           버즈    artist
65      0           오션    artist
66      0        와이투케이    artist
67      0           에스    artist
68      0    베이비 복스 리브    artist

[69 rows x 3 columns]

In [44]:
pd.DataFrame(json_prep['links'])

    source  target  value
0        0      31     68
1        1      48     40
2        2      49     26
3        3      50     24
4        4      51     23
5        5      52     22
6        6      53     19
7        7      54     19
8        3      55     18
9        8      56     17
10       9      54     16
11      10      48     16
12      11      52     14
13      12      56     14
14      13      49     14
15      14      54     14
16      15      52     13
17       7      49     13
18      16      57     13
19      17      58     12
20      18      50     12
21      19      59     11
22      12      56     11
23      20      60     11
24      21      61     11
25      22      49     11
26      23      61     11
27       7      57     11
28       5      50     10
29       7      62     10
30      24      24     10
31      25      24      9
32      26      62      9
33      27      62      9
34       3      63      9
35      28      58      9
36      29      58      9
37      30      54      9
38      31      31      9
39      32      59      9
40      18      64      9
41      33      63      8
42      34      49      8
43      35      24      8
44       3      53      8
45      36      63      8
46      37      63      7
47      27      52      7
48      38      24      7
49      39      31      7
50      40      49      7
51      41      54      6
52      42      60      6
53      43      49      6
54      44      62      6
55       9      65      6
56      45      53      6
57      46      49      6
58      47      66      6

In [45]:
filename_out = 'lyricist_gen1.json'
json_out = open(filename_out,'w')
json_out.write(json_dump)
json_out.close()

### 2) Gen2 작업

In [46]:
# lyricist_gen1의 가수 목록 데이터프레임 생성
i = 0
a = 0
b = 0
lyricist = []
artist = []

lyricist.clear()
artist.clear()
    
for i in range(0, len(lyricist_gen2)):
    try:
        for a in range(0, len(preprocess(lyricist_gen2.lyricist[i], lyricist_gen2.artist[i])[0])):
            lyricist.append(str(preprocess(lyricist_gen2.lyricist[i], lyricist_gen2.artist[i])[0][a]))
        for b in range(0, len(preprocess(lyricist_gen2.lyricist[i], lyricist_gen2.artist[i])[1])):
            artist.append(str(preprocess(lyricist_gen2.lyricist[i], lyricist_gen2.artist[i])[1][b]))
    except:
        lyricist.append('')
        artist.append('')
    
preprocessing_gen2 = pd.DataFrame({"lyricist" : lyricist, "artist" : artist, "generation" : 1})
preprocessing_gen2

                 lyricist  artist  generation
0                  용감한 형제  BP 라니아           1
1                  용감한 형제  BP 라니아           1
2                  별들의 전쟁  BP 라니아           1
3                   Tablo  BP 라니아           1
4             Isayama Mio  BP 라니아           1
5               정연준 (업타운)  BP 라니아           1
6             Teddy Riley  BP 라니아           1
7          Richard Garcia  BP 라니아           1
8         ROSEL A MINSTER  BP 라니아           1
9     DOMINIQUE RODRIGUEZ  BP 라니아           1
10         LABYRON WALTON  BP 라니아           1
11                     낯선  BP 라니아           1
12              Alexandra  BP 라니아           1
13                   똘아이박  BP 라니아           1
14                    피터팬  BP 라니아           1
15              Alexandra  BP 라니아           1
16                    김건우  BP 라니아           1
17              Alexandra  BP 라니아           1
18                   똘아이박  BP 라니아           1
19                    피터팬  BP 라니아           1
20                     낯선  BP 라니아           1
21              Alexandra  BP 라니아           1
22                    한영미  BP 라니아           1
23                    피터팬  BP 라니아           1
24                Ashtray    걸스데이           1
25                    윤여훈    걸스데이           1
26                    임은진    걸스데이           1
27                    권태은    걸스데이           1
28        배진렬 (JR Groove)    걸스데이           1
29                    신인수    걸스데이           1
...                   ...     ...         ...
5087               용감한 형제     포미닛           1
5088                  임상혁     포미닛           1
5089               Astroz     포미닛           1
5090               용감한 형제     포미닛           1
5091        권소현 (4minute)     포미닛           1
5092                  김현아     포미닛           1
5093         서재우 (TENTEN)     포미닛           1
5094   ZeroZine (MosPick)     포미닛           1
5095                  조성호     포미닛           1
5096               Misfit     포미닛           1
5097        권소현 (4minute)     포미닛           1
5098     빅싼초 (Yummy Tone)     포미닛           1
5099               Jenyer     포미닛           1
5100     빅싼초 (Yummy Tone)     포미닛           1
5101         서재우 (TENTEN)     포미닛           1
5102     빅싼초 (Yummy Tone)     포미닛           1
5103   ZeroZine (MosPick)     포미닛           1
5104                  김현아     포미닛           1
5105         서재우 (TENTEN)     포미닛           1
5106   ZeroZine (MosPick)     포미닛           1
5107               Jenyer     포미닛           1
5108                   현아     포미닛           1
5109                  라영씨     포미닛           1
5110               Genneo     포미닛           1
5111        권소현 (4minute)     포미닛           1
5112     빅싼초 (Yummy Tone)     포미닛           1
5113                  조성호     포미닛           1
5114                  Ham       햄           1
5115                  이희승       햄           1
5116                    햄       햄           1

[5117 rows x 3 columns]

In [47]:
preprocessing_gen2.rename(columns={"lyricist":"source","artist":"target"}, inplace=True)

In [48]:
grouped_idol_gen2 = preprocessing_gen2.groupby(["source","target"]).size().reset_index()
grouped_idol_gen2.head(20) # 갑자기 빈 행이 존재함 ->삭제

      source      target  0
0          -         엠블랙  1
1        072  브라운 아이드 걸스  1
2     100%서정        에프엑스  2
3     100%서정         트랙스  1
4    17HOLIC         달샤벳  3
5    17HOLIC         씨리얼  1
6    17HOLIC         투피엠  1
7    17HOLIC          틴탑  1
8      1월 8일         샤이니  1
9      1월 8일        소녀시대  2
10     1월 8일  슈퍼 주니어-디앤이  1
11     1월 8일       슈퍼주니어  1
12     1월 8일         엔소닉  1
13  220 VOLT        마이네임  2
14     2Face        투에이엠  1
15     2LSON      애프터 스쿨  1
16    2Story         시크릿  1
17      4번타자         티아라  1
18        72         엔소닉  1
19      9999         씨스타  1

In [49]:
# 엠블랙 제거
grouped_idol_gen2.drop(grouped_idol_gen2.index[[0]], inplace=True)
grouped_idol_gen2 = grouped_idol_gen2.reset_index()
grouped_idol_gen2 = grouped_idol_gen2.drop(['index'], axis = 1)

In [50]:
# 칼럼 0 -> count로 이름 칼럼명 수정
grouped_idol_gen2.rename(columns={0:'count'}, inplace=True)
len(grouped_idol_gen2)

2395

In [51]:
grouped_idol_gen2_ranking = grouped_idol_gen2.sort_values(by='count', ascending=False)
grouped_idol_gen2_ranking = grouped_idol_gen2_ranking.reset_index(drop=True)
grouped_idol_gen2_ranking.head()

         source    target  count
0      G-DRAGON        빅뱅     63
1            바로     비원에이포     54
2  정용화 (CNBLUE)      씨엔블루     49
3           한성호  에프티 아일랜드     45
4           용준형       비스트     42

#### json 파일 생성

In [52]:
unique_idol_2 = pd.Index(grouped_idol_gen2_ranking['source']
                      .append(grouped_idol_gen2_ranking['target'])
                      .reset_index(drop=True).unique())

In [53]:
unique_idol_2

Index(['G-DRAGON', '바로', '정용화 (CNBLUE)', '한성호', '용준형', '송수윤', '진영',
       '지코 (ZICO)', '미료', '이홍기 (FT아일랜드)',
       ...
       '스매쉬 (토니 & 스매쉬)', '지피베이직', '배틀', '천상지희 다나 & 선데이', '브이엔티', '애프터스쿨 블루',
       '에이스타일', '애프터스쿨 레드', '씽', '타키온'],
      dtype='object', length=1538)

In [54]:
grouped_idol_gen2_ranking.rename(columns={0:'count'}, inplace=True)
len(grouped_idol_gen2_ranking)

2395

In [55]:
grouped_idol_gen2_ranking['count'].unique()

array([63, 54, 49, 45, 42, 36, 32, 31, 30, 27, 25, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1],
      dtype=int64)

In [56]:
grouped_idol_gen2_ranking.loc[grouped_idol_gen2_ranking['source'] == "TEDDY"]

    source  target  count
18   TEDDY    투애니원     19
22   TEDDY      빅뱅     17
235  TEDDY  지디 앤 탑      4

In [57]:
grouped_idol_gen2_ranking['source'] = grouped_idol_gen2_ranking['source'].replace('TEDDY', '테디')

In [58]:
grouped_idol_gen2_ranking.loc[grouped_idol_gen2_ranking['source'] == "TEDDY"]

Empty DataFrame
Columns: [source, target, count]
Index: []

In [59]:
grouped_idol_gen2_ranking2 = grouped_idol_gen2_ranking[grouped_idol_gen2_ranking['count'] > 5]
grouped_idol_gen2_ranking2

                  source      target  count
0               G-DRAGON          빅뱅     63
1                     바로       비원에이포     54
2           정용화 (CNBLUE)        씨엔블루     49
3                    한성호    에프티 아일랜드     45
4                    용준형         비스트     42
5                    송수윤       보이프렌드     36
6                     진영       비원에이포     36
7              지코 (ZICO)         블락비     32
8                     미료  브라운 아이드 걸스     31
9           이홍기 (FT아일랜드)    에프티 아일랜드     30
10                   송수윤        인피니트     30
11                용감한 형제          틴탑     27
12                   송수윤          카라     27
13                   한성호        씨엔블루     25
14                   김이나  브라운 아이드 걸스     25
15          이재진 (FT아일랜드)    에프티 아일랜드     20
16                   유영진        동방신기     20
17                   박진영        원더걸스     19
18                    테디        투애니원     19
19                   한재호          카라     18
20                 T.O.P          빅뱅     18
21          차쿤 (일렉트로보이즈)          틴탑     17
22                    테디          빅뱅     17
23                   방시혁        투에이엠     17
24                   강지원         시크릿     16
25              박경 (블락비)         블락비     16
26                   송수윤       나인뮤지스     16
27                   김승수          카라     16
28                   김태주         비스트     15
29   직 재스퍼 (Zick Jasper)        엠아이비     15
..                   ...         ...    ...
120                   천둥         엠블랙      6
121                  이병준     더블에스오공일      6
122                   AJ         유키스      6
123                  민연재         달샤벳      6
124                  원펀치         엔소닉      6
125           민우 (보이프렌드)       보이프렌드      6
126                  김부민         샤이니      6
127                  김영후         샤이니      6
128              키 (KEY)         샤이니      6
129             G-DRAGON      지디 앤 탑      6
130               별들의 전쟁         씨스타      6
131          태완 (Taewan)         엠블랙      6
132                  김영아  브라운 아이드 걸스      6
133         마부스 (Maboos)      브레이브걸스      6
134         준케이 (JUN. K)         투피엠      6
135                  이희승        씨엔블루      6
136         Ryan S. Jhun         유키스      6
137                  전간디         샤이니      6
138                   테디        투애니원      6
139                NODAY         비스트      6
140                   CL        투애니원      6
141                   낯선     제국의 아이들      6
142                  정창욱       나인뮤지스      6
143                   인우         시크릿      6
144                  한재호     더블에스오공일      6
145                  신재훈        엠아이비      6
146                  조영수         티아라      6
147                 Dok2         엠블랙      6
148       Team One Sound  슈퍼 주니어-디앤이      6
149                  조윤경        에프엑스      6

[150 rows x 3 columns]

In [60]:
grouped_idol_gen2_ranking2 = grouped_idol_gen2_ranking2.reset_index()

In [61]:
grouped_idol_gen2_ranking2 = grouped_idol_gen2_ranking2.drop(['index'], axis = 1)

In [62]:
grouped_idol_gen2_ranking2

                  source      target  count
0               G-DRAGON          빅뱅     63
1                     바로       비원에이포     54
2           정용화 (CNBLUE)        씨엔블루     49
3                    한성호    에프티 아일랜드     45
4                    용준형         비스트     42
5                    송수윤       보이프렌드     36
6                     진영       비원에이포     36
7              지코 (ZICO)         블락비     32
8                     미료  브라운 아이드 걸스     31
9           이홍기 (FT아일랜드)    에프티 아일랜드     30
10                   송수윤        인피니트     30
11                용감한 형제          틴탑     27
12                   송수윤          카라     27
13                   한성호        씨엔블루     25
14                   김이나  브라운 아이드 걸스     25
15          이재진 (FT아일랜드)    에프티 아일랜드     20
16                   유영진        동방신기     20
17                   박진영        원더걸스     19
18                    테디        투애니원     19
19                   한재호          카라     18
20                 T.O.P          빅뱅     18
21          차쿤 (일렉트로보이즈)          틴탑     17
22                    테디          빅뱅     17
23                   방시혁        투에이엠     17
24                   강지원         시크릿     16
25              박경 (블락비)         블락비     16
26                   송수윤       나인뮤지스     16
27                   김승수          카라     16
28                   김태주         비스트     15
29   직 재스퍼 (Zick Jasper)        엠아이비     15
..                   ...         ...    ...
120                   천둥         엠블랙      6
121                  이병준     더블에스오공일      6
122                   AJ         유키스      6
123                  민연재         달샤벳      6
124                  원펀치         엔소닉      6
125           민우 (보이프렌드)       보이프렌드      6
126                  김부민         샤이니      6
127                  김영후         샤이니      6
128              키 (KEY)         샤이니      6
129             G-DRAGON      지디 앤 탑      6
130               별들의 전쟁         씨스타      6
131          태완 (Taewan)         엠블랙      6
132                  김영아  브라운 아이드 걸스      6
133         마부스 (Maboos)      브레이브걸스      6
134         준케이 (JUN. K)         투피엠      6
135                  이희승        씨엔블루      6
136         Ryan S. Jhun         유키스      6
137                  전간디         샤이니      6
138                   테디        투애니원      6
139                NODAY         비스트      6
140                   CL        투애니원      6
141                   낯선     제국의 아이들      6
142                  정창욱       나인뮤지스      6
143                   인우         시크릿      6
144                  한재호     더블에스오공일      6
145                  신재훈        엠아이비      6
146                  조영수         티아라      6
147                 Dok2         엠블랙      6
148       Team One Sound  슈퍼 주니어-디앤이      6
149                  조윤경        에프엑스      6

[150 rows x 3 columns]

In [63]:
total_2 = grouped_idol_gen2_ranking2.groupby(['source'], as_index=False).sum()
total2_2 = total_2.sort_values(by='count', ascending=False).reset_index()
total2_2 = total2_2.drop(['index'], axis = 1)
total2_2_sourcename = total2_2['source'].tolist()
total2_2_count = total2_2['count'].tolist()
total2_2

            source  count
0              송수윤    109
1              한성호     70
2         G-DRAGON     69
3           용감한 형제     67
4               바로     54
5     정용화 (CNBLUE)     49
6           kenzie     44
7              용준형     42
8               테디     42
9          신사동 호랭이     40
10             유영진     39
11             박진영     39
12             조윤경     38
13             한재호     37
14              진영     36
15             김이나     34
16       지코 (ZICO)     32
17              미료     31
18    이홍기 (FT아일랜드)     30
19             김승수     29
20           이단옆차기     22
21             최규성     21
22    동해 (DONGHAE)     20
23    마부스 (Maboos)     20
24             이희승     20
25    이재진 (FT아일랜드)     20
26           T.O.P     18
27             방시혁     17
28             김정배     17
29    차쿤 (일렉트로보이즈)     17
..             ...    ...
80           e.one      7
81   Urban Cllasik      7
82             이병준      6
83    Ryan S. Jhun      6
84             김부민      6
85              천둥      6
86      광민 (보이프렌드)      6
87     태완 (Taewan)      6
88         키 (KEY)      6
89              낯선      6
90           NODAY      6
91            Dok2      6
92              CL      6
93             김영후      6
94      민우 (보이프렌드)      6
95             이기광      6
96             박수석      6
97          별들의 전쟁      6
98        지오 (G.O)      6
99    준케이 (JUN. K)      6
100             준Q      6
101       블랙아이드 필승      6
102            신재훈      6
103            조영수      6
104            정창욱      6
105            원펀치      6
106            전간디      6
107       이기 (오레오)      6
108             인우      6
109             AJ      6

[110 rows x 2 columns]

In [64]:
a = pd.Index(total2_2_sourcename)
a

Index(['송수윤', '한성호', 'G-DRAGON', '용감한 형제', '바로', '정용화 (CNBLUE)', 'kenzie',
       '용준형', '테디', '신사동 호랭이',
       ...
       '준Q', '블랙아이드 필승', '신재훈', '조영수', '정창욱', '원펀치', '전간디', '이기 (오레오)', '인우',
       'AJ'],
      dtype='object', length=110)

In [65]:
unique_idol2_2 = pd.Index(grouped_idol_gen2_ranking2['source']
                      .append(grouped_idol_gen2_ranking2['target'])
                      .reset_index(drop=True).unique())
unique_idol2_2_lyricist = pd.Index(grouped_idol_gen2_ranking2['source'] .reset_index(drop=True).unique())
unique_idol2_2_artist = pd.Index(grouped_idol_gen2_ranking2['target'] .reset_index(drop=True).unique())

In [66]:
# lyricist_group_dict2
group_dict2_gen2_lyricist = {}
group_dict2_gen2_lyricist.clear()
counter = 0
for idol in unique_idol2_2_lyricist:
    if idol not in group_dict2_gen2_lyricist:
        counter += 1
        group_dict2_gen2_lyricist[idol] = counter
    else:
        pass
group_dict2_gen2_lyricist

{'G-DRAGON': 1,
 '바로': 2,
 '정용화 (CNBLUE)': 3,
 '한성호': 4,
 '용준형': 5,
 '송수윤': 6,
 '진영': 7,
 '지코 (ZICO)': 8,
 '미료': 9,
 '이홍기 (FT아일랜드)': 10,
 '용감한 형제': 11,
 '김이나': 12,
 '이재진 (FT아일랜드)': 13,
 '유영진': 14,
 '박진영': 15,
 '테디': 16,
 '한재호': 17,
 'T.O.P': 18,
 '차쿤 (일렉트로보이즈)': 19,
 '방시혁': 20,
 '강지원': 21,
 '박경 (블락비)': 22,
 '김승수': 23,
 '김태주': 24,
 '직 재스퍼 (Zick Jasper)': 25,
 '심스 ($IM$)': 26,
 'C.A.P': 27,
 '강남': 28,
 '은혁 (EUNHYUK)': 29,
 '이희승': 30,
 '최종훈 (FT아일랜드)': 31,
 '마부스 (Maboos)': 32,
 '신우': 33,
 '미르 (MBLAQ)': 34,
 '종현 (JONGHYUN)': 35,
 'kenzie': 36,
 '김기범': 37,
 '동해 (DONGHAE)': 38,
 '신사동 호랭이': 39,
 '이단옆차기': 40,
 '미성': 41,
 '최갑원': 42,
 '원택 (1Take)': 43,
 'M.I.B': 44,
 '박초롱 (에이핑크)': 45,
 '조윤경': 46,
 '최규성': 47,
 '김정배': 48,
 '김재중': 49,
 'Good Life': 50,
 '이종현 (CNBLUE)': 51,
 '우리형과 내동생': 52,
 '안영민': 53,
 '이트라이브': 54,
 '유빈 (Yubin)': 55,
 '민연재': 56,
 'SWIN': 57,
 '핫펠트 (예은)': 58,
 '찬성': 59,
 'BEOMxNANG': 60,
 'L.Joe': 61,
 '로빈': 62,
 '라도': 63,
 '택연': 64,
 '민호 (MINHO)': 65,
 '정하나': 66,
 '수빈': 67,
 '마르코': 68,
 '남기상': 69,
 'Team One Sound': 70,
 'Cream (M.I.B)': 71,
 '슈퍼창따이': 72,
 '최강창민 (MAX)': 73,
 'Cream': 74,
 '창조': 75,
 'Misfit': 76,
 '임상혁': 77,
 'e.one': 78,
 '홍지상': 79,
 '원태연': 80,
 'Urban Cllasik': 81,
 '블랙아이드 필승': 82,
 '지오 (G.O)': 83,
 '박수석': 84,
 '김영아': 85,
 '준Q': 86,
 '이기광': 87,
 '이기 (오레오)': 88,
 '광민 (보이프렌드)': 89,
 '천둥': 90,
 '이병준': 91,
 'AJ': 92,
 '원펀치': 93,
 '민우 (보이프렌드)': 94,
 '김부민': 95,
 '김영후': 96,
 '키 (KEY)': 97,
 '별들의 전쟁': 98,
 '태완 (Taewan)': 99,
 '준케이 (JUN. K)': 100,
 'Ryan S. Jhun': 101,
 '전간디': 102,
 'NODAY': 103,
 'CL': 104,
 '낯선': 105,
 '정창욱': 106,
 '인우': 107,
 '신재훈': 108,
 '조영수': 109,
 'Dok2': 110}

In [67]:
# artist_group_dict2
group_dict2_gen2_artist = {}
group_dict2_gen2_artist.clear()
counter = 110
for idol in unique_idol2_2_artist:
    if idol not in group_dict2_gen2_artist:
        counter += 1
        group_dict2_gen2_artist[idol] = counter
    else:
        pass
group_dict2_gen2_artist

{'빅뱅': 111,
 '비원에이포': 112,
 '씨엔블루': 113,
 '에프티 아일랜드': 114,
 '비스트': 115,
 '보이프렌드': 116,
 '블락비': 117,
 '브라운 아이드 걸스': 118,
 '인피니트': 119,
 '틴탑': 120,
 '카라': 121,
 '동방신기': 122,
 '원더걸스': 123,
 '투애니원': 124,
 '투에이엠': 125,
 '시크릿': 126,
 '나인뮤지스': 127,
 '엠아이비': 128,
 '슈퍼주니어': 129,
 '투피엠': 130,
 '엠블랙': 131,
 '샤이니': 132,
 '티아라': 133,
 '씨스타': 134,
 '써니힐': 135,
 '씨리얼': 136,
 '브레이브걸스': 137,
 '에이핑크': 138,
 '에프엑스': 139,
 '소녀시대': 140,
 '제이와이제이': 141,
 '걸스데이': 142,
 '유키스': 143,
 '달샤벳': 144,
 '슈퍼 주니어-디앤이': 145,
 '애프터 스쿨': 146,
 '포미닛': 147,
 '제국의 아이들': 148,
 '파란': 149,
 '컬러링 베이비 7공주': 150,
 '마이네임': 151,
 '오렌지캬라멜': 152,
 '더블에스오공일': 153,
 '엔소닉': 154,
 '지디 앤 탑': 155}

In [68]:
temp_link_list = []
temp_links_list = list(grouped_idol_gen2_ranking2.apply(lambda row: {"source": row['source'], "target": row['target'], "value": row['count']}, axis=1))

In [69]:
temp_links_list

[{'source': 'G-DRAGON', 'target': '빅뱅', 'value': 63},
 {'source': '바로', 'target': '비원에이포', 'value': 54},
 {'source': '정용화 (CNBLUE)', 'target': '씨엔블루', 'value': 49},
 {'source': '한성호', 'target': '에프티 아일랜드', 'value': 45},
 {'source': '용준형', 'target': '비스트', 'value': 42},
 {'source': '송수윤', 'target': '보이프렌드', 'value': 36},
 {'source': '진영', 'target': '비원에이포', 'value': 36},
 {'source': '지코 (ZICO)', 'target': '블락비', 'value': 32},
 {'source': '미료', 'target': '브라운 아이드 걸스', 'value': 31},
 {'source': '이홍기 (FT아일랜드)', 'target': '에프티 아일랜드', 'value': 30},
 {'source': '송수윤', 'target': '인피니트', 'value': 30},
 {'source': '용감한 형제', 'target': '틴탑', 'value': 27},
 {'source': '송수윤', 'target': '카라', 'value': 27},
 {'source': '한성호', 'target': '씨엔블루', 'value': 25},
 {'source': '김이나', 'target': '브라운 아이드 걸스', 'value': 25},
 {'source': '이재진 (FT아일랜드)', 'target': '에프티 아일랜드', 'value': 20},
 {'source': '유영진', 'target': '동방신기', 'value': 20},
 {'source': '박진영', 'target': '원더걸스', 'value': 19},
 {'source': '테디', 'target': '투애니원', 'value': 19},
 {'source': '한재호', 'target': '카라', 'value': 18},
 {'source': 'T.O.P', 'target': '빅뱅', 'value': 18},
 {'source': '차쿤 (일렉트로보이즈)', 'target': '틴탑', 'value': 17},
 {'source': '테디', 'target': '빅뱅', 'value': 17},
 {'source': '방시혁', 'target': '투에이엠', 'value': 17},
 {'source': '강지원', 'target': '시크릿', 'value': 16},
 {'source': '박경 (블락비)', 'target': '블락비', 'value': 16},
 {'source': '송수윤', 'target': '나인뮤지스', 'value': 16},
 {'source': '김승수', 'target': '카라', 'value': 16},
 {'source': '김태주', 'target': '비스트', 'value': 15},
 {'source': '직 재스퍼 (Zick Jasper)', 'target': '엠아이비', 'value': 15},
 {'source': '심스 ($IM$)', 'target': '엠아이비', 'value': 15},
 {'source': 'C.A.P', 'target': '틴탑', 'value': 14},
 {'source': '강남', 'target': '엠아이비', 'value': 14},
 {'source': '은혁 (EUNHYUK)', 'target': '슈퍼주니어', 'value': 14},
 {'source': '박진영', 'target': '투피엠', 'value': 14},
 {'source': '이희승', 'target': '에프티 아일랜드', 'value': 14},
 {'source': '최종훈 (FT아일랜드)', 'target': '에프티 아일랜드', 'value': 14},
 {'source': '마부스 (Maboos)', 'target': '틴탑', 'value': 14},
 {'source': '신우', 'target': '비원에이포', 'value': 13},
 {'source': '미르 (MBLAQ)', 'target': '엠블랙', 'value': 13},
 {'source': '종현 (JONGHYUN)', 'target': '샤이니', 'value': 13},
 {'source': '한재호', 'target': '인피니트', 'value': 13},
 {'source': 'kenzie', 'target': '샤이니', 'value': 13},
 {'source': '김기범', 'target': '시크릿', 'value': 13},
 {'source': '김승수', 'target': '인피니트', 'value': 13},
 {'source': '동해 (DONGHAE)', 'target': '슈퍼주니어', 'value': 12},
 {'source': '신사동 호랭이', 'target': '티아라', 'value': 12},
 {'source': '신사동 호랭이', 'target': '비스트', 'value': 12},
 {'source': '유영진', 'target': '슈퍼주니어', 'value': 12},
 {'source': '이단옆차기', 'target': '씨스타', 'value': 12},
 {'source': '미성', 'target': '써니힐', 'value': 12},
 {'source': '최갑원', 'target': '씨리얼', 'value': 11},
 {'source': '용감한 형제', 'target': '브레이브걸스', 'value': 11},
 {'source': '원택 (1Take)', 'target': '엠블랙', 'value': 11},
 {'source': 'M.I.B', 'target': '엠아이비', 'value': 11},
 {'source': '박초롱 (에이핑크)', 'target': '에이핑크', 'value': 11},
 {'source': '조윤경', 'target': '샤이니', 'value': 11},
 {'source': 'kenzie', 'target': '에프엑스', 'value': 11},
 {'source': '조윤경', 'target': '소녀시대', 'value': 11},
 {'source': '최규성', 'target': '비스트', 'value': 11},
 {'source': '용감한 형제', 'target': '씨스타', 'value': 11},
 {'source': '조윤경', 'target': '슈퍼주니어', 'value': 10},
 {'source': '최규성', 'target': '티아라', 'value': 10},
 {'source': '김정배', 'target': '슈퍼주니어', 'value': 10},
 {'source': '김재중', 'target': '제이와이제이', 'value': 10},
 {'source': '이단옆차기', 'target': '걸스데이', 'value': 10},
 {'source': 'Good Life', 'target': '비스트', 'value': 10},
 {'source': '용감한 형제', 'target': '유키스', 'value': 10},
 {'source': '이종현 (CNBLUE)', 'target': '씨엔블루', 'value': 10},
 {'source': '우리형과 내동생', 'target': '비원에이포', 'value': 10},
 {'source': '안영민', 'target': '티아라', 'value': 10},
 {'source': '김이나', 'target': '써니힐', 'value': 9},
 {'source': '이트라이브', 'target': '달샤벳', 'value': 9},
 {'source': '유빈 (Yubin)', 'target': '원더걸스', 'value': 9},
 {'source': '민연재', 'target': '보이프렌드', 'value': 9},
 {'source': 'SWIN', 'target': '유키스', 'value': 9},
 {'source': '핫펠트 (예은)', 'target': '원더걸스', 'value': 9},
 {'source': '찬성', 'target': '투피엠', 'value': 9},
 {'source': 'BEOMxNANG', 'target': '에이핑크', 'value': 9},
 {'source': 'L.Joe', 'target': '틴탑', 'value': 9},
 {'source': '로빈', 'target': '씨스타', 'value': 9},
 {'source': '동해 (DONGHAE)', 'target': '슈퍼 주니어-디앤이', 'value': 8},
 {'source': '신사동 호랭이', 'target': '에이핑크', 'value': 8},
 {'source': '용감한 형제', 'target': '애프터 스쿨', 'value': 8},
 {'source': '신사동 호랭이', 'target': '포미닛', 'value': 8},
 {'source': '라도', 'target': '엠블랙', 'value': 8},
 {'source': '택연', 'target': '투피엠', 'value': 8},
 {'source': 'kenzie', 'target': '슈퍼주니어', 'value': 8},
 {'source': '민호 (MINHO)', 'target': '샤이니', 'value': 8},
 {'source': '정하나', 'target': '시크릿', 'value': 8},
 {'source': '수빈', 'target': '달샤벳', 'value': 8},
 {'source': '마르코', 'target': '시크릿', 'value': 8},
 {'source': '남기상', 'target': '걸스데이', 'value': 8},
 {'source': 'Team One Sound', 'target': '슈퍼주니어', 'value': 8},
 {'source': 'Cream (M.I.B)', 'target': '엠아이비', 'value': 8},
 {'source': '라도', 'target': '비스트', 'value': 7},
 {'source': '슈퍼창따이', 'target': '투피엠', 'value': 7},
 {'source': '최강창민 (MAX)', 'target': '동방신기', 'value': 7},
 {'source': 'Cream', 'target': '엠아이비', 'value': 7},
 {'source': '창조', 'target': '틴탑', 'value': 7},
 {'source': 'Misfit', 'target': '에프엑스', 'value': 7},
 {'source': '임상혁', 'target': '포미닛', 'value': 7},
 {'source': 'e.one', 'target': '제국의 아이들', 'value': 7},
 {'source': '유영진', 'target': '샤이니', 'value': 7},
 {'source': '홍지상', 'target': '원더걸스', 'value': 7},
 {'source': '원태연', 'target': '파란', 'value': 7},
 {'source': '홍지상', 'target': '투피엠', 'value': 7},
 {'source': '김정배', 'target': '소녀시대', 'value': 7},
 {'source': 'Urban Cllasik', 'target': '제국의 아이들', 'value': 7},
 {'source': '블랙아이드 필승', 'target': '틴탑', 'value': 6},
 {'source': '지오 (G.O)', 'target': '엠블랙', 'value': 6},
 {'source': '박수석', 'target': '시크릿', 'value': 6},
 {'source': '김영아', 'target': '컬러링 베이비 7공주', 'value': 6},
 {'source': '준Q', 'target': '마이네임', 'value': 6},
 {'source': 'kenzie', 'target': '동방신기', 'value': 6},
 {'source': 'kenzie', 'target': '소녀시대', 'value': 6},
 {'source': '이기광', 'target': '비스트', 'value': 6},
 {'source': '이기 (오레오)', 'target': '오렌지캬라멜', 'value': 6},
 {'source': '박진영', 'target': '투에이엠', 'value': 6},
 {'source': '광민 (보이프렌드)', 'target': '보이프렌드', 'value': 6},
 {'source': '천둥', 'target': '엠블랙', 'value': 6},
 {'source': '이병준', 'target': '더블에스오공일', 'value': 6},
 {'source': 'AJ', 'target': '유키스', 'value': 6},
 {'source': '민연재', 'target': '달샤벳', 'value': 6},
 {'source': '원펀치', 'target': '엔소닉', 'value': 6},
 {'source': '민우 (보이프렌드)', 'target': '보이프렌드', 'value': 6},
 {'source': '김부민', 'target': '샤이니', 'value': 6},
 {'source': '김영후', 'target': '샤이니', 'value': 6},
 {'source': '키 (KEY)', 'target': '샤이니', 'value': 6},
 {'source': 'G-DRAGON', 'target': '지디 앤 탑', 'value': 6},
 {'source': '별들의 전쟁', 'target': '씨스타', 'value': 6},
 {'source': '태완 (Taewan)', 'target': '엠블랙', 'value': 6},
 {'source': '김영아', 'target': '브라운 아이드 걸스', 'value': 6},
 {'source': '마부스 (Maboos)', 'target': '브레이브걸스', 'value': 6},
 {'source': '준케이 (JUN. K)', 'target': '투피엠', 'value': 6},
 {'source': '이희승', 'target': '씨엔블루', 'value': 6},
 {'source': 'Ryan S. Jhun', 'target': '유키스', 'value': 6},
 {'source': '전간디', 'target': '샤이니', 'value': 6},
 {'source': '테디', 'target': '투애니원', 'value': 6},
 {'source': 'NODAY', 'target': '비스트', 'value': 6},
 {'source': 'CL', 'target': '투애니원', 'value': 6},
 {'source': '낯선', 'target': '제국의 아이들', 'value': 6},
 {'source': '정창욱', 'target': '나인뮤지스', 'value': 6},
 {'source': '인우', 'target': '시크릿', 'value': 6},
 {'source': '한재호', 'target': '더블에스오공일', 'value': 6},
 {'source': '신재훈', 'target': '엠아이비', 'value': 6},
 {'source': '조영수', 'target': '티아라', 'value': 6},
 {'source': 'Dok2', 'target': '엠블랙', 'value': 6},
 {'source': 'Team One Sound', 'target': '슈퍼 주니어-디앤이', 'value': 6},
 {'source': '조윤경', 'target': '에프엑스', 'value': 6}]

In [70]:
links_list = []
for link in temp_links_list:
    record = {"value":link['value'], "source":unique_idol2_2.get_loc(link['source']),
     "target": unique_idol2_2.get_loc(link['target'])}
    links_list.append(record)
links_list

[{'value': 63, 'source': 0, 'target': 110},
 {'value': 54, 'source': 1, 'target': 111},
 {'value': 49, 'source': 2, 'target': 112},
 {'value': 45, 'source': 3, 'target': 113},
 {'value': 42, 'source': 4, 'target': 114},
 {'value': 36, 'source': 5, 'target': 115},
 {'value': 36, 'source': 6, 'target': 111},
 {'value': 32, 'source': 7, 'target': 116},
 {'value': 31, 'source': 8, 'target': 117},
 {'value': 30, 'source': 9, 'target': 113},
 {'value': 30, 'source': 5, 'target': 118},
 {'value': 27, 'source': 10, 'target': 119},
 {'value': 27, 'source': 5, 'target': 120},
 {'value': 25, 'source': 3, 'target': 112},
 {'value': 25, 'source': 11, 'target': 117},
 {'value': 20, 'source': 12, 'target': 113},
 {'value': 20, 'source': 13, 'target': 121},
 {'value': 19, 'source': 14, 'target': 122},
 {'value': 19, 'source': 15, 'target': 123},
 {'value': 18, 'source': 16, 'target': 120},
 {'value': 18, 'source': 17, 'target': 110},
 {'value': 17, 'source': 18, 'target': 119},
 {'value': 17, 'source': 15, 'target': 110},
 {'value': 17, 'source': 19, 'target': 124},
 {'value': 16, 'source': 20, 'target': 125},
 {'value': 16, 'source': 21, 'target': 116},
 {'value': 16, 'source': 5, 'target': 126},
 {'value': 16, 'source': 22, 'target': 120},
 {'value': 15, 'source': 23, 'target': 114},
 {'value': 15, 'source': 24, 'target': 127},
 {'value': 15, 'source': 25, 'target': 127},
 {'value': 14, 'source': 26, 'target': 119},
 {'value': 14, 'source': 27, 'target': 127},
 {'value': 14, 'source': 28, 'target': 128},
 {'value': 14, 'source': 14, 'target': 129},
 {'value': 14, 'source': 29, 'target': 113},
 {'value': 14, 'source': 30, 'target': 113},
 {'value': 14, 'source': 31, 'target': 119},
 {'value': 13, 'source': 32, 'target': 111},
 {'value': 13, 'source': 33, 'target': 130},
 {'value': 13, 'source': 34, 'target': 131},
 {'value': 13, 'source': 16, 'target': 118},
 {'value': 13, 'source': 35, 'target': 131},
 {'value': 13, 'source': 36, 'target': 125},
 {'value': 13, 'source': 22, 'target': 118},
 {'value': 12, 'source': 37, 'target': 128},
 {'value': 12, 'source': 38, 'target': 132},
 {'value': 12, 'source': 38, 'target': 114},
 {'value': 12, 'source': 13, 'target': 128},
 {'value': 12, 'source': 39, 'target': 133},
 {'value': 12, 'source': 40, 'target': 134},
 {'value': 11, 'source': 41, 'target': 135},
 {'value': 11, 'source': 10, 'target': 136},
 {'value': 11, 'source': 42, 'target': 130},
 {'value': 11, 'source': 43, 'target': 127},
 {'value': 11, 'source': 44, 'target': 137},
 {'value': 11, 'source': 45, 'target': 131},
 {'value': 11, 'source': 35, 'target': 138},
 {'value': 11, 'source': 45, 'target': 139},
 {'value': 11, 'source': 46, 'target': 114},
 {'value': 11, 'source': 10, 'target': 133},
 {'value': 10, 'source': 45, 'target': 128},
 {'value': 10, 'source': 46, 'target': 132},
 {'value': 10, 'source': 47, 'target': 128},
 {'value': 10, 'source': 48, 'target': 140},
 {'value': 10, 'source': 39, 'target': 141},
 {'value': 10, 'source': 49, 'target': 114},
 {'value': 10, 'source': 10, 'target': 142},
 {'value': 10, 'source': 50, 'target': 112},
 {'value': 10, 'source': 51, 'target': 111},
 {'value': 10, 'source': 52, 'target': 132},
 {'value': 9, 'source': 11, 'target': 134},
 {'value': 9, 'source': 53, 'target': 143},
 {'value': 9, 'source': 54, 'target': 122},
 {'value': 9, 'source': 55, 'target': 115},
 {'value': 9, 'source': 56, 'target': 142},
 {'value': 9, 'source': 57, 'target': 122},
 {'value': 9, 'source': 58, 'target': 129},
 {'value': 9, 'source': 59, 'target': 137},
 {'value': 9, 'source': 60, 'target': 119},
 {'value': 9, 'source': 61, 'target': 133},
 {'value': 8, 'source': 37, 'target': 144},
 {'value': 8, 'source': 38, 'target': 137},
 {'value': 8, 'source': 10, 'target': 145},
 {'value': 8, 'source': 38, 'target': 146},
 {'value': 8, 'source': 62, 'target': 130},
 {'value': 8, 'source': 63, 'target': 129},
 {'value': 8, 'source': 35, 'target': 128},
 {'value': 8, 'source': 64, 'target': 131},
 {'value': 8, 'source': 65, 'target': 125},
 {'value': 8, 'source': 66, 'target': 143},
 {'value': 8, 'source': 67, 'target': 125},
 {'value': 8, 'source': 68, 'target': 141},
 {'value': 8, 'source': 69, 'target': 128},
 {'value': 8, 'source': 70, 'target': 127},
 {'value': 7, 'source': 62, 'target': 114},
 {'value': 7, 'source': 71, 'target': 129},
 {'value': 7, 'source': 72, 'target': 121},
 {'value': 7, 'source': 73, 'target': 127},
 {'value': 7, 'source': 74, 'target': 119},
 {'value': 7, 'source': 75, 'target': 138},
 {'value': 7, 'source': 76, 'target': 146},
 {'value': 7, 'source': 77, 'target': 147},
 {'value': 7, 'source': 13, 'target': 131},
 {'value': 7, 'source': 78, 'target': 122},
 {'value': 7, 'source': 79, 'target': 148},
 {'value': 7, 'source': 78, 'target': 129},
 {'value': 7, 'source': 47, 'target': 139},
 {'value': 7, 'source': 80, 'target': 147},
 {'value': 6, 'source': 81, 'target': 119},
 {'value': 6, 'source': 82, 'target': 130},
 {'value': 6, 'source': 83, 'target': 125},
 {'value': 6, 'source': 84, 'target': 149},
 {'value': 6, 'source': 85, 'target': 150},
 {'value': 6, 'source': 35, 'target': 121},
 {'value': 6, 'source': 35, 'target': 139},
 {'value': 6, 'source': 86, 'target': 114},
 {'value': 6, 'source': 87, 'target': 151},
 {'value': 6, 'source': 14, 'target': 124},
 {'value': 6, 'source': 88, 'target': 115},
 {'value': 6, 'source': 89, 'target': 130},
 {'value': 6, 'source': 90, 'target': 152},
 {'value': 6, 'source': 91, 'target': 142},
 {'value': 6, 'source': 55, 'target': 143},
 {'value': 6, 'source': 92, 'target': 153},
 {'value': 6, 'source': 93, 'target': 115},
 {'value': 6, 'source': 94, 'target': 131},
 {'value': 6, 'source': 95, 'target': 131},
 {'value': 6, 'source': 96, 'target': 131},
 {'value': 6, 'source': 0, 'target': 154},
 {'value': 6, 'source': 97, 'target': 133},
 {'value': 6, 'source': 98, 'target': 130},
 {'value': 6, 'source': 84, 'target': 117},
 {'value': 6, 'source': 31, 'target': 136},
 {'value': 6, 'source': 99, 'target': 129},
 {'value': 6, 'source': 29, 'target': 112},
 {'value': 6, 'source': 100, 'target': 142},
 {'value': 6, 'source': 101, 'target': 131},
 {'value': 6, 'source': 15, 'target': 123},
 {'value': 6, 'source': 102, 'target': 114},
 {'value': 6, 'source': 103, 'target': 123},
 {'value': 6, 'source': 104, 'target': 147},
 {'value': 6, 'source': 105, 'target': 126},
 {'value': 6, 'source': 106, 'target': 125},
 {'value': 6, 'source': 16, 'target': 152},
 {'value': 6, 'source': 107, 'target': 127},
 {'value': 6, 'source': 108, 'target': 132},
 {'value': 6, 'source': 109, 'target': 130},
 {'value': 6, 'source': 69, 'target': 144},
 {'value': 6, 'source': 45, 'target': 138}]

In [71]:
nodes_list = []
nodes_list.clear()

for idol in group_dict2_gen2_lyricist:
    nodes_list.append({"name":idol, "type": "lyricist", "impor":total2_2_count[a.get_loc(idol)]})
for idol2 in group_dict2_gen2_artist:  
    nodes_list.append({"name":idol2, "type": "artist", "impor":0})

In [72]:
json_prep = {"links":links_list, "nodes":nodes_list}

json_prep.keys()

dict_keys(['links', 'nodes'])

In [73]:
json_dump = json.dumps(json_prep, indent=1, sort_keys=True, ensure_ascii=False)

In [74]:
filename_out = 'lyricist_gen2.json'
json_out = open(filename_out,'w')
json_out.write(json_dump)
json_out.close()

### 3) Gen3 작업

In [75]:
# lyricist_gen1의 가수 목록 데이터프레임 생성
i = 0
a = 0
b = 0
lyricist = []
artist = []

lyricist.clear()
artist.clear()
    
for i in range(0, len(lyricist_gen3)):
    try:
        for a in range(0, len(preprocess(lyricist_gen3.lyricist[i], lyricist_gen3.artist[i])[0])):
            lyricist.append(str(preprocess(lyricist_gen3.lyricist[i], lyricist_gen3.artist[i])[0][a]))
        for b in range(0, len(preprocess(lyricist_gen3.lyricist[i], lyricist_gen3.artist[i])[1])):
            artist.append(str(preprocess(lyricist_gen3.lyricist[i], lyricist_gen3.artist[i])[1][b]))
    except:
        lyricist.append('')
        artist.append('')
    
preprocessing_gen3 = pd.DataFrame({"lyricist" : lyricist, "artist" : artist, "generation" : 1})
preprocessing_gen3

                lyricist   artist  generation
0                     소연  (여자)아이들           1
1                 Le`mon  (여자)아이들           1
2                     소연  (여자)아이들           1
3     ZeroZine (MosPick)  (여자)아이들           1
4        Ferdy (MosPick)  (여자)아이들           1
5                     소연  (여자)아이들           1
6       빅싼초 (Yummy Tone)  (여자)아이들           1
7       박해일 (Yummy Tone)  (여자)아이들           1
8                   재리포터  (여자)아이들           1
9                     소연  (여자)아이들           1
10                  ARIN  (여자)아이들           1
11              VINCENZO  (여자)아이들           1
12                 Fuxxy  (여자)아이들           1
13          Any Masingga  (여자)아이들           1
14                    소연  (여자)아이들           1
15    ZeroZine (MosPick)  (여자)아이들           1
16                   노경민  (여자)아이들           1
17                   정일훈  (여자)아이들           1
18          서재우 (TENTEN)  (여자)아이들           1
19          서용배 (TENTEN)  (여자)아이들           1
20    BreadBeat (TENTEN)  (여자)아이들           1
21                    현아  (여자)아이들           1
22                   이민혁  (여자)아이들           1
23                   프니엘  (여자)아이들           1
24                   장예은  (여자)아이들           1
25                   권은빈  (여자)아이들           1
26                    이던  (여자)아이들           1
27                    유토  (여자)아이들           1
28              우석 (펜타곤)  (여자)아이들           1
29                    소연  (여자)아이들           1
...                  ...      ...         ...
6737                  KZ     히스토리           1
6738   장이정 (JANGYIJEONG)     히스토리           1
6739               이트라이브     히스토리           1
6740   장이정 (JANGYIJEONG)     히스토리           1
6741   장이정 (JANGYIJEONG)     히스토리           1
6742                 김시형     히스토리           1
6743   장이정 (JANGYIJEONG)     히스토리           1
6744                 김시형     히스토리           1
6745   장이정 (JANGYIJEONG)     히스토리           1
6746                 송경일     히스토리           1
6747                 나도균     히스토리           1
6748                 김태영     히스토리           1
6749   장이정 (JANGYIJEONG)     히스토리           1
6750   장이정 (JANGYIJEONG)     히스토리           1
6751                 김재호     히스토리           1
6752                 김시형     히스토리           1
6753                 김태현       힌트           1
6754                 권도윤       힌트           1
6755                 TAQ       힌트           1
6756                  카푸       힌트           1
6757                 권도윤       힌트           1
6758                 TAQ       힌트           1
6759                  카푸       힌트           1
6760                 권도윤       힌트           1
6761                 TAQ       힌트           1
6762                  카푸       힌트           1
6763                 김남경       힌트           1
6764                 권도윤       힌트           1
6765                 TAQ       힌트           1
6766                  카푸       힌트           1

[6767 rows x 3 columns]

In [76]:
preprocessing_gen3.rename(columns={"lyricist":"source","artist":"target"}, inplace=True)

In [77]:
grouped_idol_gen3 = preprocessing_gen3.groupby(["source","target"]).size().reset_index()
grouped_idol_gen3.head(20) # 갑자기 빈 행이 존재함 ->삭제

     source    target  0
0       $un   엔시티 일이칠  1
1    100%서정        라붐  1
2    100%서정      레드벨벳  1
3    100%서정  소녀시대-태티서  1
4    100%서정      아스트로  1
5    100%서정        엑소  1
6    100%서정    엔시티 드림  1
7    100%서정       첸백시  1
8    100%서정     티알씨엔지  1
9    110403       업텐션  1
10     1105       임팩트  2
11  12월 32일    뉴이스트 W  1
12     1601       소나무  1
13     1601      에이프릴  1
14     1601        카드  1
15  17HOLIC      단발머리  1
16  17HOLIC       비에이  1
17  17HOLIC        빅스  1
18  17HOLIC       소나무  1
19  17HOLIC     소년공화국  1

In [78]:
# 칼럼 0 -> count로 이름 칼럼명 수정
grouped_idol_gen3.rename(columns={0:'count'}, inplace=True)
len(grouped_idol_gen3)

2821

In [79]:
grouped_idol_gen3_ranking = grouped_idol_gen3.sort_values(by='count', ascending=False)
grouped_idol_gen3_ranking = grouped_idol_gen3_ranking.reset_index(drop=True)
grouped_idol_gen3_ranking.head()

   source target  count
0      RM  방탄소년단     86
1    SUGA  방탄소년단     73
2   Pdogg  방탄소년단     70
3     방용국   비에이피     69
4  j-hope  방탄소년단     68

#### json 파일 생성

In [80]:
unique_idol_3 = pd.Index(grouped_idol_gen3_ranking['source']
                      .append(grouped_idol_gen3_ranking['target'])
                      .reset_index(drop=True).unique())

In [81]:
grouped_idol_gen3_ranking.rename(columns={0:'count'}, inplace=True)
len(grouped_idol_gen3_ranking)

2821

In [82]:
grouped_idol_gen3_ranking.loc[grouped_idol_gen3_ranking['source'] == "TEDDY"]

    source target  count
117  TEDDY   블랙핑크      9
517  TEDDY    아이콘      2

In [83]:
grouped_idol_gen3_ranking['source'] = grouped_idol_gen3_ranking['source'].replace('TEDDY', '테디')

In [84]:
grouped_idol_gen3_ranking.loc[grouped_idol_gen3_ranking['source'] == "TEDDY"]

Empty DataFrame
Columns: [source, target, count]
Index: []

In [85]:
grouped_idol_gen3_ranking2 = grouped_idol_gen3_ranking[grouped_idol_gen3_ranking['count'] > 5]
grouped_idol_gen3_ranking2

                  source    target  count
0                     RM     방탄소년단     86
1                   SUGA     방탄소년단     73
2                  Pdogg     방탄소년단     70
3                    방용국      비에이피     69
4                 j-hope     방탄소년단     68
5                라비 (빅스)        빅스     61
6                    정일훈       비투비     58
7             주헌 (몬스타엑스)     몬스타엑스     51
8      WOOZI (SEVENTEEN)       세븐틴     50
9                    이민혁       비투비     48
10           I.M (몬스타엑스)     몬스타엑스     48
11                   방시혁     방탄소년단     41
12               Young K      데이식스     37
13    Vernon (SEVENTEEN)       세븐틴     34
14           Slow Rabbit     방탄소년단     33
15   S.COUPS (SEVENTEEN)       세븐틴     33
16                   B.I       아이콘     32
17                 BUMZU       세븐틴     31
18             LE (EXID)    이엑스아이디     30
19                   프니엘       비투비     30
20              문별 (마마무)       마마무     28
21                 BOBBY       아이콘     27
22              우석 (펜타곤)       펜타곤     27
23           Supreme Boi     방탄소년단     27
24                  MINO        위너     27
25                    이던       펜타곤     26
26                    엑시      우주소녀     25
27        민규 (SEVENTEEN)       세븐틴     22
28            진진 (ASTRO)      아스트로     22
29                   이승훈        위너     21
..                   ...       ...    ...
177          DAY6 (데이식스)      데이식스      6
178            Ollounder      드림캐쳐      6
179                   72      오마이걸      6
180     빅싼초 (Yummy Tone)       비투비      6
181                  마르코       소나무      6
182                  마르코      비아이지      6
183                슈퍼창따이   레이디스 코드      6
184       진리 (Full8loom)      아스트로      6
185                   로아      프리스틴      6
186                ESBEE     몬스타엑스      6
187                   키노       펜타곤      6
188               별들의 전쟁       빅스타      6
189                  남태현        위너      6
190              코스믹 사운드       마마무      6
191  코스믹 걸 (Cosmic Girl)       마마무      6
192            유겸 (GOT7)       갓세븐      6
193           원호 (몬스타엑스)     몬스타엑스      6
194            HOYA (호야)  인피니트 에이치      6
195                   제니       다이아      6
196           MELODESIGN        빅스      6
197                  정일훈       씨엘씨      6
198                  한승훈      엔플라잉      6
199         서재우 (TENTEN)       씨엘씨      6
200           장동우 (인피니트)  인피니트 에이치      6
201                  서지음     몬스타엑스      6
202                  한승훈     에이오에이      6
203   ZeroZine (MosPick)       비투비      6
204                   성현       인투잇      6
205       정한 (SEVENTEEN)       세븐틴      6
206                가면라이더   리얼걸프로젝트      6

[207 rows x 3 columns]

In [86]:
grouped_idol_gen3_ranking2 = grouped_idol_gen3_ranking2.reset_index()

In [87]:
grouped_idol_gen3_ranking2 = grouped_idol_gen3_ranking2.drop(['index'], axis = 1)

In [88]:
total_2 = grouped_idol_gen3_ranking2.groupby(['source'], as_index=False).sum()
total2_2 = total_2.sort_values(by='count', ascending=False).reset_index()
total2_2 = total2_2.drop(['index'], axis = 1)
total2_2_sourcename = total2_2['source'].tolist()
total2_2_count = total2_2['count'].tolist()
test = total2_2.head(100)

In [89]:
writer = pd.ExcelWriter('Gen3_total_list.xlsx')
test.to_excel(writer,'Sheet1')
writer.save()

In [90]:
a = pd.Index(total2_2_sourcename)
a

Index(['RM', 'SUGA', 'Pdogg', '방용국', 'j-hope', '정일훈', '라비 (빅스)', '주헌 (몬스타엑스)',
       'WOOZI (SEVENTEEN)', 'BUMZU',
       ...
       'Ollounder', '유겸 (GOT7)', '진리 (Full8loom)', '가면라이더', '제니',
       '정한 (SEVENTEEN)', '로아', '남태현', '김이나', '72'],
      dtype='object', length=177)

In [91]:
unique_idol2 = pd.Index(grouped_idol_gen3_ranking2['source']
                      .append(grouped_idol_gen3_ranking2['target'])
                      .reset_index(drop=True).unique())
unique_idol2_lyricist = pd.Index(grouped_idol_gen3_ranking2['source'] .reset_index(drop=True).unique())
unique_idol2_artist = pd.Index(grouped_idol_gen3_ranking2['target'] .reset_index(drop=True).unique())

In [92]:
# lyricist_group_dict2
group_dict2_lyricist = {}
group_dict2_lyricist.clear()
counter = 0
for idol in unique_idol2_lyricist:
    if idol not in group_dict2_lyricist:
        counter += 1
        group_dict2_lyricist[idol] = counter
    else:
        pass
group_dict2_lyricist

{'RM': 1,
 'SUGA': 2,
 'Pdogg': 3,
 '방용국': 4,
 'j-hope': 5,
 '라비 (빅스)': 6,
 '정일훈': 7,
 '주헌 (몬스타엑스)': 8,
 'WOOZI (SEVENTEEN)': 9,
 '이민혁': 10,
 'I.M (몬스타엑스)': 11,
 '방시혁': 12,
 'Young K': 13,
 'Vernon (SEVENTEEN)': 14,
 'Slow Rabbit': 15,
 'S.COUPS (SEVENTEEN)': 16,
 'B.I': 17,
 'BUMZU': 18,
 'LE (EXID)': 19,
 '프니엘': 20,
 '문별 (마마무)': 21,
 'BOBBY': 22,
 '우석 (펜타곤)': 23,
 'Supreme Boi': 24,
 'MINO': 25,
 '이던': 26,
 '엑시': 27,
 '민규 (SEVENTEEN)': 28,
 '진진 (ASTRO)': 29,
 '이승훈': 30,
 '박우상': 31,
 '유토': 32,
 '라키 (ASTRO)': 33,
 '김지향': 34,
 '이승협 (J.DON)': 35,
 '한 (3RACHA)': 36,
 '방찬 (3RACHA)': 37,
 '서재우 (TENTEN)': 38,
 '도한세 (VICTON)': 39,
 '창빈 (3RACHA)': 40,
 '원우 (SEVENTEEN)': 41,
 '임현식': 42,
 'SWEETUNE': 43,
 'JB (GOT7)': 44,
 '지민 (AOA)': 45,
 'T.K': 46,
 '김도훈 (RBW)': 47,
 '이기 (오레오)': 48,
 'HighTop': 49,
 '강승윤': 50,
 '용감한 형제': 51,
 '신사동 호랭이': 52,
 'Rome': 53,
 '서지음': 54,
 '박수석': 55,
 '한성호': 56,
 '디노 (SEVENTEEN)': 57,
 '용배 (RBW)': 58,
 '김태주': 59,
 '강지원': 60,
 '김기범': 61,
 '화사 (마마무)': 62,
 '미미 (오마이걸)': 63,
 'kenzie': 64,
 'JQ': 65,
 '서용배 (TENTEN)': 66,
 '호시 (SEVENTEEN)': 67,
 '예빈 (다이아)': 68,
 '기희현': 69,
 '김창락': 70,
 '장예은': 71,
 'KZ': 72,
 '정욱': 73,
 '마르코': 74,
 '낯선': 75,
 'BM': 76,
 'JR (뉴이스트)': 77,
 '솔라 (마마무)': 78,
 '마크 (MARK)': 79,
 '태용 (TAEYONG)': 80,
 'Sofar': 81,
 '마부스 (Maboos)': 82,
 '한승우 (VICTON)': 83,
 '조성호': 84,
 'ADORA': 85,
 'Hip Wave Sound': 86,
 '빅싼초 (Yummy Tone)': 87,
 'J.seph': 88,
 '원필': 89,
 '알렉스 (하이포)': 90,
 '장이정 (JANGYIJEONG)': 91,
 '후이 (펜타곤)': 92,
 '임영준 (하이포)': 93,
 '신준섭': 94,
 '예지': 95,
 'Z-uK (지욱)': 96,
 '뱀뱀 (GOT7)': 97,
 '백호 (뉴이스트)': 98,
 '용준형': 99,
 '조윤경': 100,
 '은진': 101,
 '차쿤 (일렉트로보이즈)': 102,
 '인우': 103,
 'ZeroZine (MosPick)': 104,
 'P.O (블락비)': 105,
 '권현빈': 106,
 '젤로': 107,
 '비토': 108,
 'earattack': 109,
 '테디': 110,
 '장준': 111,
 '라도': 112,
 'Chloe': 113,
 '최갑원': 114,
 '이단옆차기': 115,
 '김상균': 116,
 '미친감성': 117,
 'Ferdy (MosPick)': 118,
 'NODAY': 119,
 '리시': 120,
 '웨이': 121,
 '은수': 122,
 '마크 (GOT7)': 123,
 'TAG': 124,
 '박진영': 125,
 '버피 (BUFFY)': 126,
 '승관 (SEVENTEEN)': 127,
 '성연': 128,
 '황현 (MonoTree)': 129,
 '소연': 130,
 '임팩트': 131,
 '몬스터팩토리': 132,
 '강동하': 133,
 '진영 (GOT7)': 134,
 '슬리피': 135,
 '함길수': 136,
 '리나': 137,
 '일 (IL)': 138,
 '이노베이터': 139,
 '윤후': 140,
 '잭슨 (GOT7)': 141,
 '전다운': 142,
 '박은우': 143,
 '유니스': 144,
 '정하': 145,
 '우태운': 146,
 '쿤': 147,
 'John K': 148,
 '찬열': 149,
 '영재 (GOT7)': 150,
 'Mafly': 151,
 '서림': 152,
 'David Kim': 153,
 '김미진': 154,
 '김이나': 155,
 'DAY6 (데이식스)': 156,
 'Ollounder': 157,
 '72': 158,
 '슈퍼창따이': 159,
 '진리 (Full8loom)': 160,
 '로아': 161,
 'ESBEE': 162,
 '키노': 163,
 '별들의 전쟁': 164,
 '남태현': 165,
 '코스믹 사운드': 166,
 '코스믹 걸 (Cosmic Girl)': 167,
 '유겸 (GOT7)': 168,
 '원호 (몬스타엑스)': 169,
 'HOYA (호야)': 170,
 '제니': 171,
 'MELODESIGN': 172,
 '한승훈': 173,
 '장동우 (인피니트)': 174,
 '성현': 175,
 '정한 (SEVENTEEN)': 176,
 '가면라이더': 177}

In [93]:
# artist_group_dict2
group_dict2_artist = {}
group_dict2_artist.clear()
counter = 177
for idol in unique_idol2_artist:
    if idol not in group_dict2_artist:
        counter += 1
        group_dict2_artist[idol] = counter
    else:
        pass
group_dict2_artist

{'방탄소년단': 178,
 '비에이피': 179,
 '빅스': 180,
 '비투비': 181,
 '몬스타엑스': 182,
 '세븐틴': 183,
 '데이식스': 184,
 '아이콘': 185,
 '이엑스아이디': 186,
 '마마무': 187,
 '펜타곤': 188,
 '위너': 189,
 '우주소녀': 190,
 '아스트로': 191,
 '엔플라잉': 192,
 '스트레이 키즈': 193,
 '빅톤': 194,
 '스누퍼': 195,
 '갓세븐': 196,
 '에이오에이': 197,
 '씨클라운': 198,
 '여자친구': 199,
 '빅플로': 200,
 '오마이걸': 201,
 '크나큰': 202,
 '레드벨벳': 203,
 '엑소': 204,
 '다이아': 205,
 '씨엘씨': 206,
 '헤일로': 207,
 '투포케이': 208,
 '빅스타': 209,
 '에스에프나인': 210,
 '카드': 211,
 '뉴이스트': 212,
 '엔시티 드림': 213,
 '엔시티 일이칠': 214,
 '뉴이스트 W': 215,
 '마이틴': 216,
 '비비드': 217,
 '하이포': 218,
 '히스토리': 219,
 '백퍼센트': 220,
 '피에스타': 221,
 '하이라이트': 222,
 '블락비 바스타즈': 223,
 '제이비제이': 224,
 '업텐션': 225,
 '블랙핑크': 226,
 '골든차일드': 227,
 '소나무': 228,
 '제이제이씨씨': 229,
 '매드타운': 230,
 '프리스틴': 231,
 '온앤오프': 232,
 '(여자)아이들': 233,
 '임팩트': 234,
 '러블리즈': 235,
 '미스터미스터': 236,
 '비트윈': 237,
 '스피드': 238,
 '모모랜드': 239,
 '비비드걸': 240,
 '드림캐쳐': 241,
 '비아이지': 242,
 '레이디스 코드': 243,
 '인피니트 에이치': 244,
 '인투잇': 245,
 '리얼걸프로젝트': 246}

In [94]:
temp_link_list = []
temp_links_list = list(grouped_idol_gen3_ranking2.apply(lambda row: {"source": row['source'], "target": row['target'], "value": row['count']}, axis=1))

In [95]:
links_list = []
for link in temp_links_list:
    record = {"value":link['value'], "source":unique_idol2.get_loc(link['source']),
     "target": unique_idol2.get_loc(link['target'])}
    links_list.append(record)
links_list

[{'value': 86, 'source': 0, 'target': 177},
 {'value': 73, 'source': 1, 'target': 177},
 {'value': 70, 'source': 2, 'target': 177},
 {'value': 69, 'source': 3, 'target': 178},
 {'value': 68, 'source': 4, 'target': 177},
 {'value': 61, 'source': 5, 'target': 179},
 {'value': 58, 'source': 6, 'target': 180},
 {'value': 51, 'source': 7, 'target': 181},
 {'value': 50, 'source': 8, 'target': 182},
 {'value': 48, 'source': 9, 'target': 180},
 {'value': 48, 'source': 10, 'target': 181},
 {'value': 41, 'source': 11, 'target': 177},
 {'value': 37, 'source': 12, 'target': 183},
 {'value': 34, 'source': 13, 'target': 182},
 {'value': 33, 'source': 14, 'target': 177},
 {'value': 33, 'source': 15, 'target': 182},
 {'value': 32, 'source': 16, 'target': 184},
 {'value': 31, 'source': 17, 'target': 182},
 {'value': 30, 'source': 18, 'target': 185},
 {'value': 30, 'source': 19, 'target': 180},
 {'value': 28, 'source': 20, 'target': 186},
 {'value': 27, 'source': 21, 'target': 184},
 {'value': 27, 'source': 22, 'target': 187},
 {'value': 27, 'source': 23, 'target': 177},
 {'value': 27, 'source': 24, 'target': 188},
 {'value': 26, 'source': 25, 'target': 187},
 {'value': 25, 'source': 26, 'target': 189},
 {'value': 22, 'source': 27, 'target': 182},
 {'value': 22, 'source': 28, 'target': 190},
 {'value': 21, 'source': 29, 'target': 188},
 {'value': 21, 'source': 30, 'target': 186},
 {'value': 21, 'source': 31, 'target': 187},
 {'value': 21, 'source': 32, 'target': 190},
 {'value': 21, 'source': 33, 'target': 179},
 {'value': 20, 'source': 34, 'target': 191},
 {'value': 19, 'source': 35, 'target': 192},
 {'value': 19, 'source': 36, 'target': 192},
 {'value': 19, 'source': 37, 'target': 180},
 {'value': 19, 'source': 38, 'target': 193},
 {'value': 19, 'source': 39, 'target': 192},
 {'value': 18, 'source': 40, 'target': 182},
 {'value': 18, 'source': 41, 'target': 180},
 {'value': 17, 'source': 42, 'target': 194},
 {'value': 17, 'source': 43, 'target': 195},
 {'value': 16, 'source': 44, 'target': 196},
 {'value': 16, 'source': 45, 'target': 197},
 {'value': 15, 'source': 46, 'target': 186},
 {'value': 15, 'source': 47, 'target': 198},
 {'value': 15, 'source': 48, 'target': 199},
 {'value': 15, 'source': 49, 'target': 188},
 {'value': 15, 'source': 50, 'target': 196},
 {'value': 15, 'source': 51, 'target': 185},
 {'value': 15, 'source': 52, 'target': 197},
 {'value': 15, 'source': 53, 'target': 200},
 {'value': 15, 'source': 54, 'target': 178},
 {'value': 15, 'source': 55, 'target': 196},
 {'value': 14, 'source': 56, 'target': 182},
 {'value': 14, 'source': 57, 'target': 198},
 {'value': 14, 'source': 58, 'target': 201},
 {'value': 14, 'source': 59, 'target': 178},
 {'value': 14, 'source': 60, 'target': 178},
 {'value': 13, 'source': 61, 'target': 186},
 {'value': 13, 'source': 62, 'target': 200},
 {'value': 13, 'source': 63, 'target': 202},
 {'value': 13, 'source': 64, 'target': 203},
 {'value': 13, 'source': 65, 'target': 180},
 {'value': 13, 'source': 66, 'target': 182},
 {'value': 13, 'source': 67, 'target': 204},
 {'value': 13, 'source': 68, 'target': 204},
 {'value': 13, 'source': 69, 'target': 178},
 {'value': 13, 'source': 70, 'target': 205},
 {'value': 12, 'source': 71, 'target': 206},
 {'value': 12, 'source': 72, 'target': 207},
 {'value': 12, 'source': 47, 'target': 190},
 {'value': 12, 'source': 50, 'target': 208},
 {'value': 12, 'source': 73, 'target': 178},
 {'value': 12, 'source': 69, 'target': 209},
 {'value': 12, 'source': 74, 'target': 210},
 {'value': 12, 'source': 75, 'target': 210},
 {'value': 12, 'source': 76, 'target': 211},
 {'value': 12, 'source': 77, 'target': 186},
 {'value': 12, 'source': 78, 'target': 212},
 {'value': 11, 'source': 79, 'target': 213},
 {'value': 11, 'source': 17, 'target': 214},
 {'value': 11, 'source': 80, 'target': 215},
 {'value': 11, 'source': 81, 'target': 208},
 {'value': 11, 'source': 82, 'target': 193},
 {'value': 11, 'source': 76, 'target': 214},
 {'value': 11, 'source': 83, 'target': 180},
 {'value': 11, 'source': 84, 'target': 177},
 {'value': 11, 'source': 85, 'target': 216},
 {'value': 11, 'source': 86, 'target': 205},
 {'value': 11, 'source': 87, 'target': 210},
 {'value': 10, 'source': 88, 'target': 183},
 {'value': 10, 'source': 89, 'target': 217},
 {'value': 10, 'source': 90, 'target': 218},
 {'value': 10, 'source': 91, 'target': 187},
 {'value': 10, 'source': 42, 'target': 219},
 {'value': 10, 'source': 92, 'target': 217},
 {'value': 10, 'source': 93, 'target': 215},
 {'value': 10, 'source': 94, 'target': 220},
 {'value': 10, 'source': 95, 'target': 199},
 {'value': 10, 'source': 96, 'target': 195},
 {'value': 10, 'source': 78, 'target': 213},
 {'value': 10, 'source': 83, 'target': 205},
 {'value': 9, 'source': 97, 'target': 214},
 {'value': 9, 'source': 98, 'target': 221},
 {'value': 9, 'source': 99, 'target': 203},
 {'value': 9, 'source': 100, 'target': 204},
 {'value': 9, 'source': 101, 'target': 196},
 {'value': 9, 'source': 102, 'target': 178},
 {'value': 9, 'source': 103, 'target': 205},
 {'value': 9, 'source': 104, 'target': 222},
 {'value': 9, 'source': 105, 'target': 223},
 {'value': 9, 'source': 106, 'target': 178},
 {'value': 9, 'source': 107, 'target': 224},
 {'value': 9, 'source': 108, 'target': 195},
 {'value': 9, 'source': 109, 'target': 225},
 {'value': 8, 'source': 110, 'target': 226},
 {'value': 8, 'source': 54, 'target': 227},
 {'value': 8, 'source': 111, 'target': 197},
 {'value': 8, 'source': 112, 'target': 195},
 {'value': 8, 'source': 113, 'target': 217},
 {'value': 8, 'source': 114, 'target': 228},
 {'value': 8, 'source': 115, 'target': 223},
 {'value': 8, 'source': 116, 'target': 206},
 {'value': 8, 'source': 117, 'target': 205},
 {'value': 8, 'source': 118, 'target': 195},
 {'value': 8, 'source': 57, 'target': 190},
 {'value': 8, 'source': 119, 'target': 181},
 {'value': 8, 'source': 120, 'target': 224},
 {'value': 8, 'source': 121, 'target': 215},
 {'value': 8, 'source': 122, 'target': 195},
 {'value': 8, 'source': 99, 'target': 202},
 {'value': 8, 'source': 63, 'target': 203},
 {'value': 8, 'source': 123, 'target': 226},
 {'value': 8, 'source': 53, 'target': 203},
 {'value': 8, 'source': 17, 'target': 211},
 {'value': 8, 'source': 124, 'target': 195},
 {'value': 8, 'source': 125, 'target': 229},
 {'value': 8, 'source': 126, 'target': 182},
 {'value': 8, 'source': 127, 'target': 230},
 {'value': 7, 'source': 128, 'target': 231},
 {'value': 7, 'source': 129, 'target': 232},
 {'value': 7, 'source': 130, 'target': 130},
 {'value': 7, 'source': 131, 'target': 204},
 {'value': 7, 'source': 132, 'target': 187},
 {'value': 7, 'source': 133, 'target': 195},
 {'value': 7, 'source': 134, 'target': 178},
 {'value': 7, 'source': 135, 'target': 216},
 {'value': 7, 'source': 69, 'target': 191},
 {'value': 7, 'source': 53, 'target': 233},
 {'value': 7, 'source': 136, 'target': 234},
 {'value': 7, 'source': 137, 'target': 180},
 {'value': 7, 'source': 138, 'target': 191},
 {'value': 7, 'source': 101, 'target': 208},
 {'value': 7, 'source': 139, 'target': 235},
 {'value': 7, 'source': 140, 'target': 195},
 {'value': 7, 'source': 117, 'target': 180},
 {'value': 7, 'source': 141, 'target': 178},
 {'value': 7, 'source': 142, 'target': 227},
 {'value': 7, 'source': 143, 'target': 204},
 {'value': 7, 'source': 144, 'target': 235},
 {'value': 7, 'source': 145, 'target': 236},
 {'value': 7, 'source': 146, 'target': 224},
 {'value': 7, 'source': 114, 'target': 237},
 {'value': 7, 'source': 147, 'target': 238},
 {'value': 7, 'source': 55, 'target': 209},
 {'value': 7, 'source': 148, 'target': 203},
 {'value': 6, 'source': 65, 'target': 190},
 {'value': 6, 'source': 149, 'target': 195},
 {'value': 6, 'source': 114, 'target': 236},
 {'value': 6, 'source': 150, 'target': 198},
 {'value': 6, 'source': 151, 'target': 203},
 {'value': 6, 'source': 152, 'target': 228},
 {'value': 6, 'source': 153, 'target': 179},
 {'value': 6, 'source': 154, 'target': 179},
 {'value': 6, 'source': 155, 'target': 183},
 {'value': 6, 'source': 156, 'target': 239},
 {'value': 6, 'source': 157, 'target': 200},
 {'value': 6, 'source': 86, 'target': 180},
 {'value': 6, 'source': 73, 'target': 227},
 {'value': 6, 'source': 73, 'target': 240},
 {'value': 6, 'source': 158, 'target': 241},
 {'value': 6, 'source': 159, 'target': 190},
 {'value': 6, 'source': 160, 'target': 230},
 {'value': 6, 'source': 161, 'target': 181},
 {'value': 6, 'source': 162, 'target': 187},
 {'value': 6, 'source': 163, 'target': 208},
 {'value': 6, 'source': 164, 'target': 188},
 {'value': 6, 'source': 165, 'target': 186},
 {'value': 6, 'source': 166, 'target': 186},
 {'value': 6, 'source': 167, 'target': 195},
 {'value': 6, 'source': 168, 'target': 181},
 {'value': 6, 'source': 169, 'target': 242},
 {'value': 6, 'source': 170, 'target': 204},
 {'value': 6, 'source': 171, 'target': 179},
 {'value': 6, 'source': 6, 'target': 205},
 {'value': 6, 'source': 172, 'target': 191},
 {'value': 6, 'source': 37, 'target': 205},
 {'value': 6, 'source': 173, 'target': 242},
 {'value': 6, 'source': 53, 'target': 181},
 {'value': 6, 'source': 172, 'target': 196},
 {'value': 6, 'source': 103, 'target': 180},
 {'value': 6, 'source': 174, 'target': 243},
 {'value': 6, 'source': 175, 'target': 182},
 {'value': 6, 'source': 176, 'target': 244}]

In [96]:
nodes_list = []
nodes_list.clear()

for idol in group_dict2_lyricist:
    nodes_list.append({"name":idol, "type": "lyricist", "impor":total2_2_count[a.get_loc(idol)]})
for idol2 in group_dict2_artist:  
    nodes_list.append({"name":idol2, "type": "artist", "impor":0})
nodes_list

[{'name': 'RM', 'type': 'lyricist', 'impor': 86},
 {'name': 'SUGA', 'type': 'lyricist', 'impor': 73},
 {'name': 'Pdogg', 'type': 'lyricist', 'impor': 70},
 {'name': '방용국', 'type': 'lyricist', 'impor': 69},
 {'name': 'j-hope', 'type': 'lyricist', 'impor': 68},
 {'name': '라비 (빅스)', 'type': 'lyricist', 'impor': 61},
 {'name': '정일훈', 'type': 'lyricist', 'impor': 64},
 {'name': '주헌 (몬스타엑스)', 'type': 'lyricist', 'impor': 51},
 {'name': 'WOOZI (SEVENTEEN)', 'type': 'lyricist', 'impor': 50},
 {'name': '이민혁', 'type': 'lyricist', 'impor': 48},
 {'name': 'I.M (몬스타엑스)', 'type': 'lyricist', 'impor': 48},
 {'name': '방시혁', 'type': 'lyricist', 'impor': 41},
 {'name': 'Young K', 'type': 'lyricist', 'impor': 37},
 {'name': 'Vernon (SEVENTEEN)', 'type': 'lyricist', 'impor': 34},
 {'name': 'Slow Rabbit', 'type': 'lyricist', 'impor': 33},
 {'name': 'S.COUPS (SEVENTEEN)', 'type': 'lyricist', 'impor': 33},
 {'name': 'B.I', 'type': 'lyricist', 'impor': 32},
 {'name': 'BUMZU', 'type': 'lyricist', 'impor': 50},
 {'name': 'LE (EXID)', 'type': 'lyricist', 'impor': 30},
 {'name': '프니엘', 'type': 'lyricist', 'impor': 30},
 {'name': '문별 (마마무)', 'type': 'lyricist', 'impor': 28},
 {'name': 'BOBBY', 'type': 'lyricist', 'impor': 27},
 {'name': '우석 (펜타곤)', 'type': 'lyricist', 'impor': 27},
 {'name': 'Supreme Boi', 'type': 'lyricist', 'impor': 27},
 {'name': 'MINO', 'type': 'lyricist', 'impor': 27},
 {'name': '이던', 'type': 'lyricist', 'impor': 26},
 {'name': '엑시', 'type': 'lyricist', 'impor': 25},
 {'name': '민규 (SEVENTEEN)', 'type': 'lyricist', 'impor': 22},
 {'name': '진진 (ASTRO)', 'type': 'lyricist', 'impor': 22},
 {'name': '이승훈', 'type': 'lyricist', 'impor': 21},
 {'name': '박우상', 'type': 'lyricist', 'impor': 21},
 {'name': '유토', 'type': 'lyricist', 'impor': 21},
 {'name': '라키 (ASTRO)', 'type': 'lyricist', 'impor': 21},
 {'name': '김지향', 'type': 'lyricist', 'impor': 21},
 {'name': '이승협 (J.DON)', 'type': 'lyricist', 'impor': 20},
 {'name': '한 (3RACHA)', 'type': 'lyricist', 'impor': 19},
 {'name': '방찬 (3RACHA)', 'type': 'lyricist', 'impor': 19},
 {'name': '서재우 (TENTEN)', 'type': 'lyricist', 'impor': 25},
 {'name': '도한세 (VICTON)', 'type': 'lyricist', 'impor': 19},
 {'name': '창빈 (3RACHA)', 'type': 'lyricist', 'impor': 19},
 {'name': '원우 (SEVENTEEN)', 'type': 'lyricist', 'impor': 18},
 {'name': '임현식', 'type': 'lyricist', 'impor': 18},
 {'name': 'SWEETUNE', 'type': 'lyricist', 'impor': 27},
 {'name': 'JB (GOT7)', 'type': 'lyricist', 'impor': 17},
 {'name': '지민 (AOA)', 'type': 'lyricist', 'impor': 16},
 {'name': 'T.K', 'type': 'lyricist', 'impor': 16},
 {'name': '김도훈 (RBW)', 'type': 'lyricist', 'impor': 15},
 {'name': '이기 (오레오)', 'type': 'lyricist', 'impor': 27},
 {'name': 'HighTop', 'type': 'lyricist', 'impor': 15},
 {'name': '강승윤', 'type': 'lyricist', 'impor': 15},
 {'name': '용감한 형제', 'type': 'lyricist', 'impor': 27},
 {'name': '신사동 호랭이', 'type': 'lyricist', 'impor': 15},
 {'name': 'Rome', 'type': 'lyricist', 'impor': 15},
 {'name': '서지음', 'type': 'lyricist', 'impor': 36},
 {'name': '박수석', 'type': 'lyricist', 'impor': 23},
 {'name': '한성호', 'type': 'lyricist', 'impor': 22},
 {'name': '디노 (SEVENTEEN)', 'type': 'lyricist', 'impor': 14},
 {'name': '용배 (RBW)', 'type': 'lyricist', 'impor': 22},
 {'name': '김태주', 'type': 'lyricist', 'impor': 14},
 {'name': '강지원', 'type': 'lyricist', 'impor': 14},
 {'name': '김기범', 'type': 'lyricist', 'impor': 14},
 {'name': '화사 (마마무)', 'type': 'lyricist', 'impor': 13},
 {'name': '미미 (오마이걸)', 'type': 'lyricist', 'impor': 13},
 {'name': 'kenzie', 'type': 'lyricist', 'impor': 21},
 {'name': 'JQ', 'type': 'lyricist', 'impor': 13},
 {'name': '서용배 (TENTEN)', 'type': 'lyricist', 'impor': 19},
 {'name': '호시 (SEVENTEEN)', 'type': 'lyricist', 'impor': 13},
 {'name': '예빈 (다이아)', 'type': 'lyricist', 'impor': 13},
 {'name': '기희현', 'type': 'lyricist', 'impor': 13},
 {'name': '김창락', 'type': 'lyricist', 'impor': 32},
 {'name': '장예은', 'type': 'lyricist', 'impor': 13},
 {'name': 'KZ', 'type': 'lyricist', 'impor': 12},
 {'name': '정욱', 'type': 'lyricist', 'impor': 12},
 {'name': '마르코', 'type': 'lyricist', 'impor': 24},
 {'name': '낯선', 'type': 'lyricist', 'impor': 12},
 {'name': 'BM', 'type': 'lyricist', 'impor': 12},
 {'name': 'JR (뉴이스트)', 'type': 'lyricist', 'impor': 23},
 {'name': '솔라 (마마무)', 'type': 'lyricist', 'impor': 12},
 {'name': '마크 (MARK)', 'type': 'lyricist', 'impor': 22},
 {'name': '태용 (TAEYONG)', 'type': 'lyricist', 'impor': 11},
 {'name': 'Sofar', 'type': 'lyricist', 'impor': 11},
 {'name': '마부스 (Maboos)', 'type': 'lyricist', 'impor': 11},
 {'name': '한승우 (VICTON)', 'type': 'lyricist', 'impor': 11},
 {'name': '조성호', 'type': 'lyricist', 'impor': 21},
 {'name': 'ADORA', 'type': 'lyricist', 'impor': 11},
 {'name': 'Hip Wave Sound', 'type': 'lyricist', 'impor': 11},
 {'name': '빅싼초 (Yummy Tone)', 'type': 'lyricist', 'impor': 17},
 {'name': 'J.seph', 'type': 'lyricist', 'impor': 11},
 {'name': '원필', 'type': 'lyricist', 'impor': 10},
 {'name': '알렉스 (하이포)', 'type': 'lyricist', 'impor': 10},
 {'name': '장이정 (JANGYIJEONG)', 'type': 'lyricist', 'impor': 10},
 {'name': '후이 (펜타곤)', 'type': 'lyricist', 'impor': 10},
 {'name': '임영준 (하이포)', 'type': 'lyricist', 'impor': 10},
 {'name': '신준섭', 'type': 'lyricist', 'impor': 10},
 {'name': '예지', 'type': 'lyricist', 'impor': 10},
 {'name': 'Z-uK (지욱)', 'type': 'lyricist', 'impor': 10},
 {'name': '뱀뱀 (GOT7)', 'type': 'lyricist', 'impor': 10},
 {'name': '백호 (뉴이스트)', 'type': 'lyricist', 'impor': 9},
 {'name': '용준형', 'type': 'lyricist', 'impor': 9},
 {'name': '조윤경', 'type': 'lyricist', 'impor': 17},
 {'name': '은진', 'type': 'lyricist', 'impor': 9},
 {'name': '차쿤 (일렉트로보이즈)', 'type': 'lyricist', 'impor': 16},
 {'name': '인우', 'type': 'lyricist', 'impor': 9},
 {'name': 'ZeroZine (MosPick)', 'type': 'lyricist', 'impor': 15},
 {'name': 'P.O (블락비)', 'type': 'lyricist', 'impor': 9},
 {'name': '권현빈', 'type': 'lyricist', 'impor': 9},
 {'name': '젤로', 'type': 'lyricist', 'impor': 9},
 {'name': '비토', 'type': 'lyricist', 'impor': 9},
 {'name': 'earattack', 'type': 'lyricist', 'impor': 9},
 {'name': '테디', 'type': 'lyricist', 'impor': 9},
 {'name': '장준', 'type': 'lyricist', 'impor': 8},
 {'name': '라도', 'type': 'lyricist', 'impor': 8},
 {'name': 'Chloe', 'type': 'lyricist', 'impor': 8},
 {'name': '최갑원', 'type': 'lyricist', 'impor': 8},
 {'name': '이단옆차기', 'type': 'lyricist', 'impor': 21},
 {'name': '김상균', 'type': 'lyricist', 'impor': 8},
 {'name': '미친감성', 'type': 'lyricist', 'impor': 8},
 {'name': 'Ferdy (MosPick)', 'type': 'lyricist', 'impor': 15},
 {'name': 'NODAY', 'type': 'lyricist', 'impor': 8},
 {'name': '리시', 'type': 'lyricist', 'impor': 8},
 {'name': '웨이', 'type': 'lyricist', 'impor': 8},
 {'name': '은수', 'type': 'lyricist', 'impor': 8},
 {'name': '마크 (GOT7)', 'type': 'lyricist', 'impor': 8},
 {'name': 'TAG', 'type': 'lyricist', 'impor': 8},
 {'name': '박진영', 'type': 'lyricist', 'impor': 8},
 {'name': '버피 (BUFFY)', 'type': 'lyricist', 'impor': 8},
 {'name': '승관 (SEVENTEEN)', 'type': 'lyricist', 'impor': 8},
 {'name': '성연', 'type': 'lyricist', 'impor': 8},
 {'name': '황현 (MonoTree)', 'type': 'lyricist', 'impor': 7},
 {'name': '소연', 'type': 'lyricist', 'impor': 7},
 {'name': '임팩트', 'type': 'lyricist', 'impor': 7},
 {'name': '몬스터팩토리', 'type': 'lyricist', 'impor': 7},
 {'name': '강동하', 'type': 'lyricist', 'impor': 7},
 {'name': '진영 (GOT7)', 'type': 'lyricist', 'impor': 7},
 {'name': '슬리피', 'type': 'lyricist', 'impor': 7},
 {'name': '함길수', 'type': 'lyricist', 'impor': 7},
 {'name': '리나', 'type': 'lyricist', 'impor': 7},
 {'name': '일 (IL)', 'type': 'lyricist', 'impor': 7},
 {'name': '이노베이터', 'type': 'lyricist', 'impor': 7},
 {'name': '윤후', 'type': 'lyricist', 'impor': 7},
 {'name': '잭슨 (GOT7)', 'type': 'lyricist', 'impor': 7},
 {'name': '전다운', 'type': 'lyricist', 'impor': 7},
 {'name': '박은우', 'type': 'lyricist', 'impor': 7},
 {'name': '유니스', 'type': 'lyricist', 'impor': 7},
 {'name': '정하', 'type': 'lyricist', 'impor': 7},
 {'name': '우태운', 'type': 'lyricist', 'impor': 7},
 {'name': '쿤', 'type': 'lyricist', 'impor': 7},
 {'name': 'John K', 'type': 'lyricist', 'impor': 7},
 {'name': '찬열', 'type': 'lyricist', 'impor': 7},
 {'name': '영재 (GOT7)', 'type': 'lyricist', 'impor': 6},
 {'name': 'Mafly', 'type': 'lyricist', 'impor': 6},
 {'name': '서림', 'type': 'lyricist', 'impor': 6},
 {'name': 'David Kim', 'type': 'lyricist', 'impor': 6},
 {'name': '김미진', 'type': 'lyricist', 'impor': 6},
 {'name': '김이나', 'type': 'lyricist', 'impor': 6},
 {'name': 'DAY6 (데이식스)', 'type': 'lyricist', 'impor': 6},
 {'name': 'Ollounder', 'type': 'lyricist', 'impor': 6},
 {'name': '72', 'type': 'lyricist', 'impor': 6},
 {'name': '슈퍼창따이', 'type': 'lyricist', 'impor': 6},
 {'name': '진리 (Full8loom)', 'type': 'lyricist', 'impor': 6},
 {'name': '로아', 'type': 'lyricist', 'impor': 6},
 {'name': 'ESBEE', 'type': 'lyricist', 'impor': 6},
 {'name': '키노', 'type': 'lyricist', 'impor': 6},
 {'name': '별들의 전쟁', 'type': 'lyricist', 'impor': 6},
 {'name': '남태현', 'type': 'lyricist', 'impor': 6},
 {'name': '코스믹 사운드', 'type': 'lyricist', 'impor': 6},
 {'name': '코스믹 걸 (Cosmic Girl)', 'type': 'lyricist', 'impor': 6},
 {'name': '유겸 (GOT7)', 'type': 'lyricist', 'impor': 6},
 {'name': '원호 (몬스타엑스)', 'type': 'lyricist', 'impor': 6},
 {'name': 'HOYA (호야)', 'type': 'lyricist', 'impor': 6},
 {'name': '제니', 'type': 'lyricist', 'impor': 6},
 {'name': 'MELODESIGN', 'type': 'lyricist', 'impor': 6},
 {'name': '한승훈', 'type': 'lyricist', 'impor': 12},
 {'name': '장동우 (인피니트)', 'type': 'lyricist', 'impor': 6},
 {'name': '성현', 'type': 'lyricist', 'impor': 6},
 {'name': '정한 (SEVENTEEN)', 'type': 'lyricist', 'impor': 6},
 {'name': '가면라이더', 'type': 'lyricist', 'impor': 6},
 {'name': '방탄소년단', 'type': 'artist', 'impor': 0},
 {'name': '비에이피', 'type': 'artist', 'impor': 0},
 {'name': '빅스', 'type': 'artist', 'impor': 0},
 {'name': '비투비', 'type': 'artist', 'impor': 0},
 {'name': '몬스타엑스', 'type': 'artist', 'impor': 0},
 {'name': '세븐틴', 'type': 'artist', 'impor': 0},
 {'name': '데이식스', 'type': 'artist', 'impor': 0},
 {'name': '아이콘', 'type': 'artist', 'impor': 0},
 {'name': '이엑스아이디', 'type': 'artist', 'impor': 0},
 {'name': '마마무', 'type': 'artist', 'impor': 0},
 {'name': '펜타곤', 'type': 'artist', 'impor': 0},
 {'name': '위너', 'type': 'artist', 'impor': 0},
 {'name': '우주소녀', 'type': 'artist', 'impor': 0},
 {'name': '아스트로', 'type': 'artist', 'impor': 0},
 {'name': '엔플라잉', 'type': 'artist', 'impor': 0},
 {'name': '스트레이 키즈', 'type': 'artist', 'impor': 0},
 {'name': '빅톤', 'type': 'artist', 'impor': 0},
 {'name': '스누퍼', 'type': 'artist', 'impor': 0},
 {'name': '갓세븐', 'type': 'artist', 'impor': 0},
 {'name': '에이오에이', 'type': 'artist', 'impor': 0},
 {'name': '씨클라운', 'type': 'artist', 'impor': 0},
 {'name': '여자친구', 'type': 'artist', 'impor': 0},
 {'name': '빅플로', 'type': 'artist', 'impor': 0},
 {'name': '오마이걸', 'type': 'artist', 'impor': 0},
 {'name': '크나큰', 'type': 'artist', 'impor': 0},
 {'name': '레드벨벳', 'type': 'artist', 'impor': 0},
 {'name': '엑소', 'type': 'artist', 'impor': 0},
 {'name': '다이아', 'type': 'artist', 'impor': 0},
 {'name': '씨엘씨', 'type': 'artist', 'impor': 0},
 {'name': '헤일로', 'type': 'artist', 'impor': 0},
 {'name': '투포케이', 'type': 'artist', 'impor': 0},
 {'name': '빅스타', 'type': 'artist', 'impor': 0},
 {'name': '에스에프나인', 'type': 'artist', 'impor': 0},
 {'name': '카드', 'type': 'artist', 'impor': 0},
 {'name': '뉴이스트', 'type': 'artist', 'impor': 0},
 {'name': '엔시티 드림', 'type': 'artist', 'impor': 0},
 {'name': '엔시티 일이칠', 'type': 'artist', 'impor': 0},
 {'name': '뉴이스트 W', 'type': 'artist', 'impor': 0},
 {'name': '마이틴', 'type': 'artist', 'impor': 0},
 {'name': '비비드', 'type': 'artist', 'impor': 0},
 {'name': '하이포', 'type': 'artist', 'impor': 0},
 {'name': '히스토리', 'type': 'artist', 'impor': 0},
 {'name': '백퍼센트', 'type': 'artist', 'impor': 0},
 {'name': '피에스타', 'type': 'artist', 'impor': 0},
 {'name': '하이라이트', 'type': 'artist', 'impor': 0},
 {'name': '블락비 바스타즈', 'type': 'artist', 'impor': 0},
 {'name': '제이비제이', 'type': 'artist', 'impor': 0},
 {'name': '업텐션', 'type': 'artist', 'impor': 0},
 {'name': '블랙핑크', 'type': 'artist', 'impor': 0},
 {'name': '골든차일드', 'type': 'artist', 'impor': 0},
 {'name': '소나무', 'type': 'artist', 'impor': 0},
 {'name': '제이제이씨씨', 'type': 'artist', 'impor': 0},
 {'name': '매드타운', 'type': 'artist', 'impor': 0},
 {'name': '프리스틴', 'type': 'artist', 'impor': 0},
 {'name': '온앤오프', 'type': 'artist', 'impor': 0},
 {'name': '(여자)아이들', 'type': 'artist', 'impor': 0},
 {'name': '임팩트', 'type': 'artist', 'impor': 0},
 {'name': '러블리즈', 'type': 'artist', 'impor': 0},
 {'name': '미스터미스터', 'type': 'artist', 'impor': 0},
 {'name': '비트윈', 'type': 'artist', 'impor': 0},
 {'name': '스피드', 'type': 'artist', 'impor': 0},
 {'name': '모모랜드', 'type': 'artist', 'impor': 0},
 {'name': '비비드걸', 'type': 'artist', 'impor': 0},
 {'name': '드림캐쳐', 'type': 'artist', 'impor': 0},
 {'name': '비아이지', 'type': 'artist', 'impor': 0},
 {'name': '레이디스 코드', 'type': 'artist', 'impor': 0},
 {'name': '인피니트 에이치', 'type': 'artist', 'impor': 0},
 {'name': '인투잇', 'type': 'artist', 'impor': 0},
 {'name': '리얼걸프로젝트', 'type': 'artist', 'impor': 0}]

In [97]:
json_prep = {"links":links_list, "nodes":nodes_list}

json_prep.keys()

dict_keys(['links', 'nodes'])

In [98]:
json_dump = json.dumps(json_prep, indent=1, sort_keys=True, ensure_ascii=False)

In [99]:
filename_out = 'lyricist_gen3.json'
json_out = open(filename_out,'w')
json_out.write(json_dump)
json_out.close()

## (2) Composer 작업

### 1) Gen1 작업

In [100]:
def preprocess(text1, text2):
    splitArr = list(re.split(', ', text1))
    artist_name = list(text2)

    composer = []
    artist = []
    
    composer.clear()
    artist.clear()

    i = 0
    for i in range(0, len(splitArr)):
        composer.append(splitArr[i].strip())
        artist.append(text2)
        i = i + 1
    result = [composer, artist]
    return result

In [101]:
# lyricist_gen1의 가수 목록 데이터프레임 생성
i = 0
a = 0
b = 0
composer = []
artist = []

composer.clear()
artist.clear()
    
for i in range(0, len(composer_gen1)):
    try:
        for a in range(0, len(preprocess(composer_gen1.composer[i], composer_gen1.artist[i])[0])):
            composer.append(str(preprocess(composer_gen1.composer[i], composer_gen1.artist[i])[0][a]))
        for b in range(0, len(preprocess(composer_gen1.composer[i], composer_gen1.artist[i])[1])):
            artist.append(str(preprocess(composer_gen1.composer[i], composer_gen1.artist[i])[1][b]))
    except:
        composer.append('')
        artist.append('')
    
preprocessing_gen1 = pd.DataFrame({"composer" : composer, "artist" : artist, "generation" : 1})
preprocessing_gen1

             composer artist  generation
0                  이준    god           1
1                 박진영    god           1
2                 박진영    god           1
3                 김형석    god           1
4                 박진영    god           1
5                 방시혁    god           1
6                 안용진    god           1
7                 god    god           1
8                 이철원    god           1
9                 박진영    god           1
10                                     1
11                박진영    god           1
12     josephhung bui    god           1
13                박진영    god           1
14                박준형    god           1
15                박진영    god           1
16                방시혁    god           1
17                외국곡    god           1
18                외국곡    god           1
19                방시혁    god           1
20                박진영    god           1
21                유건영    god           1
22                방시혁    god           1
23                방시혁    god           1
24                방시혁    god           1
25    배진렬 (JR Groove)    god           1
26                박진영    god           1
27                박진영    god           1
28                박진영    god           1
29                박진영    god           1
...               ...    ...         ...
2015              김지환     핑클           1
2016        J. Carbon     핑클           1
2017              김성호     핑클           1
2018              임기훈     핑클           1
2019               윤상     핑클           1
2020              김명곤     핑클           1
2021              최귀섭     핑클           1
2022              강인원     핑클           1
2023              신인수     핑클           1
2024              유정연     핑클           1
2025              황세준     핑클           1
2026              심상원     핑클           1
2027              안정훈     핑클           1
2028              전준규     핑클           1
2029              한재호     핑클           1
2030              김승수     핑클           1
2031              이현승     핑클           1
2032              마경식     핑클           1
2033     Sypher Muzik     핑클           1
2034              강태원     핑클           1
2035              박진환     핑클           1
2036              조규만     핑클           1
2037              정성윤     핑클           1
2038        정연준 (업타운)     핑클           1
2039              이현승     핑클           1
2040              김진훈     핑클           1
2041              안정훈     핑클           1
2042              김도현     핑클           1
2043              김도현     핑클           1
2044              방승철     핑클           1

[2045 rows x 3 columns]

In [102]:
preprocessing_gen1.rename(columns={"composer":"source","artist":"target"}, inplace=True)

In [103]:
grouped_idol_gen1 = preprocessing_gen1.groupby(["source","target"]).size().reset_index()
grouped_idol_gen1.head(20) # 갑자기 빈 행이 존재함 ->삭제

                     source       target   0
0                                         12
1                       220           신화   2
2                   A.minor         제이워크   1
3             Aaron Benward        에스이에스   1
4             Adam Benyahia           신화   1
5              Akira Mitake        에스이에스   1
6             Alex Niceforo           신화   1
7        Alexander Holmgren           버즈   1
8              Anders Grahn           버즈   1
9   Andreas Stone Johansson           버즈   1
10           Andrew Jackson           신화   5
11                      BYP          쥬얼리   1
12                Bob Fiori         제이티엘   1
13                Brian Kim           신화   2
14           Brian McKnight  플라이 투 더 스카이   1
15               Browncloud           신화   1
16           CARLSON SANNIE          쥬얼리   1
17             COLEGATE ROY         제이티엘   1
18            Caesar & Loui           신화   1
19            Carl Flemsten        에스이에스   1

In [104]:
# 칼럼 0 제거
grouped_idol_gen1.drop(grouped_idol_gen1.index[[0]], inplace=True)
grouped_idol_gen1 = grouped_idol_gen1.reset_index()
grouped_idol_gen1 = grouped_idol_gen1.drop(['index'], axis = 1)

In [105]:
# 칼럼 0 -> count로 이름 칼럼명 수정
grouped_idol_gen1.rename(columns={0:'count'}, inplace=True)
len(grouped_idol_gen1)

957

In [106]:
grouped_idol_gen1_ranking = grouped_idol_gen1.sort_values(by='count', ascending=False)
grouped_idol_gen1_ranking = grouped_idol_gen1_ranking.reset_index(drop=True)
grouped_idol_gen1_ranking.head()

     source target  count
0       박진영    god     47
1       유건형   언타이틀     47
2  박성호 (구피)     구피     29
3       유영진  에이치오티     19
4       윤일상     구피     17

## json 파일 생성하기

In [107]:
unique_idol = pd.Index(grouped_idol_gen1_ranking['source']
                      .append(grouped_idol_gen1_ranking['target'])
                      .reset_index(drop=True).unique())

In [108]:
unique_idol

Index(['박진영', '유건형', '박성호 (구피)', '유영진', '윤일상', '강타 (KANGTA)', '방시혁', '테디',
       '천명훈', '문희준',
       ...
       '투야', '러브', '아이돌', '클레오', '알', '에이포', '에스지', '밀크', '신비', '티앤비'],
      dtype='object', length=682)

In [109]:
grouped_idol_gen1_ranking.rename(columns={0:'count'}, inplace=True)
len(grouped_idol_gen1_ranking)

957

In [110]:
grouped_idol_gen1_ranking['count'].unique()

array([47, 29, 19, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,
        3,  2,  1], dtype=int64)

In [111]:
grouped_idol_gen1_ranking.loc[grouped_idol_gen1_ranking['source'] == "TEDDY"]

   source target  count
16  TEDDY    원타임     12

In [112]:
grouped_idol_gen1_ranking['source'] = grouped_idol_gen1_ranking['source'].replace('TEDDY', '테디')

In [113]:
grouped_idol_gen1_ranking.loc[grouped_idol_gen1_ranking['source'] == "TEDDY"]

Empty DataFrame
Columns: [source, target, count]
Index: []

In [114]:
grouped_idol_gen1_ranking2 = grouped_idol_gen1_ranking[grouped_idol_gen1_ranking['count'] > 5]
grouped_idol_gen1_ranking2

         source       target  count
0           박진영          god     47
1           유건형         언타이틀     47
2      박성호 (구피)           구피     29
3           유영진        에이치오티     19
4           윤일상           구피     17
5   강타 (KANGTA)        에이치오티     16
6           방시혁          god     15
7            테디          원타임     15
8           천명훈          엔알지     14
9           문희준        에이치오티     14
10          안성일         제이워크     14
11          신승희          테이크     13
12          유영진           신화     13
13          김형석    베이비 복스 리브     13
14          더 준           오션     13
15          고석영           버즈     12
16           테디          원타임     12
17      M (이민우)           신화     12
18          이윤상         젝스키스     12
19          유영진        에스이에스     11
20          이현우          엔알지     11
21          윤우현           버즈     11
22           Do         디베이스     10
23          이현도         디베이스     10
24           버즈           버즈     10
25          김성태          샤크라      9
26          이상준          엔알지      9
27          서융근  플라이 투 더 스카이      9
28          이재원         제이티엘      9
29          신상근          샤크라      9
30          더 준         젝스키스      9
31          이상준           버즈      8
32          한창훈          엔알지      8
33            렌           오션      8
34          조성진           구피      8
35          박근태          쥬얼리      8
36          장우혁         제이티엘      8
37          신인수           핑클      7
38          마경식         젝스키스      7
39          송백경          원타임      7
40          유영진  플라이 투 더 스카이      7
41           페리          원타임      7
42          김도현           신화      7
43          원상우    베이비 복스 리브      7
44          김세진         제이워크      7
45          박덕정           버즈      6
46        이단옆차기          god      6
47          최귀섭         젝스키스      6
48          신명호          엔알지      6
49          장용진        에이치오티      6
50          지국현           신화      6
51          윤일상         젝스키스      6
52  강타 (KANGTA)           에스      6
53           에릭           신화      6
54          남기상          쥬얼리      6

In [115]:
grouped_idol_gen1_ranking2 = grouped_idol_gen1_ranking2.reset_index()

In [116]:
grouped_idol_gen1_ranking2 = grouped_idol_gen1_ranking2.drop(['index'], axis = 1)

In [117]:
total_2 = grouped_idol_gen1_ranking2.groupby(['source'], as_index=False).sum()
total2_2 = total_2.sort_values(by='count', ascending=False).reset_index()
total2_2 = total2_2.drop(['index'], axis = 1)
total2_2_sourcename = total2_2['source'].tolist()
total2_2_count = total2_2['count'].tolist()
len(total2_2_sourcename)

47

In [118]:
total2_2

         source  count
0           유영진     50
1           유건형     47
2           박진영     47
3      박성호 (구피)     29
4            테디     27
5           윤일상     23
6   강타 (KANGTA)     22
7           더 준     22
8           이상준     17
9           방시혁     15
10          안성일     14
11          천명훈     14
12          문희준     14
13          신승희     13
14          김형석     13
15      M (이민우)     12
16          고석영     12
17          이윤상     12
18          윤우현     11
19          이현우     11
20          이현도     10
21           Do     10
22           버즈     10
23          신상근      9
24          김성태      9
25          이재원      9
26          서융근      9
27          박근태      8
28          조성진      8
29          장우혁      8
30            렌      8
31          한창훈      8
32          마경식      7
33          원상우      7
34          김세진      7
35          송백경      7
36          신인수      7
37          김도현      7
38           페리      7
39          박덕정      6
40        이단옆차기      6
41          신명호      6
42          남기상      6
43          장용진      6
44           에릭      6
45          지국현      6
46          최귀섭      6

In [119]:
a = pd.Index(total2_2_sourcename)
a

Index(['유영진', '유건형', '박진영', '박성호 (구피)', '테디', '윤일상', '강타 (KANGTA)', '더 준',
       '이상준', '방시혁', '안성일', '천명훈', '문희준', '신승희', '김형석', 'M (이민우)', '고석영',
       '이윤상', '윤우현', '이현우', '이현도', 'Do', '버즈', '신상근', '김성태', '이재원', '서융근',
       '박근태', '조성진', '장우혁', '렌', '한창훈', '마경식', '원상우', '김세진', '송백경', '신인수',
       '김도현', '페리', '박덕정', '이단옆차기', '신명호', '남기상', '장용진', '에릭', '지국현', '최귀섭'],
      dtype='object')

In [120]:
unique_idol2 = pd.Index(grouped_idol_gen1_ranking2['source']
                      .append(grouped_idol_gen1_ranking2['target'])
                      .reset_index(drop=True).unique())
unique_idol2_composer = pd.Index(grouped_idol_gen1_ranking2['source'] .reset_index(drop=True).unique())
unique_idol2_artist = pd.Index(grouped_idol_gen1_ranking2['target'] .reset_index(drop=True).unique())

In [121]:
source_name = grouped_idol_gen1_ranking2['source']

In [122]:
# composer_group_dict2
group_dict2_composer = {}
group_dict2_lyricist.clear()
counter = 0
for idol in unique_idol2_composer:
    if idol not in group_dict2_composer:
        counter += 1
        group_dict2_composer[idol] = counter
    else:
        pass
group_dict2_composer

{'박진영': 1,
 '유건형': 2,
 '박성호 (구피)': 3,
 '유영진': 4,
 '윤일상': 5,
 '강타 (KANGTA)': 6,
 '방시혁': 7,
 '테디': 8,
 '천명훈': 9,
 '문희준': 10,
 '안성일': 11,
 '신승희': 12,
 '김형석': 13,
 '더 준': 14,
 '고석영': 15,
 'M (이민우)': 16,
 '이윤상': 17,
 '이현우': 18,
 '윤우현': 19,
 'Do': 20,
 '이현도': 21,
 '버즈': 22,
 '김성태': 23,
 '이상준': 24,
 '서융근': 25,
 '이재원': 26,
 '신상근': 27,
 '한창훈': 28,
 '렌': 29,
 '조성진': 30,
 '박근태': 31,
 '장우혁': 32,
 '신인수': 33,
 '마경식': 34,
 '송백경': 35,
 '페리': 36,
 '김도현': 37,
 '원상우': 38,
 '김세진': 39,
 '박덕정': 40,
 '이단옆차기': 41,
 '최귀섭': 42,
 '신명호': 43,
 '장용진': 44,
 '지국현': 45,
 '에릭': 46,
 '남기상': 47}

In [123]:
# artist_group_dict2
group_dict2_artist = {}
group_dict2_artist.clear()
counter = 47
for idol in unique_idol2_artist:
    if idol not in group_dict2_artist:
        counter += 1
        group_dict2_artist[idol] = counter
    else:
        pass
group_dict2_artist

{'god': 48,
 '언타이틀': 49,
 '구피': 50,
 '에이치오티': 51,
 '원타임': 52,
 '엔알지': 53,
 '제이워크': 54,
 '테이크': 55,
 '신화': 56,
 '베이비 복스 리브': 57,
 '오션': 58,
 '버즈': 59,
 '젝스키스': 60,
 '에스이에스': 61,
 '디베이스': 62,
 '샤크라': 63,
 '플라이 투 더 스카이': 64,
 '제이티엘': 65,
 '쥬얼리': 66,
 '핑클': 67,
 '에스': 68}

In [124]:
temp_link_list = []
temp_links_list = list(grouped_idol_gen1_ranking2.apply(lambda row: {"source": row['source'], "target": row['target'], "value": row['count']}, axis=1))

In [125]:
links_list = []
for link in temp_links_list:
    record = {"value":link['value'], "source":unique_idol2.get_loc(link['source']),
     "target": unique_idol2.get_loc(link['target'])}
    links_list.append(record)
links_list

[{'value': 47, 'source': 0, 'target': 47},
 {'value': 47, 'source': 1, 'target': 48},
 {'value': 29, 'source': 2, 'target': 49},
 {'value': 19, 'source': 3, 'target': 50},
 {'value': 17, 'source': 4, 'target': 49},
 {'value': 16, 'source': 5, 'target': 50},
 {'value': 15, 'source': 6, 'target': 47},
 {'value': 15, 'source': 7, 'target': 51},
 {'value': 14, 'source': 8, 'target': 52},
 {'value': 14, 'source': 9, 'target': 50},
 {'value': 14, 'source': 10, 'target': 53},
 {'value': 13, 'source': 11, 'target': 54},
 {'value': 13, 'source': 3, 'target': 55},
 {'value': 13, 'source': 12, 'target': 56},
 {'value': 13, 'source': 13, 'target': 57},
 {'value': 12, 'source': 14, 'target': 21},
 {'value': 12, 'source': 7, 'target': 51},
 {'value': 12, 'source': 15, 'target': 55},
 {'value': 12, 'source': 16, 'target': 58},
 {'value': 11, 'source': 3, 'target': 59},
 {'value': 11, 'source': 17, 'target': 52},
 {'value': 11, 'source': 18, 'target': 21},
 {'value': 10, 'source': 19, 'target': 60},
 {'value': 10, 'source': 20, 'target': 60},
 {'value': 10, 'source': 21, 'target': 21},
 {'value': 9, 'source': 22, 'target': 61},
 {'value': 9, 'source': 23, 'target': 52},
 {'value': 9, 'source': 24, 'target': 62},
 {'value': 9, 'source': 25, 'target': 63},
 {'value': 9, 'source': 26, 'target': 61},
 {'value': 9, 'source': 13, 'target': 58},
 {'value': 8, 'source': 23, 'target': 21},
 {'value': 8, 'source': 27, 'target': 52},
 {'value': 8, 'source': 28, 'target': 57},
 {'value': 8, 'source': 29, 'target': 49},
 {'value': 8, 'source': 30, 'target': 64},
 {'value': 8, 'source': 31, 'target': 63},
 {'value': 7, 'source': 32, 'target': 65},
 {'value': 7, 'source': 33, 'target': 58},
 {'value': 7, 'source': 34, 'target': 51},
 {'value': 7, 'source': 3, 'target': 62},
 {'value': 7, 'source': 35, 'target': 51},
 {'value': 7, 'source': 36, 'target': 55},
 {'value': 7, 'source': 37, 'target': 56},
 {'value': 7, 'source': 38, 'target': 53},
 {'value': 6, 'source': 39, 'target': 21},
 {'value': 6, 'source': 40, 'target': 47},
 {'value': 6, 'source': 41, 'target': 58},
 {'value': 6, 'source': 42, 'target': 52},
 {'value': 6, 'source': 43, 'target': 50},
 {'value': 6, 'source': 44, 'target': 55},
 {'value': 6, 'source': 4, 'target': 58},
 {'value': 6, 'source': 5, 'target': 66},
 {'value': 6, 'source': 45, 'target': 55},
 {'value': 6, 'source': 46, 'target': 64}]

In [126]:
nodes_list = []
nodes_list.clear()

for idol in group_dict2_composer:
    nodes_list.append({"name":idol, "type": "composer", "impor":total2_2_count[a.get_loc(idol)]})
for idol2 in group_dict2_artist:  
    nodes_list.append({"name":idol2, "type": "artist", "impor":0})
nodes_list

[{'name': '박진영', 'type': 'composer', 'impor': 47},
 {'name': '유건형', 'type': 'composer', 'impor': 47},
 {'name': '박성호 (구피)', 'type': 'composer', 'impor': 29},
 {'name': '유영진', 'type': 'composer', 'impor': 50},
 {'name': '윤일상', 'type': 'composer', 'impor': 23},
 {'name': '강타 (KANGTA)', 'type': 'composer', 'impor': 22},
 {'name': '방시혁', 'type': 'composer', 'impor': 15},
 {'name': '테디', 'type': 'composer', 'impor': 27},
 {'name': '천명훈', 'type': 'composer', 'impor': 14},
 {'name': '문희준', 'type': 'composer', 'impor': 14},
 {'name': '안성일', 'type': 'composer', 'impor': 14},
 {'name': '신승희', 'type': 'composer', 'impor': 13},
 {'name': '김형석', 'type': 'composer', 'impor': 13},
 {'name': '더 준', 'type': 'composer', 'impor': 22},
 {'name': '고석영', 'type': 'composer', 'impor': 12},
 {'name': 'M (이민우)', 'type': 'composer', 'impor': 12},
 {'name': '이윤상', 'type': 'composer', 'impor': 12},
 {'name': '이현우', 'type': 'composer', 'impor': 11},
 {'name': '윤우현', 'type': 'composer', 'impor': 11},
 {'name': 'Do', 'type': 'composer', 'impor': 10},
 {'name': '이현도', 'type': 'composer', 'impor': 10},
 {'name': '버즈', 'type': 'composer', 'impor': 10},
 {'name': '김성태', 'type': 'composer', 'impor': 9},
 {'name': '이상준', 'type': 'composer', 'impor': 17},
 {'name': '서융근', 'type': 'composer', 'impor': 9},
 {'name': '이재원', 'type': 'composer', 'impor': 9},
 {'name': '신상근', 'type': 'composer', 'impor': 9},
 {'name': '한창훈', 'type': 'composer', 'impor': 8},
 {'name': '렌', 'type': 'composer', 'impor': 8},
 {'name': '조성진', 'type': 'composer', 'impor': 8},
 {'name': '박근태', 'type': 'composer', 'impor': 8},
 {'name': '장우혁', 'type': 'composer', 'impor': 8},
 {'name': '신인수', 'type': 'composer', 'impor': 7},
 {'name': '마경식', 'type': 'composer', 'impor': 7},
 {'name': '송백경', 'type': 'composer', 'impor': 7},
 {'name': '페리', 'type': 'composer', 'impor': 7},
 {'name': '김도현', 'type': 'composer', 'impor': 7},
 {'name': '원상우', 'type': 'composer', 'impor': 7},
 {'name': '김세진', 'type': 'composer', 'impor': 7},
 {'name': '박덕정', 'type': 'composer', 'impor': 6},
 {'name': '이단옆차기', 'type': 'composer', 'impor': 6},
 {'name': '최귀섭', 'type': 'composer', 'impor': 6},
 {'name': '신명호', 'type': 'composer', 'impor': 6},
 {'name': '장용진', 'type': 'composer', 'impor': 6},
 {'name': '지국현', 'type': 'composer', 'impor': 6},
 {'name': '에릭', 'type': 'composer', 'impor': 6},
 {'name': '남기상', 'type': 'composer', 'impor': 6},
 {'name': 'god', 'type': 'artist', 'impor': 0},
 {'name': '언타이틀', 'type': 'artist', 'impor': 0},
 {'name': '구피', 'type': 'artist', 'impor': 0},
 {'name': '에이치오티', 'type': 'artist', 'impor': 0},
 {'name': '원타임', 'type': 'artist', 'impor': 0},
 {'name': '엔알지', 'type': 'artist', 'impor': 0},
 {'name': '제이워크', 'type': 'artist', 'impor': 0},
 {'name': '테이크', 'type': 'artist', 'impor': 0},
 {'name': '신화', 'type': 'artist', 'impor': 0},
 {'name': '베이비 복스 리브', 'type': 'artist', 'impor': 0},
 {'name': '오션', 'type': 'artist', 'impor': 0},
 {'name': '버즈', 'type': 'artist', 'impor': 0},
 {'name': '젝스키스', 'type': 'artist', 'impor': 0},
 {'name': '에스이에스', 'type': 'artist', 'impor': 0},
 {'name': '디베이스', 'type': 'artist', 'impor': 0},
 {'name': '샤크라', 'type': 'artist', 'impor': 0},
 {'name': '플라이 투 더 스카이', 'type': 'artist', 'impor': 0},
 {'name': '제이티엘', 'type': 'artist', 'impor': 0},
 {'name': '쥬얼리', 'type': 'artist', 'impor': 0},
 {'name': '핑클', 'type': 'artist', 'impor': 0},
 {'name': '에스', 'type': 'artist', 'impor': 0}]

In [127]:
json_prep = {"links":links_list, "nodes":nodes_list}

json_prep.keys()

dict_keys(['links', 'nodes'])

In [128]:
json_dump = json.dumps(json_prep, indent=1, sort_keys=True, ensure_ascii=False)

In [129]:
pd.DataFrame(json_prep['nodes'])

    impor         name      type
0      47          박진영  composer
1      47          유건형  composer
2      29     박성호 (구피)  composer
3      50          유영진  composer
4      23          윤일상  composer
5      22  강타 (KANGTA)  composer
6      15          방시혁  composer
7      27           테디  composer
8      14          천명훈  composer
9      14          문희준  composer
10     14          안성일  composer
11     13          신승희  composer
12     13          김형석  composer
13     22          더 준  composer
14     12          고석영  composer
15     12      M (이민우)  composer
16     12          이윤상  composer
17     11          이현우  composer
18     11          윤우현  composer
19     10           Do  composer
20     10          이현도  composer
21     10           버즈  composer
22      9          김성태  composer
23     17          이상준  composer
24      9          서융근  composer
25      9          이재원  composer
26      9          신상근  composer
27      8          한창훈  composer
28      8            렌  composer
29      8          조성진  composer
..    ...          ...       ...
38      7          김세진  composer
39      6          박덕정  composer
40      6        이단옆차기  composer
41      6          최귀섭  composer
42      6          신명호  composer
43      6          장용진  composer
44      6          지국현  composer
45      6           에릭  composer
46      6          남기상  composer
47      0          god    artist
48      0         언타이틀    artist
49      0           구피    artist
50      0        에이치오티    artist
51      0          원타임    artist
52      0          엔알지    artist
53      0         제이워크    artist
54      0          테이크    artist
55      0           신화    artist
56      0    베이비 복스 리브    artist
57      0           오션    artist
58      0           버즈    artist
59      0         젝스키스    artist
60      0        에스이에스    artist
61      0         디베이스    artist
62      0          샤크라    artist
63      0  플라이 투 더 스카이    artist
64      0         제이티엘    artist
65      0          쥬얼리    artist
66      0           핑클    artist
67      0           에스    artist

[68 rows x 3 columns]

In [130]:
pd.DataFrame(json_prep['links'])

    source  target  value
0        0      47     47
1        1      48     47
2        2      49     29
3        3      50     19
4        4      49     17
5        5      50     16
6        6      47     15
7        7      51     15
8        8      52     14
9        9      50     14
10      10      53     14
11      11      54     13
12       3      55     13
13      12      56     13
14      13      57     13
15      14      21     12
16       7      51     12
17      15      55     12
18      16      58     12
19       3      59     11
20      17      52     11
21      18      21     11
22      19      60     10
23      20      60     10
24      21      21     10
25      22      61      9
26      23      52      9
27      24      62      9
28      25      63      9
29      26      61      9
30      13      58      9
31      23      21      8
32      27      52      8
33      28      57      8
34      29      49      8
35      30      64      8
36      31      63      8
37      32      65      7
38      33      58      7
39      34      51      7
40       3      62      7
41      35      51      7
42      36      55      7
43      37      56      7
44      38      53      7
45      39      21      6
46      40      47      6
47      41      58      6
48      42      52      6
49      43      50      6
50      44      55      6
51       4      58      6
52       5      66      6
53      45      55      6
54      46      64      6

In [131]:
filename_out = 'composer_gen1.json'
json_out = open(filename_out,'w')
json_out.write(json_dump)
json_out.close()

### 2) Gen2 작업

In [132]:
# composer_gen2의 가수 목록 데이터프레임 생성
i = 0
a = 0
b = 0
composer = []
artist = []

composer.clear()
artist.clear()
    
for i in range(0, len(composer_gen2)):
    try:
        for a in range(0, len(preprocess(composer_gen2.composer[i], composer_gen2.artist[i])[0])):
            composer.append(str(preprocess(composer_gen2.composer[i], composer_gen2.artist[i])[0][a]))
        for b in range(0, len(preprocess(composer_gen2.composer[i], composer_gen2.artist[i])[1])):
            artist.append(str(preprocess(composer_gen2.composer[i], composer_gen2.artist[i])[1][b]))
    except:
        composer.append('')
        artist.append('')
    
preprocessing_gen2 = pd.DataFrame({"composer" : composer, "artist" : artist, "generation" : 1})
preprocessing_gen2

                 composer  artist  generation
0                  용감한 형제  BP 라니아           1
1                  별들의 전쟁  BP 라니아           1
2                  용감한 형제  BP 라니아           1
3                  별들의 전쟁  BP 라니아           1
4                      필강  BP 라니아           1
5                   Tablo  BP 라니아           1
6                    Milo  BP 라니아           1
7                     Ray  BP 라니아           1
8          LABYRON WALTON  BP 라니아           1
9             Teddy Riley  BP 라니아           1
10         Richard Garcia  BP 라니아           1
11        ROSEL A MINSTER  BP 라니아           1
12    DOMINIQUE RODRIGUEZ  BP 라니아           1
13         JESSICA BRYANT  BP 라니아           1
14            Teddy Riley  BP 라니아           1
15         Richard Garcia  BP 라니아           1
16        ROSEL A MINSTER  BP 라니아           1
17    DOMINIQUE RODRIGUEZ  BP 라니아           1
18         LABYRON WALTON  BP 라니아           1
19              Lena Leon  BP 라니아           1
20          Krysta Youngs  BP 라니아           1
21                  A-Dee  BP 라니아           1
22                 Kepler  BP 라니아           1
23                    김건우  BP 라니아           1
24        Melanie Fontana  BP 라니아           1
25              Jon Asher  BP 라니아           1
26                  이제이 쇼  BP 라니아           1
27                     낯선  BP 라니아           1
28                     쿤타  BP 라니아           1
29              Rich Jang  BP 라니아           1
...                   ...     ...         ...
5546      Ferdy (MosPick)     포미닛           1
5547   ZeroZine (MosPick)     포미닛           1
5548                  조성호     포미닛           1
5549         서재우 (TENTEN)     포미닛           1
5550                  임광욱     포미닛           1
5551             Ryan Kim     포미닛           1
5552              Mistazo     포미닛           1
5553         Adam Kulling     포미닛           1
5554       Alice Gernandt     포미닛           1
5555     빅싼초 (Yummy Tone)     포미닛           1
5556               Jenyer     포미닛           1
5557         서재우 (TENTEN)     포미닛           1
5558   ZeroZine (MosPick)     포미닛           1
5559          Lee Brian D     포미닛           1
5560         서재우 (TENTEN)     포미닛           1
5561     빅싼초 (Yummy Tone)     포미닛           1
5562   ZeroZine (MosPick)     포미닛           1
5563         서재우 (TENTEN)     포미닛           1
5564   ZeroZine (MosPick)     포미닛           1
5565             Skrillex     포미닛           1
5566               Genneo     포미닛           1
5567                  임광욱     포미닛           1
5568             Ryan Kim     포미닛           1
5569           HUNNYKILLA     포미닛           1
5570       Amanda Moseley     포미닛           1
5571     빅싼초 (Yummy Tone)     포미닛           1
5572                  조성호     포미닛           1
5573                  전호진       햄           1
5574                  전호진       햄           1
5575                  전호진       햄           1

[5576 rows x 3 columns]

In [133]:
preprocessing_gen2.rename(columns={"composer":"source","artist":"target"}, inplace=True)

In [134]:
grouped_idol_gen2 = preprocessing_gen2.groupby(["source","target"]).size().reset_index()
grouped_idol_gen2.head(20) # 갑자기 빈 행이 존재함 ->삭제

      source  target   0
0                     10
1        $un   슈퍼주니어   1
2         13     블락비   2
3       1601    에이핑크   1
4    17HOLIC     달샤벳   1
5        220    대국남아   1
6        220   비원에이포   1
7        220   슈퍼주니어   1
8        220     유키스   1
9        220     투피엠   2
10       220     티아라   1
11  220 VOLT    마이네임   2
12     2Face     샤이니   1
13     2Face    투에이엠   1
14     2JAJA  제이와이제이   1
15     2LSON  애프터 스쿨   1
16    2Story     시크릿   1
17    4Miles     엔소닉   1
18      4번타자     티아라   1
19        72     씨스타   1

In [135]:
# 칼럼 0 제거
grouped_idol_gen2.drop(grouped_idol_gen2.index[[0]], inplace=True)
grouped_idol_gen2 = grouped_idol_gen2.reset_index()
grouped_idol_gen2 = grouped_idol_gen2.drop(['index'], axis = 1)

In [136]:
# 칼럼 0 -> count로 이름 칼럼명 수정
grouped_idol_gen2.rename(columns={0:'count'}, inplace=True)
len(grouped_idol_gen2)

2972

In [137]:
grouped_idol_gen2_ranking = grouped_idol_gen2.sort_values(by='count', ascending=False)
grouped_idol_gen2_ranking = grouped_idol_gen2_ranking.reset_index(drop=True)
grouped_idol_gen2_ranking.head()

         source    target  count
0      G-DRAGON        빅뱅     52
1  정용화 (CNBLUE)      씨엔블루     47
2            진영     비원에이포     35
3        용감한 형제        틴탑     31
4           한승훈  에프티 아일랜드     28

## json 파일 생성하기

In [138]:
unique_idol = pd.Index(grouped_idol_gen2_ranking['source']
                      .append(grouped_idol_gen2_ranking['target'])
                      .reset_index(drop=True).unique())

In [139]:
unique_idol

Index(['G-DRAGON', '정용화 (CNBLUE)', '진영', '용감한 형제', '한승훈', '김승수', '한재호',
       '지코 (ZICO)', '한성호', 'TEDDY',
       ...
       '블레이디', '천상지희 더 그레이스', '씽', '애프터스쿨 블루', '에이스타일', '타키온', '브이엔티', '지피베이직',
       '애프터스쿨 레드', '천상지희 다나 & 선데이'],
      dtype='object', length=1895)

In [140]:
grouped_idol_gen2_ranking.rename(columns={0:'count'}, inplace=True)
len(grouped_idol_gen2_ranking)

2972

In [141]:
grouped_idol_gen2_ranking['count'].unique()

array([52, 47, 35, 31, 28, 27, 26, 24, 21, 20, 19, 17, 16, 15, 14, 13, 12,
       11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1], dtype=int64)

In [142]:
grouped_idol_gen2_ranking.loc[grouped_idol_gen2_ranking['source'] == "TEDDY"]

    source  target  count
14   TEDDY    투애니원     21
15   TEDDY      빅뱅     20
465  TEDDY  지디 앤 탑      2

In [143]:
grouped_idol_gen2_ranking['source'] = grouped_idol_gen2_ranking['source'].replace('TEDDY', '테디')

In [144]:
grouped_idol_gen2_ranking.loc[grouped_idol_gen2_ranking['source'] == "TEDDY"]

Empty DataFrame
Columns: [source, target, count]
Index: []

In [145]:
grouped_idol_gen2_ranking2 = grouped_idol_gen2_ranking[grouped_idol_gen2_ranking['count'] > 5]
grouped_idol_gen2_ranking2

                source    target  count
0             G-DRAGON        빅뱅     52
1         정용화 (CNBLUE)      씨엔블루     47
2                   진영     비원에이포     35
3               용감한 형제        틴탑     31
4                  한승훈  에프티 아일랜드     28
5                  김승수        카라     27
6                  한재호        카라     27
7                  한승훈      씨엔블루     26
8                  김승수      인피니트     24
9                  한재호      인피니트     24
10                 한재호     보이프렌드     21
11           지코 (ZICO)       블락비     21
12                 김승수     보이프렌드     21
13                 한성호  에프티 아일랜드     21
14                  테디      투애니원     21
15                  테디        빅뱅     20
16                 유영진      동방신기     19
17        최종훈 (FT아일랜드)  에프티 아일랜드     19
18                 박진영      원더걸스     19
19                 용준형       비스트     17
20        이재진 (FT아일랜드)  에프티 아일랜드     16
21                 김태주       비스트     16
22                 강지원       시크릿     16
23        이종현 (CNBLUE)      씨엔블루     16
24                 조영수       티아라     16
25        이홍기 (FT아일랜드)  에프티 아일랜드     16
26                 박진영       투피엠     15
27           Good Life       비스트     15
28                 김재양  에프티 아일랜드     15
29              kenzie       샤이니     15
..                 ...       ...    ...
104            Poptime       블락비      7
105          김도훈 (RBW)  에프티 아일랜드      7
106                김태성       샤이니      7
107           지오 (G.O)       엠블랙      7
108     Team One Sound     슈퍼주니어      7
109           이기 (오레오)    오렌지캬라멜      7
110                 창조        틴탑      7
111               KUSH        빅뱅      6
112  G-High (MonoTree)       스텔라      6
113                원펀치       엔소닉      6
114                 천둥       엠블랙      6
115      Andreas Oberg       샤이니      6
116       Ryan S. Jhun       유키스      6
117                정창욱     나인뮤지스      6
118                안영민       티아라      6
119               MZMC       샤이니      6
120                류광민       티맥스      6
121                김태현       티아라      6
122                전다운       시크릿      6
123                유한진      동방신기      6
124                이기광       비스트      6
125                임상혁       포미닛      6
126              NODAY       비스트      6
127          김도훈 (RBW)       티아라      6
128             kenzie      에프엑스      6
129                 테디      투애니원      6
130                 디즈       샤이니      6
131             kenzie      동방신기      6
132       준케이 (JUN. K)       투피엠      6
133              이단옆차기       티아라      6

[134 rows x 3 columns]

In [146]:
grouped_idol_gen2_ranking2 = grouped_idol_gen2_ranking2.reset_index()

In [147]:
grouped_idol_gen2_ranking2 = grouped_idol_gen2_ranking2.drop(['index'], axis = 1)

In [148]:
total_2 = grouped_idol_gen2_ranking2.groupby(['source'], as_index=False).sum()
total2_2 = total_2.sort_values(by='count', ascending=False).reset_index()
total2_2 = total2_2.drop(['index'], axis = 1)
total2_2_sourcename = total2_2['source'].tolist()
total2_2_count = total2_2['count'].tolist()
len(total2_2_sourcename)

100

In [149]:
a = pd.Index(total2_2_sourcename)
a

Index(['김승수', '한재호', '용감한 형제', '한승훈', 'G-DRAGON', '정용화 (CNBLUE)', '테디',
       '신사동 호랭이', 'kenzie', '유영진', '진영', '박진영', '이단옆차기', '김재양', '이민수', '한성호',
       '최규성', '지코 (ZICO)', '최종훈 (FT아일랜드)', '동해 (DONGHAE)', '홍지상', '용준형', '강지원',
       '김태주', '이재진 (FT아일랜드)', '이홍기 (FT아일랜드)', '이종현 (CNBLUE)', '조영수',
       'Good Life', '라도', 'T.O.P', '방시혁', 'Kenzie', '김도훈 (RBW)', '김기범', '원상우',
       '원택 (1Take)', '별들의 전쟁', '페리', '전준규', '우리형과 내동생', 'e.one', 'J. Yoon',
       '직 재스퍼 (Zick Jasper)', '정모 (JUNGMO)', '핫펠트 (예은)', '안준성', '로빈', 'SWIN',
       '마르코', '남기상', 'KZ', '신우', '제아', '태완 (Taewan)', '윤일상', '유빈 (Yubin)',
       '이트라이브', 'Thomas Troelsen', '수빈', 'Steven Lee', 'BEOMxNANG',
       '차쿤 (일렉트로보이즈)', 'ZigZag Note', '투챔프', '지오 (G.O)', '김태성',
       'Team One Sound', '신재훈', 'Poptime', '코끼리 왕국', '이상호', '이병준',
       '마부스 (Maboos)', '이기 (오레오)', '박경 (블락비)', '박수석', '블랙아이드 필승',
       '서재우 (TENTEN)', '슈퍼창따이', '앤드류 최', '창조', 'NODAY', 'MZMC', 'KUSH',
       'Ryan S. Jhun', 'G-High (MonoTree)', '전다운', '천둥', '준케이 (JUN. K)', '정창욱',
       '김태현', '임상혁', '디즈', '류광민', '이기광', '유한진', '원펀치', '안영민', 'Andreas Oberg'],
      dtype='object')

In [150]:
unique_idol2 = pd.Index(grouped_idol_gen2_ranking2['source']
                      .append(grouped_idol_gen2_ranking2['target'])
                      .reset_index(drop=True).unique())
unique_idol2_composer = pd.Index(grouped_idol_gen2_ranking2['source'] .reset_index(drop=True).unique())
unique_idol2_artist = pd.Index(grouped_idol_gen2_ranking2['target'] .reset_index(drop=True).unique())

In [151]:
source_name = grouped_idol_gen2_ranking2['source']

In [152]:
# composer_group_dict2
group_dict2_composer = {}
group_dict2_composer.clear()
counter = 0
for idol in unique_idol2_composer:
    if idol not in group_dict2_composer:
        counter += 1
        group_dict2_composer[idol] = counter
    else:
        pass
group_dict2_composer

{'G-DRAGON': 1,
 '정용화 (CNBLUE)': 2,
 '진영': 3,
 '용감한 형제': 4,
 '한승훈': 5,
 '김승수': 6,
 '한재호': 7,
 '지코 (ZICO)': 8,
 '한성호': 9,
 '테디': 10,
 '유영진': 11,
 '최종훈 (FT아일랜드)': 12,
 '박진영': 13,
 '용준형': 14,
 '이재진 (FT아일랜드)': 15,
 '김태주': 16,
 '강지원': 17,
 '이종현 (CNBLUE)': 18,
 '조영수': 19,
 '이홍기 (FT아일랜드)': 20,
 'Good Life': 21,
 '김재양': 22,
 'kenzie': 23,
 '방시혁': 24,
 'T.O.P': 25,
 '이민수': 26,
 'Kenzie': 27,
 '김기범': 28,
 '신사동 호랭이': 29,
 '원상우': 30,
 '이단옆차기': 31,
 '최규성': 32,
 '원택 (1Take)': 33,
 '별들의 전쟁': 34,
 '동해 (DONGHAE)': 35,
 'e.one': 36,
 '우리형과 내동생': 37,
 '페리': 38,
 'J. Yoon': 39,
 '전준규': 40,
 '남기상': 41,
 'SWIN': 42,
 '핫펠트 (예은)': 43,
 '홍지상': 44,
 '마르코': 45,
 '안준성': 46,
 'KZ': 47,
 '정모 (JUNGMO)': 48,
 '로빈': 49,
 '직 재스퍼 (Zick Jasper)': 50,
 'BEOMxNANG': 51,
 'Steven Lee': 52,
 'Thomas Troelsen': 53,
 '유빈 (Yubin)': 54,
 '차쿤 (일렉트로보이즈)': 55,
 '라도': 56,
 '제아': 57,
 '태완 (Taewan)': 58,
 '이트라이브': 59,
 '수빈': 60,
 '신우': 61,
 '윤일상': 62,
 '투챔프': 63,
 '앤드류 최': 64,
 'ZigZag Note': 65,
 '슈퍼창따이': 66,
 '신재훈': 67,
 '박경 (블락비)': 68,
 '이병준': 69,
 '블랙아이드 필승': 70,
 '이상호': 71,
 '서재우 (TENTEN)': 72,
 '박수석': 73,
 '마부스 (Maboos)': 74,
 '코끼리 왕국': 75,
 'Poptime': 76,
 '김도훈 (RBW)': 77,
 '김태성': 78,
 '지오 (G.O)': 79,
 'Team One Sound': 80,
 '이기 (오레오)': 81,
 '창조': 82,
 'KUSH': 83,
 'G-High (MonoTree)': 84,
 '원펀치': 85,
 '천둥': 86,
 'Andreas Oberg': 87,
 'Ryan S. Jhun': 88,
 '정창욱': 89,
 '안영민': 90,
 'MZMC': 91,
 '류광민': 92,
 '김태현': 93,
 '전다운': 94,
 '유한진': 95,
 '이기광': 96,
 '임상혁': 97,
 'NODAY': 98,
 '디즈': 99,
 '준케이 (JUN. K)': 100}

In [153]:
# artist_group_dict2
group_dict2_artist = {}
group_dict2_artist.clear()
counter = 100
for idol in unique_idol2_artist:
    if idol not in group_dict2_artist:
        counter += 1
        group_dict2_artist[idol] = counter
    else:
        pass
group_dict2_artist

{'빅뱅': 101,
 '씨엔블루': 102,
 '비원에이포': 103,
 '틴탑': 104,
 '에프티 아일랜드': 105,
 '카라': 106,
 '인피니트': 107,
 '보이프렌드': 108,
 '블락비': 109,
 '투애니원': 110,
 '동방신기': 111,
 '원더걸스': 112,
 '비스트': 113,
 '시크릿': 114,
 '티아라': 115,
 '투피엠': 116,
 '샤이니': 117,
 '투에이엠': 118,
 '브라운 아이드 걸스': 119,
 '나인뮤지스': 120,
 '씨스타': 121,
 '슈퍼주니어': 122,
 '브레이브걸스': 123,
 '소녀시대': 124,
 '파란': 125,
 '유키스': 126,
 '엠블랙': 127,
 '제국의 아이들': 128,
 '걸스데이': 129,
 '컬러링 베이비 7공주': 130,
 '애프터 스쿨': 131,
 '에이핑크': 132,
 '써니힐': 133,
 '트랙스': 134,
 '엠아이비': 135,
 '더블에스오공일': 136,
 '슈퍼 주니어-디앤이': 137,
 '달샤벳': 138,
 '포미닛': 139,
 '오렌지캬라멜': 140,
 '스텔라': 141,
 '엔소닉': 142,
 '티맥스': 143,
 '에프엑스': 144}

In [154]:
temp_link_list = []
temp_links_list = list(grouped_idol_gen2_ranking2.apply(lambda row: {"source": row['source'], "target": row['target'], "value": row['count']}, axis=1))

In [155]:
links_list = []
for link in temp_links_list:
    record = {"value":link['value'], "source":unique_idol2.get_loc(link['source']),
     "target": unique_idol2.get_loc(link['target'])}
    links_list.append(record)
links_list

[{'value': 52, 'source': 0, 'target': 100},
 {'value': 47, 'source': 1, 'target': 101},
 {'value': 35, 'source': 2, 'target': 102},
 {'value': 31, 'source': 3, 'target': 103},
 {'value': 28, 'source': 4, 'target': 104},
 {'value': 27, 'source': 5, 'target': 105},
 {'value': 27, 'source': 6, 'target': 105},
 {'value': 26, 'source': 4, 'target': 101},
 {'value': 24, 'source': 5, 'target': 106},
 {'value': 24, 'source': 6, 'target': 106},
 {'value': 21, 'source': 6, 'target': 107},
 {'value': 21, 'source': 7, 'target': 108},
 {'value': 21, 'source': 5, 'target': 107},
 {'value': 21, 'source': 8, 'target': 104},
 {'value': 21, 'source': 9, 'target': 109},
 {'value': 20, 'source': 9, 'target': 100},
 {'value': 19, 'source': 10, 'target': 110},
 {'value': 19, 'source': 11, 'target': 104},
 {'value': 19, 'source': 12, 'target': 111},
 {'value': 17, 'source': 13, 'target': 112},
 {'value': 16, 'source': 14, 'target': 104},
 {'value': 16, 'source': 15, 'target': 112},
 {'value': 16, 'source': 16, 'target': 113},
 {'value': 16, 'source': 17, 'target': 101},
 {'value': 16, 'source': 18, 'target': 114},
 {'value': 16, 'source': 19, 'target': 104},
 {'value': 15, 'source': 12, 'target': 115},
 {'value': 15, 'source': 20, 'target': 112},
 {'value': 15, 'source': 21, 'target': 104},
 {'value': 15, 'source': 22, 'target': 116},
 {'value': 14, 'source': 23, 'target': 117},
 {'value': 14, 'source': 24, 'target': 100},
 {'value': 14, 'source': 25, 'target': 118},
 {'value': 13, 'source': 6, 'target': 119},
 {'value': 13, 'source': 3, 'target': 120},
 {'value': 13, 'source': 26, 'target': 121},
 {'value': 13, 'source': 5, 'target': 119},
 {'value': 12, 'source': 27, 'target': 113},
 {'value': 12, 'source': 3, 'target': 122},
 {'value': 12, 'source': 3, 'target': 100},
 {'value': 12, 'source': 22, 'target': 123},
 {'value': 12, 'source': 28, 'target': 112},
 {'value': 12, 'source': 29, 'target': 124},
 {'value': 12, 'source': 28, 'target': 114},
 {'value': 11, 'source': 30, 'target': 120},
 {'value': 11, 'source': 3, 'target': 125},
 {'value': 11, 'source': 10, 'target': 121},
 {'value': 11, 'source': 31, 'target': 112},
 {'value': 11, 'source': 32, 'target': 126},
 {'value': 11, 'source': 33, 'target': 103},
 {'value': 11, 'source': 21, 'target': 101},
 {'value': 10, 'source': 34, 'target': 121},
 {'value': 10, 'source': 35, 'target': 127},
 {'value': 10, 'source': 30, 'target': 128},
 {'value': 10, 'source': 31, 'target': 114},
 {'value': 10, 'source': 36, 'target': 102},
 {'value': 10, 'source': 37, 'target': 100},
 {'value': 10, 'source': 38, 'target': 106},
 {'value': 10, 'source': 39, 'target': 129},
 {'value': 9, 'source': 40, 'target': 128},
 {'value': 9, 'source': 41, 'target': 125},
 {'value': 9, 'source': 3, 'target': 130},
 {'value': 9, 'source': 42, 'target': 111},
 {'value': 9, 'source': 43, 'target': 115},
 {'value': 9, 'source': 44, 'target': 113},
 {'value': 9, 'source': 45, 'target': 107},
 {'value': 9, 'source': 28, 'target': 131},
 {'value': 9, 'source': 46, 'target': 132},
 {'value': 9, 'source': 47, 'target': 133},
 {'value': 9, 'source': 48, 'target': 120},
 {'value': 9, 'source': 43, 'target': 111},
 {'value': 9, 'source': 10, 'target': 116},
 {'value': 9, 'source': 49, 'target': 134},
 {'value': 8, 'source': 50, 'target': 131},
 {'value': 8, 'source': 51, 'target': 135},
 {'value': 8, 'source': 52, 'target': 116},
 {'value': 8, 'source': 53, 'target': 111},
 {'value': 8, 'source': 54, 'target': 103},
 {'value': 8, 'source': 55, 'target': 126},
 {'value': 8, 'source': 34, 'target': 136},
 {'value': 8, 'source': 56, 'target': 118},
 {'value': 8, 'source': 57, 'target': 126},
 {'value': 8, 'source': 58, 'target': 137},
 {'value': 8, 'source': 25, 'target': 132},
 {'value': 8, 'source': 59, 'target': 137},
 {'value': 8, 'source': 60, 'target': 102},
 {'value': 8, 'source': 61, 'target': 118},
 {'value': 7, 'source': 6, 'target': 135},
 {'value': 7, 'source': 62, 'target': 103},
 {'value': 7, 'source': 63, 'target': 116},
 {'value': 7, 'source': 64, 'target': 131},
 {'value': 7, 'source': 65, 'target': 115},
 {'value': 7, 'source': 66, 'target': 134},
 {'value': 7, 'source': 67, 'target': 108},
 {'value': 7, 'source': 28, 'target': 138},
 {'value': 7, 'source': 68, 'target': 135},
 {'value': 7, 'source': 69, 'target': 103},
 {'value': 7, 'source': 55, 'target': 112},
 {'value': 7, 'source': 70, 'target': 104},
 {'value': 7, 'source': 71, 'target': 138},
 {'value': 7, 'source': 72, 'target': 113},
 {'value': 7, 'source': 73, 'target': 103},
 {'value': 7, 'source': 5, 'target': 135},
 {'value': 7, 'source': 74, 'target': 103},
 {'value': 7, 'source': 75, 'target': 108},
 {'value': 7, 'source': 76, 'target': 104},
 {'value': 7, 'source': 77, 'target': 116},
 {'value': 7, 'source': 78, 'target': 126},
 {'value': 7, 'source': 79, 'target': 121},
 {'value': 7, 'source': 80, 'target': 139},
 {'value': 7, 'source': 81, 'target': 103},
 {'value': 6, 'source': 82, 'target': 100},
 {'value': 6, 'source': 83, 'target': 140},
 {'value': 6, 'source': 84, 'target': 141},
 {'value': 6, 'source': 85, 'target': 126},
 {'value': 6, 'source': 86, 'target': 116},
 {'value': 6, 'source': 87, 'target': 125},
 {'value': 6, 'source': 88, 'target': 119},
 {'value': 6, 'source': 89, 'target': 114},
 {'value': 6, 'source': 90, 'target': 116},
 {'value': 6, 'source': 91, 'target': 142},
 {'value': 6, 'source': 92, 'target': 114},
 {'value': 6, 'source': 93, 'target': 113},
 {'value': 6, 'source': 94, 'target': 110},
 {'value': 6, 'source': 95, 'target': 112},
 {'value': 6, 'source': 96, 'target': 138},
 {'value': 6, 'source': 97, 'target': 112},
 {'value': 6, 'source': 76, 'target': 114},
 {'value': 6, 'source': 22, 'target': 143},
 {'value': 6, 'source': 9, 'target': 109},
 {'value': 6, 'source': 98, 'target': 116},
 {'value': 6, 'source': 22, 'target': 110},
 {'value': 6, 'source': 99, 'target': 115},
 {'value': 6, 'source': 30, 'target': 114}]

In [156]:
nodes_list = []
nodes_list.clear()

for idol in group_dict2_composer:
    nodes_list.append({"name":idol, "type": "composer", "impor":total2_2_count[a.get_loc(idol)]})
for idol2 in group_dict2_artist:  
    nodes_list.append({"name":idol2, "type": "artist", "impor":0})
nodes_list

[{'name': 'G-DRAGON', 'type': 'composer', 'impor': 52},
 {'name': '정용화 (CNBLUE)', 'type': 'composer', 'impor': 47},
 {'name': '진영', 'type': 'composer', 'impor': 35},
 {'name': '용감한 형제', 'type': 'composer', 'impor': 88},
 {'name': '한승훈', 'type': 'composer', 'impor': 54},
 {'name': '김승수', 'type': 'composer', 'impor': 92},
 {'name': '한재호', 'type': 'composer', 'impor': 92},
 {'name': '지코 (ZICO)', 'type': 'composer', 'impor': 21},
 {'name': '한성호', 'type': 'composer', 'impor': 21},
 {'name': '테디', 'type': 'composer', 'impor': 47},
 {'name': '유영진', 'type': 'composer', 'impor': 39},
 {'name': '최종훈 (FT아일랜드)', 'type': 'composer', 'impor': 19},
 {'name': '박진영', 'type': 'composer', 'impor': 34},
 {'name': '용준형', 'type': 'composer', 'impor': 17},
 {'name': '이재진 (FT아일랜드)', 'type': 'composer', 'impor': 16},
 {'name': '김태주', 'type': 'composer', 'impor': 16},
 {'name': '강지원', 'type': 'composer', 'impor': 16},
 {'name': '이종현 (CNBLUE)', 'type': 'composer', 'impor': 16},
 {'name': '조영수', 'type': 'composer', 'impor': 16},
 {'name': '이홍기 (FT아일랜드)', 'type': 'composer', 'impor': 16},
 {'name': 'Good Life', 'type': 'composer', 'impor': 15},
 {'name': '김재양', 'type': 'composer', 'impor': 26},
 {'name': 'kenzie', 'type': 'composer', 'impor': 39},
 {'name': '방시혁', 'type': 'composer', 'impor': 14},
 {'name': 'T.O.P', 'type': 'composer', 'impor': 14},
 {'name': '이민수', 'type': 'composer', 'impor': 22},
 {'name': 'Kenzie', 'type': 'composer', 'impor': 13},
 {'name': '김기범', 'type': 'composer', 'impor': 12},
 {'name': '신사동 호랭이', 'type': 'composer', 'impor': 40},
 {'name': '원상우', 'type': 'composer', 'impor': 12},
 {'name': '이단옆차기', 'type': 'composer', 'impor': 27},
 {'name': '최규성', 'type': 'composer', 'impor': 21},
 {'name': '원택 (1Take)', 'type': 'composer', 'impor': 11},
 {'name': '별들의 전쟁', 'type': 'composer', 'impor': 11},
 {'name': '동해 (DONGHAE)', 'type': 'composer', 'impor': 18},
 {'name': 'e.one', 'type': 'composer', 'impor': 10},
 {'name': '우리형과 내동생', 'type': 'composer', 'impor': 10},
 {'name': '페리', 'type': 'composer', 'impor': 10},
 {'name': 'J. Yoon', 'type': 'composer', 'impor': 10},
 {'name': '전준규', 'type': 'composer', 'impor': 10},
 {'name': '남기상', 'type': 'composer', 'impor': 9},
 {'name': 'SWIN', 'type': 'composer', 'impor': 9},
 {'name': '핫펠트 (예은)', 'type': 'composer', 'impor': 9},
 {'name': '홍지상', 'type': 'composer', 'impor': 18},
 {'name': '마르코', 'type': 'composer', 'impor': 9},
 {'name': '안준성', 'type': 'composer', 'impor': 9},
 {'name': 'KZ', 'type': 'composer', 'impor': 9},
 {'name': '정모 (JUNGMO)', 'type': 'composer', 'impor': 9},
 {'name': '로빈', 'type': 'composer', 'impor': 9},
 {'name': '직 재스퍼 (Zick Jasper)', 'type': 'composer', 'impor': 9},
 {'name': 'BEOMxNANG', 'type': 'composer', 'impor': 8},
 {'name': 'Steven Lee', 'type': 'composer', 'impor': 8},
 {'name': 'Thomas Troelsen', 'type': 'composer', 'impor': 8},
 {'name': '유빈 (Yubin)', 'type': 'composer', 'impor': 8},
 {'name': '차쿤 (일렉트로보이즈)', 'type': 'composer', 'impor': 8},
 {'name': '라도', 'type': 'composer', 'impor': 15},
 {'name': '제아', 'type': 'composer', 'impor': 8},
 {'name': '태완 (Taewan)', 'type': 'composer', 'impor': 8},
 {'name': '이트라이브', 'type': 'composer', 'impor': 8},
 {'name': '수빈', 'type': 'composer', 'impor': 8},
 {'name': '신우', 'type': 'composer', 'impor': 8},
 {'name': '윤일상', 'type': 'composer', 'impor': 8},
 {'name': '투챔프', 'type': 'composer', 'impor': 7},
 {'name': '앤드류 최', 'type': 'composer', 'impor': 7},
 {'name': 'ZigZag Note', 'type': 'composer', 'impor': 7},
 {'name': '슈퍼창따이', 'type': 'composer', 'impor': 7},
 {'name': '신재훈', 'type': 'composer', 'impor': 7},
 {'name': '박경 (블락비)', 'type': 'composer', 'impor': 7},
 {'name': '이병준', 'type': 'composer', 'impor': 7},
 {'name': '블랙아이드 필승', 'type': 'composer', 'impor': 7},
 {'name': '이상호', 'type': 'composer', 'impor': 7},
 {'name': '서재우 (TENTEN)', 'type': 'composer', 'impor': 7},
 {'name': '박수석', 'type': 'composer', 'impor': 7},
 {'name': '마부스 (Maboos)', 'type': 'composer', 'impor': 7},
 {'name': '코끼리 왕국', 'type': 'composer', 'impor': 7},
 {'name': 'Poptime', 'type': 'composer', 'impor': 7},
 {'name': '김도훈 (RBW)', 'type': 'composer', 'impor': 13},
 {'name': '김태성', 'type': 'composer', 'impor': 7},
 {'name': '지오 (G.O)', 'type': 'composer', 'impor': 7},
 {'name': 'Team One Sound', 'type': 'composer', 'impor': 7},
 {'name': '이기 (오레오)', 'type': 'composer', 'impor': 7},
 {'name': '창조', 'type': 'composer', 'impor': 7},
 {'name': 'KUSH', 'type': 'composer', 'impor': 6},
 {'name': 'G-High (MonoTree)', 'type': 'composer', 'impor': 6},
 {'name': '원펀치', 'type': 'composer', 'impor': 6},
 {'name': '천둥', 'type': 'composer', 'impor': 6},
 {'name': 'Andreas Oberg', 'type': 'composer', 'impor': 6},
 {'name': 'Ryan S. Jhun', 'type': 'composer', 'impor': 6},
 {'name': '정창욱', 'type': 'composer', 'impor': 6},
 {'name': '안영민', 'type': 'composer', 'impor': 6},
 {'name': 'MZMC', 'type': 'composer', 'impor': 6},
 {'name': '류광민', 'type': 'composer', 'impor': 6},
 {'name': '김태현', 'type': 'composer', 'impor': 6},
 {'name': '전다운', 'type': 'composer', 'impor': 6},
 {'name': '유한진', 'type': 'composer', 'impor': 6},
 {'name': '이기광', 'type': 'composer', 'impor': 6},
 {'name': '임상혁', 'type': 'composer', 'impor': 6},
 {'name': 'NODAY', 'type': 'composer', 'impor': 6},
 {'name': '디즈', 'type': 'composer', 'impor': 6},
 {'name': '준케이 (JUN. K)', 'type': 'composer', 'impor': 6},
 {'name': '빅뱅', 'type': 'artist', 'impor': 0},
 {'name': '씨엔블루', 'type': 'artist', 'impor': 0},
 {'name': '비원에이포', 'type': 'artist', 'impor': 0},
 {'name': '틴탑', 'type': 'artist', 'impor': 0},
 {'name': '에프티 아일랜드', 'type': 'artist', 'impor': 0},
 {'name': '카라', 'type': 'artist', 'impor': 0},
 {'name': '인피니트', 'type': 'artist', 'impor': 0},
 {'name': '보이프렌드', 'type': 'artist', 'impor': 0},
 {'name': '블락비', 'type': 'artist', 'impor': 0},
 {'name': '투애니원', 'type': 'artist', 'impor': 0},
 {'name': '동방신기', 'type': 'artist', 'impor': 0},
 {'name': '원더걸스', 'type': 'artist', 'impor': 0},
 {'name': '비스트', 'type': 'artist', 'impor': 0},
 {'name': '시크릿', 'type': 'artist', 'impor': 0},
 {'name': '티아라', 'type': 'artist', 'impor': 0},
 {'name': '투피엠', 'type': 'artist', 'impor': 0},
 {'name': '샤이니', 'type': 'artist', 'impor': 0},
 {'name': '투에이엠', 'type': 'artist', 'impor': 0},
 {'name': '브라운 아이드 걸스', 'type': 'artist', 'impor': 0},
 {'name': '나인뮤지스', 'type': 'artist', 'impor': 0},
 {'name': '씨스타', 'type': 'artist', 'impor': 0},
 {'name': '슈퍼주니어', 'type': 'artist', 'impor': 0},
 {'name': '브레이브걸스', 'type': 'artist', 'impor': 0},
 {'name': '소녀시대', 'type': 'artist', 'impor': 0},
 {'name': '파란', 'type': 'artist', 'impor': 0},
 {'name': '유키스', 'type': 'artist', 'impor': 0},
 {'name': '엠블랙', 'type': 'artist', 'impor': 0},
 {'name': '제국의 아이들', 'type': 'artist', 'impor': 0},
 {'name': '걸스데이', 'type': 'artist', 'impor': 0},
 {'name': '컬러링 베이비 7공주', 'type': 'artist', 'impor': 0},
 {'name': '애프터 스쿨', 'type': 'artist', 'impor': 0},
 {'name': '에이핑크', 'type': 'artist', 'impor': 0},
 {'name': '써니힐', 'type': 'artist', 'impor': 0},
 {'name': '트랙스', 'type': 'artist', 'impor': 0},
 {'name': '엠아이비', 'type': 'artist', 'impor': 0},
 {'name': '더블에스오공일', 'type': 'artist', 'impor': 0},
 {'name': '슈퍼 주니어-디앤이', 'type': 'artist', 'impor': 0},
 {'name': '달샤벳', 'type': 'artist', 'impor': 0},
 {'name': '포미닛', 'type': 'artist', 'impor': 0},
 {'name': '오렌지캬라멜', 'type': 'artist', 'impor': 0},
 {'name': '스텔라', 'type': 'artist', 'impor': 0},
 {'name': '엔소닉', 'type': 'artist', 'impor': 0},
 {'name': '티맥스', 'type': 'artist', 'impor': 0},
 {'name': '에프엑스', 'type': 'artist', 'impor': 0}]

In [157]:
json_prep = {"links":links_list, "nodes":nodes_list}

json_prep.keys()

dict_keys(['links', 'nodes'])

In [158]:
json_dump = json.dumps(json_prep, indent=1, sort_keys=True, ensure_ascii=False)

In [159]:
pd.DataFrame(json_prep['nodes'])

     impor          name      type
0       52      G-DRAGON  composer
1       47  정용화 (CNBLUE)  composer
2       35            진영  composer
3       88        용감한 형제  composer
4       54           한승훈  composer
5       92           김승수  composer
6       92           한재호  composer
7       21     지코 (ZICO)  composer
8       21           한성호  composer
9       47            테디  composer
10      39           유영진  composer
11      19  최종훈 (FT아일랜드)  composer
12      34           박진영  composer
13      17           용준형  composer
14      16  이재진 (FT아일랜드)  composer
15      16           김태주  composer
16      16           강지원  composer
17      16  이종현 (CNBLUE)  composer
18      16           조영수  composer
19      16  이홍기 (FT아일랜드)  composer
20      15     Good Life  composer
21      26           김재양  composer
22      39        kenzie  composer
23      14           방시혁  composer
24      14         T.O.P  composer
25      22           이민수  composer
26      13        Kenzie  composer
27      12           김기범  composer
28      40       신사동 호랭이  composer
29      12           원상우  composer
..     ...           ...       ...
114      0           티아라    artist
115      0           투피엠    artist
116      0           샤이니    artist
117      0          투에이엠    artist
118      0    브라운 아이드 걸스    artist
119      0         나인뮤지스    artist
120      0           씨스타    artist
121      0         슈퍼주니어    artist
122      0        브레이브걸스    artist
123      0          소녀시대    artist
124      0            파란    artist
125      0           유키스    artist
126      0           엠블랙    artist
127      0       제국의 아이들    artist
128      0          걸스데이    artist
129      0   컬러링 베이비 7공주    artist
130      0        애프터 스쿨    artist
131      0          에이핑크    artist
132      0           써니힐    artist
133      0           트랙스    artist
134      0          엠아이비    artist
135      0       더블에스오공일    artist
136      0    슈퍼 주니어-디앤이    artist
137      0           달샤벳    artist
138      0           포미닛    artist
139      0        오렌지캬라멜    artist
140      0           스텔라    artist
141      0           엔소닉    artist
142      0           티맥스    artist
143      0          에프엑스    artist

[144 rows x 3 columns]

In [160]:
pd.DataFrame(json_prep['links'])

     source  target  value
0         0     100     52
1         1     101     47
2         2     102     35
3         3     103     31
4         4     104     28
5         5     105     27
6         6     105     27
7         4     101     26
8         5     106     24
9         6     106     24
10        6     107     21
11        7     108     21
12        5     107     21
13        8     104     21
14        9     109     21
15        9     100     20
16       10     110     19
17       11     104     19
18       12     111     19
19       13     112     17
20       14     104     16
21       15     112     16
22       16     113     16
23       17     101     16
24       18     114     16
25       19     104     16
26       12     115     15
27       20     112     15
28       21     104     15
29       22     116     15
..      ...     ...    ...
104      75     108      7
105      76     104      7
106      77     116      7
107      78     126      7
108      79     121      7
109      80     139      7
110      81     103      7
111      82     100      6
112      83     140      6
113      84     141      6
114      85     126      6
115      86     116      6
116      87     125      6
117      88     119      6
118      89     114      6
119      90     116      6
120      91     142      6
121      92     114      6
122      93     113      6
123      94     110      6
124      95     112      6
125      96     138      6
126      97     112      6
127      76     114      6
128      22     143      6
129       9     109      6
130      98     116      6
131      22     110      6
132      99     115      6
133      30     114      6

[134 rows x 3 columns]

In [161]:
filename_out = 'composer_gen2.json'
json_out = open(filename_out,'w')
json_out.write(json_dump)
json_out.close()

### 3) Gen3 작업

In [162]:
# composer_gen2의 가수 목록 데이터프레임 생성
i = 0
a = 0
b = 0
composer = []
artist = []

composer.clear()
artist.clear()
    
for i in range(0, len(composer_gen3)):
    try:
        for a in range(0, len(preprocess(composer_gen3.composer[i], composer_gen3.artist[i])[0])):
            composer.append(str(preprocess(composer_gen3.composer[i], composer_gen3.artist[i])[0][a]))
        for b in range(0, len(preprocess(composer_gen3.composer[i], composer_gen3.artist[i])[1])):
            artist.append(str(preprocess(composer_gen3.composer[i], composer_gen3.artist[i])[1][b]))
    except:
        composer.append('')
        artist.append('')
    
preprocessing_gen3 = pd.DataFrame({"composer" : composer, "artist" : artist, "generation" : 1})
preprocessing_gen3

                composer   artist  generation
0                     소연  (여자)아이들           1
1       빅싼초 (Yummy Tone)  (여자)아이들           1
2                    윤종성  (여자)아이들           1
3                 Le`mon  (여자)아이들           1
4     ZeroZine (MosPick)  (여자)아이들           1
5        Ferdy (MosPick)  (여자)아이들           1
6       빅싼초 (Yummy Tone)  (여자)아이들           1
7       박해일 (Yummy Tone)  (여자)아이들           1
8                   재리포터  (여자)아이들           1
9                   ARIN  (여자)아이들           1
10              VINCENZO  (여자)아이들           1
11                 Fuxxy  (여자)아이들           1
12          Any Masingga  (여자)아이들           1
13    ZeroZine (MosPick)  (여자)아이들           1
14                   정일훈  (여자)아이들           1
15              VINCENZO  (여자)아이들           1
16          Any Masingga  (여자)아이들           1
17                 Fuxxy  (여자)아이들           1
18          서재우 (TENTEN)  (여자)아이들           1
19          서용배 (TENTEN)  (여자)아이들           1
20    BreadBeat (TENTEN)  (여자)아이들           1
21                    소연  (여자)아이들           1
22      빅싼초 (Yummy Tone)  (여자)아이들           1
23                   박진영      갓세븐           1
24                 NODAY      갓세븐           1
25                 Chloe      갓세븐           1
26                   박진영      갓세븐           1
27               S. Bros      갓세븐           1
28                                          1
29               Mr. Cho      갓세븐           1
...                  ...      ...         ...
7100               이트라이브     히스토리           1
7101          BlueRhythm     히스토리           1
7102   장이정 (JANGYIJEONG)     히스토리           1
7103   장이정 (JANGYIJEONG)     히스토리           1
7104               이어달리기     히스토리           1
7105   장이정 (JANGYIJEONG)     히스토리           1
7106          BlueRhythm     히스토리           1
7107   장이정 (JANGYIJEONG)     히스토리           1
7108                 송경일     히스토리           1
7109                 나도균     히스토리           1
7110                 김태영     히스토리           1
7111   장이정 (JANGYIJEONG)     히스토리           1
7112          BlueRhythm     히스토리           1
7113   장이정 (JANGYIJEONG)     히스토리           1
7114                 김재호     히스토리           1
7115          BlueRhythm     히스토리           1
7116                 조영수       힌트           1
7117                 권도윤       힌트           1
7118                 TAQ       힌트           1
7119                  카푸       힌트           1
7120                 권도윤       힌트           1
7121                 TAQ       힌트           1
7122                  카푸       힌트           1
7123                 권도윤       힌트           1
7124                 TAQ       힌트           1
7125                  카푸       힌트           1
7126                 김남경       힌트           1
7127                 권도윤       힌트           1
7128                 TAQ       힌트           1
7129                  카푸       힌트           1

[7130 rows x 3 columns]

In [163]:
preprocessing_gen3.rename(columns={"composer":"source","artist":"target"}, inplace=True)

In [164]:
grouped_idol_gen3 = preprocessing_gen3.groupby(["source","target"]).size().reset_index()
grouped_idol_gen3.head(20) # 갑자기 빈 행이 존재함 ->삭제

    source target   0
0                   2
1      $un   더보이즈   1
2      $un     빅스   1
3      $un    업텐션   1
4   110403    갓세븐   2
5     1105    임팩트   2
6     14o2   러버소울   1
7     1601    소나무   1
8     1601   에이프릴   1
9     1601   온앤오프   1
10    1601     카드   1
11     1Hz    업텐션   1
12    1MAD  몬스타엑스   1
13  1Piece   러블리즈  15
14    1of1   더보이즈   2
15    1of1  제이비제이   1
16     220    갓세븐   2
17     220   더보이즈   1
18     220   데이식스   3
19     220   레드벨벳   1

In [165]:
# 칼럼 0 제거
grouped_idol_gen3.drop(grouped_idol_gen3.index[[0]], inplace=True)
grouped_idol_gen3 = grouped_idol_gen3.reset_index()
grouped_idol_gen3 = grouped_idol_gen3.drop(['index'], axis = 1)

In [166]:
# 칼럼 0 -> count로 이름 칼럼명 수정
grouped_idol_gen3.rename(columns={0:'count'}, inplace=True)
len(grouped_idol_gen3)

3842

In [167]:
grouped_idol_gen3_ranking = grouped_idol_gen3.sort_values(by='count', ascending=False)
grouped_idol_gen3_ranking = grouped_idol_gen3_ranking.reset_index(drop=True)
grouped_idol_gen3_ranking.head()

              source target  count
0                 RM  방탄소년단     85
1               SUGA  방탄소년단     72
2              Pdogg  방탄소년단     71
3             j-hope  방탄소년단     66
4  WOOZI (SEVENTEEN)    세븐틴     47

## json 파일 생성하기

In [168]:
unique_idol = pd.Index(grouped_idol_gen3_ranking['source']
                      .append(grouped_idol_gen3_ranking['target'])
                      .reset_index(drop=True).unique())

In [169]:
unique_idol

Index(['RM', 'SUGA', 'Pdogg', 'j-hope', 'WOOZI (SEVENTEEN)', '방시혁', 'BUMZU',
       'Young K', 'Slow Rabbit', '원필',
       ...
       '구구단 오구오구', '옆집소녀', '에이오에이 크림', '단발머리', '핫젝갓알지', '구구단 세미나', '지디 앤 태양',
       '소녀시대 오지지', '프리스틴 V', '엠앤엔'],
      dtype='object', length=2174)

In [170]:
grouped_idol_gen3_ranking.rename(columns={0:'count'}, inplace=True)
len(grouped_idol_gen3_ranking)

3842

In [171]:
grouped_idol_gen3_ranking['count'].unique()

array([85, 72, 71, 66, 47, 41, 36, 33, 29, 26, 25, 24, 23, 22, 21, 20, 19,
       18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,
        1], dtype=int64)

In [172]:
grouped_idol_gen3_ranking.loc[grouped_idol_gen3_ranking['source'] == "TEDDY"]

     source target  count
71    TEDDY   블랙핑크      9
327   TEDDY    아이콘      3
986   TEDDY      맙      2
3349  TEDDY     위너      1

In [173]:
grouped_idol_gen3_ranking['source'] = grouped_idol_gen3_ranking['source'].replace('TEDDY', '테디')

In [174]:
grouped_idol_gen3_ranking.loc[grouped_idol_gen3_ranking['source'] == "TEDDY"]

Empty DataFrame
Columns: [source, target, count]
Index: []

In [175]:
grouped_idol_gen3_ranking2 = grouped_idol_gen3_ranking[grouped_idol_gen3_ranking['count'] > 5]
grouped_idol_gen3_ranking2

                  source    target  count
0                     RM     방탄소년단     85
1                   SUGA     방탄소년단     72
2                  Pdogg     방탄소년단     71
3                 j-hope     방탄소년단     66
4      WOOZI (SEVENTEEN)       세븐틴     47
5                    방시혁     방탄소년단     41
6                  BUMZU       세븐틴     36
7                Young K      데이식스     36
8            Slow Rabbit     방탄소년단     33
9                     원필      데이식스     33
10                   홍지상      데이식스     29
11                   B.I       아이콘     29
12           Supreme Boi     방탄소년단     26
13                    성진      데이식스     25
14                   Jae      데이식스     25
15             김도훈 (RBW)       마마무     24
16    이우민 `collapsedone`      데이식스     23
17          서재우 (TENTEN)       비투비     23
18             LE (EXID)    이엑스아이디     22
19               신사동 호랭이    이엑스아이디     22
20                   박우상       마마무     21
21            MELODESIGN        빅스     20
22            한 (3RACHA)   스트레이 키즈     19
23           방찬 (3RACHA)   스트레이 키즈     19
24                   임현식       비투비     18
25                   강승윤        위너     18
26                   김태주       크나큰     18
27                   정일훈       비투비     17
28              SWEETUNE       스누퍼     17
29           창빈 (3RACHA)   스트레이 키즈     17
..                   ...       ...    ...
124                이단옆차기       스피드      6
125          DAY6 (데이식스)      데이식스      6
126  코스믹 걸 (Cosmic Girl)       마마무      6
127         마부스 (Maboos)       빅스타      6
128                가면라이더   리얼걸프로젝트      6
129                  마르코      비아이지      6
130                슈퍼창따이   레이디스 코드      6
131             Distract       갓세븐      6
132                   제니       다이아      6
133                  박수석     티알씨엔지      6
134        황현 (MonoTree)      온앤오프      6
135       Razer (Strike)      러블리즈      6
136             CHOICE37       아이콘      6
137   ZeroZine (MosPick)       비투비      6
138                  피터팬       다이아      6
139            진영 (GOT7)       갓세븐      6
140          Erik Lidbom    에스에프나인      6
141                 LEEZ      드림캐쳐      6
142                  임팩트       임팩트      6
143                  박기태       세븐틴      6
144                  남태현        위너      6
145                  전다운       헤일로      6
146                  한승훈    에스에프나인      6
147            유겸 (GOT7)       갓세븐      6
148                   KZ      히스토리      6
149                   성연      프리스틴      6
150            P.O (블락비)  블락비 바스타즈      6
151                  황세준        빅스      6
152           Tay Jasper   엔시티 일이칠      6
153              코스믹 사운드       마마무      6

[154 rows x 3 columns]

In [176]:
grouped_idol_gen3_ranking2 = grouped_idol_gen3_ranking2.reset_index()

In [177]:
grouped_idol_gen3_ranking2 = grouped_idol_gen3_ranking2.drop(['index'], axis = 1)

In [178]:
total_2 = grouped_idol_gen3_ranking2.groupby(['source'], as_index=False).sum()
total2_2 = total_2.sort_values(by='count', ascending=False).reset_index()
total2_2 = total2_2.drop(['index'], axis = 1)
total2_2_sourcename = total2_2['source'].tolist()
total2_2_count = total2_2['count'].tolist()
len(total2_2_sourcename)

128

In [179]:
a = pd.Index(total2_2_sourcename)
a

Index(['RM', 'SUGA', 'Pdogg', 'j-hope', 'BUMZU', 'WOOZI (SEVENTEEN)', '방시혁',
       '김창락', 'Young K', 'Slow Rabbit',
       ...
       'DAY6 (데이식스)', '제니', 'Razer (Strike)', '슈퍼창따이', 'P.O (블락비)', 'Distract',
       '임팩트', '어벤전승', '남태현', '박기태'],
      dtype='object', length=128)

In [180]:
unique_idol2 = pd.Index(grouped_idol_gen3_ranking2['source']
                      .append(grouped_idol_gen3_ranking2['target'])
                      .reset_index(drop=True).unique())
unique_idol2_composer = pd.Index(grouped_idol_gen3_ranking2['source'] .reset_index(drop=True).unique())
unique_idol2_artist = pd.Index(grouped_idol_gen3_ranking2['target'] .reset_index(drop=True).unique())

In [181]:
source_name = grouped_idol_gen3_ranking2['source']

In [182]:
# composer_group_dict2
group_dict2_composer = {}
group_dict2_composer.clear()
counter = 0
for idol in unique_idol2_composer:
    if idol not in group_dict2_composer:
        counter += 1
        group_dict2_composer[idol] = counter
    else:
        pass
group_dict2_composer

{'RM': 1,
 'SUGA': 2,
 'Pdogg': 3,
 'j-hope': 4,
 'WOOZI (SEVENTEEN)': 5,
 '방시혁': 6,
 'BUMZU': 7,
 'Young K': 8,
 'Slow Rabbit': 9,
 '원필': 10,
 '홍지상': 11,
 'B.I': 12,
 'Supreme Boi': 13,
 '성진': 14,
 'Jae': 15,
 '김도훈 (RBW)': 16,
 '이우민 `collapsedone`': 17,
 '서재우 (TENTEN)': 18,
 'LE (EXID)': 19,
 '신사동 호랭이': 20,
 '박우상': 21,
 'MELODESIGN': 22,
 '한 (3RACHA)': 23,
 '방찬 (3RACHA)': 24,
 '임현식': 25,
 '강승윤': 26,
 '김태주': 27,
 '정일훈': 28,
 'SWEETUNE': 29,
 '창빈 (3RACHA)': 30,
 '김창락': 31,
 '방용국': 32,
 '이기 (오레오)': 33,
 '1Piece': 34,
 '박수석': 35,
 '용감한 형제': 36,
 '서용배 (TENTEN)': 37,
 '용배 (RBW)': 38,
 'JB (GOT7)': 39,
 '동네형': 40,
 '김기범': 41,
 '원영헌': 42,
 'Andreas Oberg': 43,
 'Hip Wave Sound': 44,
 'MZMC': 45,
 'KZ': 46,
 '강지원': 47,
 '코리': 48,
 '낯선': 49,
 'MINO': 50,
 '마르코': 51,
 'Sean Alexander': 52,
 '예빈 (다이아)': 53,
 '강욱진': 54,
 'ADORA': 55,
 'Ferdy (MosPick)': 56,
 '후이 (펜타곤)': 57,
 '조성호': 58,
 '라비 (빅스)': 59,
 '한승훈': 60,
 '별들의 전쟁': 61,
 '기희현': 62,
 '리시': 63,
 '주헌 (몬스타엑스)': 64,
 '테디': 65,
 '장이정 (JANGYIJEONG)': 66,
 'Adrian Mckinnon': 67,
 'ZeroZine (MosPick)': 68,
 'earattack': 69,
 'Good Life': 70,
 '미친감성': 71,
 '빅싼초 (Yummy Tone)': 72,
 'Daniel Obi Klein': 73,
 '라도': 74,
 'AiRPLAY': 75,
 'LDN Noise': 76,
 '강동하': 77,
 '전다운': 78,
 '박근태': 79,
 'Otha `Vakseen` Davis III': 80,
 'Tay Jasper': 81,
 '백호 (뉴이스트)': 82,
 'Chloe': 83,
 '정균': 84,
 '유니스': 85,
 'kenzie': 86,
 'Ollounder': 87,
 'NODAY': 88,
 'John K': 89,
 '박은우': 90,
 '신혁': 91,
 '박진영': 92,
 '에스나 (eSNa)': 93,
 '이상호': 94,
 '이단옆차기': 95,
 'Erik Lidbom': 96,
 'Albi Albertsson': 97,
 'Ryan S. Jhun': 98,
 '일 (IL)': 99,
 'Darren Smith': 100,
 'ESBEE': 101,
 '함길수': 102,
 '이던': 103,
 '주태영': 104,
 'Ye-Yo!': 105,
 '어벤전승': 106,
 '차쿤 (일렉트로보이즈)': 107,
 'DAY6 (데이식스)': 108,
 '코스믹 걸 (Cosmic Girl)': 109,
 '마부스 (Maboos)': 110,
 '가면라이더': 111,
 '슈퍼창따이': 112,
 'Distract': 113,
 '제니': 114,
 '황현 (MonoTree)': 115,
 'Razer (Strike)': 116,
 'CHOICE37': 117,
 '피터팬': 118,
 '진영 (GOT7)': 119,
 'LEEZ': 120,
 '임팩트': 121,
 '박기태': 122,
 '남태현': 123,
 '유겸 (GOT7)': 124,
 '성연': 125,
 'P.O (블락비)': 126,
 '황세준': 127,
 '코스믹 사운드': 128}

In [183]:
# artist_group_dict2
group_dict2_artist = {}
group_dict2_artist.clear()
counter = 128
for idol in unique_idol2_artist:
    if idol not in group_dict2_artist:
        counter += 1
        group_dict2_artist[idol] = counter
    else:
        pass
group_dict2_artist

{'방탄소년단': 129,
 '세븐틴': 130,
 '데이식스': 131,
 '아이콘': 132,
 '마마무': 133,
 '비투비': 134,
 '이엑스아이디': 135,
 '빅스': 136,
 '스트레이 키즈': 137,
 '위너': 138,
 '크나큰': 139,
 '스누퍼': 140,
 '에스에프나인': 141,
 '비에이피': 142,
 '여자친구': 143,
 '러블리즈': 144,
 '에이오에이': 145,
 '아스트로': 146,
 '갓세븐': 147,
 '오마이걸': 148,
 '비비드': 149,
 '엑소': 150,
 '헤일로': 151,
 '투포케이': 152,
 '카드': 153,
 '빅스타': 154,
 '다이아': 155,
 '뉴이스트 W': 156,
 '씨엘씨': 157,
 '펜타곤': 158,
 '소나무': 159,
 '엔플라잉': 160,
 '몬스타엑스': 161,
 '백퍼센트': 162,
 '블랙핑크': 163,
 '히스토리': 164,
 '하이라이트': 165,
 '레드벨벳': 166,
 '씨클라운': 167,
 '소년공화국': 168,
 '빅플로': 169,
 '뉴이스트': 170,
 '드림캐쳐': 171,
 '비비드걸': 172,
 '업텐션': 173,
 '제이제이씨씨': 174,
 '브이에이브이': 175,
 '베리굿': 176,
 '라붐': 177,
 '스피드': 178,
 '리얼걸프로젝트': 179,
 '비아이지': 180,
 '레이디스 코드': 181,
 '티알씨엔지': 182,
 '온앤오프': 183,
 '임팩트': 184,
 '프리스틴': 185,
 '블락비 바스타즈': 186,
 '엔시티 일이칠': 187}

In [184]:
temp_link_list = []
temp_links_list = list(grouped_idol_gen3_ranking2.apply(lambda row: {"source": row['source'], "target": row['target'], "value": row['count']}, axis=1))

In [185]:
links_list = []
for link in temp_links_list:
    record = {"value":link['value'], "source":unique_idol2.get_loc(link['source']),
     "target": unique_idol2.get_loc(link['target'])}
    links_list.append(record)
links_list

[{'value': 85, 'source': 0, 'target': 128},
 {'value': 72, 'source': 1, 'target': 128},
 {'value': 71, 'source': 2, 'target': 128},
 {'value': 66, 'source': 3, 'target': 128},
 {'value': 47, 'source': 4, 'target': 129},
 {'value': 41, 'source': 5, 'target': 128},
 {'value': 36, 'source': 6, 'target': 129},
 {'value': 36, 'source': 7, 'target': 130},
 {'value': 33, 'source': 8, 'target': 128},
 {'value': 33, 'source': 9, 'target': 130},
 {'value': 29, 'source': 10, 'target': 130},
 {'value': 29, 'source': 11, 'target': 131},
 {'value': 26, 'source': 12, 'target': 128},
 {'value': 25, 'source': 13, 'target': 130},
 {'value': 25, 'source': 14, 'target': 130},
 {'value': 24, 'source': 15, 'target': 132},
 {'value': 23, 'source': 16, 'target': 130},
 {'value': 23, 'source': 17, 'target': 133},
 {'value': 22, 'source': 18, 'target': 134},
 {'value': 22, 'source': 19, 'target': 134},
 {'value': 21, 'source': 20, 'target': 132},
 {'value': 20, 'source': 21, 'target': 135},
 {'value': 19, 'source': 22, 'target': 136},
 {'value': 19, 'source': 23, 'target': 136},
 {'value': 18, 'source': 24, 'target': 133},
 {'value': 18, 'source': 25, 'target': 137},
 {'value': 18, 'source': 26, 'target': 138},
 {'value': 17, 'source': 27, 'target': 133},
 {'value': 17, 'source': 28, 'target': 139},
 {'value': 17, 'source': 29, 'target': 136},
 {'value': 17, 'source': 30, 'target': 140},
 {'value': 16, 'source': 31, 'target': 141},
 {'value': 15, 'source': 32, 'target': 142},
 {'value': 15, 'source': 33, 'target': 143},
 {'value': 15, 'source': 34, 'target': 141},
 {'value': 15, 'source': 35, 'target': 144},
 {'value': 14, 'source': 36, 'target': 133},
 {'value': 14, 'source': 32, 'target': 145},
 {'value': 14, 'source': 37, 'target': 142},
 {'value': 14, 'source': 38, 'target': 146},
 {'value': 14, 'source': 39, 'target': 129},
 {'value': 14, 'source': 40, 'target': 141},
 {'value': 14, 'source': 41, 'target': 129},
 {'value': 13, 'source': 42, 'target': 147},
 {'value': 13, 'source': 43, 'target': 148},
 {'value': 13, 'source': 44, 'target': 149},
 {'value': 13, 'source': 45, 'target': 150},
 {'value': 13, 'source': 30, 'target': 141},
 {'value': 13, 'source': 46, 'target': 141},
 {'value': 13, 'source': 47, 'target': 151},
 {'value': 12, 'source': 48, 'target': 152},
 {'value': 12, 'source': 35, 'target': 153},
 {'value': 12, 'source': 49, 'target': 137},
 {'value': 12, 'source': 50, 'target': 141},
 {'value': 12, 'source': 51, 'target': 147},
 {'value': 12, 'source': 52, 'target': 154},
 {'value': 12, 'source': 53, 'target': 137},
 {'value': 11, 'source': 54, 'target': 128},
 {'value': 11, 'source': 6, 'target': 155},
 {'value': 11, 'source': 55, 'target': 156},
 {'value': 11, 'source': 56, 'target': 157},
 {'value': 11, 'source': 57, 'target': 133},
 {'value': 11, 'source': 57, 'target': 156},
 {'value': 10, 'source': 58, 'target': 135},
 {'value': 10, 'source': 34, 'target': 158},
 {'value': 10, 'source': 59, 'target': 159},
 {'value': 10, 'source': 60, 'target': 153},
 {'value': 10, 'source': 61, 'target': 154},
 {'value': 10, 'source': 62, 'target': 160},
 {'value': 10, 'source': 63, 'target': 160},
 {'value': 10, 'source': 28, 'target': 161},
 {'value': 9, 'source': 64, 'target': 162},
 {'value': 9, 'source': 65, 'target': 163},
 {'value': 9, 'source': 66, 'target': 149},
 {'value': 9, 'source': 67, 'target': 156},
 {'value': 9, 'source': 68, 'target': 146},
 {'value': 9, 'source': 69, 'target': 164},
 {'value': 9, 'source': 37, 'target': 145},
 {'value': 9, 'source': 70, 'target': 150},
 {'value': 9, 'source': 71, 'target': 156},
 {'value': 8, 'source': 30, 'target': 159},
 {'value': 8, 'source': 72, 'target': 165},
 {'value': 8, 'source': 73, 'target': 166},
 {'value': 8, 'source': 59, 'target': 144},
 {'value': 8, 'source': 74, 'target': 137},
 {'value': 8, 'source': 75, 'target': 149},
 {'value': 8, 'source': 53, 'target': 131},
 {'value': 8, 'source': 76, 'target': 157},
 {'value': 8, 'source': 77, 'target': 141},
 {'value': 8, 'source': 78, 'target': 167},
 {'value': 8, 'source': 79, 'target': 149},
 {'value': 8, 'source': 80, 'target': 149},
 {'value': 8, 'source': 81, 'target': 155},
 {'value': 7, 'source': 82, 'target': 146},
 {'value': 7, 'source': 83, 'target': 168},
 {'value': 7, 'source': 84, 'target': 154},
 {'value': 7, 'source': 85, 'target': 149},
 {'value': 7, 'source': 6, 'target': 169},
 {'value': 7, 'source': 86, 'target': 170},
 {'value': 7, 'source': 85, 'target': 165},
 {'value': 7, 'source': 87, 'target': 146},
 {'value': 7, 'source': 88, 'target': 171},
 {'value': 7, 'source': 89, 'target': 158},
 {'value': 7, 'source': 17, 'target': 156},
 {'value': 7, 'source': 90, 'target': 172},
 {'value': 7, 'source': 91, 'target': 146},
 {'value': 7, 'source': 92, 'target': 132},
 {'value': 7, 'source': 93, 'target': 144},
 {'value': 7, 'source': 94, 'target': 173},
 {'value': 7, 'source': 95, 'target': 135},
 {'value': 7, 'source': 96, 'target': 135},
 {'value': 7, 'source': 97, 'target': 174},
 {'value': 7, 'source': 55, 'target': 133},
 {'value': 7, 'source': 98, 'target': 133},
 {'value': 7, 'source': 99, 'target': 147},
 {'value': 7, 'source': 100, 'target': 160},
 {'value': 7, 'source': 55, 'target': 157},
 {'value': 7, 'source': 101, 'target': 148},
 {'value': 7, 'source': 102, 'target': 157},
 {'value': 6, 'source': 103, 'target': 175},
 {'value': 6, 'source': 36, 'target': 145},
 {'value': 6, 'source': 104, 'target': 160},
 {'value': 6, 'source': 105, 'target': 176},
 {'value': 6, 'source': 106, 'target': 144},
 {'value': 6, 'source': 94, 'target': 177},
 {'value': 6, 'source': 107, 'target': 130},
 {'value': 6, 'source': 108, 'target': 132},
 {'value': 6, 'source': 109, 'target': 153},
 {'value': 6, 'source': 110, 'target': 178},
 {'value': 6, 'source': 50, 'target': 179},
 {'value': 6, 'source': 111, 'target': 180},
 {'value': 6, 'source': 112, 'target': 146},
 {'value': 6, 'source': 113, 'target': 154},
 {'value': 6, 'source': 34, 'target': 181},
 {'value': 6, 'source': 114, 'target': 182},
 {'value': 6, 'source': 115, 'target': 143},
 {'value': 6, 'source': 116, 'target': 131},
 {'value': 6, 'source': 67, 'target': 133},
 {'value': 6, 'source': 117, 'target': 154},
 {'value': 6, 'source': 118, 'target': 146},
 {'value': 6, 'source': 95, 'target': 140},
 {'value': 6, 'source': 119, 'target': 170},
 {'value': 6, 'source': 120, 'target': 120},
 {'value': 6, 'source': 121, 'target': 129},
 {'value': 6, 'source': 122, 'target': 137},
 {'value': 6, 'source': 77, 'target': 150},
 {'value': 6, 'source': 59, 'target': 140},
 {'value': 6, 'source': 123, 'target': 146},
 {'value': 6, 'source': 45, 'target': 163},
 {'value': 6, 'source': 124, 'target': 183},
 {'value': 6, 'source': 125, 'target': 184},
 {'value': 6, 'source': 126, 'target': 135},
 {'value': 6, 'source': 80, 'target': 185},
 {'value': 6, 'source': 127, 'target': 132}]

In [186]:
nodes_list = []
nodes_list.clear()

for idol in group_dict2_composer:
    nodes_list.append({"name":idol, "type": "composer", "impor":total2_2_count[a.get_loc(idol)]})
for idol2 in group_dict2_artist:  
    nodes_list.append({"name":idol2, "type": "artist", "impor":0})
nodes_list

[{'name': 'RM', 'type': 'composer', 'impor': 85},
 {'name': 'SUGA', 'type': 'composer', 'impor': 72},
 {'name': 'Pdogg', 'type': 'composer', 'impor': 71},
 {'name': 'j-hope', 'type': 'composer', 'impor': 66},
 {'name': 'WOOZI (SEVENTEEN)', 'type': 'composer', 'impor': 47},
 {'name': '방시혁', 'type': 'composer', 'impor': 41},
 {'name': 'BUMZU', 'type': 'composer', 'impor': 54},
 {'name': 'Young K', 'type': 'composer', 'impor': 36},
 {'name': 'Slow Rabbit', 'type': 'composer', 'impor': 33},
 {'name': '원필', 'type': 'composer', 'impor': 33},
 {'name': '홍지상', 'type': 'composer', 'impor': 29},
 {'name': 'B.I', 'type': 'composer', 'impor': 29},
 {'name': 'Supreme Boi', 'type': 'composer', 'impor': 26},
 {'name': '성진', 'type': 'composer', 'impor': 25},
 {'name': 'Jae', 'type': 'composer', 'impor': 25},
 {'name': '김도훈 (RBW)', 'type': 'composer', 'impor': 24},
 {'name': '이우민 `collapsedone`', 'type': 'composer', 'impor': 23},
 {'name': '서재우 (TENTEN)', 'type': 'composer', 'impor': 30},
 {'name': 'LE (EXID)', 'type': 'composer', 'impor': 22},
 {'name': '신사동 호랭이', 'type': 'composer', 'impor': 22},
 {'name': '박우상', 'type': 'composer', 'impor': 21},
 {'name': 'MELODESIGN', 'type': 'composer', 'impor': 20},
 {'name': '한 (3RACHA)', 'type': 'composer', 'impor': 19},
 {'name': '방찬 (3RACHA)', 'type': 'composer', 'impor': 19},
 {'name': '임현식', 'type': 'composer', 'impor': 18},
 {'name': '강승윤', 'type': 'composer', 'impor': 18},
 {'name': '김태주', 'type': 'composer', 'impor': 18},
 {'name': '정일훈', 'type': 'composer', 'impor': 17},
 {'name': 'SWEETUNE', 'type': 'composer', 'impor': 27},
 {'name': '창빈 (3RACHA)', 'type': 'composer', 'impor': 17},
 {'name': '김창락', 'type': 'composer', 'impor': 38},
 {'name': '방용국', 'type': 'composer', 'impor': 16},
 {'name': '이기 (오레오)', 'type': 'composer', 'impor': 29},
 {'name': '1Piece', 'type': 'composer', 'impor': 15},
 {'name': '박수석', 'type': 'composer', 'impor': 31},
 {'name': '용감한 형제', 'type': 'composer', 'impor': 27},
 {'name': '서용배 (TENTEN)', 'type': 'composer', 'impor': 20},
 {'name': '용배 (RBW)', 'type': 'composer', 'impor': 23},
 {'name': 'JB (GOT7)', 'type': 'composer', 'impor': 14},
 {'name': '동네형', 'type': 'composer', 'impor': 14},
 {'name': '김기범', 'type': 'composer', 'impor': 14},
 {'name': '원영헌', 'type': 'composer', 'impor': 14},
 {'name': 'Andreas Oberg', 'type': 'composer', 'impor': 13},
 {'name': 'Hip Wave Sound', 'type': 'composer', 'impor': 13},
 {'name': 'MZMC', 'type': 'composer', 'impor': 13},
 {'name': 'KZ', 'type': 'composer', 'impor': 19},
 {'name': '강지원', 'type': 'composer', 'impor': 13},
 {'name': '코리', 'type': 'composer', 'impor': 13},
 {'name': '낯선', 'type': 'composer', 'impor': 12},
 {'name': 'MINO', 'type': 'composer', 'impor': 12},
 {'name': '마르코', 'type': 'composer', 'impor': 18},
 {'name': 'Sean Alexander', 'type': 'composer', 'impor': 12},
 {'name': '예빈 (다이아)', 'type': 'composer', 'impor': 12},
 {'name': '강욱진', 'type': 'composer', 'impor': 20},
 {'name': 'ADORA', 'type': 'composer', 'impor': 11},
 {'name': 'Ferdy (MosPick)', 'type': 'composer', 'impor': 25},
 {'name': '후이 (펜타곤)', 'type': 'composer', 'impor': 11},
 {'name': '조성호', 'type': 'composer', 'impor': 22},
 {'name': '라비 (빅스)', 'type': 'composer', 'impor': 10},
 {'name': '한승훈', 'type': 'composer', 'impor': 24},
 {'name': '별들의 전쟁', 'type': 'composer', 'impor': 10},
 {'name': '기희현', 'type': 'composer', 'impor': 10},
 {'name': '리시', 'type': 'composer', 'impor': 10},
 {'name': '주헌 (몬스타엑스)', 'type': 'composer', 'impor': 10},
 {'name': '테디', 'type': 'composer', 'impor': 9},
 {'name': '장이정 (JANGYIJEONG)', 'type': 'composer', 'impor': 9},
 {'name': 'Adrian Mckinnon', 'type': 'composer', 'impor': 9},
 {'name': 'ZeroZine (MosPick)', 'type': 'composer', 'impor': 15},
 {'name': 'earattack', 'type': 'composer', 'impor': 9},
 {'name': 'Good Life', 'type': 'composer', 'impor': 9},
 {'name': '미친감성', 'type': 'composer', 'impor': 9},
 {'name': '빅싼초 (Yummy Tone)', 'type': 'composer', 'impor': 9},
 {'name': 'Daniel Obi Klein', 'type': 'composer', 'impor': 8},
 {'name': '라도', 'type': 'composer', 'impor': 8},
 {'name': 'AiRPLAY', 'type': 'composer', 'impor': 8},
 {'name': 'LDN Noise', 'type': 'composer', 'impor': 8},
 {'name': '강동하', 'type': 'composer', 'impor': 8},
 {'name': '전다운', 'type': 'composer', 'impor': 14},
 {'name': '박근태', 'type': 'composer', 'impor': 8},
 {'name': 'Otha `Vakseen` Davis III', 'type': 'composer', 'impor': 8},
 {'name': 'Tay Jasper', 'type': 'composer', 'impor': 14},
 {'name': '백호 (뉴이스트)', 'type': 'composer', 'impor': 8},
 {'name': 'Chloe', 'type': 'composer', 'impor': 7},
 {'name': '정균', 'type': 'composer', 'impor': 7},
 {'name': '유니스', 'type': 'composer', 'impor': 7},
 {'name': 'kenzie', 'type': 'composer', 'impor': 14},
 {'name': 'Ollounder', 'type': 'composer', 'impor': 7},
 {'name': 'NODAY', 'type': 'composer', 'impor': 7},
 {'name': 'John K', 'type': 'composer', 'impor': 7},
 {'name': '박은우', 'type': 'composer', 'impor': 7},
 {'name': '신혁', 'type': 'composer', 'impor': 7},
 {'name': '박진영', 'type': 'composer', 'impor': 7},
 {'name': '에스나 (eSNa)', 'type': 'composer', 'impor': 7},
 {'name': '이상호', 'type': 'composer', 'impor': 7},
 {'name': '이단옆차기', 'type': 'composer', 'impor': 13},
 {'name': 'Erik Lidbom', 'type': 'composer', 'impor': 13},
 {'name': 'Albi Albertsson', 'type': 'composer', 'impor': 7},
 {'name': 'Ryan S. Jhun', 'type': 'composer', 'impor': 7},
 {'name': '일 (IL)', 'type': 'composer', 'impor': 7},
 {'name': 'Darren Smith', 'type': 'composer', 'impor': 7},
 {'name': 'ESBEE', 'type': 'composer', 'impor': 7},
 {'name': '함길수', 'type': 'composer', 'impor': 7},
 {'name': '이던', 'type': 'composer', 'impor': 7},
 {'name': '주태영', 'type': 'composer', 'impor': 6},
 {'name': 'Ye-Yo!', 'type': 'composer', 'impor': 6},
 {'name': '어벤전승', 'type': 'composer', 'impor': 6},
 {'name': '차쿤 (일렉트로보이즈)', 'type': 'composer', 'impor': 6},
 {'name': 'DAY6 (데이식스)', 'type': 'composer', 'impor': 6},
 {'name': '코스믹 걸 (Cosmic Girl)', 'type': 'composer', 'impor': 6},
 {'name': '마부스 (Maboos)', 'type': 'composer', 'impor': 6},
 {'name': '가면라이더', 'type': 'composer', 'impor': 6},
 {'name': '슈퍼창따이', 'type': 'composer', 'impor': 6},
 {'name': 'Distract', 'type': 'composer', 'impor': 6},
 {'name': '제니', 'type': 'composer', 'impor': 6},
 {'name': '황현 (MonoTree)', 'type': 'composer', 'impor': 6},
 {'name': 'Razer (Strike)', 'type': 'composer', 'impor': 6},
 {'name': 'CHOICE37', 'type': 'composer', 'impor': 6},
 {'name': '피터팬', 'type': 'composer', 'impor': 6},
 {'name': '진영 (GOT7)', 'type': 'composer', 'impor': 6},
 {'name': 'LEEZ', 'type': 'composer', 'impor': 6},
 {'name': '임팩트', 'type': 'composer', 'impor': 6},
 {'name': '박기태', 'type': 'composer', 'impor': 6},
 {'name': '남태현', 'type': 'composer', 'impor': 6},
 {'name': '유겸 (GOT7)', 'type': 'composer', 'impor': 6},
 {'name': '성연', 'type': 'composer', 'impor': 6},
 {'name': 'P.O (블락비)', 'type': 'composer', 'impor': 6},
 {'name': '황세준', 'type': 'composer', 'impor': 6},
 {'name': '코스믹 사운드', 'type': 'composer', 'impor': 6},
 {'name': '방탄소년단', 'type': 'artist', 'impor': 0},
 {'name': '세븐틴', 'type': 'artist', 'impor': 0},
 {'name': '데이식스', 'type': 'artist', 'impor': 0},
 {'name': '아이콘', 'type': 'artist', 'impor': 0},
 {'name': '마마무', 'type': 'artist', 'impor': 0},
 {'name': '비투비', 'type': 'artist', 'impor': 0},
 {'name': '이엑스아이디', 'type': 'artist', 'impor': 0},
 {'name': '빅스', 'type': 'artist', 'impor': 0},
 {'name': '스트레이 키즈', 'type': 'artist', 'impor': 0},
 {'name': '위너', 'type': 'artist', 'impor': 0},
 {'name': '크나큰', 'type': 'artist', 'impor': 0},
 {'name': '스누퍼', 'type': 'artist', 'impor': 0},
 {'name': '에스에프나인', 'type': 'artist', 'impor': 0},
 {'name': '비에이피', 'type': 'artist', 'impor': 0},
 {'name': '여자친구', 'type': 'artist', 'impor': 0},
 {'name': '러블리즈', 'type': 'artist', 'impor': 0},
 {'name': '에이오에이', 'type': 'artist', 'impor': 0},
 {'name': '아스트로', 'type': 'artist', 'impor': 0},
 {'name': '갓세븐', 'type': 'artist', 'impor': 0},
 {'name': '오마이걸', 'type': 'artist', 'impor': 0},
 {'name': '비비드', 'type': 'artist', 'impor': 0},
 {'name': '엑소', 'type': 'artist', 'impor': 0},
 {'name': '헤일로', 'type': 'artist', 'impor': 0},
 {'name': '투포케이', 'type': 'artist', 'impor': 0},
 {'name': '카드', 'type': 'artist', 'impor': 0},
 {'name': '빅스타', 'type': 'artist', 'impor': 0},
 {'name': '다이아', 'type': 'artist', 'impor': 0},
 {'name': '뉴이스트 W', 'type': 'artist', 'impor': 0},
 {'name': '씨엘씨', 'type': 'artist', 'impor': 0},
 {'name': '펜타곤', 'type': 'artist', 'impor': 0},
 {'name': '소나무', 'type': 'artist', 'impor': 0},
 {'name': '엔플라잉', 'type': 'artist', 'impor': 0},
 {'name': '몬스타엑스', 'type': 'artist', 'impor': 0},
 {'name': '백퍼센트', 'type': 'artist', 'impor': 0},
 {'name': '블랙핑크', 'type': 'artist', 'impor': 0},
 {'name': '히스토리', 'type': 'artist', 'impor': 0},
 {'name': '하이라이트', 'type': 'artist', 'impor': 0},
 {'name': '레드벨벳', 'type': 'artist', 'impor': 0},
 {'name': '씨클라운', 'type': 'artist', 'impor': 0},
 {'name': '소년공화국', 'type': 'artist', 'impor': 0},
 {'name': '빅플로', 'type': 'artist', 'impor': 0},
 {'name': '뉴이스트', 'type': 'artist', 'impor': 0},
 {'name': '드림캐쳐', 'type': 'artist', 'impor': 0},
 {'name': '비비드걸', 'type': 'artist', 'impor': 0},
 {'name': '업텐션', 'type': 'artist', 'impor': 0},
 {'name': '제이제이씨씨', 'type': 'artist', 'impor': 0},
 {'name': '브이에이브이', 'type': 'artist', 'impor': 0},
 {'name': '베리굿', 'type': 'artist', 'impor': 0},
 {'name': '라붐', 'type': 'artist', 'impor': 0},
 {'name': '스피드', 'type': 'artist', 'impor': 0},
 {'name': '리얼걸프로젝트', 'type': 'artist', 'impor': 0},
 {'name': '비아이지', 'type': 'artist', 'impor': 0},
 {'name': '레이디스 코드', 'type': 'artist', 'impor': 0},
 {'name': '티알씨엔지', 'type': 'artist', 'impor': 0},
 {'name': '온앤오프', 'type': 'artist', 'impor': 0},
 {'name': '임팩트', 'type': 'artist', 'impor': 0},
 {'name': '프리스틴', 'type': 'artist', 'impor': 0},
 {'name': '블락비 바스타즈', 'type': 'artist', 'impor': 0},
 {'name': '엔시티 일이칠', 'type': 'artist', 'impor': 0}]

In [187]:
json_prep = {"links":links_list, "nodes":nodes_list}

json_prep.keys()

dict_keys(['links', 'nodes'])

In [188]:
json_dump = json.dumps(json_prep, indent=1, sort_keys=True, ensure_ascii=False)

In [189]:
pd.DataFrame(json_prep['nodes'])

     impor                name      type
0       85                  RM  composer
1       72                SUGA  composer
2       71               Pdogg  composer
3       66              j-hope  composer
4       47   WOOZI (SEVENTEEN)  composer
5       41                 방시혁  composer
6       54               BUMZU  composer
7       36             Young K  composer
8       33         Slow Rabbit  composer
9       33                  원필  composer
10      29                 홍지상  composer
11      29                 B.I  composer
12      26         Supreme Boi  composer
13      25                  성진  composer
14      25                 Jae  composer
15      24           김도훈 (RBW)  composer
16      23  이우민 `collapsedone`  composer
17      30        서재우 (TENTEN)  composer
18      22           LE (EXID)  composer
19      22             신사동 호랭이  composer
20      21                 박우상  composer
21      20          MELODESIGN  composer
22      19          한 (3RACHA)  composer
23      19         방찬 (3RACHA)  composer
24      18                 임현식  composer
25      18                 강승윤  composer
26      18                 김태주  composer
27      17                 정일훈  composer
28      27            SWEETUNE  composer
29      17         창빈 (3RACHA)  composer
..     ...                 ...       ...
157      0                 펜타곤    artist
158      0                 소나무    artist
159      0                엔플라잉    artist
160      0               몬스타엑스    artist
161      0                백퍼센트    artist
162      0                블랙핑크    artist
163      0                히스토리    artist
164      0               하이라이트    artist
165      0                레드벨벳    artist
166      0                씨클라운    artist
167      0               소년공화국    artist
168      0                 빅플로    artist
169      0                뉴이스트    artist
170      0                드림캐쳐    artist
171      0                비비드걸    artist
172      0                 업텐션    artist
173      0              제이제이씨씨    artist
174      0              브이에이브이    artist
175      0                 베리굿    artist
176      0                  라붐    artist
177      0                 스피드    artist
178      0             리얼걸프로젝트    artist
179      0                비아이지    artist
180      0             레이디스 코드    artist
181      0               티알씨엔지    artist
182      0                온앤오프    artist
183      0                 임팩트    artist
184      0                프리스틴    artist
185      0            블락비 바스타즈    artist
186      0             엔시티 일이칠    artist

[187 rows x 3 columns]

In [190]:
pd.DataFrame(json_prep['links'])

     source  target  value
0         0     128     85
1         1     128     72
2         2     128     71
3         3     128     66
4         4     129     47
5         5     128     41
6         6     129     36
7         7     130     36
8         8     128     33
9         9     130     33
10       10     130     29
11       11     131     29
12       12     128     26
13       13     130     25
14       14     130     25
15       15     132     24
16       16     130     23
17       17     133     23
18       18     134     22
19       19     134     22
20       20     132     21
21       21     135     20
22       22     136     19
23       23     136     19
24       24     133     18
25       25     137     18
26       26     138     18
27       27     133     17
28       28     139     17
29       29     136     17
..      ...     ...    ...
124      94     177      6
125     107     130      6
126     108     132      6
127     109     153      6
128     110     178      6
129      50     179      6
130     111     180      6
131     112     146      6
132     113     154      6
133      34     181      6
134     114     182      6
135     115     143      6
136     116     131      6
137      67     133      6
138     117     154      6
139     118     146      6
140      95     140      6
141     119     170      6
142     120     120      6
143     121     129      6
144     122     137      6
145      77     150      6
146      59     140      6
147     123     146      6
148      45     163      6
149     124     183      6
150     125     184      6
151     126     135      6
152      80     185      6
153     127     132      6

[154 rows x 3 columns]

In [191]:
filename_out = 'composer_gen3.json'
json_out = open(filename_out,'w')
json_out.write(json_dump)
json_out.close()