## 작사/작곡가 -> 아이돌그룹 네트워크 시각화

In [312]:
import pandas as pd
import json
import re
import warnings
warnings.filterwarnings('ignore')

idol = pd.read_csv('C:/Users/Kavin/Projects/study/idol_generation_1_kavin_ver01.csv', encoding='euc-kr')

In [313]:
idol[idol['lyricist'].isnull()]

,Unnamed: 0,title,artist,gender,lyricist,composer,arranger,debut_year,generation
57,78,사랑이전부였던날,god,남,NaN,권태은,권태은,1999,1
70,91,사랑이너무아프던날,god,남,NaN,권태은,권태은,1999,1
87,108,5+4+1+5=15,god,남,NaN,"박진영, 방시혁, Elliot Lurie, Tupac Shakur, 조커",조커,1999,1
201,1060,byebye,러브,여,NaN,S-One,S-One,2002,1
206,1065,allright,러브,여,NaN,권기명,권기명,2002,1
283,1919,가슴이운다,버즈,남,NaN,윤우현,윤우현,2003,1
324,1998,theone,베이비 복스 리브,여,NaN,NaN,김신일,1997,1
398,3104,미녀사총사,샤크라,여,NaN,김성태,"김성태, 이상민",2000,1
447,3472,babyboy-혜승솔로,슈가,여,NaN,"박성수, 김진수",김진수,2001,1
467,3739,funnyhowlove,스위티,여,NaN,리로이 브라운,NaN,2002,1
549,3956,세월의흔적다버리고,신화,남,NaN,"M.A.R.S., 지수",M.A.R.S.,1998,1
583,3990,lasttrainhome,신화,남,NaN,임형빈,임형빈,1998,1
670,4452,변심,악동 클럽 (디 에이디),남,NaN,김형석,NaN,2002,1
679,4461,theonlyone,악동 클럽 (디 에이디),남,NaN,NaN,김지웅,2002,1
684,4466,찻잔,악동 클럽 (디 에이디),남,NaN,NaN,안정훈,2002,1
877,4911,아이야!(iyah!)-80인조오케스트라,에이치오티,남,NaN,"유영진, Groovie. K",유영진,1996,1
981,5478,별이빛나는밤에(hitsong),엔알지,남,NaN,NaN,이현우,1997,1
1077,5980,fallinginlove,원타임,남,NaN,페리,페리,1998,1
1085,5988,goodlove,원타임,남,NaN,페리,페리,1998,1
1099,6002,hip-hopkids,원타임,남,NaN,테디,테디,1998,1
1108,6011,cry,원타임,남,NaN,NaN,테디,1998,1
1114,6017,ok,원타임,남,NaN,"테디, 페리",테디,1998,1
1210,6564,walkingintherain,젝스키스,남,NaN,NaN,윤일상,1997,1
1527,7892,intro,티앤비,남,NaN,JAY-Z,NaN,1997,1
1552,8040,선물,파이브,남,NaN,기호,양준영,2002,1
1554,8042,crazyforyou,파이브,남,NaN,Sypher Muzik,Sypher Muzik,2002,1
1564,8052,한마디,파이브,남,NaN,NaN,김도훈 (RBW),2002,1
1628,8265,"snowbaby(feat.동완,전진)",플라이 투 더 스카이,남,NaN,NaN,서융근,1999,1

In [314]:
# # NaN값 제거
# idol =  idol.dropna()
# idol = idol.reset_index()
# idol.head(11)

In [315]:
idol.isna().sum()

Unnamed: 0      0
title           0
artist          0
gender          0
lyricist       28
composer       20
arranger      233
debut_year      0
generation      0
dtype: int64

In [316]:
idol_ly = idol.dropna(subset=['lyricist'])
idol_ly = idol_ly.reset_index()
idol_co = idol.dropna(subset=['composer'])
ido_co = idol_co.reset_index()

In [317]:
idol_ly.isna().sum()

index           0
Unnamed: 0      0
title           0
artist          0
gender          0
lyricist        0
composer       12
arranger      230
debut_year      0
generation      0
dtype: int64

In [318]:
idol_co.isna().sum()

Unnamed: 0      0
title           0
artist          0
gender          0
lyricist       20
composer        0
arranger      226
debut_year      0
generation      0
dtype: int64

In [319]:
idol_ly.loc[idol_ly['artist'] == "방탄소년단"]

# 추가로 원하는 열만 볼 수도 있다
# idol.loc[idol['artist'] == "엠블랙", ['artist','title']]

Empty DataFrame
Columns: [index, Unnamed: 0, title, artist, gender, lyricist, composer, arranger, debut_year, generation]
Index: []

## (1) 데이터 전처리 - 작사가 칼럼 전부 분리하기

In [320]:
idol_ly.loc[idol_ly['lyricist'] == "na"]

Empty DataFrame
Columns: [index, Unnamed: 0, title, artist, gender, lyricist, composer, arranger, debut_year, generation]
Index: []

In [321]:
idol1 = idol_ly[["artist","lyricist"]]

In [322]:
idol1.isna().sum()

artist      0
lyricist    0
dtype: int64

In [323]:
idol1.loc[57]

artist           god
lyricist    박진영, 김광진
Name: 57, dtype: object

In [324]:
def preprocess(text1, text2):
    splitArr = list(re.split(', ', text1))
    artist_name = list(text2)

    lyricist = []
    artist = []
    
    lyricist.clear()
    artist.clear()

    i = 0
    for i in range(0, len(splitArr)):
        lyricist.append(splitArr[i].strip())
        artist.append(text2)
        i = i + 1
    result = [lyricist, artist]
    return result

In [325]:
preprocess(idol1.lyricist[57],idol1.artist[57])[0]

['박진영', '김광진']

In [326]:
len(preprocess(idol1.lyricist[400], idol1.artist[400])[0])

1

In [327]:
preprocess(idol1.lyricist[401], idol1.artist[401])[0]

['이택승']

In [328]:
# song 데이터프레임 전처리함수 이용하여 전처리 후 dataframe 추가로 만들기
i = 0
a = 0
b = 0
lyricist = []
artist = []

lyricist.clear()
artist.clear()
    
for i in range(0, len(idol1)):
#     try:
    for a in range(0, len(preprocess(idol1.lyricist[i], idol1.artist[i])[0])):
        lyricist.append(str(preprocess(idol1.lyricist[i], idol1.artist[i])[0][a]))
    for b in range(0, len(preprocess(idol1.lyricist[i], idol1.artist[i])[1])):
        artist.append(str(preprocess(idol1.lyricist[i], idol1.artist[i])[1][b]))
#     except:
#         lyricist.append('')
#         artist.append('')
    
preprocessing_result = pd.DataFrame({"lyricist" : lyricist, "artist" : artist})

In [329]:
preprocessing_result.head()

  lyricist artist
0      박진영    god
1      박진영    god
2      박진영    god
3      박진영    god
4      박진영    god

In [330]:
preprocessing_result.loc[preprocessing_result['lyricist'] == "TEDDY"]

     lyricist artist
1224    TEDDY    원타임
1228    TEDDY    원타임
1229    TEDDY    원타임
1249    TEDDY    원타임
1250    TEDDY    원타임
1251    TEDDY    원타임
1252    TEDDY    원타임
1253    TEDDY    원타임
1254    TEDDY    원타임
1256    TEDDY    원타임
1261    TEDDY    원타임

In [331]:
preprocessing_result['lyricist'] = preprocessing_result['lyricist'].replace('TEDDY', '테디')

In [332]:
preprocessing_result.loc[preprocessing_result['lyricist'] == "TEDDY"]

Empty DataFrame
Columns: [lyricist, artist]
Index: []

In [333]:
preprocessing_result.sample(10)

     lyricist       artist
565       김동완           신화
1402      김영아         젝스키스
1311   물만난물고기         제이워크
677       김이나           신화
1885      조규찬  플라이 투 더 스카이
1112      천명훈          엔알지
966       유영진        에이치오티
752       주영훈          아이돌
1947      배정은           핑클
1878      최갑원  플라이 투 더 스카이

In [334]:
preprocessing_result.loc[preprocessing_result['lyricist'] == "-"]

Empty DataFrame
Columns: [lyricist, artist]
Index: []

In [335]:
# 위의 행 삭제 - 위의 행번호로 괄호 안 숫자 바꿔줘야함
#  preprocessing_result.drop(preprocessing_result.index[[8241]], inplace=True)

In [336]:
# preprocessing_result.loc[preprocessing_result['lyricist'] == "-"]

In [337]:
preprocessing_result.head()

  lyricist artist
0      박진영    god
1      박진영    god
2      박진영    god
3      박진영    god
4      박진영    god

In [338]:
# null값이 없음을 알 수 있습니다
preprocessing_result.isnull().sum()

lyricist    0
artist      0
dtype: int64

In [339]:
# NaN값도 없음을 알 수 있습니다
preprocessing_result.isna().sum()

lyricist    0
artist      0
dtype: int64

## (2) 데이터 전처리 - 작곡가 칼럼 전부 분리하기

In [340]:
idol_co.loc[idol_co['composer'] == "na"]

Empty DataFrame
Columns: [Unnamed: 0, title, artist, gender, lyricist, composer, arranger, debut_year, generation]
Index: []

In [341]:
idol2 = idol_co[["artist","composer"]]

In [342]:
# song 데이터프레임 전처리함수 이용하여 전처리 후 dataframe 추가로 만들기
i = 0
a = 0
b = 0
composer = []
artist = []

composer.clear()
artist.clear()
    
for i in range(0, len(idol2)):
    try:
        for a in range(0, len(preprocess(idol2.composer[i], idol2.artist[i])[0])):
            composer.append(str(preprocess(idol2.composer[i], idol2.artist[i])[0][a]))
        for b in range(0, len(preprocess(idol2.composer[i], idol2.artist[i])[1])):
            artist.append(str(preprocess(idol2.composer[i], idol2.artist[i])[1][b]))
    except:
        composer.append('')
        artist.append('')
    
preprocessing_result2 = pd.DataFrame({"composer" : composer, "artist" : artist})

In [343]:
preprocessing_result2.head()

  composer artist
0       이준    god
1      박진영    god
2      박진영    god
3      김형석    god
4      박진영    god

In [344]:
preprocessing_result2.loc[preprocessing_result2['composer'] == "TEDDY"]

     composer artist
1280    TEDDY    원타임
1284    TEDDY    원타임
1285    TEDDY    원타임
1310    TEDDY    원타임
1311    TEDDY    원타임
1312    TEDDY    원타임
1313    TEDDY    원타임
1314    TEDDY    원타임
1315    TEDDY    원타임
1318    TEDDY    원타임
1323    TEDDY    원타임
1324    TEDDY    원타임

In [345]:
preprocessing_result2['composer'] = preprocessing_result2['composer'].replace('TEDDY', '테디')

In [346]:
preprocessing_result2.loc[preprocessing_result2['composer'] == "TEDDY"]

Empty DataFrame
Columns: [composer, artist]
Index: []

In [347]:
preprocessing_result2.loc[preprocessing_result2['composer'] == "-"]

Empty DataFrame
Columns: [composer, artist]
Index: []

In [348]:
preprocessing_result2.isnull().sum()

composer    0
artist      0
dtype: int64

In [349]:
preprocessing_result2.isna().sum()

composer    0
artist      0
dtype: int64

In [350]:
preprocessing_result2.head(10)

  composer artist
0       이준    god
1      박진영    god
2      박진영    god
3      김형석    god
4      박진영    god
5      방시혁    god
6      안용진    god
7      god    god
8      이철원    god
9      박진영    god

## (3) 작사가(lyricist) json 파일 생성하기

#### 작사가로 json 데이터프레임 만들기

In [351]:
preprocessing_result.rename(columns={"lyricist":"source","artist":"target"}, inplace=True)

In [352]:
grouped_idol = preprocessing_result.groupby(["source","target"]).size().reset_index()
grouped_idol.head() # 갑자기 빈 행이 존재함 ->삭제

    source target  0
0    1월 8일     신화  2
1     3534    엔알지  2
2     3534    태사자  1
3  A.minor   제이워크  1
4       A4    에이포  1

In [353]:
grouped_idol.drop(grouped_idol.index[[0]], inplace=True)

In [354]:
grouped_idol = grouped_idol.reset_index()

In [355]:
grouped_idol = grouped_idol.drop(['index'], axis = 1)

In [356]:
grouped_idol.head()

    source target  0
0     3534    엔알지  2
1     3534    태사자  1
2  A.minor   제이워크  1
3       A4    에이포  1
4      BYP    쥬얼리  1

In [357]:
unique_idol = pd.Index(grouped_idol['source']
                      .append(grouped_idol['target'])
                      .reset_index(drop=True).unique())

In [358]:
grouped_idol.rename(columns={0:'count'}, inplace=True)
len(grouped_idol)

872

In [359]:
grouped_idol_ranking = grouped_idol.sort_values(by='count', ascending=False)
grouped_idol_ranking = grouped_idol_ranking.reset_index(drop=True)

#### 작사가 전체랭킹 저장

In [360]:
grouped_idol_ranking.to_csv('작사가_전체랭킹.csv', encoding='euc-kr')

#### 작사가 json 파일 생성(세대별)

In [361]:
# 파일 불러오기
lyricist_gen1 = pd.read_csv('idol_generation_1_kavin_ver01.csv', encoding = 'euc-kr')
lyricist_gen2 = pd.read_csv('idol_generation_2_kavin_ver01.csv', encoding = 'utf-8')
lyricist_gen3 = pd.read_csv('idol_generation_3_kavin_ver01.csv', encoding = 'utf-8')

In [362]:
# 맨 앞 Unnamed: 0 칼럼 제거
lyricist_gen1 = lyricist_gen1.drop(['Unnamed: 0'], axis = 1)
lyricist_gen2 = lyricist_gen2.drop(['Unnamed: 0'], axis = 1)
lyricist_gen3 = lyricist_gen3.drop(['Unnamed: 0'], axis = 1)

In [363]:
lyricist_gen1.isna().sum()

title           0
artist          0
gender          0
lyricist       28
composer       20
arranger      233
debut_year      0
generation      0
dtype: int64

In [364]:
lyricist_gen2.isna().sum()

title           0
artist          0
gender          0
lyricist       28
composer       18
arranger      602
debut_year      0
generation      0
dtype: int64

In [365]:
lyricist_gen3.isna().sum()

title           0
artist          0
gender          0
lyricist        9
composer        2
arranger      259
debut_year      0
generation      0
dtype: int64

In [366]:
# NaN값 제거, lyricist에 있는 NA만을 제거
lyricist_gen1 =  lyricist_gen1.dropna(subset=['lyricist'])
lyricist_gen1 = lyricist_gen1.reset_index()
lyricist_gen2 =  lyricist_gen2.dropna(subset=['lyricist'])
lyricist_gen2 = lyricist_gen2.reset_index()
lyricist_gen3 =  lyricist_gen3.dropna(subset=['lyricist'])
lyricist_gen3 = lyricist_gen3.reset_index()

In [367]:
lyricist_gen1.isna().sum()

index           0
title           0
artist          0
gender          0
lyricist        0
composer       12
arranger      230
debut_year      0
generation      0
dtype: int64

In [368]:
lyricist_gen2.isna().sum()

index           0
title           0
artist          0
gender          0
lyricist        0
composer       10
arranger      592
debut_year      0
generation      0
dtype: int64

In [369]:
lyricist_gen3.isna().sum()

index           0
title           0
artist          0
gender          0
lyricist        0
composer        2
arranger      252
debut_year      0
generation      0
dtype: int64

In [370]:
# 맨 앞 Unnamed: 0 칼럼 제거
lyricist_gen1 = lyricist_gen1.drop(['index'], axis = 1)
lyricist_gen2 = lyricist_gen2.drop(['index'], axis = 1)
lyricist_gen3 = lyricist_gen3.drop(['index'], axis = 1)

#### 1) lyricist_gen1 작업

In [371]:
# lyricist_gen1의 가수 목록 데이터프레임 생성
i = 0
a = 0
b = 0
lyricist = []
artist = []

lyricist.clear()
artist.clear()
    
for i in range(0, len(lyricist_gen1)):
    try:
        for a in range(0, len(preprocess(lyricist_gen1.lyricist[i], lyricist_gen1.artist[i])[0])):
            lyricist.append(str(preprocess(lyricist_gen1.lyricist[i], lyricist_gen1.artist[i])[0][a]))
        for b in range(0, len(preprocess(lyricist_gen1.lyricist[i], lyricist_gen1.artist[i])[1])):
            artist.append(str(preprocess(lyricist_gen1.lyricist[i], lyricist_gen1.artist[i])[1][b]))
    except:
        lyricist.append('')
        artist.append('')
    
preprocessing_gen1 = pd.DataFrame({"lyricist" : lyricist, "artist" : artist, "generation" : 1})

In [372]:
preprocessing_gen1.head()

  lyricist artist  generation
0      박진영    god           1
1      박진영    god           1
2      박진영    god           1
3      박진영    god           1
4      박진영    god           1

In [373]:
preprocessing_gen1.rename(columns={"lyricist":"source","artist":"target"}, inplace=True)

In [374]:
grouped_idol_gen1 = preprocessing_gen1.groupby(["source","target"]).size().reset_index()
grouped_idol_gen1.head(20) # 갑자기 빈 행이 존재함 ->삭제

            source       target   0
0            1월 8일           신화   2
1             3534          엔알지   2
2             3534          태사자   1
3          A.minor         제이워크   1
4               A4          에이포   1
5              BYP          쥬얼리   1
6         Boy Club        보이 클럽   2
7        Brian Joo  플라이 투 더 스카이   3
8        Brian Kim           신화  11
9   Brian McKnight  플라이 투 더 스카이   1
10      Browncloud           신화   1
11  CARLSON SANNIE          쥬얼리   1
12    COLEGATE ROY         제이티엘   1
13            Crom         문차일드   4
14          Curbin          에이포   1
15           Cyren          태사자   1
16       D.PICKELL           신화   1
17    DAVINK (다빈크)         문차일드   2
18    DAVINK (다빈크)         제이워크   1
19         DJ Tama          쥬얼리   1

In [375]:
grouped_idol_gen1.loc[grouped_idol_gen1['source'] == "TEDDY"]

   source target   0
75  TEDDY    원타임  11

In [376]:
grouped_idol_gen1['source'] = grouped_idol_gen1['source'].replace('TEDDY', '테디')

In [377]:
grouped_idol_gen1.loc[grouped_idol_gen1['source'] == "TEDDY"]

Empty DataFrame
Columns: [source, target, 0]
Index: []

In [378]:
# 칼럼 0 -> count로 이름 칼럼명 수정
grouped_idol_gen1.rename(columns={0:'count'}, inplace=True)
len(grouped_idol_gen1)

874

In [379]:
grouped_idol_gen1_ranking = grouped_idol_gen1.sort_values(by='count', ascending=False)
grouped_idol_gen1_ranking = grouped_idol_gen1_ranking.reset_index(drop=True)
grouped_idol_gen1_ranking.head()

    source target  count
0      박진영    god     68
1      유건형   언타이틀     40
2  M (이민우)     신화     26
3      김영아   젝스키스     24
4      이상민    샤크라     23

In [380]:
grouped_idol_gen1_ranking.loc[grouped_idol_gen1_ranking['target'] == "에이치오티", ['source','count']]

          source  count
7            유영진     19
10   강타 (KANGTA)     16
15           문희준     14
37          토니 안      9
51           장용진      6
67           장우혁      5
99           이재원      4
147          곽상엽      3
152     Jay Kang      3
512          홍성민      1
563      Jay Kim      1
820          김수지      1

In [381]:
len(grouped_idol_gen1_ranking)

874

In [382]:
# unique한 source
generate_node_gen1 = grouped_idol_gen1_ranking.groupby(['source', 'count']).size().reset_index()
# generate_node.rename(columns={0:'count'}, inplace=True)
generate_node_gen1 = generate_node_gen1.sort_values(by='count', ascending=False)
generate_node_gen1 = generate_node_gen1.reset_index(drop=True)
generate_node_gen1 = generate_node_gen1.drop([0], axis = 1)
len(generate_node_gen1)

731

In [383]:
# unique해지려면 총 478이어야함
generate_node2_gen1 = generate_node_gen1.groupby(['source']).sum()
generate_node2_gen1 = generate_node2_gen1.sort_values(by='count', ascending=False)
len(generate_node2_gen1) == len(generate_node_gen1.source.unique()) == len(grouped_idol_gen1_ranking['source'].unique())

True

In [384]:
# 리스트의 전체원소를 보고싶을때
# print(*lyricist_gen1_unique, sep='\n')

In [385]:
grouped_idol2_gen1 = grouped_idol_gen1_ranking[grouped_idol_gen1_ranking['count'] > 2]
generate_node_gen1 = generate_node2_gen1[generate_node2_gen1['count']>2]

In [386]:
grouped_idol2_gen1 = grouped_idol2_gen1.reset_index()
generate_node_gen1 = generate_node_gen1.reset_index()

In [387]:
grouped_idol2_gen1 = grouped_idol2_gen1.drop(['index'], axis = 1)

In [388]:
##추후삭제
grouped_idol2_gen1.loc[grouped_idol2_gen1['target'] == "에이치오티", ['source','count']]

          source  count
7            유영진     19
10   강타 (KANGTA)     16
15           문희준     14
37          토니 안      9
51           장용진      6
67           장우혁      5
99           이재원      4
147          곽상엽      3
152     Jay Kang      3

In [389]:
generate_node2_gen1.head(10)

             count
source
김영아             69
박진영             69
유영진             54
이승호             43
유건형             40
M (이민우)         28
강타 (KANGTA)     28
이상민             28
장대성             26
테디              25

In [390]:
unique_idol_gen1_all = pd.Index(grouped_idol2_gen1['source']
                      .append(grouped_idol2_gen1['target'])
                      .reset_index(drop=True).unique())
unique_idol_gen1_lyricist = pd.Index(grouped_idol2_gen1['source']
                      .reset_index(drop=True).unique())
unique_idol_gen1_artist = pd.Index(grouped_idol2_gen1['target']
                      .reset_index(drop=True).unique())

In [391]:
len(unique_idol_gen1_lyricist)

123

In [392]:
# grouped_idol2_gen1 = grouped_idol2_gen1.drop(['level_0'], axis = 1)
# grouped_idol2_gen1.head()

In [393]:
group_dict_gen1_lyricist = {}
group_dict_gen1_lyricist.clear()
counter = 0
for idol in unique_idol_gen1_lyricist:
    if idol not in group_dict_gen1_lyricist:
        counter += 1
        group_dict_gen1_lyricist[idol] = counter
    else:
        pass
group_dict_gen1_lyricist

{'박진영': 1,
 '유건형': 2,
 'M (이민우)': 3,
 '김영아': 4,
 '이상민': 5,
 '이승호': 6,
 '천명훈': 7,
 '유영진': 8,
 '송백경': 9,
 '강타 (KANGTA)': 10,
 '서정환': 11,
 '박성호 (구피)': 12,
 '테디': 13,
 '에릭': 14,
 '문희준': 15,
 '신동욱': 16,
 '바다': 17,
 '제드': 18,
 '장대성': 19,
 'Rain': 20,
 '신승희': 21,
 '장우혁': 22,
 'Brian Kim': 23,
 '이재원': 24,
 '버즈': 25,
 '이도연': 26,
 '서융근': 27,
 '조은희': 28,
 'Do': 29,
 '이현도': 30,
 '토니 안': 31,
 'god': 32,
 '안성일': 33,
 '김수정': 34,
 '신혜성': 35,
 '임선아': 36,
 '렌': 37,
 '정진환': 38,
 '김진아': 39,
 '이단옆차기': 40,
 '안영민': 41,
 '장용진': 42,
 '장성재': 43,
 '지국현': 44,
 '조규만': 45,
 '이현우': 46,
 '김이나': 47,
 '양재선': 48,
 '김우진': 49,
 '이재경': 50,
 '오종혁': 51,
 '이희승': 52,
 '김광휘': 53,
 '이용민': 54,
 '강은경': 55,
 '정진수': 56,
 'LIØN': 57,
 '김종숙': 58,
 '데니안': 59,
 '김태희': 60,
 '노유민': 61,
 '최태규': 62,
 '최명섭': 63,
 '최갑원': 64,
 '한경혜': 65,
 '김재덕': 66,
 '노민혁': 67,
 '남기상': 68,
 '유진': 69,
 '홍지유': 70,
 '이희성': 71,
 '최희진': 72,
 '민경훈': 73,
 '조준영': 74,
 'David Kim': 75,
 '옥주현': 76,
 '김민지': 77,
 '황성진': 78,
 '허인창': 79,
 '전승우': 80,
 '주찬양 (티맥스)': 81,
 '디스코 파이터': 82,
 '박창현': 83,
 'Unknown': 84,
 '이상인': 85,
 '박선주 (Pak Sun Zoo)': 86,
 'Tablo': 87,
 'Crom': 88,
 '김태윤': 89,
 '김달우피터': 90,
 '유유진': 91,
 '윤우현': 92,
 '김동완': 93,
 '서정진': 94,
 '김동현': 95,
 '신준기': 96,
 '김유라': 97,
 '김유민': 98,
 '김이지': 99,
 '방시혁': 100,
 '박채원': 101,
 '써니사이드 챙': 102,
 '박기영': 103,
 '김창환': 104,
 '양현석': 105,
 '오지훈': 106,
 '우연석': 107,
 '문스톤': 108,
 '이상호': 109,
 '김희선': 110,
 '곽상엽': 111,
 '이효리': 112,
 '주영훈': 113,
 'Jay Kang': 114,
 '강성훈': 115,
 'Urban Cllasik': 116,
 '이제이': 117,
 '강우경': 118,
 '강욱진': 119,
 '한재호': 120,
 '환희': 121,
 'Brian Joo': 122,
 '정성헌': 123}

In [394]:
group_dict_gen1_artist = {}
group_dict_gen1_artist.clear()
counter = 123
for idol in unique_idol_gen1_artist:
    if idol not in group_dict_gen1_artist:
        counter += 1
        group_dict_gen1_artist[idol] = counter
    else:
        pass
group_dict_gen1_artist

{'god': 124,
 '언타이틀': 125,
 '신화': 126,
 '젝스키스': 127,
 '샤크라': 128,
 '구피': 129,
 '엔알지': 130,
 '에이치오티': 131,
 '핑클': 132,
 '원타임': 133,
 '에스이에스': 134,
 '디베이스': 135,
 '제이워크': 136,
 '테이크': 137,
 '제이티엘': 138,
 '플라이 투 더 스카이': 139,
 '버즈': 140,
 '오션': 141,
 '와이투케이': 142,
 '에스': 143,
 '베이비 복스 리브': 144,
 '클릭비': 145,
 '파파야': 146,
 '문차일드': 147,
 '케이팝': 148,
 '씨유': 149,
 '쥬얼리': 150,
 '에이포': 151,
 '클레오': 152,
 '태사자': 153,
 '보이스립': 154,
 '슈가': 155,
 '악동 클럽 (디 에이디)': 156,
 '써클': 157,
 '티티마': 158,
 '파이브': 159,
 '아이돌': 160,
 '스위티': 161,
 '투야': 162,
 '스맥스': 163}

In [395]:
temp_links_list_gen1 = []
temp_links_list_gen1 = list(grouped_idol2_gen1.apply(lambda row: {"source": row['source'], "target": row['target'], "value": row['count']}, axis=1))

In [396]:
temp_links_list_gen1

[{'source': '박진영', 'target': 'god', 'value': 68},
 {'source': '유건형', 'target': '언타이틀', 'value': 40},
 {'source': 'M (이민우)', 'target': '신화', 'value': 26},
 {'source': '김영아', 'target': '젝스키스', 'value': 24},
 {'source': '이상민', 'target': '샤크라', 'value': 23},
 {'source': '이승호', 'target': '구피', 'value': 22},
 {'source': '천명훈', 'target': '엔알지', 'value': 19},
 {'source': '유영진', 'target': '에이치오티', 'value': 19},
 {'source': '김영아', 'target': '핑클', 'value': 18},
 {'source': '송백경', 'target': '원타임', 'value': 17},
 {'source': '강타 (KANGTA)', 'target': '에이치오티', 'value': 16},
 {'source': '서정환', 'target': '언타이틀', 'value': 16},
 {'source': '박성호 (구피)', 'target': '구피', 'value': 14},
 {'source': '테디', 'target': '원타임', 'value': 14},
 {'source': '에릭', 'target': '신화', 'value': 14},
 {'source': '문희준', 'target': '에이치오티', 'value': 14},
 {'source': '신동욱', 'target': '구피', 'value': 13},
 {'source': '유영진', 'target': '신화', 'value': 13},
 {'source': '바다', 'target': '에스이에스', 'value': 13},
 {'source': '제드', 'target': '디베이스', 'value': 12},
 {'source': '장대성', 'target': '젝스키스', 'value': 12},
 {'source': 'Rain', 'target': '제이워크', 'value': 11},
 {'source': '테디', 'target': '원타임', 'value': 11},
 {'source': '신승희', 'target': '테이크', 'value': 11},
 {'source': '장우혁', 'target': '제이티엘', 'value': 11},
 {'source': 'Brian Kim', 'target': '신화', 'value': 11},
 {'source': '이재원', 'target': '제이티엘', 'value': 11},
 {'source': '유영진', 'target': '에스이에스', 'value': 11},
 {'source': '이승호', 'target': '젝스키스', 'value': 10},
 {'source': '유영진', 'target': '플라이 투 더 스카이', 'value': 10},
 {'source': '버즈', 'target': '버즈', 'value': 10},
 {'source': '이도연', 'target': '버즈', 'value': 9},
 {'source': '서융근', 'target': '플라이 투 더 스카이', 'value': 9},
 {'source': '조은희', 'target': '플라이 투 더 스카이', 'value': 9},
 {'source': '김영아', 'target': '오션', 'value': 9},
 {'source': 'Do', 'target': '디베이스', 'value': 9},
 {'source': '이현도', 'target': '디베이스', 'value': 9},
 {'source': '토니 안', 'target': '에이치오티', 'value': 9},
 {'source': 'god', 'target': 'god', 'value': 9},
 {'source': '안성일', 'target': '제이워크', 'value': 9},
 {'source': '장대성', 'target': '와이투케이', 'value': 9},
 {'source': '김수정', 'target': '오션', 'value': 8},
 {'source': '신혜성', 'target': '신화', 'value': 8},
 {'source': '임선아', 'target': '버즈', 'value': 8},
 {'source': '김영아', 'target': '엔알지', 'value': 8},
 {'source': '렌', 'target': '오션', 'value': 8},
 {'source': '정진환', 'target': '오션', 'value': 7},
 {'source': '조은희', 'target': '구피', 'value': 7},
 {'source': '김진아', 'target': '버즈', 'value': 7},
 {'source': '이단옆차기', 'target': 'god', 'value': 7},
 {'source': '안영민', 'target': '신화', 'value': 7},
 {'source': '장용진', 'target': '에이치오티', 'value': 6},
 {'source': '장성재', 'target': '테이크', 'value': 6},
 {'source': '지국현', 'target': '신화', 'value': 6},
 {'source': '조규만', 'target': '플라이 투 더 스카이', 'value': 6},
 {'source': '강타 (KANGTA)', 'target': '에스', 'value': 6},
 {'source': '이현우', 'target': '엔알지', 'value': 6},
 {'source': '김이나', 'target': '신화', 'value': 6},
 {'source': '양재선', 'target': '베이비 복스 리브', 'value': 6},
 {'source': '김우진', 'target': '베이비 복스 리브', 'value': 5},
 {'source': '이재경', 'target': '핑클', 'value': 5},
 {'source': '이승호', 'target': '핑클', 'value': 5},
 {'source': '오종혁', 'target': '클릭비', 'value': 5},
 {'source': '이희승', 'target': '클릭비', 'value': 5},
 {'source': '김광휘', 'target': '젝스키스', 'value': 5},
 {'source': '이용민', 'target': '파파야', 'value': 5},
 {'source': '강은경', 'target': '문차일드', 'value': 5},
 {'source': '장우혁', 'target': '에이치오티', 'value': 5},
 {'source': '정진수', 'target': '케이팝', 'value': 5},
 {'source': 'LIØN', 'target': '젝스키스', 'value': 5},
 {'source': '김종숙', 'target': '씨유', 'value': 5},
 {'source': '데니안', 'target': 'god', 'value': 5},
 {'source': '토니 안', 'target': '제이티엘', 'value': 5},
 {'source': '김태희', 'target': '케이팝', 'value': 5},
 {'source': '노유민', 'target': '엔알지', 'value': 5},
 {'source': '최태규', 'target': '테이크', 'value': 5},
 {'source': '최명섭', 'target': '젝스키스', 'value': 5},
 {'source': '최갑원', 'target': '플라이 투 더 스카이', 'value': 5},
 {'source': '최갑원', 'target': '버즈', 'value': 5},
 {'source': '지국현', 'target': '플라이 투 더 스카이', 'value': 5},
 {'source': '한경혜', 'target': '베이비 복스 리브', 'value': 5},
 {'source': '김재덕', 'target': '제이워크', 'value': 5},
 {'source': '노민혁', 'target': '클릭비', 'value': 5},
 {'source': '남기상', 'target': '쥬얼리', 'value': 5},
 {'source': '유진', 'target': '에스이에스', 'value': 4},
 {'source': '조은희', 'target': '베이비 복스 리브', 'value': 4},
 {'source': '홍지유', 'target': '플라이 투 더 스카이', 'value': 4},
 {'source': '이희성', 'target': '에이포', 'value': 4},
 {'source': '최희진', 'target': '파파야', 'value': 4},
 {'source': '민경훈', 'target': '버즈', 'value': 4},
 {'source': '조준영', 'target': '플라이 투 더 스카이', 'value': 4},
 {'source': '강타 (KANGTA)', 'target': '플라이 투 더 스카이', 'value': 4},
 {'source': '이상민', 'target': '클레오', 'value': 4},
 {'source': 'David Kim', 'target': '신화', 'value': 4},
 {'source': '홍지유', 'target': '태사자', 'value': 4},
 {'source': '옥주현', 'target': '핑클', 'value': 4},
 {'source': '김민지', 'target': '버즈', 'value': 4},
 {'source': '황성진', 'target': '제이워크', 'value': 4},
 {'source': '허인창', 'target': '에이포', 'value': 4},
 {'source': '이재원', 'target': '에이치오티', 'value': 4},
 {'source': '전승우', 'target': '플라이 투 더 스카이', 'value': 4},
 {'source': '김영아', 'target': '보이스립', 'value': 4},
 {'source': '홍지유', 'target': '슈가', 'value': 4},
 {'source': '김영아', 'target': '클릭비', 'value': 4},
 {'source': '주찬양 (티맥스)', 'target': '신화', 'value': 4},
 {'source': '디스코 파이터', 'target': '쥬얼리', 'value': 4},
 {'source': '박창현', 'target': '플라이 투 더 스카이', 'value': 4},
 {'source': 'Unknown', 'target': '핑클', 'value': 4},
 {'source': '이상인', 'target': '신화', 'value': 4},
 {'source': '박선주 (Pak Sun Zoo)', 'target': '엔알지', 'value': 4},
 {'source': '홍지유', 'target': '악동 클럽 (디 에이디)', 'value': 4},
 {'source': '장대성', 'target': '쥬얼리', 'value': 4},
 {'source': '이용민', 'target': '엔알지', 'value': 4},
 {'source': 'Tablo', 'target': '젝스키스', 'value': 4},
 {'source': '장대성', 'target': '써클', 'value': 4},
 {'source': 'Crom', 'target': '문차일드', 'value': 4},
 {'source': '김태윤', 'target': '베이비 복스 리브', 'value': 4},
 {'source': '김달우피터', 'target': '테이크', 'value': 3},
 {'source': '유유진', 'target': '클릭비', 'value': 3},
 {'source': '김태희', 'target': '핑클', 'value': 3},
 {'source': '유유진', 'target': '티티마', 'value': 3},
 {'source': '유유진', 'target': '핑클', 'value': 3},
 {'source': '윤우현', 'target': '버즈', 'value': 3},
 {'source': '김동완', 'target': '신화', 'value': 3},
 {'source': '서정진', 'target': '제이워크', 'value': 3},
 {'source': '김동현', 'target': '신화', 'value': 3},
 {'source': '신준기', 'target': '버즈', 'value': 3},
 {'source': '김유라', 'target': '에스이에스', 'value': 3},
 {'source': '김유민', 'target': '엔알지', 'value': 3},
 {'source': '김이지', 'target': '베이비 복스 리브', 'value': 3},
 {'source': '방시혁', 'target': '파이브', 'value': 3},
 {'source': '김영아', 'target': '티티마', 'value': 3},
 {'source': '김영아', 'target': '쥬얼리', 'value': 3},
 {'source': '김종숙', 'target': '베이비 복스 리브', 'value': 3},
 {'source': '박채원', 'target': '파이브', 'value': 3},
 {'source': '써니사이드 챙', 'target': '태사자', 'value': 3},
 {'source': '김태희', 'target': '악동 클럽 (디 에이디)', 'value': 3},
 {'source': '박기영', 'target': '아이돌', 'value': 3},
 {'source': '김창환', 'target': '베이비 복스 리브', 'value': 3},
 {'source': '김창환', 'target': '악동 클럽 (디 에이디)', 'value': 3},
 {'source': '김태윤', 'target': '슈가', 'value': 3},
 {'source': '양현석', 'target': '스위티', 'value': 3},
 {'source': '오지훈', 'target': '태사자', 'value': 3},
 {'source': '우연석', 'target': '클릭비', 'value': 3},
 {'source': '문스톤', 'target': '에스이에스', 'value': 3},
 {'source': '이상호', 'target': '와이투케이', 'value': 3},
 {'source': '김희선', 'target': '플라이 투 더 스카이', 'value': 3},
 {'source': '곽상엽', 'target': '에이치오티', 'value': 3},
 {'source': '이상인', 'target': '플라이 투 더 스카이', 'value': 3},
 {'source': '이효리', 'target': '핑클', 'value': 3},
 {'source': '최갑원', 'target': '쥬얼리', 'value': 3},
 {'source': '주영훈', 'target': '슈가', 'value': 3},
 {'source': 'Jay Kang', 'target': '에이치오티', 'value': 3},
 {'source': '강성훈', 'target': '젝스키스', 'value': 3},
 {'source': 'Urban Cllasik', 'target': '쥬얼리', 'value': 3},
 {'source': '이제이', 'target': '투야', 'value': 3},
 {'source': '강우경', 'target': '구피', 'value': 3},
 {'source': '강욱진', 'target': '젝스키스', 'value': 3},
 {'source': '이재경', 'target': '버즈', 'value': 3},
 {'source': 'Unknown', 'target': '문차일드', 'value': 3},
 {'source': '한재호', 'target': '슈가', 'value': 3},
 {'source': '이승호', 'target': '악동 클럽 (디 에이디)', 'value': 3},
 {'source': '주영훈', 'target': '파파야', 'value': 3},
 {'source': '홍지유', 'target': '티티마', 'value': 3},
 {'source': '환희', 'target': '플라이 투 더 스카이', 'value': 3},
 {'source': '홍지유', 'target': '샤크라', 'value': 3},
 {'source': '홍지유', 'target': '신화', 'value': 3},
 {'source': 'Brian Joo', 'target': '플라이 투 더 스카이', 'value': 3},
 {'source': '이상인', 'target': '슈가', 'value': 3},
 {'source': '정성헌', 'target': '스맥스', 'value': 3}]

In [397]:
# 링크 생성하기
links_list_gen1 = []
for link in temp_links_list_gen1:
    record = {"value":link['value'], "source":unique_idol_gen1_all.get_loc(link['source']),
     "target": unique_idol_gen1_all.get_loc(link['target'])}
    links_list_gen1.append(record)
links_list_gen1

[{'value': 68, 'source': 0, 'target': 31},
 {'value': 40, 'source': 1, 'target': 123},
 {'value': 26, 'source': 2, 'target': 124},
 {'value': 24, 'source': 3, 'target': 125},
 {'value': 23, 'source': 4, 'target': 126},
 {'value': 22, 'source': 5, 'target': 127},
 {'value': 19, 'source': 6, 'target': 128},
 {'value': 19, 'source': 7, 'target': 129},
 {'value': 18, 'source': 3, 'target': 130},
 {'value': 17, 'source': 8, 'target': 131},
 {'value': 16, 'source': 9, 'target': 129},
 {'value': 16, 'source': 10, 'target': 123},
 {'value': 14, 'source': 11, 'target': 127},
 {'value': 14, 'source': 12, 'target': 131},
 {'value': 14, 'source': 13, 'target': 124},
 {'value': 14, 'source': 14, 'target': 129},
 {'value': 13, 'source': 15, 'target': 127},
 {'value': 13, 'source': 7, 'target': 124},
 {'value': 13, 'source': 16, 'target': 132},
 {'value': 12, 'source': 17, 'target': 133},
 {'value': 12, 'source': 18, 'target': 125},
 {'value': 11, 'source': 19, 'target': 134},
 {'value': 11, 'source': 12, 'target': 131},
 {'value': 11, 'source': 20, 'target': 135},
 {'value': 11, 'source': 21, 'target': 136},
 {'value': 11, 'source': 22, 'target': 124},
 {'value': 11, 'source': 23, 'target': 136},
 {'value': 11, 'source': 7, 'target': 132},
 {'value': 10, 'source': 5, 'target': 125},
 {'value': 10, 'source': 7, 'target': 137},
 {'value': 10, 'source': 24, 'target': 24},
 {'value': 9, 'source': 25, 'target': 24},
 {'value': 9, 'source': 26, 'target': 137},
 {'value': 9, 'source': 27, 'target': 137},
 {'value': 9, 'source': 3, 'target': 138},
 {'value': 9, 'source': 28, 'target': 133},
 {'value': 9, 'source': 29, 'target': 133},
 {'value': 9, 'source': 30, 'target': 129},
 {'value': 9, 'source': 31, 'target': 31},
 {'value': 9, 'source': 32, 'target': 134},
 {'value': 9, 'source': 18, 'target': 139},
 {'value': 8, 'source': 33, 'target': 138},
 {'value': 8, 'source': 34, 'target': 124},
 {'value': 8, 'source': 35, 'target': 24},
 {'value': 8, 'source': 3, 'target': 128},
 {'value': 8, 'source': 36, 'target': 138},
 {'value': 7, 'source': 37, 'target': 138},
 {'value': 7, 'source': 27, 'target': 127},
 {'value': 7, 'source': 38, 'target': 24},
 {'value': 7, 'source': 39, 'target': 31},
 {'value': 7, 'source': 40, 'target': 124},
 {'value': 6, 'source': 41, 'target': 129},
 {'value': 6, 'source': 42, 'target': 135},
 {'value': 6, 'source': 43, 'target': 124},
 {'value': 6, 'source': 44, 'target': 137},
 {'value': 6, 'source': 9, 'target': 140},
 {'value': 6, 'source': 45, 'target': 128},
 {'value': 6, 'source': 46, 'target': 124},
 {'value': 6, 'source': 47, 'target': 141},
 {'value': 5, 'source': 48, 'target': 141},
 {'value': 5, 'source': 49, 'target': 130},
 {'value': 5, 'source': 5, 'target': 130},
 {'value': 5, 'source': 50, 'target': 142},
 {'value': 5, 'source': 51, 'target': 142},
 {'value': 5, 'source': 52, 'target': 125},
 {'value': 5, 'source': 53, 'target': 143},
 {'value': 5, 'source': 54, 'target': 144},
 {'value': 5, 'source': 21, 'target': 129},
 {'value': 5, 'source': 55, 'target': 145},
 {'value': 5, 'source': 56, 'target': 125},
 {'value': 5, 'source': 57, 'target': 146},
 {'value': 5, 'source': 58, 'target': 31},
 {'value': 5, 'source': 30, 'target': 136},
 {'value': 5, 'source': 59, 'target': 145},
 {'value': 5, 'source': 60, 'target': 128},
 {'value': 5, 'source': 61, 'target': 135},
 {'value': 5, 'source': 62, 'target': 125},
 {'value': 5, 'source': 63, 'target': 137},
 {'value': 5, 'source': 63, 'target': 24},
 {'value': 5, 'source': 43, 'target': 137},
 {'value': 5, 'source': 64, 'target': 141},
 {'value': 5, 'source': 65, 'target': 134},
 {'value': 5, 'source': 66, 'target': 142},
 {'value': 5, 'source': 67, 'target': 147},
 {'value': 4, 'source': 68, 'target': 132},
 {'value': 4, 'source': 27, 'target': 141},
 {'value': 4, 'source': 69, 'target': 137},
 {'value': 4, 'source': 70, 'target': 148},
 {'value': 4, 'source': 71, 'target': 143},
 {'value': 4, 'source': 72, 'target': 24},
 {'value': 4, 'source': 73, 'target': 137},
 {'value': 4, 'source': 9, 'target': 137},
 {'value': 4, 'source': 4, 'target': 149},
 {'value': 4, 'source': 74, 'target': 124},
 {'value': 4, 'source': 69, 'target': 150},
 {'value': 4, 'source': 75, 'target': 130},
 {'value': 4, 'source': 76, 'target': 24},
 {'value': 4, 'source': 77, 'target': 134},
 {'value': 4, 'source': 78, 'target': 148},
 {'value': 4, 'source': 23, 'target': 129},
 {'value': 4, 'source': 79, 'target': 137},
 {'value': 4, 'source': 3, 'target': 151},
 {'value': 4, 'source': 69, 'target': 152},
 {'value': 4, 'source': 3, 'target': 142},
 {'value': 4, 'source': 80, 'target': 124},
 {'value': 4, 'source': 81, 'target': 147},
 {'value': 4, 'source': 82, 'target': 137},
 {'value': 4, 'source': 83, 'target': 130},
 {'value': 4, 'source': 84, 'target': 124},
 {'value': 4, 'source': 85, 'target': 128},
 {'value': 4, 'source': 69, 'target': 153},
 {'value': 4, 'source': 18, 'target': 147},
 {'value': 4, 'source': 53, 'target': 128},
 {'value': 4, 'source': 86, 'target': 125},
 {'value': 4, 'source': 18, 'target': 154},
 {'value': 4, 'source': 87, 'target': 144},
 {'value': 4, 'source': 88, 'target': 141},
 {'value': 3, 'source': 89, 'target': 135},
 {'value': 3, 'source': 90, 'target': 142},
 {'value': 3, 'source': 59, 'target': 130},
 {'value': 3, 'source': 90, 'target': 155},
 {'value': 3, 'source': 90, 'target': 130},
 {'value': 3, 'source': 91, 'target': 24},
 {'value': 3, 'source': 92, 'target': 124},
 {'value': 3, 'source': 93, 'target': 134},
 {'value': 3, 'source': 94, 'target': 124},
 {'value': 3, 'source': 95, 'target': 24},
 {'value': 3, 'source': 96, 'target': 132},
 {'value': 3, 'source': 97, 'target': 128},
 {'value': 3, 'source': 98, 'target': 141},
 {'value': 3, 'source': 99, 'target': 156},
 {'value': 3, 'source': 3, 'target': 155},
 {'value': 3, 'source': 3, 'target': 147},
 {'value': 3, 'source': 57, 'target': 141},
 {'value': 3, 'source': 100, 'target': 156},
 {'value': 3, 'source': 101, 'target': 150},
 {'value': 3, 'source': 59, 'target': 153},
 {'value': 3, 'source': 102, 'target': 157},
 {'value': 3, 'source': 103, 'target': 141},
 {'value': 3, 'source': 103, 'target': 153},
 {'value': 3, 'source': 88, 'target': 152},
 {'value': 3, 'source': 104, 'target': 158},
 {'value': 3, 'source': 105, 'target': 150},
 {'value': 3, 'source': 106, 'target': 142},
 {'value': 3, 'source': 107, 'target': 132},
 {'value': 3, 'source': 108, 'target': 139},
 {'value': 3, 'source': 109, 'target': 137},
 {'value': 3, 'source': 110, 'target': 129},
 {'value': 3, 'source': 84, 'target': 137},
 {'value': 3, 'source': 111, 'target': 130},
 {'value': 3, 'source': 63, 'target': 147},
 {'value': 3, 'source': 112, 'target': 152},
 {'value': 3, 'source': 113, 'target': 129},
 {'value': 3, 'source': 114, 'target': 125},
 {'value': 3, 'source': 115, 'target': 147},
 {'value': 3, 'source': 116, 'target': 159},
 {'value': 3, 'source': 117, 'target': 127},
 {'value': 3, 'source': 118, 'target': 125},
 {'value': 3, 'source': 49, 'target': 24},
 {'value': 3, 'source': 83, 'target': 144},
 {'value': 3, 'source': 119, 'target': 152},
 {'value': 3, 'source': 5, 'target': 153},
 {'value': 3, 'source': 112, 'target': 143},
 {'value': 3, 'source': 69, 'target': 155},
 {'value': 3, 'source': 120, 'target': 137},
 {'value': 3, 'source': 69, 'target': 126},
 {'value': 3, 'source': 69, 'target': 124},
 {'value': 3, 'source': 121, 'target': 137},
 {'value': 3, 'source': 84, 'target': 152},
 {'value': 3, 'source': 122, 'target': 160}]

In [398]:
# 노드 생성하기
nodes_list_gen1= []
nodes_list_gen1.clear()
for index,row in generate_node_gen1.iterrows():
    nodes_list_gen1.append({ "name":row['source'], "type":"lyricist", "impor":row['count']})
for idol in group_dict_gen1_artist:
    nodes_list_gen1.append({"name":idol, "type":"artist", "impor":0})
nodes_list_gen1

[{'name': '김영아', 'type': 'lyricist', 'impor': 69},
 {'name': '박진영', 'type': 'lyricist', 'impor': 69},
 {'name': '유영진', 'type': 'lyricist', 'impor': 54},
 {'name': '이승호', 'type': 'lyricist', 'impor': 43},
 {'name': '유건형', 'type': 'lyricist', 'impor': 40},
 {'name': 'M (이민우)', 'type': 'lyricist', 'impor': 28},
 {'name': '강타 (KANGTA)', 'type': 'lyricist', 'impor': 28},
 {'name': '이상민', 'type': 'lyricist', 'impor': 28},
 {'name': '장대성', 'type': 'lyricist', 'impor': 26},
 {'name': '테디', 'type': 'lyricist', 'impor': 25},
 {'name': '조은희', 'type': 'lyricist', 'impor': 23},
 {'name': '천명훈', 'type': 'lyricist', 'impor': 19},
 {'name': '송백경', 'type': 'lyricist', 'impor': 19},
 {'name': '서정환', 'type': 'lyricist', 'impor': 17},
 {'name': '장우혁', 'type': 'lyricist', 'impor': 16},
 {'name': '이재원', 'type': 'lyricist', 'impor': 15},
 {'name': '에릭', 'type': 'lyricist', 'impor': 15},
 {'name': '박성호 (구피)', 'type': 'lyricist', 'impor': 14},
 {'name': '지국현', 'type': 'lyricist', 'impor': 14},
 {'name': '토니 안', 'type': 'lyricist', 'impor': 14},
 {'name': '문희준', 'type': 'lyricist', 'impor': 14},
 {'name': '신동욱', 'type': 'lyricist', 'impor': 13},
 {'name': '바다', 'type': 'lyricist', 'impor': 13},
 {'name': '이용민', 'type': 'lyricist', 'impor': 12},
 {'name': '서융근', 'type': 'lyricist', 'impor': 12},
 {'name': '제드', 'type': 'lyricist', 'impor': 12},
 {'name': '이도연', 'type': 'lyricist', 'impor': 12},
 {'name': '김태희', 'type': 'lyricist', 'impor': 11},
 {'name': 'Brian Kim', 'type': 'lyricist', 'impor': 11},
 {'name': '김수정', 'type': 'lyricist', 'impor': 11},
 {'name': '신승희', 'type': 'lyricist', 'impor': 11},
 {'name': 'Rain', 'type': 'lyricist', 'impor': 11},
 {'name': '최갑원', 'type': 'lyricist', 'impor': 11},
 {'name': 'Unknown', 'type': 'lyricist', 'impor': 10},
 {'name': '임선아', 'type': 'lyricist', 'impor': 10},
 {'name': '버즈', 'type': 'lyricist', 'impor': 10},
 {'name': '이현도', 'type': 'lyricist', 'impor': 10},
 {'name': '김진아', 'type': 'lyricist', 'impor': 10},
 {'name': '안성일', 'type': 'lyricist', 'impor': 10},
 {'name': '안영민', 'type': 'lyricist', 'impor': 10},
 {'name': 'Do', 'type': 'lyricist', 'impor': 9},
 {'name': '김종숙', 'type': 'lyricist', 'impor': 9},
 {'name': '김이나', 'type': 'lyricist', 'impor': 9},
 {'name': '홍지유', 'type': 'lyricist', 'impor': 9},
 {'name': '이상인', 'type': 'lyricist', 'impor': 9},
 {'name': 'god', 'type': 'lyricist', 'impor': 9},
 {'name': '조규만', 'type': 'lyricist', 'impor': 9},
 {'name': '양재선', 'type': 'lyricist', 'impor': 9},
 {'name': '이재경', 'type': 'lyricist', 'impor': 9},
 {'name': '렌', 'type': 'lyricist', 'impor': 8},
 {'name': '강은경', 'type': 'lyricist', 'impor': 8},
 {'name': '김태윤', 'type': 'lyricist', 'impor': 8},
 {'name': '한경혜', 'type': 'lyricist', 'impor': 8},
 {'name': '이단옆차기', 'type': 'lyricist', 'impor': 8},
 {'name': '이희승', 'type': 'lyricist', 'impor': 8},
 {'name': '신혜성', 'type': 'lyricist', 'impor': 8},
 {'name': '정진환', 'type': 'lyricist', 'impor': 8},
 {'name': '장용진', 'type': 'lyricist', 'impor': 7},
 {'name': '김재덕', 'type': 'lyricist', 'impor': 7},
 {'name': '전승우', 'type': 'lyricist', 'impor': 7},
 {'name': '이현우', 'type': 'lyricist', 'impor': 7},
 {'name': '최희진', 'type': 'lyricist', 'impor': 7},
 {'name': '주영훈', 'type': 'lyricist', 'impor': 6},
 {'name': '김동현', 'type': 'lyricist', 'impor': 6},
 {'name': '이상호', 'type': 'lyricist', 'impor': 6},
 {'name': '최명섭', 'type': 'lyricist', 'impor': 6},
 {'name': '방시혁', 'type': 'lyricist', 'impor': 6},
 {'name': '박선주 (Pak Sun Zoo)', 'type': 'lyricist', 'impor': 6},
 {'name': '장성재', 'type': 'lyricist', 'impor': 6},
 {'name': '유유진', 'type': 'lyricist', 'impor': 6},
 {'name': '최태규', 'type': 'lyricist', 'impor': 5},
 {'name': '박창현', 'type': 'lyricist', 'impor': 5},
 {'name': '데니안', 'type': 'lyricist', 'impor': 5},
 {'name': '김민지', 'type': 'lyricist', 'impor': 5},
 {'name': '노유민', 'type': 'lyricist', 'impor': 5},
 {'name': '노민혁', 'type': 'lyricist', 'impor': 5},
 {'name': '남기상', 'type': 'lyricist', 'impor': 5},
 {'name': 'LIØN', 'type': 'lyricist', 'impor': 5},
 {'name': '이희성', 'type': 'lyricist', 'impor': 5},
 {'name': '김우진', 'type': 'lyricist', 'impor': 5},
 {'name': '김광휘', 'type': 'lyricist', 'impor': 5},
 {'name': '정진수', 'type': 'lyricist', 'impor': 5},
 {'name': '오지훈', 'type': 'lyricist', 'impor': 5},
 {'name': '오종혁', 'type': 'lyricist', 'impor': 5},
 {'name': '박기영', 'type': 'lyricist', 'impor': 4},
 {'name': '조준영', 'type': 'lyricist', 'impor': 4},
 {'name': 'Tablo', 'type': 'lyricist', 'impor': 4},
 {'name': '박채원', 'type': 'lyricist', 'impor': 4},
 {'name': '옥주현', 'type': 'lyricist', 'impor': 4},
 {'name': '허인창', 'type': 'lyricist', 'impor': 4},
 {'name': 'David Kim', 'type': 'lyricist', 'impor': 4},
 {'name': '주찬양 (티맥스)', 'type': 'lyricist', 'impor': 4},
 {'name': '강우경', 'type': 'lyricist', 'impor': 4},
 {'name': '민경훈', 'type': 'lyricist', 'impor': 4},
 {'name': '유진', 'type': 'lyricist', 'impor': 4},
 {'name': '김희선', 'type': 'lyricist', 'impor': 4},
 {'name': '황성진', 'type': 'lyricist', 'impor': 4},
 {'name': '이제이', 'type': 'lyricist', 'impor': 4},
 {'name': '김유라', 'type': 'lyricist', 'impor': 4},
 {'name': '한재호', 'type': 'lyricist', 'impor': 4},
 {'name': '서정진', 'type': 'lyricist', 'impor': 4},
 {'name': 'Crom', 'type': 'lyricist', 'impor': 4},
 {'name': '디스코 파이터', 'type': 'lyricist', 'impor': 4},
 {'name': '김남희', 'type': 'lyricist', 'impor': 3},
 {'name': '김동완', 'type': 'lyricist', 'impor': 3},
 {'name': '문스톤', 'type': 'lyricist', 'impor': 3},
 {'name': '무', 'type': 'lyricist', 'impor': 3},
 {'name': '정성헌', 'type': 'lyricist', 'impor': 3},
 {'name': '김달우피터', 'type': 'lyricist', 'impor': 3},
 {'name': '김기범', 'type': 'lyricist', 'impor': 3},
 {'name': '이택승', 'type': 'lyricist', 'impor': 3},
 {'name': '김유민', 'type': 'lyricist', 'impor': 3},
 {'name': '우연석', 'type': 'lyricist', 'impor': 3},
 {'name': 'Brian Joo', 'type': 'lyricist', 'impor': 3},
 {'name': '김형석', 'type': 'lyricist', 'impor': 3},
 {'name': '황성제', 'type': 'lyricist', 'impor': 3},
 {'name': '김이지', 'type': 'lyricist', 'impor': 3},
 {'name': '환희', 'type': 'lyricist', 'impor': 3},
 {'name': '홍재선', 'type': 'lyricist', 'impor': 3},
 {'name': '김세진', 'type': 'lyricist', 'impor': 3},
 {'name': '이효리', 'type': 'lyricist', 'impor': 3},
 {'name': 'DAVINK (다빈크)', 'type': 'lyricist', 'impor': 3},
 {'name': '정한종', 'type': 'lyricist', 'impor': 3},
 {'name': '양현석', 'type': 'lyricist', 'impor': 3},
 {'name': '대니', 'type': 'lyricist', 'impor': 3},
 {'name': '이현규', 'type': 'lyricist', 'impor': 3},
 {'name': '민연재', 'type': 'lyricist', 'impor': 3},
 {'name': '김창환', 'type': 'lyricist', 'impor': 3},
 {'name': '최수정', 'type': 'lyricist', 'impor': 3},
 {'name': 'Minuki', 'type': 'lyricist', 'impor': 3},
 {'name': '신지원', 'type': 'lyricist', 'impor': 3},
 {'name': '신준기', 'type': 'lyricist', 'impor': 3},
 {'name': '태훈', 'type': 'lyricist', 'impor': 3},
 {'name': '강원석', 'type': 'lyricist', 'impor': 3},
 {'name': '강욱진', 'type': 'lyricist', 'impor': 3},
 {'name': '강성훈', 'type': 'lyricist', 'impor': 3},
 {'name': 'e.one', 'type': 'lyricist', 'impor': 3},
 {'name': '박정란', 'type': 'lyricist', 'impor': 3},
 {'name': '신연아', 'type': 'lyricist', 'impor': 3},
 {'name': '차상민', 'type': 'lyricist', 'impor': 3},
 {'name': 'YOUNG H.KIM', 'type': 'lyricist', 'impor': 3},
 {'name': '이건우', 'type': 'lyricist', 'impor': 3},
 {'name': 'Urban Cllasik', 'type': 'lyricist', 'impor': 3},
 {'name': '3534', 'type': 'lyricist', 'impor': 3},
 {'name': '윤우현', 'type': 'lyricist', 'impor': 3},
 {'name': '배화영', 'type': 'lyricist', 'impor': 3},
 {'name': '이우천', 'type': 'lyricist', 'impor': 3},
 {'name': '곽상엽', 'type': 'lyricist', 'impor': 3},
 {'name': '박건호', 'type': 'lyricist', 'impor': 3},
 {'name': '싸이 (PSY)', 'type': 'lyricist', 'impor': 3},
 {'name': '써니사이드 챙', 'type': 'lyricist', 'impor': 3},
 {'name': '윤경', 'type': 'lyricist', 'impor': 3},
 {'name': '박성수', 'type': 'lyricist', 'impor': 3},
 {'name': 'Jay Kang', 'type': 'lyricist', 'impor': 3},
 {'name': '윤사라', 'type': 'lyricist', 'impor': 3},
 {'name': 'god', 'type': 'artist', 'impor': 0},
 {'name': '언타이틀', 'type': 'artist', 'impor': 0},
 {'name': '신화', 'type': 'artist', 'impor': 0},
 {'name': '젝스키스', 'type': 'artist', 'impor': 0},
 {'name': '샤크라', 'type': 'artist', 'impor': 0},
 {'name': '구피', 'type': 'artist', 'impor': 0},
 {'name': '엔알지', 'type': 'artist', 'impor': 0},
 {'name': '에이치오티', 'type': 'artist', 'impor': 0},
 {'name': '핑클', 'type': 'artist', 'impor': 0},
 {'name': '원타임', 'type': 'artist', 'impor': 0},
 {'name': '에스이에스', 'type': 'artist', 'impor': 0},
 {'name': '디베이스', 'type': 'artist', 'impor': 0},
 {'name': '제이워크', 'type': 'artist', 'impor': 0},
 {'name': '테이크', 'type': 'artist', 'impor': 0},
 {'name': '제이티엘', 'type': 'artist', 'impor': 0},
 {'name': '플라이 투 더 스카이', 'type': 'artist', 'impor': 0},
 {'name': '버즈', 'type': 'artist', 'impor': 0},
 {'name': '오션', 'type': 'artist', 'impor': 0},
 {'name': '와이투케이', 'type': 'artist', 'impor': 0},
 {'name': '에스', 'type': 'artist', 'impor': 0},
 {'name': '베이비 복스 리브', 'type': 'artist', 'impor': 0},
 {'name': '클릭비', 'type': 'artist', 'impor': 0},
 {'name': '파파야', 'type': 'artist', 'impor': 0},
 {'name': '문차일드', 'type': 'artist', 'impor': 0},
 {'name': '케이팝', 'type': 'artist', 'impor': 0},
 {'name': '씨유', 'type': 'artist', 'impor': 0},
 {'name': '쥬얼리', 'type': 'artist', 'impor': 0},
 {'name': '에이포', 'type': 'artist', 'impor': 0},
 {'name': '클레오', 'type': 'artist', 'impor': 0},
 {'name': '태사자', 'type': 'artist', 'impor': 0},
 {'name': '보이스립', 'type': 'artist', 'impor': 0},
 {'name': '슈가', 'type': 'artist', 'impor': 0},
 {'name': '악동 클럽 (디 에이디)', 'type': 'artist', 'impor': 0},
 {'name': '써클', 'type': 'artist', 'impor': 0},
 {'name': '티티마', 'type': 'artist', 'impor': 0},
 {'name': '파이브', 'type': 'artist', 'impor': 0},
 {'name': '아이돌', 'type': 'artist', 'impor': 0},
 {'name': '스위티', 'type': 'artist', 'impor': 0},
 {'name': '투야', 'type': 'artist', 'impor': 0},
 {'name': '스맥스', 'type': 'artist', 'impor': 0}]

In [399]:
links_list_gen1[:5]

[{'value': 68, 'source': 0, 'target': 31},
 {'value': 40, 'source': 1, 'target': 123},
 {'value': 26, 'source': 2, 'target': 124},
 {'value': 24, 'source': 3, 'target': 125},
 {'value': 23, 'source': 4, 'target': 126}]

In [400]:
nodes_list_gen1[:5]

[{'name': '김영아', 'type': 'lyricist', 'impor': 69},
 {'name': '박진영', 'type': 'lyricist', 'impor': 69},
 {'name': '유영진', 'type': 'lyricist', 'impor': 54},
 {'name': '이승호', 'type': 'lyricist', 'impor': 43},
 {'name': '유건형', 'type': 'lyricist', 'impor': 40}]

In [401]:
json_prep_gen1 = {"links":links_list_gen1, "nodes":nodes_list_gen1}
json_prep_gen1.keys()

dict_keys(['links', 'nodes'])

In [402]:
json_dump_gen1 = json.dumps(json_prep_gen1, indent=1, sort_keys=True, ensure_ascii=False)

In [403]:
print(json_dump_gen1)

{
 "links": [
  {
   "source": 0,
   "target": 31,
   "value": 68
  },
  {
   "source": 1,
   "target": 123,
   "value": 40
  },
  {
   "source": 2,
   "target": 124,
   "value": 26
  },
  {
   "source": 3,
   "target": 125,
   "value": 24
  },
  {
   "source": 4,
   "target": 126,
   "value": 23
  },
  {
   "source": 5,
   "target": 127,
   "value": 22
  },
  {
   "source": 6,
   "target": 128,
   "value": 19
  },
  {
   "source": 7,
   "target": 129,
   "value": 19
  },
  {
   "source": 3,
   "target": 130,
   "value": 18
  },
  {
   "source": 8,
   "target": 131,
   "value": 17
  },
  {
   "source": 9,
   "target": 129,
   "value": 16
  },
  {
   "source": 10,
   "target": 123,
   "value": 16
  },
  {
   "source": 11,
   "target": 127,
   "value": 14
  },
  {
   "source": 12,
   "target": 131,
   "value": 14
  },
  {
   "source": 13,
   "target": 124,
   "value": 14
  },
  {
   "source": 14,
   "target": 129,
   "value": 14
  },
  {
   "source": 15,
   "target": 127,
   "value": 13
  },
  {
   "source": 7,
   "target": 124,
   "value": 13
  },
  {
   "source": 16,
   "target": 132,
   "value": 13
  },
  {
   "source": 17,
   "target": 133,
   "value": 12
  },
  {
   "source": 18,
   "target": 125,
   "value": 12
  },
  {
   "source": 19,
   "target": 134,
   "value": 11
  },
  {
   "source": 12,
   "target": 131,
   "value": 11
  },
  {
   "source": 20,
   "target": 135,
   "value": 11
  },
  {
   "source": 21,
   "target": 136,
   "value": 11
  },
  {
   "source": 22,
   "target": 124,
   "value": 11
  },
  {
   "source": 23,
   "target": 136,
   "value": 11
  },
  {
   "source": 7,
   "target": 132,
   "value": 11
  },
  {
   "source": 5,
   "target": 125,
   "value": 10
  },
  {
   "source": 7,
   "target": 137,
   "value": 10
  },
  {
   "source": 24,
   "target": 24,
   "value": 10
  },
  {
   "source": 25,
   "target": 24,
   "value": 9
  },
  {
   "source": 26,
   "target": 137,
   "value": 9
  },
  {
   "source": 27,
   "target": 137,
   "value": 9
  },
  {
   "source": 3,
   "target": 138,
   "value": 9
  },
  {
   "source": 28,
   "target": 133,
   "value": 9
  },
  {
   "source": 29,
   "target": 133,
   "value": 9
  },
  {
   "source": 30,
   "target": 129,
   "value": 9
  },
  {
   "source": 31,
   "target": 31,
   "value": 9
  },
  {
   "source": 32,
   "target": 134,
   "value": 9
  },
  {
   "source": 18,
   "target": 139,
   "value": 9
  },
  {
   "source": 33,
   "target": 138,
   "value": 8
  },
  {
   "source": 34,
   "target": 124,
   "value": 8
  },
  {
   "source": 35,
   "target": 24,
   "value": 8
  },
  {
   "source": 3,
   "target": 128,
   "value": 8
  },
  {
   "source": 36,
   "target": 138,
   "value": 8
  },
  {
   "source": 37,
   "target": 138,
   "value": 7
  },
  {
   "source": 27,
   "target": 127,
   "value": 7
  },
  {
   "source": 38,
   "target": 24,
   "value": 7
  },
  {
   "source": 39,
   "target": 31,
   "value": 7
  },
  {
   "source": 40,
   "target": 124,
   "value": 7
  },
  {
   "source": 41,
   "target": 129,
   "value": 6
  },
  {
   "source": 42,
   "target": 135,
   "value": 6
  },
  {
   "source": 43,
   "target": 124,
   "value": 6
  },
  {
   "source": 44,
   "target": 137,
   "value": 6
  },
  {
   "source": 9,
   "target": 140,
   "value": 6
  },
  {
   "source": 45,
   "target": 128,
   "value": 6
  },
  {
   "source": 46,
   "target": 124,
   "value": 6
  },
  {
   "source": 47,
   "target": 141,
   "value": 6
  },
  {
   "source": 48,
   "target": 141,
   "value": 5
  },
  {
   "source": 49,
   "target": 130,
   "value": 5
  },
  {
   "source": 5,
   "target": 130,
   "value": 5
  },
  {
   "source": 50,
   "target": 142,
   "value": 5
  },
  {
   "source": 51,
   "target": 142,
   "value": 5
  },
  {
   "source": 52,
   "target": 125,
   "value": 5
  },
  {
   "source": 53,
   "target": 143,
   "value": 5
  },
  {
   "source": 54,
   "target": 144,
   "value": 5
  },
  {
   "source": 21,
   "target": 129,
   "value": 5
  },
  {
   "source": 55,
   "target": 145,
   "value": 5
  },
  {
   "source": 56,
   "target": 125,
   "value": 5
  },
  {
   "source": 57,
   "target": 146,
   "value": 5
  },
  {
   "source": 58,
   "target": 31,
   "value": 5
  },
  {
   "source": 30,
   "target": 136,
   "value": 5
  },
  {
   "source": 59,
   "target": 145,
   "value": 5
  },
  {
   "source": 60,
   "target": 128,
   "value": 5
  },
  {
   "source": 61,
   "target": 135,
   "value": 5
  },
  {
   "source": 62,
   "target": 125,
   "value": 5
  },
  {
   "source": 63,
   "target": 137,
   "value": 5
  },
  {
   "source": 63,
   "target": 24,
   "value": 5
  },
  {
   "source": 43,
   "target": 137,
   "value": 5
  },
  {
   "source": 64,
   "target": 141,
   "value": 5
  },
  {
   "source": 65,
   "target": 134,
   "value": 5
  },
  {
   "source": 66,
   "target": 142,
   "value": 5
  },
  {
   "source": 67,
   "target": 147,
   "value": 5
  },
  {
   "source": 68,
   "target": 132,
   "value": 4
  },
  {
   "source": 27,
   "target": 141,
   "value": 4
  },
  {
   "source": 69,
   "target": 137,
   "value": 4
  },
  {
   "source": 70,
   "target": 148,
   "value": 4
  },
  {
   "source": 71,
   "target": 143,
   "value": 4
  },
  {
   "source": 72,
   "target": 24,
   "value": 4
  },
  {
   "source": 73,
   "target": 137,
   "value": 4
  },
  {
   "source": 9,
   "target": 137,
   "value": 4
  },
  {
   "source": 4,
   "target": 149,
   "value": 4
  },
  {
   "source": 74,
   "target": 124,
   "value": 4
  },
  {
   "source": 69,
   "target": 150,
   "value": 4
  },
  {
   "source": 75,
   "target": 130,
   "value": 4
  },
  {
   "source": 76,
   "target": 24,
   "value": 4
  },
  {
   "source": 77,
   "target": 134,
   "value": 4
  },
  {
   "source": 78,
   "target": 148,
   "value": 4
  },
  {
   "source": 23,
   "target": 129,
   "value": 4
  },
  {
   "source": 79,
   "target": 137,
   "value": 4
  },
  {
   "source": 3,
   "target": 151,
   "value": 4
  },
  {
   "source": 69,
   "target": 152,
   "value": 4
  },
  {
   "source": 3,
   "target": 142,
   "value": 4
  },
  {
   "source": 80,
   "target": 124,
   "value": 4
  },
  {
   "source": 81,
   "target": 147,
   "value": 4
  },
  {
   "source": 82,
   "target": 137,
   "value": 4
  },
  {
   "source": 83,
   "target": 130,
   "value": 4
  },
  {
   "source": 84,
   "target": 124,
   "value": 4
  },
  {
   "source": 85,
   "target": 128,
   "value": 4
  },
  {
   "source": 69,
   "target": 153,
   "value": 4
  },
  {
   "source": 18,
   "target": 147,
   "value": 4
  },
  {
   "source": 53,
   "target": 128,
   "value": 4
  },
  {
   "source": 86,
   "target": 125,
   "value": 4
  },
  {
   "source": 18,
   "target": 154,
   "value": 4
  },
  {
   "source": 87,
   "target": 144,
   "value": 4
  },
  {
   "source": 88,
   "target": 141,
   "value": 4
  },
  {
   "source": 89,
   "target": 135,
   "value": 3
  },
  {
   "source": 90,
   "target": 142,
   "value": 3
  },
  {
   "source": 59,
   "target": 130,
   "value": 3
  },
  {
   "source": 90,
   "target": 155,
   "value": 3
  },
  {
   "source": 90,
   "target": 130,
   "value": 3
  },
  {
   "source": 91,
   "target": 24,
   "value": 3
  },
  {
   "source": 92,
   "target": 124,
   "value": 3
  },
  {
   "source": 93,
   "target": 134,
   "value": 3
  },
  {
   "source": 94,
   "target": 124,
   "value": 3
  },
  {
   "source": 95,
   "target": 24,
   "value": 3
  },
  {
   "source": 96,
   "target": 132,
   "value": 3
  },
  {
   "source": 97,
   "target": 128,
   "value": 3
  },
  {
   "source": 98,
   "target": 141,
   "value": 3
  },
  {
   "source": 99,
   "target": 156,
   "value": 3
  },
  {
   "source": 3,
   "target": 155,
   "value": 3
  },
  {
   "source": 3,
   "target": 147,
   "value": 3
  },
  {
   "source": 57,
   "target": 141,
   "value": 3
  },
  {
   "source": 100,
   "target": 156,
   "value": 3
  },
  {
   "source": 101,
   "target": 150,
   "value": 3
  },
  {
   "source": 59,
   "target": 153,
   "value": 3
  },
  {
   "source": 102,
   "target": 157,
   "value": 3
  },
  {
   "source": 103,
   "target": 141,
   "value": 3
  },
  {
   "source": 103,
   "target": 153,
   "value": 3
  },
  {
   "source": 88,
   "target": 152,
   "value": 3
  },
  {
   "source": 104,
   "target": 158,
   "value": 3
  },
  {
   "source": 105,
   "target": 150,
   "value": 3
  },
  {
   "source": 106,
   "target": 142,
   "value": 3
  },
  {
   "source": 107,
   "target": 132,
   "value": 3
  },
  {
   "source": 108,
   "target": 139,
   "value": 3
  },
  {
   "source": 109,
   "target": 137,
   "value": 3
  },
  {
   "source": 110,
   "target": 129,
   "value": 3
  },
  {
   "source": 84,
   "target": 137,
   "value": 3
  },
  {
   "source": 111,
   "target": 130,
   "value": 3
  },
  {
   "source": 63,
   "target": 147,
   "value": 3
  },
  {
   "source": 112,
   "target": 152,
   "value": 3
  },
  {
   "source": 113,
   "target": 129,
   "value": 3
  },
  {
   "source": 114,
   "target": 125,
   "value": 3
  },
  {
   "source": 115,
   "target": 147,
   "value": 3
  },
  {
   "source": 116,
   "target": 159,
   "value": 3
  },
  {
   "source": 117,
   "target": 127,
   "value": 3
  },
  {
   "source": 118,
   "target": 125,
   "value": 3
  },
  {
   "source": 49,
   "target": 24,
   "value": 3
  },
  {
   "source": 83,
   "target": 144,
   "value": 3
  },
  {
   "source": 119,
   "target": 152,
   "value": 3
  },
  {
   "source": 5,
   "target": 153,
   "value": 3
  },
  {
   "source": 112,
   "target": 143,
   "value": 3
  },
  {
   "source": 69,
   "target": 155,
   "value": 3
  },
  {
   "source": 120,
   "target": 137,
   "value": 3
  },
  {
   "source": 69,
   "target": 126,
   "value": 3
  },
  {
   "source": 69,
   "target": 124,
   "value": 3
  },
  {
   "source": 121,
   "target": 137,
   "value": 3
  },
  {
   "source": 84,
   "target": 152,
   "value": 3
  },
  {
   "source": 122,
   "target": 160,
   "value": 3
  }
 ],
 "nodes": [
  {
   "impor": 69,
   "name": "김영아",
   "type": "lyricist"
  },
  {
   "impor": 69,
   "name": "박진영",
   "type": "lyricist"
  },
  {
   "impor": 54,
   "name": "유영진",
   "type": "lyricist"
  },
  {
   "impor": 43,
   "name": "이승호",
   "type": "lyricist"
  },
  {
   "impor": 40,
   "name": "유건형",
   "type": "lyricist"
  },
  {
   "impor": 28,
   "name": "M (이민우)",
   "type": "lyricist"
  },
  {
   "impor": 28,
   "name": "강타 (KANGTA)",
   "type": "lyricist"
  },
  {
   "impor": 28,
   "name": "이상민",
   "type": "lyricist"
  },
  {
   "impor": 26,
   "name": "장대성",
   "type": "lyricist"
  },
  {
   "impor": 25,
   "name": "테디",
   "type": "lyricist"
  },
  {
   "impor": 23,
   "name": "조은희",
   "type": "lyricist"
  },
  {
   "impor": 19,
   "name": "천명훈",
   "type": "lyricist"
  },
  {
   "impor": 19,
   "name": "송백경",
   "type": "lyricist"
  },
  {
   "impor": 17,
   "name": "서정환",
   "type": "lyricist"
  },
  {
   "impor": 16,
   "name": "장우혁",
   "type": "lyricist"
  },
  {
   "impor": 15,
   "name": "이재원",
   "type": "lyricist"
  },
  {
   "impor": 15,
   "name": "에릭",
   "type": "lyricist"
  },
  {
   "impor": 14,
   "name": "박성호 (구피)",
   "type": "lyricist"
  },
  {
   "impor": 14,
   "name": "지국현",
   "type": "lyricist"
  },
  {
   "impor": 14,
   "name": "토니 안",
   "type": "lyricist"
  },
  {
   "impor": 14,
   "name": "문희준",
   "type": "lyricist"
  },
  {
   "impor": 13,
   "name": "신동욱",
   "type": "lyricist"
  },
  {
   "impor": 13,
   "name": "바다",
   "type": "lyricist"
  },
  {
   "impor": 12,
   "name": "이용민",
   "type": "lyricist"
  },
  {
   "impor": 12,
   "name": "서융근",
   "type": "lyricist"
  },
  {
   "impor": 12,
   "name": "제드",
   "type": "lyricist"
  },
  {
   "impor": 12,
   "name": "이도연",
   "type": "lyricist"
  },
  {
   "impor": 11,
   "name": "김태희",
   "type": "lyricist"
  },
  {
   "impor": 11,
   "name": "Brian Kim",
   "type": "lyricist"
  },
  {
   "impor": 11,
   "name": "김수정",
   "type": "lyricist"
  },
  {
   "impor": 11,
   "name": "신승희",
   "type": "lyricist"
  },
  {
   "impor": 11,
   "name": "Rain",
   "type": "lyricist"
  },
  {
   "impor": 11,
   "name": "최갑원",
   "type": "lyricist"
  },
  {
   "impor": 10,
   "name": "Unknown",
   "type": "lyricist"
  },
  {
   "impor": 10,
   "name": "임선아",
   "type": "lyricist"
  },
  {
   "impor": 10,
   "name": "버즈",
   "type": "lyricist"
  },
  {
   "impor": 10,
   "name": "이현도",
   "type": "lyricist"
  },
  {
   "impor": 10,
   "name": "김진아",
   "type": "lyricist"
  },
  {
   "impor": 10,
   "name": "안성일",
   "type": "lyricist"
  },
  {
   "impor": 10,
   "name": "안영민",
   "type": "lyricist"
  },
  {
   "impor": 9,
   "name": "Do",
   "type": "lyricist"
  },
  {
   "impor": 9,
   "name": "김종숙",
   "type": "lyricist"
  },
  {
   "impor": 9,
   "name": "김이나",
   "type": "lyricist"
  },
  {
   "impor": 9,
   "name": "홍지유",
   "type": "lyricist"
  },
  {
   "impor": 9,
   "name": "이상인",
   "type": "lyricist"
  },
  {
   "impor": 9,
   "name": "god",
   "type": "lyricist"
  },
  {
   "impor": 9,
   "name": "조규만",
   "type": "lyricist"
  },
  {
   "impor": 9,
   "name": "양재선",
   "type": "lyricist"
  },
  {
   "impor": 9,
   "name": "이재경",
   "type": "lyricist"
  },
  {
   "impor": 8,
   "name": "렌",
   "type": "lyricist"
  },
  {
   "impor": 8,
   "name": "강은경",
   "type": "lyricist"
  },
  {
   "impor": 8,
   "name": "김태윤",
   "type": "lyricist"
  },
  {
   "impor": 8,
   "name": "한경혜",
   "type": "lyricist"
  },
  {
   "impor": 8,
   "name": "이단옆차기",
   "type": "lyricist"
  },
  {
   "impor": 8,
   "name": "이희승",
   "type": "lyricist"
  },
  {
   "impor": 8,
   "name": "신혜성",
   "type": "lyricist"
  },
  {
   "impor": 8,
   "name": "정진환",
   "type": "lyricist"
  },
  {
   "impor": 7,
   "name": "장용진",
   "type": "lyricist"
  },
  {
   "impor": 7,
   "name": "김재덕",
   "type": "lyricist"
  },
  {
   "impor": 7,
   "name": "전승우",
   "type": "lyricist"
  },
  {
   "impor": 7,
   "name": "이현우",
   "type": "lyricist"
  },
  {
   "impor": 7,
   "name": "최희진",
   "type": "lyricist"
  },
  {
   "impor": 6,
   "name": "주영훈",
   "type": "lyricist"
  },
  {
   "impor": 6,
   "name": "김동현",
   "type": "lyricist"
  },
  {
   "impor": 6,
   "name": "이상호",
   "type": "lyricist"
  },
  {
   "impor": 6,
   "name": "최명섭",
   "type": "lyricist"
  },
  {
   "impor": 6,
   "name": "방시혁",
   "type": "lyricist"
  },
  {
   "impor": 6,
   "name": "박선주 (Pak Sun Zoo)",
   "type": "lyricist"
  },
  {
   "impor": 6,
   "name": "장성재",
   "type": "lyricist"
  },
  {
   "impor": 6,
   "name": "유유진",
   "type": "lyricist"
  },
  {
   "impor": 5,
   "name": "최태규",
   "type": "lyricist"
  },
  {
   "impor": 5,
   "name": "박창현",
   "type": "lyricist"
  },
  {
   "impor": 5,
   "name": "데니안",
   "type": "lyricist"
  },
  {
   "impor": 5,
   "name": "김민지",
   "type": "lyricist"
  },
  {
   "impor": 5,
   "name": "노유민",
   "type": "lyricist"
  },
  {
   "impor": 5,
   "name": "노민혁",
   "type": "lyricist"
  },
  {
   "impor": 5,
   "name": "남기상",
   "type": "lyricist"
  },
  {
   "impor": 5,
   "name": "LIØN",
   "type": "lyricist"
  },
  {
   "impor": 5,
   "name": "이희성",
   "type": "lyricist"
  },
  {
   "impor": 5,
   "name": "김우진",
   "type": "lyricist"
  },
  {
   "impor": 5,
   "name": "김광휘",
   "type": "lyricist"
  },
  {
   "impor": 5,
   "name": "정진수",
   "type": "lyricist"
  },
  {
   "impor": 5,
   "name": "오지훈",
   "type": "lyricist"
  },
  {
   "impor": 5,
   "name": "오종혁",
   "type": "lyricist"
  },
  {
   "impor": 4,
   "name": "박기영",
   "type": "lyricist"
  },
  {
   "impor": 4,
   "name": "조준영",
   "type": "lyricist"
  },
  {
   "impor": 4,
   "name": "Tablo",
   "type": "lyricist"
  },
  {
   "impor": 4,
   "name": "박채원",
   "type": "lyricist"
  },
  {
   "impor": 4,
   "name": "옥주현",
   "type": "lyricist"
  },
  {
   "impor": 4,
   "name": "허인창",
   "type": "lyricist"
  },
  {
   "impor": 4,
   "name": "David Kim",
   "type": "lyricist"
  },
  {
   "impor": 4,
   "name": "주찬양 (티맥스)",
   "type": "lyricist"
  },
  {
   "impor": 4,
   "name": "강우경",
   "type": "lyricist"
  },
  {
   "impor": 4,
   "name": "민경훈",
   "type": "lyricist"
  },
  {
   "impor": 4,
   "name": "유진",
   "type": "lyricist"
  },
  {
   "impor": 4,
   "name": "김희선",
   "type": "lyricist"
  },
  {
   "impor": 4,
   "name": "황성진",
   "type": "lyricist"
  },
  {
   "impor": 4,
   "name": "이제이",
   "type": "lyricist"
  },
  {
   "impor": 4,
   "name": "김유라",
   "type": "lyricist"
  },
  {
   "impor": 4,
   "name": "한재호",
   "type": "lyricist"
  },
  {
   "impor": 4,
   "name": "서정진",
   "type": "lyricist"
  },
  {
   "impor": 4,
   "name": "Crom",
   "type": "lyricist"
  },
  {
   "impor": 4,
   "name": "디스코 파이터",
   "type": "lyricist"
  },
  {
   "impor": 3,
   "name": "김남희",
   "type": "lyricist"
  },
  {
   "impor": 3,
   "name": "김동완",
   "type": "lyricist"
  },
  {
   "impor": 3,
   "name": "문스톤",
   "type": "lyricist"
  },
  {
   "impor": 3,
   "name": "무",
   "type": "lyricist"
  },
  {
   "impor": 3,
   "name": "정성헌",
   "type": "lyricist"
  },
  {
   "impor": 3,
   "name": "김달우피터",
   "type": "lyricist"
  },
  {
   "impor": 3,
   "name": "김기범",
   "type": "lyricist"
  },
  {
   "impor": 3,
   "name": "이택승",
   "type": "lyricist"
  },
  {
   "impor": 3,
   "name": "김유민",
   "type": "lyricist"
  },
  {
   "impor": 3,
   "name": "우연석",
   "type": "lyricist"
  },
  {
   "impor": 3,
   "name": "Brian Joo",
   "type": "lyricist"
  },
  {
   "impor": 3,
   "name": "김형석",
   "type": "lyricist"
  },
  {
   "impor": 3,
   "name": "황성제",
   "type": "lyricist"
  },
  {
   "impor": 3,
   "name": "김이지",
   "type": "lyricist"
  },
  {
   "impor": 3,
   "name": "환희",
   "type": "lyricist"
  },
  {
   "impor": 3,
   "name": "홍재선",
   "type": "lyricist"
  },
  {
   "impor": 3,
   "name": "김세진",
   "type": "lyricist"
  },
  {
   "impor": 3,
   "name": "이효리",
   "type": "lyricist"
  },
  {
   "impor": 3,
   "name": "DAVINK (다빈크)",
   "type": "lyricist"
  },
  {
   "impor": 3,
   "name": "정한종",
   "type": "lyricist"
  },
  {
   "impor": 3,
   "name": "양현석",
   "type": "lyricist"
  },
  {
   "impor": 3,
   "name": "대니",
   "type": "lyricist"
  },
  {
   "impor": 3,
   "name": "이현규",
   "type": "lyricist"
  },
  {
   "impor": 3,
   "name": "민연재",
   "type": "lyricist"
  },
  {
   "impor": 3,
   "name": "김창환",
   "type": "lyricist"
  },
  {
   "impor": 3,
   "name": "최수정",
   "type": "lyricist"
  },
  {
   "impor": 3,
   "name": "Minuki",
   "type": "lyricist"
  },
  {
   "impor": 3,
   "name": "신지원",
   "type": "lyricist"
  },
  {
   "impor": 3,
   "name": "신준기",
   "type": "lyricist"
  },
  {
   "impor": 3,
   "name": "태훈",
   "type": "lyricist"
  },
  {
   "impor": 3,
   "name": "강원석",
   "type": "lyricist"
  },
  {
   "impor": 3,
   "name": "강욱진",
   "type": "lyricist"
  },
  {
   "impor": 3,
   "name": "강성훈",
   "type": "lyricist"
  },
  {
   "impor": 3,
   "name": "e.one",
   "type": "lyricist"
  },
  {
   "impor": 3,
   "name": "박정란",
   "type": "lyricist"
  },
  {
   "impor": 3,
   "name": "신연아",
   "type": "lyricist"
  },
  {
   "impor": 3,
   "name": "차상민",
   "type": "lyricist"
  },
  {
   "impor": 3,
   "name": "YOUNG H.KIM",
   "type": "lyricist"
  },
  {
   "impor": 3,
   "name": "이건우",
   "type": "lyricist"
  },
  {
   "impor": 3,
   "name": "Urban Cllasik",
   "type": "lyricist"
  },
  {
   "impor": 3,
   "name": "3534",
   "type": "lyricist"
  },
  {
   "impor": 3,
   "name": "윤우현",
   "type": "lyricist"
  },
  {
   "impor": 3,
   "name": "배화영",
   "type": "lyricist"
  },
  {
   "impor": 3,
   "name": "이우천",
   "type": "lyricist"
  },
  {
   "impor": 3,
   "name": "곽상엽",
   "type": "lyricist"
  },
  {
   "impor": 3,
   "name": "박건호",
   "type": "lyricist"
  },
  {
   "impor": 3,
   "name": "싸이 (PSY)",
   "type": "lyricist"
  },
  {
   "impor": 3,
   "name": "써니사이드 챙",
   "type": "lyricist"
  },
  {
   "impor": 3,
   "name": "윤경",
   "type": "lyricist"
  },
  {
   "impor": 3,
   "name": "박성수",
   "type": "lyricist"
  },
  {
   "impor": 3,
   "name": "Jay Kang",
   "type": "lyricist"
  },
  {
   "impor": 3,
   "name": "윤사라",
   "type": "lyricist"
  },
  {
   "impor": 0,

In [404]:
pd.DataFrame(json_prep_gen1['nodes']).head()

   impor name      type
0     69  김영아  lyricist
1     69  박진영  lyricist
2     54  유영진  lyricist
3     43  이승호  lyricist
4     40  유건형  lyricist

In [405]:
pd.DataFrame(json_prep_gen1['links']).head()

   source  target  value
0       0      31     68
1       1     123     40
2       2     124     26
3       3     125     24
4       4     126     23

In [406]:
filename_out = 'idol_lyricist_gen1.json'
json_out = open(filename_out,'w')
json_out.write(json_dump_gen1)
json_out.close()

In [407]:
# 명령 프롬프트 켜고, html 파일이 있는 폴더로 이동
# python -m http.server 입력
# http://localhost:8000/index.html 실행 후 확인

#### 2) lyricist_gen2 작업

In [408]:
# lyricist_gen1의 가수 목록 데이터프레임 생성
i = 0
a = 0
b = 0
lyricist = []
artist = []

lyricist.clear()
artist.clear()
    
for i in range(0, len(lyricist_gen2)):
    try:
        for a in range(0, len(preprocess(lyricist_gen2.lyricist[i], lyricist_gen2.artist[i])[0])):
            lyricist.append(str(preprocess(lyricist_gen2.lyricist[i], lyricist_gen2.artist[i])[0][a]))
        for b in range(0, len(preprocess(lyricist_gen2.lyricist[i], lyricist_gen2.artist[i])[1])):
            artist.append(str(preprocess(lyricist_gen2.lyricist[i], lyricist_gen2.artist[i])[1][b]))
    except:
        lyricist.append('')
        artist.append('')
    
preprocessing_gen2 = pd.DataFrame({"lyricist" : lyricist, "artist" : artist, "generation" : 2})

In [409]:
preprocessing_gen2.rename(columns={"lyricist":"source","artist":"target"}, inplace=True)

In [410]:
grouped_idol_gen2 = preprocessing_gen2.groupby(["source","target"]).size().reset_index()
grouped_idol_gen2.head(20) # 갑자기 빈 행이 존재함 ->삭제

      source      target  0
0          -         엠블랙  1
1        072  브라운 아이드 걸스  1
2     100%서정        에프엑스  2
3     100%서정         트랙스  1
4    17HOLIC         달샤벳  3
5    17HOLIC         씨리얼  1
6    17HOLIC         투피엠  1
7    17HOLIC          틴탑  1
8      1월 8일         샤이니  1
9      1월 8일        소녀시대  2
10     1월 8일  슈퍼 주니어-디앤이  1
11     1월 8일       슈퍼주니어  1
12     1월 8일         엔소닉  1
13  220 VOLT        마이네임  2
14     2Face        투에이엠  1
15     2LSON      애프터 스쿨  1
16    2Story         시크릿  1
17      4번타자         티아라  1
18        72         엔소닉  1
19      9999         씨스타  1

In [411]:
grouped_idol_gen2.loc[grouped_idol_gen2['source'] == "-"]

  source target  0
0      -    엠블랙  1

In [412]:
grouped_idol_gen2.drop(grouped_idol_gen2.index[[0]], inplace=True)
grouped_idol_gen2 = grouped_idol_gen2.reset_index()
grouped_idol_gen2 = grouped_idol_gen2.drop(['index'], axis = 1)

In [413]:
grouped_idol_gen2.loc[grouped_idol_gen2['source'] == "TEDDY"]

    source  target   0
662  TEDDY      빅뱅  17
663  TEDDY  지디 앤 탑   4
664  TEDDY    투애니원  19

In [414]:
grouped_idol_gen2['source'] = grouped_idol_gen2['source'].replace('TEDDY', '테디')

In [415]:
grouped_idol_gen2.loc[grouped_idol_gen2['source'] == "TEDDY"]

Empty DataFrame
Columns: [source, target, 0]
Index: []

In [416]:
# 칼럼 0 -> count로 이름 칼럼명 수정
grouped_idol_gen2.rename(columns={0:'count'}, inplace=True)
len(grouped_idol_gen2)

2395

In [417]:
grouped_idol_gen2_ranking = grouped_idol_gen2.sort_values(by='count', ascending=False)
grouped_idol_gen2_ranking = grouped_idol_gen2_ranking.reset_index(drop=True)
grouped_idol_gen2_ranking.head()

         source    target  count
0      G-DRAGON        빅뱅     63
1            바로     비원에이포     54
2  정용화 (CNBLUE)      씨엔블루     49
3           한성호  에프티 아일랜드     45
4           용준형       비스트     42

In [418]:
len(grouped_idol_gen2_ranking)

2395

In [419]:
# unique한 source
generate_node_gen2 = grouped_idol_gen2_ranking.groupby(['source', 'count']).size().reset_index()
# generate_node.rename(columns={0:'count'}, inplace=True)
generate_node_gen2 = generate_node_gen2.sort_values(by='count', ascending=False)
generate_node_gen2 = generate_node_gen2.reset_index(drop=True)
generate_node_gen2 = generate_node_gen2.drop([0], axis = 1)
len(generate_node_gen2)

1851

In [420]:
generate_node_gen2

                 source  count
0              G-DRAGON     63
1                    바로     54
2          정용화 (CNBLUE)     49
3                   한성호     45
4                   용준형     42
5                   송수윤     36
6                    진영     36
7             지코 (ZICO)     32
8                    미료     31
9          이홍기 (FT아일랜드)     30
10                  송수윤     30
11                  송수윤     27
12               용감한 형제     27
13                  김이나     25
14                  한성호     25
15         이재진 (FT아일랜드)     20
16                  유영진     20
17                  박진영     19
18                   테디     19
19                  한재호     18
20                T.O.P     18
21                   테디     17
22                  방시혁     17
23         차쿤 (일렉트로보이즈)     17
24                  김승수     16
25                  송수윤     16
26             박경 (블락비)     16
27                  강지원     16
28            심스 ($IM$)     15
29                  김태주     15
...                 ...    ...
1821       real-fantasy      1
1822               pH-1      1
1823           luvssong      1
1824             kenzie      1
1825             indi K      1
1826              e.one      1
1827                강정훈      1
1828                강준우      1
1829                강지원      1
1830        강타 (KANGTA)      1
1831                권정열      1
1832                권윤정      1
1833       권순일 (어반 자카파)      1
1834                권순관      1
1835                권선익      1
1836                권기명      1
1837           구하라 (카라)      1
1838                구태우      1
1839                구지안      1
1840                구슬윤      1
1841                곽영준      1
1842                곽소영      1
1843                공현식      1
1844                공보경      1
1845               골드피그      1
1846                고기태      1
1847  경진희 (Jam Factory)      1
1848         경리 (나인뮤지스)      1
1849                 개미      1
1850                 동우      1

[1851 rows x 2 columns]

In [421]:
# unique해지려면 총
generate_node2_gen2 = generate_node_gen2.groupby(['source']).sum()
generate_node2_gen2 = generate_node2_gen2.sort_values(by='count', ascending=False)
len(generate_node2_gen2) == len(generate_node_gen2.source.unique()) == len(grouped_idol_gen2_ranking['source'].unique())

True

In [422]:
grouped_idol2_gen2 = grouped_idol_gen2_ranking[grouped_idol_gen2_ranking['count'] > 5]
generate_node_gen2 = generate_node2_gen2[generate_node2_gen2['count']>5]

In [423]:
grouped_idol2_gen2 = grouped_idol2_gen2.reset_index()
generate_node_gen2 = generate_node_gen2.reset_index()

In [424]:
grouped_idol2_gen2 = grouped_idol2_gen2.drop(['index'], axis = 1)

In [425]:
grouped_idol2_gen2.head(10)

         source      target  count
0      G-DRAGON          빅뱅     63
1            바로       비원에이포     54
2  정용화 (CNBLUE)        씨엔블루     49
3           한성호    에프티 아일랜드     45
4           용준형         비스트     42
5           송수윤       보이프렌드     36
6            진영       비원에이포     36
7     지코 (ZICO)         블락비     32
8            미료  브라운 아이드 걸스     31
9  이홍기 (FT아일랜드)    에프티 아일랜드     30

In [426]:
generate_node_gen2.head(10)

         source  count
0           송수윤    122
1           한성호     71
2      G-DRAGON     70
3        용감한 형제     63
4            바로     54
5            테디     49
6  정용화 (CNBLUE)     49
7           박진영     45
8           김이나     44
9           용준형     43

In [427]:
unique_idol_gen2_all = pd.Index(grouped_idol2_gen2['source']
                      .append(grouped_idol2_gen2['target'])
                      .reset_index(drop=True).unique())
unique_idol_gen2_lyricist = pd.Index(grouped_idol2_gen2['source']
                      .reset_index(drop=True).unique())
unique_idol_gen2_artist = pd.Index(grouped_idol2_gen2['target']
                      .reset_index(drop=True).unique())

In [428]:
len(unique_idol_gen2_all)

155

In [429]:
len(unique_idol_gen2_lyricist)+len(unique_idol_gen2_artist)

155

In [430]:
group_dict_gen2_lyricist = {}
group_dict_gen2_lyricist.clear()
counter = 0
for idol in unique_idol_gen2_lyricist:
    if idol not in group_dict_gen2_lyricist:
        counter += 1
        group_dict_gen2_lyricist[idol] = counter
    else:
        pass
group_dict_gen2_lyricist

{'G-DRAGON': 1,
 '바로': 2,
 '정용화 (CNBLUE)': 3,
 '한성호': 4,
 '용준형': 5,
 '송수윤': 6,
 '진영': 7,
 '지코 (ZICO)': 8,
 '미료': 9,
 '이홍기 (FT아일랜드)': 10,
 '용감한 형제': 11,
 '김이나': 12,
 '이재진 (FT아일랜드)': 13,
 '유영진': 14,
 '박진영': 15,
 '테디': 16,
 '한재호': 17,
 'T.O.P': 18,
 '차쿤 (일렉트로보이즈)': 19,
 '방시혁': 20,
 '강지원': 21,
 '박경 (블락비)': 22,
 '김승수': 23,
 '김태주': 24,
 '직 재스퍼 (Zick Jasper)': 25,
 '심스 ($IM$)': 26,
 'C.A.P': 27,
 '강남': 28,
 '은혁 (EUNHYUK)': 29,
 '이희승': 30,
 '최종훈 (FT아일랜드)': 31,
 '마부스 (Maboos)': 32,
 '신우': 33,
 '미르 (MBLAQ)': 34,
 '종현 (JONGHYUN)': 35,
 'kenzie': 36,
 '김기범': 37,
 '동해 (DONGHAE)': 38,
 '신사동 호랭이': 39,
 '이단옆차기': 40,
 '미성': 41,
 '최갑원': 42,
 '원택 (1Take)': 43,
 'M.I.B': 44,
 '박초롱 (에이핑크)': 45,
 '조윤경': 46,
 '최규성': 47,
 '김정배': 48,
 '김재중': 49,
 'Good Life': 50,
 '이종현 (CNBLUE)': 51,
 '우리형과 내동생': 52,
 '안영민': 53,
 '이트라이브': 54,
 '유빈 (Yubin)': 55,
 '민연재': 56,
 'SWIN': 57,
 '핫펠트 (예은)': 58,
 '찬성': 59,
 'BEOMxNANG': 60,
 'L.Joe': 61,
 '로빈': 62,
 '라도': 63,
 '택연': 64,
 '민호 (MINHO)': 65,
 '정하나': 66,
 '수빈': 67,
 '마르코': 68,
 '남기상': 69,
 'Team One Sound': 70,
 'Cream (M.I.B)': 71,
 '슈퍼창따이': 72,
 '최강창민 (MAX)': 73,
 'Cream': 74,
 '창조': 75,
 'Misfit': 76,
 '임상혁': 77,
 'e.one': 78,
 '홍지상': 79,
 '원태연': 80,
 'Urban Cllasik': 81,
 '블랙아이드 필승': 82,
 '지오 (G.O)': 83,
 '박수석': 84,
 '김영아': 85,
 '준Q': 86,
 '이기광': 87,
 '이기 (오레오)': 88,
 '광민 (보이프렌드)': 89,
 '천둥': 90,
 '이병준': 91,
 'AJ': 92,
 '원펀치': 93,
 '민우 (보이프렌드)': 94,
 '김부민': 95,
 '김영후': 96,
 '키 (KEY)': 97,
 '별들의 전쟁': 98,
 '태완 (Taewan)': 99,
 '준케이 (JUN. K)': 100,
 'Ryan S. Jhun': 101,
 '전간디': 102,
 'NODAY': 103,
 'CL': 104,
 '낯선': 105,
 '정창욱': 106,
 '인우': 107,
 '신재훈': 108,
 '조영수': 109,
 'Dok2': 110}

In [431]:
group_dict_gen2_artist = {}
group_dict_gen2_artist.clear()
counter = 110
for idol in unique_idol_gen2_artist:
    if idol not in group_dict_gen2_artist:
        counter += 1
        group_dict_gen2_artist[idol] = counter
    else:
        pass
group_dict_gen2_artist

{'빅뱅': 111,
 '비원에이포': 112,
 '씨엔블루': 113,
 '에프티 아일랜드': 114,
 '비스트': 115,
 '보이프렌드': 116,
 '블락비': 117,
 '브라운 아이드 걸스': 118,
 '인피니트': 119,
 '틴탑': 120,
 '카라': 121,
 '동방신기': 122,
 '원더걸스': 123,
 '투애니원': 124,
 '투에이엠': 125,
 '시크릿': 126,
 '나인뮤지스': 127,
 '엠아이비': 128,
 '슈퍼주니어': 129,
 '투피엠': 130,
 '엠블랙': 131,
 '샤이니': 132,
 '티아라': 133,
 '씨스타': 134,
 '써니힐': 135,
 '씨리얼': 136,
 '브레이브걸스': 137,
 '에이핑크': 138,
 '에프엑스': 139,
 '소녀시대': 140,
 '제이와이제이': 141,
 '걸스데이': 142,
 '유키스': 143,
 '달샤벳': 144,
 '슈퍼 주니어-디앤이': 145,
 '애프터 스쿨': 146,
 '포미닛': 147,
 '제국의 아이들': 148,
 '파란': 149,
 '컬러링 베이비 7공주': 150,
 '마이네임': 151,
 '오렌지캬라멜': 152,
 '더블에스오공일': 153,
 '엔소닉': 154,
 '지디 앤 탑': 155}

In [432]:
temp_links_list_gen2 = []
temp_links_list_gen2 = list(grouped_idol2_gen2.apply(lambda row: {"source": row['source'], "target": row['target'], "value": row['count']}, axis=1))

In [433]:
temp_links_list_gen2

[{'source': 'G-DRAGON', 'target': '빅뱅', 'value': 63},
 {'source': '바로', 'target': '비원에이포', 'value': 54},
 {'source': '정용화 (CNBLUE)', 'target': '씨엔블루', 'value': 49},
 {'source': '한성호', 'target': '에프티 아일랜드', 'value': 45},
 {'source': '용준형', 'target': '비스트', 'value': 42},
 {'source': '송수윤', 'target': '보이프렌드', 'value': 36},
 {'source': '진영', 'target': '비원에이포', 'value': 36},
 {'source': '지코 (ZICO)', 'target': '블락비', 'value': 32},
 {'source': '미료', 'target': '브라운 아이드 걸스', 'value': 31},
 {'source': '이홍기 (FT아일랜드)', 'target': '에프티 아일랜드', 'value': 30},
 {'source': '송수윤', 'target': '인피니트', 'value': 30},
 {'source': '용감한 형제', 'target': '틴탑', 'value': 27},
 {'source': '송수윤', 'target': '카라', 'value': 27},
 {'source': '한성호', 'target': '씨엔블루', 'value': 25},
 {'source': '김이나', 'target': '브라운 아이드 걸스', 'value': 25},
 {'source': '이재진 (FT아일랜드)', 'target': '에프티 아일랜드', 'value': 20},
 {'source': '유영진', 'target': '동방신기', 'value': 20},
 {'source': '박진영', 'target': '원더걸스', 'value': 19},
 {'source': '테디', 'target': '투애니원', 'value': 19},
 {'source': '한재호', 'target': '카라', 'value': 18},
 {'source': 'T.O.P', 'target': '빅뱅', 'value': 18},
 {'source': '차쿤 (일렉트로보이즈)', 'target': '틴탑', 'value': 17},
 {'source': '테디', 'target': '빅뱅', 'value': 17},
 {'source': '방시혁', 'target': '투에이엠', 'value': 17},
 {'source': '강지원', 'target': '시크릿', 'value': 16},
 {'source': '박경 (블락비)', 'target': '블락비', 'value': 16},
 {'source': '송수윤', 'target': '나인뮤지스', 'value': 16},
 {'source': '김승수', 'target': '카라', 'value': 16},
 {'source': '김태주', 'target': '비스트', 'value': 15},
 {'source': '직 재스퍼 (Zick Jasper)', 'target': '엠아이비', 'value': 15},
 {'source': '심스 ($IM$)', 'target': '엠아이비', 'value': 15},
 {'source': 'C.A.P', 'target': '틴탑', 'value': 14},
 {'source': '강남', 'target': '엠아이비', 'value': 14},
 {'source': '은혁 (EUNHYUK)', 'target': '슈퍼주니어', 'value': 14},
 {'source': '박진영', 'target': '투피엠', 'value': 14},
 {'source': '이희승', 'target': '에프티 아일랜드', 'value': 14},
 {'source': '최종훈 (FT아일랜드)', 'target': '에프티 아일랜드', 'value': 14},
 {'source': '마부스 (Maboos)', 'target': '틴탑', 'value': 14},
 {'source': '신우', 'target': '비원에이포', 'value': 13},
 {'source': '미르 (MBLAQ)', 'target': '엠블랙', 'value': 13},
 {'source': '종현 (JONGHYUN)', 'target': '샤이니', 'value': 13},
 {'source': '한재호', 'target': '인피니트', 'value': 13},
 {'source': 'kenzie', 'target': '샤이니', 'value': 13},
 {'source': '김기범', 'target': '시크릿', 'value': 13},
 {'source': '김승수', 'target': '인피니트', 'value': 13},
 {'source': '동해 (DONGHAE)', 'target': '슈퍼주니어', 'value': 12},
 {'source': '신사동 호랭이', 'target': '티아라', 'value': 12},
 {'source': '신사동 호랭이', 'target': '비스트', 'value': 12},
 {'source': '유영진', 'target': '슈퍼주니어', 'value': 12},
 {'source': '이단옆차기', 'target': '씨스타', 'value': 12},
 {'source': '미성', 'target': '써니힐', 'value': 12},
 {'source': '최갑원', 'target': '씨리얼', 'value': 11},
 {'source': '용감한 형제', 'target': '브레이브걸스', 'value': 11},
 {'source': '원택 (1Take)', 'target': '엠블랙', 'value': 11},
 {'source': 'M.I.B', 'target': '엠아이비', 'value': 11},
 {'source': '박초롱 (에이핑크)', 'target': '에이핑크', 'value': 11},
 {'source': '조윤경', 'target': '샤이니', 'value': 11},
 {'source': 'kenzie', 'target': '에프엑스', 'value': 11},
 {'source': '조윤경', 'target': '소녀시대', 'value': 11},
 {'source': '최규성', 'target': '비스트', 'value': 11},
 {'source': '용감한 형제', 'target': '씨스타', 'value': 11},
 {'source': '조윤경', 'target': '슈퍼주니어', 'value': 10},
 {'source': '최규성', 'target': '티아라', 'value': 10},
 {'source': '김정배', 'target': '슈퍼주니어', 'value': 10},
 {'source': '김재중', 'target': '제이와이제이', 'value': 10},
 {'source': '이단옆차기', 'target': '걸스데이', 'value': 10},
 {'source': 'Good Life', 'target': '비스트', 'value': 10},
 {'source': '용감한 형제', 'target': '유키스', 'value': 10},
 {'source': '이종현 (CNBLUE)', 'target': '씨엔블루', 'value': 10},
 {'source': '우리형과 내동생', 'target': '비원에이포', 'value': 10},
 {'source': '안영민', 'target': '티아라', 'value': 10},
 {'source': '김이나', 'target': '써니힐', 'value': 9},
 {'source': '이트라이브', 'target': '달샤벳', 'value': 9},
 {'source': '유빈 (Yubin)', 'target': '원더걸스', 'value': 9},
 {'source': '민연재', 'target': '보이프렌드', 'value': 9},
 {'source': 'SWIN', 'target': '유키스', 'value': 9},
 {'source': '핫펠트 (예은)', 'target': '원더걸스', 'value': 9},
 {'source': '찬성', 'target': '투피엠', 'value': 9},
 {'source': 'BEOMxNANG', 'target': '에이핑크', 'value': 9},
 {'source': 'L.Joe', 'target': '틴탑', 'value': 9},
 {'source': '로빈', 'target': '씨스타', 'value': 9},
 {'source': '동해 (DONGHAE)', 'target': '슈퍼 주니어-디앤이', 'value': 8},
 {'source': '신사동 호랭이', 'target': '에이핑크', 'value': 8},
 {'source': '용감한 형제', 'target': '애프터 스쿨', 'value': 8},
 {'source': '신사동 호랭이', 'target': '포미닛', 'value': 8},
 {'source': '라도', 'target': '엠블랙', 'value': 8},
 {'source': '택연', 'target': '투피엠', 'value': 8},
 {'source': 'kenzie', 'target': '슈퍼주니어', 'value': 8},
 {'source': '민호 (MINHO)', 'target': '샤이니', 'value': 8},
 {'source': '정하나', 'target': '시크릿', 'value': 8},
 {'source': '수빈', 'target': '달샤벳', 'value': 8},
 {'source': '마르코', 'target': '시크릿', 'value': 8},
 {'source': '남기상', 'target': '걸스데이', 'value': 8},
 {'source': 'Team One Sound', 'target': '슈퍼주니어', 'value': 8},
 {'source': 'Cream (M.I.B)', 'target': '엠아이비', 'value': 8},
 {'source': '라도', 'target': '비스트', 'value': 7},
 {'source': '슈퍼창따이', 'target': '투피엠', 'value': 7},
 {'source': '최강창민 (MAX)', 'target': '동방신기', 'value': 7},
 {'source': 'Cream', 'target': '엠아이비', 'value': 7},
 {'source': '창조', 'target': '틴탑', 'value': 7},
 {'source': 'Misfit', 'target': '에프엑스', 'value': 7},
 {'source': '임상혁', 'target': '포미닛', 'value': 7},
 {'source': 'e.one', 'target': '제국의 아이들', 'value': 7},
 {'source': '유영진', 'target': '샤이니', 'value': 7},
 {'source': '홍지상', 'target': '원더걸스', 'value': 7},
 {'source': '원태연', 'target': '파란', 'value': 7},
 {'source': '홍지상', 'target': '투피엠', 'value': 7},
 {'source': '김정배', 'target': '소녀시대', 'value': 7},
 {'source': 'Urban Cllasik', 'target': '제국의 아이들', 'value': 7},
 {'source': '블랙아이드 필승', 'target': '틴탑', 'value': 6},
 {'source': '지오 (G.O)', 'target': '엠블랙', 'value': 6},
 {'source': '박수석', 'target': '시크릿', 'value': 6},
 {'source': '김영아', 'target': '컬러링 베이비 7공주', 'value': 6},
 {'source': '준Q', 'target': '마이네임', 'value': 6},
 {'source': 'kenzie', 'target': '동방신기', 'value': 6},
 {'source': 'kenzie', 'target': '소녀시대', 'value': 6},
 {'source': '이기광', 'target': '비스트', 'value': 6},
 {'source': '이기 (오레오)', 'target': '오렌지캬라멜', 'value': 6},
 {'source': '박진영', 'target': '투에이엠', 'value': 6},
 {'source': '광민 (보이프렌드)', 'target': '보이프렌드', 'value': 6},
 {'source': '천둥', 'target': '엠블랙', 'value': 6},
 {'source': '이병준', 'target': '더블에스오공일', 'value': 6},
 {'source': 'AJ', 'target': '유키스', 'value': 6},
 {'source': '민연재', 'target': '달샤벳', 'value': 6},
 {'source': '원펀치', 'target': '엔소닉', 'value': 6},
 {'source': '민우 (보이프렌드)', 'target': '보이프렌드', 'value': 6},
 {'source': '김부민', 'target': '샤이니', 'value': 6},
 {'source': '김영후', 'target': '샤이니', 'value': 6},
 {'source': '키 (KEY)', 'target': '샤이니', 'value': 6},
 {'source': 'G-DRAGON', 'target': '지디 앤 탑', 'value': 6},
 {'source': '별들의 전쟁', 'target': '씨스타', 'value': 6},
 {'source': '태완 (Taewan)', 'target': '엠블랙', 'value': 6},
 {'source': '김영아', 'target': '브라운 아이드 걸스', 'value': 6},
 {'source': '마부스 (Maboos)', 'target': '브레이브걸스', 'value': 6},
 {'source': '준케이 (JUN. K)', 'target': '투피엠', 'value': 6},
 {'source': '이희승', 'target': '씨엔블루', 'value': 6},
 {'source': 'Ryan S. Jhun', 'target': '유키스', 'value': 6},
 {'source': '전간디', 'target': '샤이니', 'value': 6},
 {'source': '테디', 'target': '투애니원', 'value': 6},
 {'source': 'NODAY', 'target': '비스트', 'value': 6},
 {'source': 'CL', 'target': '투애니원', 'value': 6},
 {'source': '낯선', 'target': '제국의 아이들', 'value': 6},
 {'source': '정창욱', 'target': '나인뮤지스', 'value': 6},
 {'source': '인우', 'target': '시크릿', 'value': 6},
 {'source': '한재호', 'target': '더블에스오공일', 'value': 6},
 {'source': '신재훈', 'target': '엠아이비', 'value': 6},
 {'source': '조영수', 'target': '티아라', 'value': 6},
 {'source': 'Dok2', 'target': '엠블랙', 'value': 6},
 {'source': 'Team One Sound', 'target': '슈퍼 주니어-디앤이', 'value': 6},
 {'source': '조윤경', 'target': '에프엑스', 'value': 6}]

In [434]:
# 링크 생성하기
links_list_gen2 = []
for link in temp_links_list_gen2:
    record = {"value":link['value'], "source":unique_idol_gen2_all.get_loc(link['source']),
     "target": unique_idol_gen2_all.get_loc(link['target'])}
    links_list_gen2.append(record)

In [435]:
# 노드 생성하기
nodes_list_gen2= []
nodes_list_gen2.clear()
for index,row in generate_node_gen2.iterrows():
    nodes_list_gen2.append({ "name":row['source'], "type":"lyricist", "impor":row['count']})
for idol in group_dict_gen2_artist:
    nodes_list_gen2.append({"name":idol, "type":"artist", "impor":0})

In [436]:
links_list_gen2[:5]

[{'value': 63, 'source': 0, 'target': 110},
 {'value': 54, 'source': 1, 'target': 111},
 {'value': 49, 'source': 2, 'target': 112},
 {'value': 45, 'source': 3, 'target': 113},
 {'value': 42, 'source': 4, 'target': 114}]

In [437]:
nodes_list_gen2[:5]

[{'name': '송수윤', 'type': 'lyricist', 'impor': 122},
 {'name': '한성호', 'type': 'lyricist', 'impor': 71},
 {'name': 'G-DRAGON', 'type': 'lyricist', 'impor': 70},
 {'name': '용감한 형제', 'type': 'lyricist', 'impor': 63},
 {'name': '바로', 'type': 'lyricist', 'impor': 54}]

In [438]:
json_prep_gen2 = {"links":links_list_gen2, "nodes":nodes_list_gen2}
json_prep_gen2.keys()

dict_keys(['links', 'nodes'])

In [439]:
json_dump_gen2 = json.dumps(json_prep_gen2, indent=1, sort_keys=True, ensure_ascii=False)
print(json_dump_gen2)

{
 "links": [
  {
   "source": 0,
   "target": 110,
   "value": 63
  },
  {
   "source": 1,
   "target": 111,
   "value": 54
  },
  {
   "source": 2,
   "target": 112,
   "value": 49
  },
  {
   "source": 3,
   "target": 113,
   "value": 45
  },
  {
   "source": 4,
   "target": 114,
   "value": 42
  },
  {
   "source": 5,
   "target": 115,
   "value": 36
  },
  {
   "source": 6,
   "target": 111,
   "value": 36
  },
  {
   "source": 7,
   "target": 116,
   "value": 32
  },
  {
   "source": 8,
   "target": 117,
   "value": 31
  },
  {
   "source": 9,
   "target": 113,
   "value": 30
  },
  {
   "source": 5,
   "target": 118,
   "value": 30
  },
  {
   "source": 10,
   "target": 119,
   "value": 27
  },
  {
   "source": 5,
   "target": 120,
   "value": 27
  },
  {
   "source": 3,
   "target": 112,
   "value": 25
  },
  {
   "source": 11,
   "target": 117,
   "value": 25
  },
  {
   "source": 12,
   "target": 113,
   "value": 20
  },
  {
   "source": 13,
   "target": 121,
   "value": 20
  },
  {
   "source": 14,
   "target": 122,
   "value": 19
  },
  {
   "source": 15,
   "target": 123,
   "value": 19
  },
  {
   "source": 16,
   "target": 120,
   "value": 18
  },
  {
   "source": 17,
   "target": 110,
   "value": 18
  },
  {
   "source": 18,
   "target": 119,
   "value": 17
  },
  {
   "source": 15,
   "target": 110,
   "value": 17
  },
  {
   "source": 19,
   "target": 124,
   "value": 17
  },
  {
   "source": 20,
   "target": 125,
   "value": 16
  },
  {
   "source": 21,
   "target": 116,
   "value": 16
  },
  {
   "source": 5,
   "target": 126,
   "value": 16
  },
  {
   "source": 22,
   "target": 120,
   "value": 16
  },
  {
   "source": 23,
   "target": 114,
   "value": 15
  },
  {
   "source": 24,
   "target": 127,
   "value": 15
  },
  {
   "source": 25,
   "target": 127,
   "value": 15
  },
  {
   "source": 26,
   "target": 119,
   "value": 14
  },
  {
   "source": 27,
   "target": 127,
   "value": 14
  },
  {
   "source": 28,
   "target": 128,
   "value": 14
  },
  {
   "source": 14,
   "target": 129,
   "value": 14
  },
  {
   "source": 29,
   "target": 113,
   "value": 14
  },
  {
   "source": 30,
   "target": 113,
   "value": 14
  },
  {
   "source": 31,
   "target": 119,
   "value": 14
  },
  {
   "source": 32,
   "target": 111,
   "value": 13
  },
  {
   "source": 33,
   "target": 130,
   "value": 13
  },
  {
   "source": 34,
   "target": 131,
   "value": 13
  },
  {
   "source": 16,
   "target": 118,
   "value": 13
  },
  {
   "source": 35,
   "target": 131,
   "value": 13
  },
  {
   "source": 36,
   "target": 125,
   "value": 13
  },
  {
   "source": 22,
   "target": 118,
   "value": 13
  },
  {
   "source": 37,
   "target": 128,
   "value": 12
  },
  {
   "source": 38,
   "target": 132,
   "value": 12
  },
  {
   "source": 38,
   "target": 114,
   "value": 12
  },
  {
   "source": 13,
   "target": 128,
   "value": 12
  },
  {
   "source": 39,
   "target": 133,
   "value": 12
  },
  {
   "source": 40,
   "target": 134,
   "value": 12
  },
  {
   "source": 41,
   "target": 135,
   "value": 11
  },
  {
   "source": 10,
   "target": 136,
   "value": 11
  },
  {
   "source": 42,
   "target": 130,
   "value": 11
  },
  {
   "source": 43,
   "target": 127,
   "value": 11
  },
  {
   "source": 44,
   "target": 137,
   "value": 11
  },
  {
   "source": 45,
   "target": 131,
   "value": 11
  },
  {
   "source": 35,
   "target": 138,
   "value": 11
  },
  {
   "source": 45,
   "target": 139,
   "value": 11
  },
  {
   "source": 46,
   "target": 114,
   "value": 11
  },
  {
   "source": 10,
   "target": 133,
   "value": 11
  },
  {
   "source": 45,
   "target": 128,
   "value": 10
  },
  {
   "source": 46,
   "target": 132,
   "value": 10
  },
  {
   "source": 47,
   "target": 128,
   "value": 10
  },
  {
   "source": 48,
   "target": 140,
   "value": 10
  },
  {
   "source": 39,
   "target": 141,
   "value": 10
  },
  {
   "source": 49,
   "target": 114,
   "value": 10
  },
  {
   "source": 10,
   "target": 142,
   "value": 10
  },
  {
   "source": 50,
   "target": 112,
   "value": 10
  },
  {
   "source": 51,
   "target": 111,
   "value": 10
  },
  {
   "source": 52,
   "target": 132,
   "value": 10
  },
  {
   "source": 11,
   "target": 134,
   "value": 9
  },
  {
   "source": 53,
   "target": 143,
   "value": 9
  },
  {
   "source": 54,
   "target": 122,
   "value": 9
  },
  {
   "source": 55,
   "target": 115,
   "value": 9
  },
  {
   "source": 56,
   "target": 142,
   "value": 9
  },
  {
   "source": 57,
   "target": 122,
   "value": 9
  },
  {
   "source": 58,
   "target": 129,
   "value": 9
  },
  {
   "source": 59,
   "target": 137,
   "value": 9
  },
  {
   "source": 60,
   "target": 119,
   "value": 9
  },
  {
   "source": 61,
   "target": 133,
   "value": 9
  },
  {
   "source": 37,
   "target": 144,
   "value": 8
  },
  {
   "source": 38,
   "target": 137,
   "value": 8
  },
  {
   "source": 10,
   "target": 145,
   "value": 8
  },
  {
   "source": 38,
   "target": 146,
   "value": 8
  },
  {
   "source": 62,
   "target": 130,
   "value": 8
  },
  {
   "source": 63,
   "target": 129,
   "value": 8
  },
  {
   "source": 35,
   "target": 128,
   "value": 8
  },
  {
   "source": 64,
   "target": 131,
   "value": 8
  },
  {
   "source": 65,
   "target": 125,
   "value": 8
  },
  {
   "source": 66,
   "target": 143,
   "value": 8
  },
  {
   "source": 67,
   "target": 125,
   "value": 8
  },
  {
   "source": 68,
   "target": 141,
   "value": 8
  },
  {
   "source": 69,
   "target": 128,
   "value": 8
  },
  {
   "source": 70,
   "target": 127,
   "value": 8
  },
  {
   "source": 62,
   "target": 114,
   "value": 7
  },
  {
   "source": 71,
   "target": 129,
   "value": 7
  },
  {
   "source": 72,
   "target": 121,
   "value": 7
  },
  {
   "source": 73,
   "target": 127,
   "value": 7
  },
  {
   "source": 74,
   "target": 119,
   "value": 7
  },
  {
   "source": 75,
   "target": 138,
   "value": 7
  },
  {
   "source": 76,
   "target": 146,
   "value": 7
  },
  {
   "source": 77,
   "target": 147,
   "value": 7
  },
  {
   "source": 13,
   "target": 131,
   "value": 7
  },
  {
   "source": 78,
   "target": 122,
   "value": 7
  },
  {
   "source": 79,
   "target": 148,
   "value": 7
  },
  {
   "source": 78,
   "target": 129,
   "value": 7
  },
  {
   "source": 47,
   "target": 139,
   "value": 7
  },
  {
   "source": 80,
   "target": 147,
   "value": 7
  },
  {
   "source": 81,
   "target": 119,
   "value": 6
  },
  {
   "source": 82,
   "target": 130,
   "value": 6
  },
  {
   "source": 83,
   "target": 125,
   "value": 6
  },
  {
   "source": 84,
   "target": 149,
   "value": 6
  },
  {
   "source": 85,
   "target": 150,
   "value": 6
  },
  {
   "source": 35,
   "target": 121,
   "value": 6
  },
  {
   "source": 35,
   "target": 139,
   "value": 6
  },
  {
   "source": 86,
   "target": 114,
   "value": 6
  },
  {
   "source": 87,
   "target": 151,
   "value": 6
  },
  {
   "source": 14,
   "target": 124,
   "value": 6
  },
  {
   "source": 88,
   "target": 115,
   "value": 6
  },
  {
   "source": 89,
   "target": 130,
   "value": 6
  },
  {
   "source": 90,
   "target": 152,
   "value": 6
  },
  {
   "source": 91,
   "target": 142,
   "value": 6
  },
  {
   "source": 55,
   "target": 143,
   "value": 6
  },
  {
   "source": 92,
   "target": 153,
   "value": 6
  },
  {
   "source": 93,
   "target": 115,
   "value": 6
  },
  {
   "source": 94,
   "target": 131,
   "value": 6
  },
  {
   "source": 95,
   "target": 131,
   "value": 6
  },
  {
   "source": 96,
   "target": 131,
   "value": 6
  },
  {
   "source": 0,
   "target": 154,
   "value": 6
  },
  {
   "source": 97,
   "target": 133,
   "value": 6
  },
  {
   "source": 98,
   "target": 130,
   "value": 6
  },
  {
   "source": 84,
   "target": 117,
   "value": 6
  },
  {
   "source": 31,
   "target": 136,
   "value": 6
  },
  {
   "source": 99,
   "target": 129,
   "value": 6
  },
  {
   "source": 29,
   "target": 112,
   "value": 6
  },
  {
   "source": 100,
   "target": 142,
   "value": 6
  },
  {
   "source": 101,
   "target": 131,
   "value": 6
  },
  {
   "source": 15,
   "target": 123,
   "value": 6
  },
  {
   "source": 102,
   "target": 114,
   "value": 6
  },
  {
   "source": 103,
   "target": 123,
   "value": 6
  },
  {
   "source": 104,
   "target": 147,
   "value": 6
  },
  {
   "source": 105,
   "target": 126,
   "value": 6
  },
  {
   "source": 106,
   "target": 125,
   "value": 6
  },
  {
   "source": 16,
   "target": 152,
   "value": 6
  },
  {
   "source": 107,
   "target": 127,
   "value": 6
  },
  {
   "source": 108,
   "target": 132,
   "value": 6
  },
  {
   "source": 109,
   "target": 130,
   "value": 6
  },
  {
   "source": 69,
   "target": 144,
   "value": 6
  },
  {
   "source": 45,
   "target": 138,
   "value": 6
  }
 ],
 "nodes": [
  {
   "impor": 122,
   "name": "송수윤",
   "type": "lyricist"
  },
  {
   "impor": 71,
   "name": "한성호",
   "type": "lyricist"
  },
  {
   "impor": 70,
   "name": "G-DRAGON",
   "type": "lyricist"
  },
  {
   "impor": 63,
   "name": "용감한 형제",
   "type": "lyricist"
  },
  {
   "impor": 54,
   "name": "바로",
   "type": "lyricist"
  },
  {
   "impor": 49,
   "name": "테디",
   "type": "lyricist"
  },
  {
   "impor": 49,
   "name": "정용화 (CNBLUE)",
   "type": "lyricist"
  },
  {
   "impor": 45,
   "name": "박진영",
   "type": "lyricist"
  },
  {
   "impor": 44,
   "name": "김이나",
   "type": "lyricist"
  },
  {
   "impor": 43,
   "name": "용준형",
   "type": "lyricist"
  },
  {
   "impor": 43,
   "name": "유영진",
   "type": "lyricist"
  },
  {
   "impor": 41,
   "name": "한재호",
   "type": "lyricist"
  },
  {
   "impor": 39,
   "name": "kenzie",
   "type": "lyricist"
  },
  {
   "impor": 37,
   "name": "이단옆차기",
   "type": "lyricist"
  },
  {
   "impor": 36,
   "name": "진영",
   "type": "lyricist"
  },
  {
   "impor": 34,
   "name": "조윤경",
   "type": "lyricist"
  },
  {
   "impor": 33,
   "name": "지코 (ZICO)",
   "type": "lyricist"
  },
  {
   "impor": 33,
   "name": "김승수",
   "type": "lyricist"
  },
  {
   "impor": 31,
   "name": "미료",
   "type": "lyricist"
  },
  {
   "impor": 30,
   "name": "마부스 (Maboos)",
   "type": "lyricist"
  },
  {
   "impor": 30,
   "name": "이홍기 (FT아일랜드)",
   "type": "lyricist"
  },
  {
   "impor": 27,
   "name": "최규성",
   "type": "lyricist"
  },
  {
   "impor": 25,
   "name": "김정배",
   "type": "lyricist"
  },
  {
   "impor": 25,
   "name": "차쿤 (일렉트로보이즈)",
   "type": "lyricist"
  },
  {
   "impor": 23,
   "name": "T.O.P",
   "type": "lyricist"
  },
  {
   "impor": 23,
   "name": "민연재",
   "type": "lyricist"
  },
  {
   "impor": 23,
   "name": "라도",
   "type": "lyricist"
  },
  {
   "impor": 23,
   "name": "신사동 호랭이",
   "type": "lyricist"
  },
  {
   "impor": 21,
   "name": "이희승",
   "type": "lyricist"
  },
  {
   "impor": 20,
   "name": "이재진 (FT아일랜드)",
   "type": "lyricist"
  },
  {
   "impor": 20,
   "name": "동해 (DONGHAE)",
   "type": "lyricist"
  },
  {
   "impor": 20,
   "name": "안영민",
   "type": "lyricist"
  },
  {
   "impor": 19,
   "name": "강지원",
   "type": "lyricist"
  },
  {
   "impor": 19,
   "name": "김기범",
   "type": "lyricist"
  },
  {
   "impor": 19,
   "name": "김부민",
   "type": "lyricist"
  },
  {
   "impor": 18,
   "name": "방시혁",
   "type": "lyricist"
  },
  {
   "impor": 17,
   "name": "최갑원",
   "type": "lyricist"
  },
  {
   "impor": 17,
   "name": "이트라이브",
   "type": "lyricist"
  },
  {
   "impor": 17,
   "name": "슈퍼창따이",
   "type": "lyricist"
  },
  {
   "impor": 17,
   "name": "e.one",
   "type": "lyricist"
  },
  {
   "impor": 17,
   "name": "은혁 (EUNHYUK)",
   "type": "lyricist"
  },
  {
   "impor": 16,
   "name": "심스 ($IM$)",
   "type": "lyricist"
  },
  {
   "impor": 16,
   "name": "김태주",
   "type": "lyricist"
  },
  {
   "impor": 16,
   "name": "박경 (블락비)",
   "type": "lyricist"
  },
  {
   "impor": 15,
   "name": "David Kim",
   "type": "lyricist"
  },
  {
   "impor": 15,
   "name": "Team One Sound",
   "type": "lyricist"
  },
  {
   "impor": 15,
   "name": "라이머",
   "type": "lyricist"
  },
  {
   "impor": 15,
   "name": "직 재스퍼 (Zick Jasper)",
   "type": "lyricist"
  },
  {
   "impor": 14,
   "name": "최종훈 (FT아일랜드)",
   "type": "lyricist"
  },
  {
   "impor": 14,
   "name": "강남",
   "type": "lyricist"
  },
  {
   "impor": 14,
   "name": "남기상",
   "type": "lyricist"
  },
  {
   "impor": 14,
   "name": "C.A.P",
   "type": "lyricist"
  },
  {
   "impor": 13,
   "name": "Ryan S. Jhun",
   "type": "lyricist"
  },
  {
   "impor": 13,
   "name": "Misfit",
   "type": "lyricist"
  },
  {
   "impor": 13,
   "name": "미성",
   "type": "lyricist"
  },
  {
   "impor": 13,
   "name": "블랙아이드 필승",
   "type": "lyricist"
  },
  {
   "impor": 13,
   "name": "미르 (MBLAQ)",
   "type": "lyricist"
  },
  {
   "impor": 13,
   "name": "신우",
   "type": "lyricist"
  },
  {
   "impor": 13,
   "name": "종현 (JONGHYUN)",
   "type": "lyricist"
  },
  {
   "impor": 12,
   "name": "이기 (오레오)",
   "type": "lyricist"
  },
  {
   "impor": 12,
   "name": "노는어린이",
   "type": "lyricist"
  },
  {
   "impor": 12,
   "name": "김영후",
   "type": "lyricist"
  },
  {
   "impor": 12,
   "name": "원택 (1Take)",
   "type": "lyricist"
  },
  {
   "impor": 12,
   "name": "BEOMxNANG",
   "type": "lyricist"
  },
  {
   "impor": 12,
   "name": "ZigZag Note",
   "type": "lyricist"
  },
  {
   "impor": 12,
   "name": "SWIN",
   "type": "lyricist"
  },
  {
   "impor": 11,
   "name": "박초롱 (에이핑크)",
   "type": "lyricist"
  },
  {
   "impor": 11,
   "name": "M.I.B",
   "type": "lyricist"
  },
  {
   "impor": 11,
   "name": "우리형과 내동생",
   "type": "lyricist"
  },
  {
   "impor": 10,
   "name": "태완 (Taewan)",
   "type": "lyricist"
  },
  {
   "impor": 10,
   "name": "JQ",
   "type": "lyricist"
  },
  {
   "impor": 10,
   "name": "한상원",
   "type": "lyricist"
  },
  {
   "impor": 10,
   "name": "Good Life",
   "type": "lyricist"
  },
  {
   "impor": 10,
   "name": "Sean Alexander",
   "type": "lyricist"
  },
  {
   "impor": 10,
   "name": "Urban Cllasik",
   "type": "lyricist"
  },
  {
   "impor": 10,
   "name": "홍지상",
   "type": "lyricist"
  },
  {
   "impor": 10,
   "name": "이종현 (CNBLUE)",
   "type": "lyricist"
  },
  {
   "impor": 10,
   "name": "D`DAY",
   "type": "lyricist"
  },
  {
   "impor": 10,
   "name": "김재중",
   "type": "lyricist"
  },
  {
   "impor": 9,
   "name": "김영아",
   "type": "lyricist"
  },
  {
   "impor": 9,
   "name": "로빈",
   "type": "lyricist"
  },
  {
   "impor": 9,
   "name": "핫펠트 (예은)",
   "type": "lyricist"
  },
  {
   "impor": 9,
   "name": "별들의 전쟁",
   "type": "lyricist"
  },
  {
   "impor": 9,
   "name": "낯선",
   "type": "lyricist"
  },
  {
   "impor": 9,
   "name": "김태윤",
   "type": "lyricist"
  },
  {
   "impor": 9,
   "name": "찬성",
   "type": "lyricist"
  },
  {
   "impor": 9,
   "name": "Mafly",
   "type": "lyricist"
  },
  {
   "impor": 9,
   "name": "이상호",
   "type": "lyricist"
  },
  {
   "impor": 9,
   "name": "마르코",
   "type": "lyricist"
  },
  {
   "impor": 9,
   "name": "Kenzie",
   "type": "lyricist"
  },
  {
   "impor": 9,
   "name": "전간디",
   "type": "lyricist"
  },
  {
   "impor": 9,
   "name": "유빈 (Yubin)",
   "type": "lyricist"
  },
  {
   "impor": 9,
   "name": "L.Joe",
   "type": "lyricist"
  },
  {
   "impor": 9,
   "name": "NODAY",
   "type": "lyricist"
  },
  {
   "impor": 9,
   "name": "임상혁",
   "type": "lyricist"
  },
  {
   "impor": 8,
   "name": "민호 (MINHO)",
   "type": "lyricist"
  },
  {
   "impor": 8,
   "name": "택연",
   "type": "lyricist"
  },
  {
   "impor": 8,
   "name": "Denis Seo",
   "type": "lyricist"
  },
  {
   "impor": 8,
   "name": "홍지유",
   "type": "lyricist"
  },
  {
   "impor": 8,
   "name": "황현 (MonoTree)",
   "type": "lyricist"
  },
  {
   "impor": 8,
   "name": "수빈",
   "type": "lyricist"
  },
  {
   "impor": 8,
   "name": "원태연",
   "type": "lyricist"
  },
  {
   "impor": 8,
   "name": "Cream (M.I.B)",
   "type": "lyricist"
  },
  {
   "impor": 8,
   "name": "최강창민 (MAX)",
   "type": "lyricist"
  },
  {
   "impor": 8,
   "name": "정하나",
   "type": "lyricist"
  },
  {
   "impor": 8,
   "name": "제이하트 (J.Heart)",
   "type": "lyricist"
  },
  {
   "impor": 8,
   "name": "창조",
   "type": "lyricist"
  },
  {
   "impor": 8,
   "name": "서용배 (TENTEN)",
   "type": "lyricist"
  },
  {
   "impor": 8,
   "name": "김태성",
   "type": "lyricist"
  },
  {
   "impor": 8,
   "name": "심은지",
   "type": "lyricist"
  },
  {
   "impor": 7,
   "name": "김도훈 (RBW)",
   "type": "lyricist"
  },
  {
   "impor": 7,
   "name": "KZ",
   "type": "lyricist"
  },
  {
   "impor": 7,
   "name": "원펀치",
   "type": "lyricist"
  },
  {
   "impor": 7,
   "name": "은종태",
   "type": "lyricist"
  },
  {
   "impor": 7,
   "name": "황성제",
   "type": "lyricist"
  },
  {
   "impor": 7,
   "name": "권윤정",
   "type": "lyricist"
  },
  {
   "impor": 7,
   "name": "조영수",
   "type": "lyricist"
  },
  {
   "impor": 7,
   "name": "박수석",
   "type": "lyricist"
  },
  {
   "impor": 7,
   "name": "이병준",
   "type": "lyricist"
  },
  {
   "impor": 7,
   "name": "오준성",
   "type": "lyricist"
  },
  {
   "impor": 7,
   "name": "Cream",
   "type": "lyricist"
  },
  {
   "impor": 7,
   "name": "배진렬 (JR Groove)",
   "type": "lyricist"
  },
  {
   "impor": 7,
   "name": "서지음",
   "type": "lyricist"
  },
  {
   "impor": 7,
   "name": "신재훈",
   "type": "lyricist"
  },
  {
   "impor": 6,
   "name": "서재우 (TENTEN)",
   "type": "lyricist"
  },
  {
   "impor": 6,
   "name": "박덕상",
   "type": "lyricist"
  },
  {
   "impor": 6,
   "name": "박창현",
   "type": "lyricist"
  },
  {
   "impor": 6,
   "name": "민우 (보이프렌드)",
   "type": "lyricist"
  },
  {
   "impor": 6,
   "name": "Dok2",
   "type": "lyricist"
  },
  {
   "impor": 6,
   "name": "희철 (HEECHUL)",
   "type": "lyricist"
  },
  {
   "impor": 6,
   "name": "이기광",
   "type": "lyricist"
  },
  {
   "impor": 6,
   "name": "키 (KEY)",
   "type": "lyricist"
  },
  {
   "impor": 6,
   "name": "준Q",
   "type": "lyricist"
  },
  {
   "impor": 6,
   "name": "준케이 (JUN. K)",
   "type": "lyricist"
  },
  {
   "impor": 6,
   "name": "준호",
   "type": "lyricist"
  },
  {
   "impor": 6,
   "name": "지오 (G.O)",
   "type": "lyricist"
  },
  {
   "impor": 6,
   "name": "천둥",
   "type": "lyricist"
  },
  {
   "impor": 6,
   "name": "Long Candy",
   "type": "lyricist"
  },
  {
   "impor": 6,
   "name": "피터팬",
   "type": "lyricist"
  },
  {
   "impor": 6,
   "name": "제이덥 (JDUB)",
   "type": "lyricist"
  },
  {
   "impor": 6,
   "name": "Steven Lee",
   "type": "lyricist"
  },
  {
   "impor": 6,
   "name": "AJ",
   "type": "lyricist"
  },
  {
   "impor": 6,
   "name": "SIGVARDT",
   "type": "lyricist"
  },
  {
   "impor": 6,
   "name": "황금두현",
   "type": "lyricist"
  },
  {
   "impor": 6,
   "name": "Rphabet",
   "type": "lyricist"
  },
  {
   "impor": 6,
   "name": "MIKKEL REME",
   "type": "lyricist"
  },
  {
   "impor": 6,
   "name": "를(LEL)",
   "type": "lyricist"
  },
  {
   "impor": 6,
   "name": "인우",
   "type": "lyricist"
  },
  {
   "impor": 6,
   "name": "정창욱",
   "type": "lyricist"
  },
  {
   "impor": 6,
   "name": "CL",
   "type": "lyricist"
  },
  {
   "impor": 6,
   "name": "정진환",
   "type": "lyricist"
  },
  {
   "impor": 6,
   "name": "이스란",
   "type": "lyricist"
  },
  {
   "impor": 6,
   "name": "강전명",
   "type": "lyricist"
  },
  {
   "impor": 6,
   "name": "이윤재",
   "type": "lyricist"
  },
  {
   "impor": 6,
   "name": "전다운",
   "type": "lyricist"
  },
  {
   "impor": 6,
   "name": "광민 (보이프렌드)",
   "type": "lyricist"
  },
  {
   "impor": 6,
   "name": "김재양",
   "type": "lyricist"
  },
  {
   "impor": 0,
   "name": "빅뱅",
   "type": "artist"
  },
  {
   "impor": 0,
   "name": "비원에이포",
   "type": "artist"
  },
  {
   "impor": 0,
   "name": "씨엔블루",
   "type": "artist"
  },
  {
   "impor": 0,
   "name": "에프티 아일랜드",
   "type": "artist"
  },
  {
   "impor": 0,
   "name": "비스트",
   "type": "artist"
  },
  {
   "impor": 0,
   "name": "보이프렌드",
   "type": "artist"
  },
  {
   "impor": 0,
   "name": "블락비",
   "type": "artist"
  },
  {
   "impor": 0,
   "name": "브라운 아이드 걸스",
   "type": "artist"
  },
  {
   "impor": 0,
   "name": "인피니트",
   "type": "artist"
  },
  {
   "impor": 0,
   "name": "틴탑",

In [440]:
pd.DataFrame(json_prep_gen2['nodes']).head()

   impor      name      type
0    122       송수윤  lyricist
1     71       한성호  lyricist
2     70  G-DRAGON  lyricist
3     63    용감한 형제  lyricist
4     54        바로  lyricist

In [441]:
pd.DataFrame(json_prep_gen2['links']).head()

   source  target  value
0       0     110     63
1       1     111     54
2       2     112     49
3       3     113     45
4       4     114     42

In [442]:
filename_out = 'idol_lyricist_gen2.json'
json_out = open(filename_out,'w')
json_out.write(json_dump_gen2)
json_out.close()

#### 3) lyricist_gen3 작업

In [443]:
# lyricist_gen1의 가수 목록 데이터프레임 생성
i = 0
a = 0
b = 0
lyricist = []
artist = []

lyricist.clear()
artist.clear()
    
for i in range(0, len(lyricist_gen3)):
    try:
        for a in range(0, len(preprocess(lyricist_gen3.lyricist[i], lyricist_gen3.artist[i])[0])):
            lyricist.append(str(preprocess(lyricist_gen3.lyricist[i], lyricist_gen3.artist[i])[0][a]))
        for b in range(0, len(preprocess(lyricist_gen3.lyricist[i], lyricist_gen3.artist[i])[1])):
            artist.append(str(preprocess(lyricist_gen3.lyricist[i], lyricist_gen3.artist[i])[1][b]))
    except:
        lyricist.append('')
        artist.append('')
    
preprocessing_gen3 = pd.DataFrame({"lyricist" : lyricist, "artist" : artist, "generation" : 3})

In [444]:
preprocessing_gen3.rename(columns={"lyricist":"source","artist":"target"}, inplace=True)

In [445]:
grouped_idol_gen3 = preprocessing_gen3.groupby(["source","target"]).size().reset_index()
grouped_idol_gen3.head(20) # 갑자기 빈 행이 존재함 ->삭제

     source    target  0
0       $un   엔시티 일이칠  1
1    100%서정        라붐  1
2    100%서정      레드벨벳  1
3    100%서정  소녀시대-태티서  1
4    100%서정      아스트로  1
5    100%서정        엑소  1
6    100%서정    엔시티 드림  1
7    100%서정       첸백시  1
8    100%서정     티알씨엔지  1
9    110403       업텐션  1
10     1105       임팩트  2
11  12월 32일    뉴이스트 W  1
12     1601       소나무  1
13     1601      에이프릴  1
14     1601        카드  1
15  17HOLIC      단발머리  1
16  17HOLIC       비에이  1
17  17HOLIC        빅스  1
18  17HOLIC       소나무  1
19  17HOLIC     소년공화국  1

In [446]:
grouped_idol_gen3.loc[grouped_idol_gen3['source'] == "-"]

Empty DataFrame
Columns: [source, target, 0]
Index: []

In [447]:
grouped_idol_gen3.loc[grouped_idol_gen3['source'] == "TEDDY"]

    source target  0
721  TEDDY   블랙핑크  9
722  TEDDY    아이콘  2

In [448]:
grouped_idol_gen3['source'] = grouped_idol_gen3['source'].replace('TEDDY', '테디')

In [449]:
grouped_idol_gen3.loc[grouped_idol_gen3['source'] == "TEDDY"]

Empty DataFrame
Columns: [source, target, 0]
Index: []

In [450]:
# 칼럼 0 -> count로 이름 칼럼명 수정
grouped_idol_gen3.rename(columns={0:'count'}, inplace=True)
len(grouped_idol_gen3)

2821

In [451]:
grouped_idol_gen3_ranking = grouped_idol_gen3.sort_values(by='count', ascending=False)
grouped_idol_gen3_ranking = grouped_idol_gen3_ranking.reset_index(drop=True)
grouped_idol_gen3_ranking.head()

   source target  count
0      RM  방탄소년단     86
1    SUGA  방탄소년단     73
2   Pdogg  방탄소년단     70
3     방용국   비에이피     69
4  j-hope  방탄소년단     68

In [452]:
len(grouped_idol_gen3_ranking)

2821

In [453]:
# unique한 source
generate_node_gen3 = grouped_idol_gen3_ranking.groupby(['source', 'count']).size().reset_index()
# generate_node.rename(columns={0:'count'}, inplace=True)
generate_node_gen3 = generate_node_gen3.sort_values(by='count', ascending=False)
generate_node_gen3 = generate_node_gen3.reset_index(drop=True)
generate_node_gen3 = generate_node_gen3.drop([0], axis = 1)
len(generate_node_gen3)

1993

In [454]:
# unique해지려면 총 478이어야함
generate_node2_gen3 = generate_node_gen3.groupby(['source']).sum()
generate_node2_gen3 = generate_node2_gen3.sort_values(by='count', ascending=False)
len(generate_node2_gen3) == len(generate_node_gen3.source.unique()) == len(grouped_idol_gen3_ranking['source'].unique())

True

In [455]:
grouped_idol2_gen3 = grouped_idol_gen3_ranking[grouped_idol_gen3_ranking['count'] > 5]
generate_node_gen3 = generate_node2_gen3[generate_node2_gen3['count']>5]

In [456]:
grouped_idol2_gen3 = grouped_idol2_gen3.reset_index()
generate_node_gen3 = generate_node_gen3.reset_index()

In [457]:
grouped_idol2_gen3 = grouped_idol2_gen3.drop(['index'], axis = 1)

In [458]:
generate_node_gen3.head(10)

       source  count
0          RM     86
1        SUGA     73
2       Pdogg     72
3         방용국     69
4         정일훈     68
5      j-hope     68
6     라비 (빅스)     64
7         이민혁     51
8       BUMZU     51
9  주헌 (몬스타엑스)     51

In [459]:
unique_idol_gen3_all = pd.Index(grouped_idol2_gen3['source']
                      .append(grouped_idol2_gen3['target'])
                      .reset_index(drop=True).unique())
unique_idol_gen3_lyricist = pd.Index(grouped_idol2_gen3['source']
                      .reset_index(drop=True).unique())
unique_idol_gen3_artist = pd.Index(grouped_idol2_gen3['target']
                      .reset_index(drop=True).unique())

In [460]:
group_dict_gen3_lyricist = {}
group_dict_gen3_lyricist.clear()
counter = 0
for idol in unique_idol_gen3_lyricist:
    if idol not in group_dict_gen3_lyricist:
        counter += 1
        group_dict_gen3_lyricist[idol] = counter
    else:
        pass
group_dict_gen3_lyricist

{'RM': 1,
 'SUGA': 2,
 'Pdogg': 3,
 '방용국': 4,
 'j-hope': 5,
 '라비 (빅스)': 6,
 '정일훈': 7,
 '주헌 (몬스타엑스)': 8,
 'WOOZI (SEVENTEEN)': 9,
 '이민혁': 10,
 'I.M (몬스타엑스)': 11,
 '방시혁': 12,
 'Young K': 13,
 'Vernon (SEVENTEEN)': 14,
 'Slow Rabbit': 15,
 'S.COUPS (SEVENTEEN)': 16,
 'B.I': 17,
 'BUMZU': 18,
 'LE (EXID)': 19,
 '프니엘': 20,
 '문별 (마마무)': 21,
 'BOBBY': 22,
 '우석 (펜타곤)': 23,
 'Supreme Boi': 24,
 'MINO': 25,
 '이던': 26,
 '엑시': 27,
 '민규 (SEVENTEEN)': 28,
 '진진 (ASTRO)': 29,
 '이승훈': 30,
 '박우상': 31,
 '유토': 32,
 '라키 (ASTRO)': 33,
 '김지향': 34,
 '이승협 (J.DON)': 35,
 '한 (3RACHA)': 36,
 '방찬 (3RACHA)': 37,
 '서재우 (TENTEN)': 38,
 '도한세 (VICTON)': 39,
 '창빈 (3RACHA)': 40,
 '원우 (SEVENTEEN)': 41,
 '임현식': 42,
 'SWEETUNE': 43,
 'JB (GOT7)': 44,
 '지민 (AOA)': 45,
 'T.K': 46,
 '김도훈 (RBW)': 47,
 '이기 (오레오)': 48,
 'HighTop': 49,
 '강승윤': 50,
 '용감한 형제': 51,
 '신사동 호랭이': 52,
 'Rome': 53,
 '서지음': 54,
 '박수석': 55,
 '한성호': 56,
 '디노 (SEVENTEEN)': 57,
 '용배 (RBW)': 58,
 '김태주': 59,
 '강지원': 60,
 '김기범': 61,
 '화사 (마마무)': 62,
 '미미 (오마이걸)': 63,
 'kenzie': 64,
 'JQ': 65,
 '서용배 (TENTEN)': 66,
 '호시 (SEVENTEEN)': 67,
 '예빈 (다이아)': 68,
 '기희현': 69,
 '김창락': 70,
 '장예은': 71,
 'KZ': 72,
 '정욱': 73,
 '마르코': 74,
 '낯선': 75,
 'BM': 76,
 'JR (뉴이스트)': 77,
 '솔라 (마마무)': 78,
 '마크 (MARK)': 79,
 '태용 (TAEYONG)': 80,
 'Sofar': 81,
 '마부스 (Maboos)': 82,
 '한승우 (VICTON)': 83,
 '조성호': 84,
 'ADORA': 85,
 'Hip Wave Sound': 86,
 '빅싼초 (Yummy Tone)': 87,
 'J.seph': 88,
 '원필': 89,
 '알렉스 (하이포)': 90,
 '장이정 (JANGYIJEONG)': 91,
 '후이 (펜타곤)': 92,
 '임영준 (하이포)': 93,
 '신준섭': 94,
 '예지': 95,
 'Z-uK (지욱)': 96,
 '뱀뱀 (GOT7)': 97,
 '백호 (뉴이스트)': 98,
 '용준형': 99,
 '조윤경': 100,
 '은진': 101,
 '차쿤 (일렉트로보이즈)': 102,
 '인우': 103,
 'ZeroZine (MosPick)': 104,
 'P.O (블락비)': 105,
 '권현빈': 106,
 '젤로': 107,
 '비토': 108,
 'earattack': 109,
 '테디': 110,
 '장준': 111,
 '라도': 112,
 'Chloe': 113,
 '최갑원': 114,
 '이단옆차기': 115,
 '김상균': 116,
 '미친감성': 117,
 'Ferdy (MosPick)': 118,
 'NODAY': 119,
 '리시': 120,
 '웨이': 121,
 '은수': 122,
 '마크 (GOT7)': 123,
 'TAG': 124,
 '박진영': 125,
 '버피 (BUFFY)': 126,
 '승관 (SEVENTEEN)': 127,
 '성연': 128,
 '황현 (MonoTree)': 129,
 '소연': 130,
 '임팩트': 131,
 '몬스터팩토리': 132,
 '강동하': 133,
 '진영 (GOT7)': 134,
 '슬리피': 135,
 '함길수': 136,
 '리나': 137,
 '일 (IL)': 138,
 '이노베이터': 139,
 '윤후': 140,
 '잭슨 (GOT7)': 141,
 '전다운': 142,
 '박은우': 143,
 '유니스': 144,
 '정하': 145,
 '우태운': 146,
 '쿤': 147,
 'John K': 148,
 '찬열': 149,
 '영재 (GOT7)': 150,
 'Mafly': 151,
 '서림': 152,
 'David Kim': 153,
 '김미진': 154,
 '김이나': 155,
 'DAY6 (데이식스)': 156,
 'Ollounder': 157,
 '72': 158,
 '슈퍼창따이': 159,
 '진리 (Full8loom)': 160,
 '로아': 161,
 'ESBEE': 162,
 '키노': 163,
 '별들의 전쟁': 164,
 '남태현': 165,
 '코스믹 사운드': 166,
 '코스믹 걸 (Cosmic Girl)': 167,
 '유겸 (GOT7)': 168,
 '원호 (몬스타엑스)': 169,
 'HOYA (호야)': 170,
 '제니': 171,
 'MELODESIGN': 172,
 '한승훈': 173,
 '장동우 (인피니트)': 174,
 '성현': 175,
 '정한 (SEVENTEEN)': 176,
 '가면라이더': 177}

In [461]:
group_dict_gen3_artist = {}
group_dict_gen3_artist.clear()
counter = 177
for idol in unique_idol_gen3_artist:
    if idol not in group_dict_gen3_artist:
        counter += 1
        group_dict_gen3_artist[idol] = counter
    else:
        pass
group_dict_gen3_artist

{'방탄소년단': 178,
 '비에이피': 179,
 '빅스': 180,
 '비투비': 181,
 '몬스타엑스': 182,
 '세븐틴': 183,
 '데이식스': 184,
 '아이콘': 185,
 '이엑스아이디': 186,
 '마마무': 187,
 '펜타곤': 188,
 '위너': 189,
 '우주소녀': 190,
 '아스트로': 191,
 '엔플라잉': 192,
 '스트레이 키즈': 193,
 '빅톤': 194,
 '스누퍼': 195,
 '갓세븐': 196,
 '에이오에이': 197,
 '씨클라운': 198,
 '여자친구': 199,
 '빅플로': 200,
 '오마이걸': 201,
 '크나큰': 202,
 '레드벨벳': 203,
 '엑소': 204,
 '다이아': 205,
 '씨엘씨': 206,
 '헤일로': 207,
 '투포케이': 208,
 '빅스타': 209,
 '에스에프나인': 210,
 '카드': 211,
 '뉴이스트': 212,
 '엔시티 드림': 213,
 '엔시티 일이칠': 214,
 '뉴이스트 W': 215,
 '마이틴': 216,
 '비비드': 217,
 '하이포': 218,
 '히스토리': 219,
 '백퍼센트': 220,
 '피에스타': 221,
 '하이라이트': 222,
 '블락비 바스타즈': 223,
 '제이비제이': 224,
 '업텐션': 225,
 '블랙핑크': 226,
 '골든차일드': 227,
 '소나무': 228,
 '제이제이씨씨': 229,
 '매드타운': 230,
 '프리스틴': 231,
 '온앤오프': 232,
 '(여자)아이들': 233,
 '임팩트': 234,
 '러블리즈': 235,
 '미스터미스터': 236,
 '비트윈': 237,
 '스피드': 238,
 '모모랜드': 239,
 '비비드걸': 240,
 '드림캐쳐': 241,
 '비아이지': 242,
 '레이디스 코드': 243,
 '인피니트 에이치': 244,
 '인투잇': 245,
 '리얼걸프로젝트': 246}

In [462]:
temp_links_list_gen3 = []
temp_links_list_gen3 = list(grouped_idol2_gen3.apply(lambda row: {"source": row['source'], "target": row['target'], "value": row['count']}, axis=1))

In [463]:
temp_links_list_gen3

[{'source': 'RM', 'target': '방탄소년단', 'value': 86},
 {'source': 'SUGA', 'target': '방탄소년단', 'value': 73},
 {'source': 'Pdogg', 'target': '방탄소년단', 'value': 70},
 {'source': '방용국', 'target': '비에이피', 'value': 69},
 {'source': 'j-hope', 'target': '방탄소년단', 'value': 68},
 {'source': '라비 (빅스)', 'target': '빅스', 'value': 61},
 {'source': '정일훈', 'target': '비투비', 'value': 58},
 {'source': '주헌 (몬스타엑스)', 'target': '몬스타엑스', 'value': 51},
 {'source': 'WOOZI (SEVENTEEN)', 'target': '세븐틴', 'value': 50},
 {'source': '이민혁', 'target': '비투비', 'value': 48},
 {'source': 'I.M (몬스타엑스)', 'target': '몬스타엑스', 'value': 48},
 {'source': '방시혁', 'target': '방탄소년단', 'value': 41},
 {'source': 'Young K', 'target': '데이식스', 'value': 37},
 {'source': 'Vernon (SEVENTEEN)', 'target': '세븐틴', 'value': 34},
 {'source': 'Slow Rabbit', 'target': '방탄소년단', 'value': 33},
 {'source': 'S.COUPS (SEVENTEEN)', 'target': '세븐틴', 'value': 33},
 {'source': 'B.I', 'target': '아이콘', 'value': 32},
 {'source': 'BUMZU', 'target': '세븐틴', 'value': 31},
 {'source': 'LE (EXID)', 'target': '이엑스아이디', 'value': 30},
 {'source': '프니엘', 'target': '비투비', 'value': 30},
 {'source': '문별 (마마무)', 'target': '마마무', 'value': 28},
 {'source': 'BOBBY', 'target': '아이콘', 'value': 27},
 {'source': '우석 (펜타곤)', 'target': '펜타곤', 'value': 27},
 {'source': 'Supreme Boi', 'target': '방탄소년단', 'value': 27},
 {'source': 'MINO', 'target': '위너', 'value': 27},
 {'source': '이던', 'target': '펜타곤', 'value': 26},
 {'source': '엑시', 'target': '우주소녀', 'value': 25},
 {'source': '민규 (SEVENTEEN)', 'target': '세븐틴', 'value': 22},
 {'source': '진진 (ASTRO)', 'target': '아스트로', 'value': 22},
 {'source': '이승훈', 'target': '위너', 'value': 21},
 {'source': '박우상', 'target': '마마무', 'value': 21},
 {'source': '유토', 'target': '펜타곤', 'value': 21},
 {'source': '라키 (ASTRO)', 'target': '아스트로', 'value': 21},
 {'source': '김지향', 'target': '빅스', 'value': 21},
 {'source': '이승협 (J.DON)', 'target': '엔플라잉', 'value': 20},
 {'source': '한 (3RACHA)', 'target': '스트레이 키즈', 'value': 19},
 {'source': '방찬 (3RACHA)', 'target': '스트레이 키즈', 'value': 19},
 {'source': '서재우 (TENTEN)', 'target': '비투비', 'value': 19},
 {'source': '도한세 (VICTON)', 'target': '빅톤', 'value': 19},
 {'source': '창빈 (3RACHA)', 'target': '스트레이 키즈', 'value': 19},
 {'source': '원우 (SEVENTEEN)', 'target': '세븐틴', 'value': 18},
 {'source': '임현식', 'target': '비투비', 'value': 18},
 {'source': 'SWEETUNE', 'target': '스누퍼', 'value': 17},
 {'source': 'JB (GOT7)', 'target': '갓세븐', 'value': 17},
 {'source': '지민 (AOA)', 'target': '에이오에이', 'value': 16},
 {'source': 'T.K', 'target': '씨클라운', 'value': 16},
 {'source': '김도훈 (RBW)', 'target': '마마무', 'value': 15},
 {'source': '이기 (오레오)', 'target': '여자친구', 'value': 15},
 {'source': 'HighTop', 'target': '빅플로', 'value': 15},
 {'source': '강승윤', 'target': '위너', 'value': 15},
 {'source': '용감한 형제', 'target': '에이오에이', 'value': 15},
 {'source': '신사동 호랭이', 'target': '이엑스아이디', 'value': 15},
 {'source': 'Rome', 'target': '씨클라운', 'value': 15},
 {'source': '서지음', 'target': '오마이걸', 'value': 15},
 {'source': '박수석', 'target': '비에이피', 'value': 15},
 {'source': '한성호', 'target': '에이오에이', 'value': 15},
 {'source': '디노 (SEVENTEEN)', 'target': '세븐틴', 'value': 14},
 {'source': '용배 (RBW)', 'target': '여자친구', 'value': 14},
 {'source': '김태주', 'target': '크나큰', 'value': 14},
 {'source': '강지원', 'target': '비에이피', 'value': 14},
 {'source': '김기범', 'target': '비에이피', 'value': 14},
 {'source': '화사 (마마무)', 'target': '마마무', 'value': 13},
 {'source': '미미 (오마이걸)', 'target': '오마이걸', 'value': 13},
 {'source': 'kenzie', 'target': '레드벨벳', 'value': 13},
 {'source': 'JQ', 'target': '엑소', 'value': 13},
 {'source': '서용배 (TENTEN)', 'target': '비투비', 'value': 13},
 {'source': '호시 (SEVENTEEN)', 'target': '세븐틴', 'value': 13},
 {'source': '예빈 (다이아)', 'target': '다이아', 'value': 13},
 {'source': '기희현', 'target': '다이아', 'value': 13},
 {'source': '김창락', 'target': '비에이피', 'value': 13},
 {'source': '장예은', 'target': '씨엘씨', 'value': 13},
 {'source': 'KZ', 'target': '헤일로', 'value': 12},
 {'source': '정욱', 'target': '투포케이', 'value': 12},
 {'source': '이기 (오레오)', 'target': '아스트로', 'value': 12},
 {'source': '용감한 형제', 'target': '빅스타', 'value': 12},
 {'source': '마르코', 'target': '비에이피', 'value': 12},
 {'source': '김창락', 'target': '에스에프나인', 'value': 12},
 {'source': '낯선', 'target': '카드', 'value': 12},
 {'source': 'BM', 'target': '카드', 'value': 12},
 {'source': 'JR (뉴이스트)', 'target': '뉴이스트', 'value': 12},
 {'source': '솔라 (마마무)', 'target': '마마무', 'value': 12},
 {'source': '마크 (MARK)', 'target': '엔시티 드림', 'value': 12},
 {'source': '태용 (TAEYONG)', 'target': '엔시티 일이칠', 'value': 11},
 {'source': 'BUMZU', 'target': '뉴이스트 W', 'value': 11},
 {'source': 'Sofar', 'target': '마이틴', 'value': 11},
 {'source': '마부스 (Maboos)', 'target': '빅스타', 'value': 11},
 {'source': '한승우 (VICTON)', 'target': '빅톤', 'value': 11},
 {'source': 'JR (뉴이스트)', 'target': '뉴이스트 W', 'value': 11},
 {'source': '조성호', 'target': '비투비', 'value': 11},
 {'source': 'ADORA', 'target': '방탄소년단', 'value': 11},
 {'source': 'Hip Wave Sound', 'target': '비비드', 'value': 11},
 {'source': '빅싼초 (Yummy Tone)', 'target': '씨엘씨', 'value': 11},
 {'source': 'J.seph', 'target': '카드', 'value': 11},
 {'source': '원필', 'target': '데이식스', 'value': 10},
 {'source': '알렉스 (하이포)', 'target': '하이포', 'value': 10},
 {'source': '장이정 (JANGYIJEONG)', 'target': '히스토리', 'value': 10},
 {'source': '후이 (펜타곤)', 'target': '펜타곤', 'value': 10},
 {'source': 'SWEETUNE', 'target': '백퍼센트', 'value': 10},
 {'source': '임영준 (하이포)', 'target': '하이포', 'value': 10},
 {'source': '신준섭', 'target': '마이틴', 'value': 10},
 {'source': '예지', 'target': '피에스타', 'value': 10},
 {'source': 'Z-uK (지욱)', 'target': '빅플로', 'value': 10},
 {'source': '뱀뱀 (GOT7)', 'target': '갓세븐', 'value': 10},
 {'source': '마크 (MARK)', 'target': '엔시티 일이칠', 'value': 10},
 {'source': '조성호', 'target': '씨엘씨', 'value': 10},
 {'source': '백호 (뉴이스트)', 'target': '뉴이스트 W', 'value': 9},
 {'source': '용준형', 'target': '하이라이트', 'value': 9},
 {'source': '조윤경', 'target': '엑소', 'value': 9},
 {'source': '은진', 'target': '다이아', 'value': 9},
 {'source': '차쿤 (일렉트로보이즈)', 'target': '에이오에이', 'value': 9},
 {'source': '인우', 'target': '비에이피', 'value': 9},
 {'source': 'ZeroZine (MosPick)', 'target': '씨엘씨', 'value': 9},
 {'source': 'P.O (블락비)', 'target': '블락비 바스타즈', 'value': 9},
 {'source': '권현빈', 'target': '제이비제이', 'value': 9},
 {'source': '젤로', 'target': '비에이피', 'value': 9},
 {'source': '비토', 'target': '업텐션', 'value': 9},
 {'source': 'earattack', 'target': '갓세븐', 'value': 9},
 {'source': '테디', 'target': '블랙핑크', 'value': 9},
 {'source': '장준', 'target': '골든차일드', 'value': 8},
 {'source': '박수석', 'target': '소나무', 'value': 8},
 {'source': '라도', 'target': '씨클라운', 'value': 8},
 {'source': 'Chloe', 'target': '갓세븐', 'value': 8},
 {'source': '최갑원', 'target': '하이포', 'value': 8},
 {'source': '이단옆차기', 'target': '제이제이씨씨', 'value': 8},
 {'source': '김상균', 'target': '제이비제이', 'value': 8},
 {'source': '미친감성', 'target': '헤일로', 'value': 8},
 {'source': 'Ferdy (MosPick)', 'target': '씨엘씨', 'value': 8},
 {'source': 'NODAY', 'target': '갓세븐', 'value': 8},
 {'source': '용배 (RBW)', 'target': '아스트로', 'value': 8},
 {'source': '리시', 'target': '몬스타엑스', 'value': 8},
 {'source': '웨이', 'target': '업텐션', 'value': 8},
 {'source': '은수', 'target': '마이틴', 'value': 8},
 {'source': '마크 (GOT7)', 'target': '갓세븐', 'value': 8},
 {'source': '조윤경', 'target': '레드벨벳', 'value': 8},
 {'source': 'kenzie', 'target': '엑소', 'value': 8},
 {'source': 'TAG', 'target': '골든차일드', 'value': 8},
 {'source': '서지음', 'target': '엑소', 'value': 8},
 {'source': 'BUMZU', 'target': '뉴이스트', 'value': 8},
 {'source': '박진영', 'target': '갓세븐', 'value': 8},
 {'source': '버피 (BUFFY)', 'target': '매드타운', 'value': 8},
 {'source': '승관 (SEVENTEEN)', 'target': '세븐틴', 'value': 8},
 {'source': '성연', 'target': '프리스틴', 'value': 8},
 {'source': '황현 (MonoTree)', 'target': '온앤오프', 'value': 7},
 {'source': '소연', 'target': '(여자)아이들', 'value': 7},
 {'source': '임팩트', 'target': '임팩트', 'value': 7},
 {'source': '몬스터팩토리', 'target': '다이아', 'value': 7},
 {'source': '강동하', 'target': '펜타곤', 'value': 7},
 {'source': '진영 (GOT7)', 'target': '갓세븐', 'value': 7},
 {'source': '슬리피', 'target': '비에이피', 'value': 7},
 {'source': '함길수', 'target': '비비드', 'value': 7},
 {'source': '김창락', 'target': '엔플라잉', 'value': 7},
 {'source': '서지음', 'target': '러블리즈', 'value': 7},
 {'source': '리나', 'target': '미스터미스터', 'value': 7},
 {'source': '일 (IL)', 'target': '비투비', 'value': 7},
 {'source': '이노베이터', 'target': '엔플라잉', 'value': 7},
 {'source': '차쿤 (일렉트로보이즈)', 'target': '빅스타', 'value': 7},
 {'source': '윤후', 'target': '비트윈', 'value': 7},
 {'source': '잭슨 (GOT7)', 'target': '갓세븐', 'value': 7},
 {'source': 'Ferdy (MosPick)', 'target': '비투비', 'value': 7},
 {'source': '전다운', 'target': '비에이피', 'value': 7},
 {'source': '박은우', 'target': '소나무', 'value': 7},
 {'source': '유니스', 'target': '다이아', 'value': 7},
 {'source': '정하', 'target': '비트윈', 'value': 7},
 {'source': '우태운', 'target': '스피드', 'value': 7},
 {'source': '쿤', 'target': '업텐션', 'value': 7},
 {'source': '이단옆차기', 'target': '모모랜드', 'value': 7},
 {'source': 'John K', 'target': '비비드걸', 'value': 7},
 {'source': '한성호', 'target': '에스에프나인', 'value': 7},
 {'source': '찬열', 'target': '엑소', 'value': 7},
 {'source': '서용배 (TENTEN)', 'target': '아스트로', 'value': 6},
 {'source': '영재 (GOT7)', 'target': '갓세븐', 'value': 6},
 {'source': '이단옆차기', 'target': '스피드', 'value': 6},
 {'source': 'Mafly', 'target': '여자친구', 'value': 6},
 {'source': '서림', 'target': '엑소', 'value': 6},
 {'source': 'David Kim', 'target': '제이제이씨씨', 'value': 6},
 {'source': '김미진', 'target': '빅스', 'value': 6},
 {'source': '김이나', 'target': '빅스', 'value': 6},
 {'source': 'DAY6 (데이식스)', 'target': '데이식스', 'value': 6},
 {'source': 'Ollounder', 'target': '드림캐쳐', 'value': 6},
 {'source': '72', 'target': '오마이걸', 'value': 6},
 {'source': '빅싼초 (Yummy Tone)', 'target': '비투비', 'value': 6},
 {'source': '마르코', 'target': '소나무', 'value': 6},
 {'source': '마르코', 'target': '비아이지', 'value': 6},
 {'source': '슈퍼창따이', 'target': '레이디스 코드', 'value': 6},
 {'source': '진리 (Full8loom)', 'target': '아스트로', 'value': 6},
 {'source': '로아', 'target': '프리스틴', 'value': 6},
 {'source': 'ESBEE', 'target': '몬스타엑스', 'value': 6},
 {'source': '키노', 'target': '펜타곤', 'value': 6},
 {'source': '별들의 전쟁', 'target': '빅스타', 'value': 6},
 {'source': '남태현', 'target': '위너', 'value': 6},
 {'source': '코스믹 사운드', 'target': '마마무', 'value': 6},
 {'source': '코스믹 걸 (Cosmic Girl)', 'target': '마마무', 'value': 6},
 {'source': '유겸 (GOT7)', 'target': '갓세븐', 'value': 6},
 {'source': '원호 (몬스타엑스)', 'target': '몬스타엑스', 'value': 6},
 {'source': 'HOYA (호야)', 'target': '인피니트 에이치', 'value': 6},
 {'source': '제니', 'target': '다이아', 'value': 6},
 {'source': 'MELODESIGN', 'target': '빅스', 'value': 6},
 {'source': '정일훈', 'target': '씨엘씨', 'value': 6},
 {'source': '한승훈', 'target': '엔플라잉', 'value': 6},
 {'source': '서재우 (TENTEN)', 'target': '씨엘씨', 'value': 6},
 {'source': '장동우 (인피니트)', 'target': '인피니트 에이치', 'value': 6},
 {'source': '서지음', 'target': '몬스타엑스', 'value': 6},
 {'source': '한승훈', 'target': '에이오에이', 'value': 6},
 {'source': 'ZeroZine (MosPick)', 'target': '비투비', 'value': 6},
 {'source': '성현', 'target': '인투잇', 'value': 6},
 {'source': '정한 (SEVENTEEN)', 'target': '세븐틴', 'value': 6},
 {'source': '가면라이더', 'target': '리얼걸프로젝트', 'value': 6}]

In [464]:
# 링크 생성하기
links_list_gen3 = []
for link in temp_links_list_gen3:
    record = {"value":link['value'], "source":unique_idol_gen3_all.get_loc(link['source']),
     "target": unique_idol_gen3_all.get_loc(link['target'])}
    links_list_gen3.append(record)

In [465]:
# 노드 생성하기
nodes_list_gen3= []
nodes_list_gen3.clear()
for index,row in generate_node_gen3.iterrows():
    nodes_list_gen3.append({ "name":row['source'], "type":"lyricist", "impor":row['count']})
for idol in group_dict_gen3_artist:
    nodes_list_gen3.append({"name":idol, "type":"artist", "impor":0})

In [466]:
json_prep_gen3 = {"links":links_list_gen3, "nodes":nodes_list_gen3}
json_prep_gen3.keys()

dict_keys(['links', 'nodes'])

In [467]:
json_dump_gen3 = json.dumps(json_prep_gen3, indent=1, sort_keys=True, ensure_ascii=False)
print(json_dump_gen3)

{
 "links": [
  {
   "source": 0,
   "target": 177,
   "value": 86
  },
  {
   "source": 1,
   "target": 177,
   "value": 73
  },
  {
   "source": 2,
   "target": 177,
   "value": 70
  },
  {
   "source": 3,
   "target": 178,
   "value": 69
  },
  {
   "source": 4,
   "target": 177,
   "value": 68
  },
  {
   "source": 5,
   "target": 179,
   "value": 61
  },
  {
   "source": 6,
   "target": 180,
   "value": 58
  },
  {
   "source": 7,
   "target": 181,
   "value": 51
  },
  {
   "source": 8,
   "target": 182,
   "value": 50
  },
  {
   "source": 9,
   "target": 180,
   "value": 48
  },
  {
   "source": 10,
   "target": 181,
   "value": 48
  },
  {
   "source": 11,
   "target": 177,
   "value": 41
  },
  {
   "source": 12,
   "target": 183,
   "value": 37
  },
  {
   "source": 13,
   "target": 182,
   "value": 34
  },
  {
   "source": 14,
   "target": 177,
   "value": 33
  },
  {
   "source": 15,
   "target": 182,
   "value": 33
  },
  {
   "source": 16,
   "target": 184,
   "value": 32
  },
  {
   "source": 17,
   "target": 182,
   "value": 31
  },
  {
   "source": 18,
   "target": 185,
   "value": 30
  },
  {
   "source": 19,
   "target": 180,
   "value": 30
  },
  {
   "source": 20,
   "target": 186,
   "value": 28
  },
  {
   "source": 21,
   "target": 184,
   "value": 27
  },
  {
   "source": 22,
   "target": 187,
   "value": 27
  },
  {
   "source": 23,
   "target": 177,
   "value": 27
  },
  {
   "source": 24,
   "target": 188,
   "value": 27
  },
  {
   "source": 25,
   "target": 187,
   "value": 26
  },
  {
   "source": 26,
   "target": 189,
   "value": 25
  },
  {
   "source": 27,
   "target": 182,
   "value": 22
  },
  {
   "source": 28,
   "target": 190,
   "value": 22
  },
  {
   "source": 29,
   "target": 188,
   "value": 21
  },
  {
   "source": 30,
   "target": 186,
   "value": 21
  },
  {
   "source": 31,
   "target": 187,
   "value": 21
  },
  {
   "source": 32,
   "target": 190,
   "value": 21
  },
  {
   "source": 33,
   "target": 179,
   "value": 21
  },
  {
   "source": 34,
   "target": 191,
   "value": 20
  },
  {
   "source": 35,
   "target": 192,
   "value": 19
  },
  {
   "source": 36,
   "target": 192,
   "value": 19
  },
  {
   "source": 37,
   "target": 180,
   "value": 19
  },
  {
   "source": 38,
   "target": 193,
   "value": 19
  },
  {
   "source": 39,
   "target": 192,
   "value": 19
  },
  {
   "source": 40,
   "target": 182,
   "value": 18
  },
  {
   "source": 41,
   "target": 180,
   "value": 18
  },
  {
   "source": 42,
   "target": 194,
   "value": 17
  },
  {
   "source": 43,
   "target": 195,
   "value": 17
  },
  {
   "source": 44,
   "target": 196,
   "value": 16
  },
  {
   "source": 45,
   "target": 197,
   "value": 16
  },
  {
   "source": 46,
   "target": 186,
   "value": 15
  },
  {
   "source": 47,
   "target": 198,
   "value": 15
  },
  {
   "source": 48,
   "target": 199,
   "value": 15
  },
  {
   "source": 49,
   "target": 188,
   "value": 15
  },
  {
   "source": 50,
   "target": 196,
   "value": 15
  },
  {
   "source": 51,
   "target": 185,
   "value": 15
  },
  {
   "source": 52,
   "target": 197,
   "value": 15
  },
  {
   "source": 53,
   "target": 200,
   "value": 15
  },
  {
   "source": 54,
   "target": 178,
   "value": 15
  },
  {
   "source": 55,
   "target": 196,
   "value": 15
  },
  {
   "source": 56,
   "target": 182,
   "value": 14
  },
  {
   "source": 57,
   "target": 198,
   "value": 14
  },
  {
   "source": 58,
   "target": 201,
   "value": 14
  },
  {
   "source": 59,
   "target": 178,
   "value": 14
  },
  {
   "source": 60,
   "target": 178,
   "value": 14
  },
  {
   "source": 61,
   "target": 186,
   "value": 13
  },
  {
   "source": 62,
   "target": 200,
   "value": 13
  },
  {
   "source": 63,
   "target": 202,
   "value": 13
  },
  {
   "source": 64,
   "target": 203,
   "value": 13
  },
  {
   "source": 65,
   "target": 180,
   "value": 13
  },
  {
   "source": 66,
   "target": 182,
   "value": 13
  },
  {
   "source": 67,
   "target": 204,
   "value": 13
  },
  {
   "source": 68,
   "target": 204,
   "value": 13
  },
  {
   "source": 69,
   "target": 178,
   "value": 13
  },
  {
   "source": 70,
   "target": 205,
   "value": 13
  },
  {
   "source": 71,
   "target": 206,
   "value": 12
  },
  {
   "source": 72,
   "target": 207,
   "value": 12
  },
  {
   "source": 47,
   "target": 190,
   "value": 12
  },
  {
   "source": 50,
   "target": 208,
   "value": 12
  },
  {
   "source": 73,
   "target": 178,
   "value": 12
  },
  {
   "source": 69,
   "target": 209,
   "value": 12
  },
  {
   "source": 74,
   "target": 210,
   "value": 12
  },
  {
   "source": 75,
   "target": 210,
   "value": 12
  },
  {
   "source": 76,
   "target": 211,
   "value": 12
  },
  {
   "source": 77,
   "target": 186,
   "value": 12
  },
  {
   "source": 78,
   "target": 212,
   "value": 12
  },
  {
   "source": 79,
   "target": 213,
   "value": 11
  },
  {
   "source": 17,
   "target": 214,
   "value": 11
  },
  {
   "source": 80,
   "target": 215,
   "value": 11
  },
  {
   "source": 81,
   "target": 208,
   "value": 11
  },
  {
   "source": 82,
   "target": 193,
   "value": 11
  },
  {
   "source": 76,
   "target": 214,
   "value": 11
  },
  {
   "source": 83,
   "target": 180,
   "value": 11
  },
  {
   "source": 84,
   "target": 177,
   "value": 11
  },
  {
   "source": 85,
   "target": 216,
   "value": 11
  },
  {
   "source": 86,
   "target": 205,
   "value": 11
  },
  {
   "source": 87,
   "target": 210,
   "value": 11
  },
  {
   "source": 88,
   "target": 183,
   "value": 10
  },
  {
   "source": 89,
   "target": 217,
   "value": 10
  },
  {
   "source": 90,
   "target": 218,
   "value": 10
  },
  {
   "source": 91,
   "target": 187,
   "value": 10
  },
  {
   "source": 42,
   "target": 219,
   "value": 10
  },
  {
   "source": 92,
   "target": 217,
   "value": 10
  },
  {
   "source": 93,
   "target": 215,
   "value": 10
  },
  {
   "source": 94,
   "target": 220,
   "value": 10
  },
  {
   "source": 95,
   "target": 199,
   "value": 10
  },
  {
   "source": 96,
   "target": 195,
   "value": 10
  },
  {
   "source": 78,
   "target": 213,
   "value": 10
  },
  {
   "source": 83,
   "target": 205,
   "value": 10
  },
  {
   "source": 97,
   "target": 214,
   "value": 9
  },
  {
   "source": 98,
   "target": 221,
   "value": 9
  },
  {
   "source": 99,
   "target": 203,
   "value": 9
  },
  {
   "source": 100,
   "target": 204,
   "value": 9
  },
  {
   "source": 101,
   "target": 196,
   "value": 9
  },
  {
   "source": 102,
   "target": 178,
   "value": 9
  },
  {
   "source": 103,
   "target": 205,
   "value": 9
  },
  {
   "source": 104,
   "target": 222,
   "value": 9
  },
  {
   "source": 105,
   "target": 223,
   "value": 9
  },
  {
   "source": 106,
   "target": 178,
   "value": 9
  },
  {
   "source": 107,
   "target": 224,
   "value": 9
  },
  {
   "source": 108,
   "target": 195,
   "value": 9
  },
  {
   "source": 109,
   "target": 225,
   "value": 9
  },
  {
   "source": 110,
   "target": 226,
   "value": 8
  },
  {
   "source": 54,
   "target": 227,
   "value": 8
  },
  {
   "source": 111,
   "target": 197,
   "value": 8
  },
  {
   "source": 112,
   "target": 195,
   "value": 8
  },
  {
   "source": 113,
   "target": 217,
   "value": 8
  },
  {
   "source": 114,
   "target": 228,
   "value": 8
  },
  {
   "source": 115,
   "target": 223,
   "value": 8
  },
  {
   "source": 116,
   "target": 206,
   "value": 8
  },
  {
   "source": 117,
   "target": 205,
   "value": 8
  },
  {
   "source": 118,
   "target": 195,
   "value": 8
  },
  {
   "source": 57,
   "target": 190,
   "value": 8
  },
  {
   "source": 119,
   "target": 181,
   "value": 8
  },
  {
   "source": 120,
   "target": 224,
   "value": 8
  },
  {
   "source": 121,
   "target": 215,
   "value": 8
  },
  {
   "source": 122,
   "target": 195,
   "value": 8
  },
  {
   "source": 99,
   "target": 202,
   "value": 8
  },
  {
   "source": 63,
   "target": 203,
   "value": 8
  },
  {
   "source": 123,
   "target": 226,
   "value": 8
  },
  {
   "source": 53,
   "target": 203,
   "value": 8
  },
  {
   "source": 17,
   "target": 211,
   "value": 8
  },
  {
   "source": 124,
   "target": 195,
   "value": 8
  },
  {
   "source": 125,
   "target": 229,
   "value": 8
  },
  {
   "source": 126,
   "target": 182,
   "value": 8
  },
  {
   "source": 127,
   "target": 230,
   "value": 8
  },
  {
   "source": 128,
   "target": 231,
   "value": 7
  },
  {
   "source": 129,
   "target": 232,
   "value": 7
  },
  {
   "source": 130,
   "target": 130,
   "value": 7
  },
  {
   "source": 131,
   "target": 204,
   "value": 7
  },
  {
   "source": 132,
   "target": 187,
   "value": 7
  },
  {
   "source": 133,
   "target": 195,
   "value": 7
  },
  {
   "source": 134,
   "target": 178,
   "value": 7
  },
  {
   "source": 135,
   "target": 216,
   "value": 7
  },
  {
   "source": 69,
   "target": 191,
   "value": 7
  },
  {
   "source": 53,
   "target": 233,
   "value": 7
  },
  {
   "source": 136,
   "target": 234,
   "value": 7
  },
  {
   "source": 137,
   "target": 180,
   "value": 7
  },
  {
   "source": 138,
   "target": 191,
   "value": 7
  },
  {
   "source": 101,
   "target": 208,
   "value": 7
  },
  {
   "source": 139,
   "target": 235,
   "value": 7
  },
  {
   "source": 140,
   "target": 195,
   "value": 7
  },
  {
   "source": 117,
   "target": 180,
   "value": 7
  },
  {
   "source": 141,
   "target": 178,
   "value": 7
  },
  {
   "source": 142,
   "target": 227,
   "value": 7
  },
  {
   "source": 143,
   "target": 204,
   "value": 7
  },
  {
   "source": 144,
   "target": 235,
   "value": 7
  },
  {
   "source": 145,
   "target": 236,
   "value": 7
  },
  {
   "source": 146,
   "target": 224,
   "value": 7
  },
  {
   "source": 114,
   "target": 237,
   "value": 7
  },
  {
   "source": 147,
   "target": 238,
   "value": 7
  },
  {
   "source": 55,
   "target": 209,
   "value": 7
  },
  {
   "source": 148,
   "target": 203,
   "value": 7
  },
  {
   "source": 65,
   "target": 190,
   "value": 6
  },
  {
   "source": 149,
   "target": 195,
   "value": 6
  },
  {
   "source": 114,
   "target": 236,
   "value": 6
  },
  {
   "source": 150,
   "target": 198,
   "value": 6
  },
  {
   "source": 151,
   "target": 203,
   "value": 6
  },
  {
   "source": 152,
   "target": 228,
   "value": 6
  },
  {
   "source": 153,
   "target": 179,
   "value": 6
  },
  {
   "source": 154,
   "target": 179,
   "value": 6
  },
  {
   "source": 155,
   "target": 183,
   "value": 6
  },
  {
   "source": 156,
   "target": 239,
   "value": 6
  },
  {
   "source": 157,
   "target": 200,
   "value": 6
  },
  {
   "source": 86,
   "target": 180,
   "value": 6
  },
  {
   "source": 73,
   "target": 227,
   "value": 6
  },
  {
   "source": 73,
   "target": 240,
   "value": 6
  },
  {
   "source": 158,
   "target": 241,
   "value": 6
  },
  {
   "source": 159,
   "target": 190,
   "value": 6
  },
  {
   "source": 160,
   "target": 230,
   "value": 6
  },
  {
   "source": 161,
   "target": 181,
   "value": 6
  },
  {
   "source": 162,
   "target": 187,
   "value": 6
  },
  {
   "source": 163,
   "target": 208,
   "value": 6
  },
  {
   "source": 164,
   "target": 188,
   "value": 6
  },
  {
   "source": 165,
   "target": 186,
   "value": 6
  },
  {
   "source": 166,
   "target": 186,
   "value": 6
  },
  {
   "source": 167,
   "target": 195,
   "value": 6
  },
  {
   "source": 168,
   "target": 181,
   "value": 6
  },
  {
   "source": 169,
   "target": 242,
   "value": 6
  },
  {
   "source": 170,
   "target": 204,
   "value": 6
  },
  {
   "source": 171,
   "target": 179,
   "value": 6
  },
  {
   "source": 6,
   "target": 205,
   "value": 6
  },
  {
   "source": 172,
   "target": 191,
   "value": 6
  },
  {
   "source": 37,
   "target": 205,
   "value": 6
  },
  {
   "source": 173,
   "target": 242,
   "value": 6
  },
  {
   "source": 53,
   "target": 181,
   "value": 6
  },
  {
   "source": 172,
   "target": 196,
   "value": 6
  },
  {
   "source": 103,
   "target": 180,
   "value": 6
  },
  {
   "source": 174,
   "target": 243,
   "value": 6
  },
  {
   "source": 175,
   "target": 182,
   "value": 6
  },
  {
   "source": 176,
   "target": 244,
   "value": 6
  }
 ],
 "nodes": [
  {
   "impor": 86,
   "name": "RM",
   "type": "lyricist"
  },
  {
   "impor": 73,
   "name": "SUGA",
   "type": "lyricist"
  },
  {
   "impor": 72,
   "name": "Pdogg",
   "type": "lyricist"
  },
  {
   "impor": 69,
   "name": "방용국",
   "type": "lyricist"
  },
  {
   "impor": 68,
   "name": "정일훈",
   "type": "lyricist"
  },
  {
   "impor": 68,
   "name": "j-hope",
   "type": "lyricist"
  },
  {
   "impor": 64,
   "name": "라비 (빅스)",
   "type": "lyricist"
  },
  {
   "impor": 51,
   "name": "이민혁",
   "type": "lyricist"
  },
  {
   "impor": 51,
   "name": "BUMZU",
   "type": "lyricist"
  },
  {
   "impor": 51,
   "name": "주헌 (몬스타엑스)",
   "type": "lyricist"
  },
  {
   "impor": 51,
   "name": "서지음",
   "type": "lyricist"
  },
  {
   "impor": 51,
   "name": "WOOZI (SEVENTEEN)",
   "type": "lyricist"
  },
  {
   "impor": 48,
   "name": "I.M (몬스타엑스)",
   "type": "lyricist"
  },
  {
   "impor": 44,
   "name": "방시혁",
   "type": "lyricist"
  },
  {
   "impor": 38,
   "name": "Young K",
   "type": "lyricist"
  },
  {
   "impor": 36,
   "name": "이단옆차기",
   "type": "lyricist"
  },
  {
   "impor": 34,
   "name": "용감한 형제",
   "type": "lyricist"
  },
  {
   "impor": 34,
   "name": "Vernon (SEVENTEEN)",
   "type": "lyricist"
  },
  {
   "impor": 33,
   "name": "김창락",
   "type": "lyricist"
  },
  {
   "impor": 33,
   "name": "SWEETUNE",
   "type": "lyricist"
  },
  {
   "impor": 33,
   "name": "S.COUPS (SEVENTEEN)",
   "type": "lyricist"
  },
  {
   "impor": 33,
   "name": "Slow Rabbit",
   "type": "lyricist"
  },
  {
   "impor": 33,
   "name": "B.I",
   "type": "lyricist"
  },
  {
   "impor": 33,
   "name": "프니엘",
   "type": "lyricist"
  },
  {
   "impor": 33,
   "name": "이기 (오레오)",
   "type": "lyricist"
  },
  {
   "impor": 31,
   "name": "LE (EXID)",
   "type": "lyricist"
  },
  {
   "impor": 30,
   "name": "우석 (펜타곤)",
   "type": "lyricist"
  },
  {
   "impor": 30,
   "name": "서용배 (TENTEN)",
   "type": "lyricist"
  },
  {
   "impor": 30,
   "name": "MINO",
   "type": "lyricist"
  },
  {
   "impor": 30,
   "name": "BOBBY",
   "type": "lyricist"
  },
  {
   "impor": 29,
   "name": "문별 (마마무)",
   "type": "lyricist"
  },
  {
   "impor": 29,
   "name": "이던",
   "type": "lyricist"
  },
  {
   "impor": 28,
   "name": "용배 (RBW)",
   "type": "lyricist"
  },
  {
   "impor": 28,
   "name": "Supreme Boi",
   "type": "lyricist"
  },
  {
   "impor": 28,
   "name": "서재우 (TENTEN)",
   "type": "lyricist"
  },
  {
   "impor": 27,
   "name": "박우상",
   "type": "lyricist"
  },
  {
   "impor": 26,
   "name": "한성호",
   "type": "lyricist"
  },
  {
   "impor": 26,
   "name": "조성호",
   "type": "lyricist"
  },
  {
   "impor": 25,
   "name": "마크 (MARK)",
   "type": "lyricist"
  },
  {
   "impor": 25,
   "name": "엑시",
   "type": "lyricist"
  },
  {
   "impor": 25,
   "name": "김지향",
   "type": "lyricist"
  },
  {
   "impor": 24,
   "name": "유토",
   "type": "lyricist"
  },
  {
   "impor": 24,
   "name": "박수석",
   "type": "lyricist"
  },
  {
   "impor": 24,
   "name": "kenzie",
   "type": "lyricist"
  },
  {
   "impor": 23,
   "name": "신사동 호랭이",
   "type": "lyricist"
  },
  {
   "impor": 23,
   "name": "Ferdy (MosPick)",
   "type": "lyricist"
  },
  {
   "impor": 23,
   "name": "JR (뉴이스트)",
   "type": "lyricist"
  },
  {
   "impor": 23,
   "name": "조윤경",
   "type": "lyricist"
  },
  {
   "impor": 23,
   "name": "JQ",
   "type": "lyricist"
  },
  {
   "impor": 23,
   "name": "차쿤 (일렉트로보이즈)",
   "type": "lyricist"
  },
  {
   "impor": 22,
   "name": "민규 (SEVENTEEN)",
   "type": "lyricist"
  },
  {
   "impor": 22,
   "name": "진진 (ASTRO)",
   "type": "lyricist"
  },
  {
   "impor": 22,
   "name": "마르코",
   "type": "lyricist"
  },
  {
   "impor": 22,
   "name": "ZeroZine (MosPick)",
   "type": "lyricist"
  },
  {
   "impor": 21,
   "name": "이승훈",
   "type": "lyricist"
  },
  {
   "impor": 21,
   "name": "라키 (ASTRO)",
   "type": "lyricist"
  },
  {
   "impor": 21,
   "name": "김이나",
   "type": "lyricist"
  },
  {
   "impor": 21,
   "name": "Mafly",
   "type": "lyricist"
  },
  {
   "impor": 21,
   "name": "빅싼초 (Yummy Tone)",
   "type": "lyricist"
  },
  {
   "impor": 20,
   "name": "이승협 (J.DON)",
   "type": "lyricist"
  },
  {
   "impor": 19,
   "name": "한 (3RACHA)",
   "type": "lyricist"
  },
  {
   "impor": 19,
   "name": "창빈 (3RACHA)",
   "type": "lyricist"
  },
  {
   "impor": 19,
   "name": "도한세 (VICTON)",
   "type": "lyricist"
  },
  {
   "impor": 19,
   "name": "방찬 (3RACHA)",
   "type": "lyricist"
  },
  {
   "impor": 19,
   "name": "임현식",
   "type": "lyricist"
  },
  {
   "impor": 19,
   "name": "KZ",
   "type": "lyricist"
  },
  {
   "impor": 18,
   "name": "원우 (SEVENTEEN)",
   "type": "lyricist"
  },
  {
   "impor": 18,
   "name": "김도훈 (RBW)",
   "type": "lyricist"
  },
  {
   "impor": 18,
   "name": "전다운",
   "type": "lyricist"
  },
  {
   "impor": 17,
   "name": "김태주",
   "type": "lyricist"
  },
  {
   "impor": 17,
   "name": "낯선",
   "type": "lyricist"
  },
  {
   "impor": 17,
   "name": "JB (GOT7)",
   "type": "lyricist"
  },
  {
   "impor": 16,
   "name": "장예은",
   "type": "lyricist"
  },
  {
   "impor": 16,
   "name": "지민 (AOA)",
   "type": "lyricist"
  },
  {
   "impor": 16,
   "name": "T.K",
   "type": "lyricist"
  },
  {
   "impor": 16,
   "name": "별들의 전쟁",
   "type": "lyricist"
  },
  {
   "impor": 16,
   "name": "진리 (Full8loom)",
   "type": "lyricist"
  },
  {
   "impor": 16,
   "name": "태용 (TAEYONG)",
   "type": "lyricist"
  },
  {
   "impor": 15,
   "name": "Rome",
   "type": "lyricist"
  },
  {
   "impor": 15,
   "name": "HighTop",
   "type": "lyricist"
  },
  {
   "impor": 15,
   "name": "김기범",
   "type": "lyricist"
  },
  {
   "impor": 15,
   "name": "황현 (MonoTree)",
   "type": "lyricist"
  },
  {
   "impor": 15,
   "name": "강동하",
   "type": "lyricist"
  },
  {
   "impor": 15,
   "name": "강승윤",
   "type": "lyricist"
  },
  {
   "impor": 15,
   "name": "강지원",
   "type": "lyricist"
  },
  {
   "impor": 14,
   "name": "마부스 (Maboos)",
   "type": "lyricist"
  },
  {
   "impor": 14,
   "name": "디노 (SEVENTEEN)",
   "type": "lyricist"
  },
  {
   "impor": 14,
   "name": "미미 (오마이걸)",
   "type": "lyricist"
  },
  {
   "impor": 14,
   "name": "박진영",
   "type": "lyricist"
  },
  {
   "impor": 14,
   "name": "기희현",
   "type": "lyricist"
  },
  {
   "impor": 14,
   "name": "예빈 (다이아)",
   "type": "lyricist"
  },
  {
   "impor": 13,
   "name": "최갑원",
   "type": "lyricist"
  },
  {
   "impor": 13,
   "name": "화사 (마마무)",
   "type": "lyricist"
  },
  {
   "impor": 13,
   "name": "슬리피",
   "type": "lyricist"
  },
  {
   "impor": 13,
   "name": "BEOMxNANG",
   "type": "lyricist"
  },
  {
   "impor": 13,
   "name": "호시 (SEVENTEEN)",
   "type": "lyricist"
  },
  {
   "impor": 12,
   "name": "earattack",
   "type": "lyricist"
  },
  {
   "impor": 12,
   "name": "BM",
   "type": "lyricist"
  },
  {
   "impor": 12,
   "name": "가면라이더",
   "type": "lyricist"
  },
  {
   "impor": 12,
   "name": "e.one",
   "type": "lyricist"
  },
  {
   "impor": 12,
   "name": "우태운",
   "type": "lyricist"
  },
  {
   "impor": 12,
   "name": "백호 (뉴이스트)",
   "type": "lyricist"
  },
  {
   "impor": 12,
   "name": "정욱",
   "type": "lyricist"
  },
  {
   "impor": 12,
   "name": "David Kim",
   "type": "lyricist"
  },
  {
   "impor": 12,
   "name": "슈퍼창따이",
   "type": "lyricist"
  },
  {
   "impor": 12,
   "name": "이노베이터",
   "type": "lyricist"
  },
  {
   "impor": 12,
   "name": "솔라 (마마무)",
   "type": "lyricist"
  },
  {
   "impor": 11,
   "name": "한승우 (VICTON)",
   "type": "lyricist"
  },
  {
   "impor": 11,
   "name": "몬스터팩토리",
   "type": "lyricist"
  },
  {
   "impor": 11,
   "name": "미친감성",
   "type": "lyricist"
  },
  {
   "impor": 11,
   "name": "1월 8일",
   "type": "lyricist"
  },
  {
   "impor": 11,
   "name": "J.seph",
   "type": "lyricist"
  },
  {
   "impor": 11,
   "name": "테디",
   "type": "lyricist"
  },

In [468]:
filename_out = 'idol_lyricist_gen3.json'
json_out = open(filename_out,'w')
json_out.write(json_dump_gen3)
json_out.close()

## (4) 작곡가(composer) json 파일 생성하기

#### 작곡가로 json 데이터프레임 만들기

In [469]:
preprocessing_result2.rename(columns={"composer":"source","artist":"target"}, inplace=True)

In [470]:
grouped_idol_2 = preprocessing_result2.groupby(["source","target"]).size().reset_index()
grouped_idol_2.head() # 갑자기 빈 행이 존재함 ->삭제

          source target   0
0                        20
1            220     신화   2
2        A.minor   제이워크   1
3  Aaron Benward  에스이에스   1
4  Adam Benyahia     신화   1

In [471]:
grouped_idol_2.drop(grouped_idol_2.index[[0]], inplace=True)

In [472]:
grouped_idol_2 = grouped_idol_2.reset_index()

In [473]:
grouped_idol_2 = grouped_idol_2.drop(['index'], axis = 1)

In [474]:
unique_idol_2 = pd.Index(grouped_idol_2['source']
                      .append(grouped_idol_2['target'])
                      .reset_index(drop=True).unique())

In [475]:
grouped_idol_2.rename(columns={0:'count'}, inplace=True)
len(grouped_idol_2)

950

In [476]:
grouped_idol_2_ranking = grouped_idol_2.sort_values(by='count', ascending=False)
grouped_idol_2_ranking = grouped_idol_2_ranking.reset_index(drop=True)

In [477]:
grouped_idol_2_ranking.head(24)

         source     target  count
0           박진영        god     48
1           유건형       언타이틀     47
2            테디        원타임     29
3      박성호 (구피)         구피     29
4           유영진      에이치오티     20
5           윤일상         구피     17
6           방시혁        god     16
7   강타 (KANGTA)      에이치오티     16
8           천명훈        엔알지     14
9           안성일       제이워크     14
10          문희준      에이치오티     14
11          유영진         신화     13
12          신승희        테이크     13
13          더 준         오션     13
14          김형석  베이비 복스 리브     13
15          고석영         버즈     12
16          이윤상       젝스키스     12
17          윤우현         버즈     12
18      M (이민우)         신화     12
19          유영진      에스이에스     11
20          이현우        엔알지     11
21           페리        원타임     10
22          이현도       디베이스     10
23          김성태        샤크라     10

#### 작곡가 전체랭킹 저장

In [478]:
grouped_idol_2_ranking.to_csv('작곡가_전체랭킹.csv', index=False)